### ISSUE TITLE
Still pulling Agile pricing

### ISSUE THREAD

**Issue by mdeakin99** [BottlecapDave/HomeAssistant-OctopusEnergy#1]
I have installed this but it still seems to be pulling Agile pricing and not Go (which I am on).  I have correctly selected 'Go' in the drop down but I am concious I might not be using the right code (which include AGILE in it).

Also it isnt pulling in gas/electric meters yet.

Any help greatly appreciated.

**Comment by mdeakin99** [comment]
I used https://energy.guylipman.com/sm/admin?source=octopus to confirm the tariff code (changed it to a GO code) and there are no entities etc created by the integration.

**Comment by BottlecapDave** [comment]
Hii, sorry to hear you're having issues. This component is still a work in progress and I've only just switched to Octopus myself so I'm still waiting to get data myself to iron out the bugs. I'll update the readme to make this clearer. 

In regards to the GO prices, I have a todo in the code to adjust the rates for this, which I'll try and get to as soon as possible.

For tthe gas/electric meters, are you receiving any errors in your logs?

**Comment by mdeakin99** [comment]
No worries at about being work in progress.  Happy to help where I can.  Two log items.

This error originated from a custom integration.

Logger: custom_components.octopus_energy
Source: custom_components/octopus_energy/api_client.py:18 
Integration: Octopus Energy (documentation, issues) 
First occurred: 19:04:43 (1 occurrences) 
Last logged: 19:04:43

Unexpected error fetching rates data: 'results'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/octopus_energy/__init__.py", line 36, in async_update_data
    hass.data[DOMAIN][DATA_RATES] = await client.async_get_rates('AGILE-18-02-21', config[CONFIG_MAIN_TARIFF_CODE])
  File "/config/custom_components/octopus_energy/api_client.py", line 18, in async_get_rates
    data = data["results"]
KeyError: 'results'

….. and the second one….

This error originated from a custom integration.

Logger: custom_components.octopus_energy
Source: custom_components/octopus_energy/api_client.py:18 
Integration: Octopus Energy (documentation, issues) 
First occurred: 19:04:43 (1 occurrences) 
Last logged: 19:04:43

Unexpected error fetching rates data: 'results'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/octopus_energy/__init__.py", line 36, in async_update_data
    hass.data[DOMAIN][DATA_RATES] = await client.async_get_rates('AGILE-18-02-21', config[CONFIG_MAIN_TARIFF_CODE])
  File "/config/custom_components/octopus_energy/api_client.py", line 18, in async_get_rates
    data = data["results"]
KeyError: 'results'

**Comment by BottlecapDave** [comment]
Thanks for that. In my investigation, I've managed to find an easier way to setup the integration where you just need to provide an API key and account number. The upside is it should now be pulling down the right data. Downside is you'll need to remove the integration, install the update and restart home assistant. I've also updated the readme with further information.

**Comment by mdeakin99** [comment]
Seen the update and pulled that one down. Still no  entities created I am afraid. 


Logger: OctopusAgile
Source: custom_components/octopusagile/OctopusAgile/Agile.py:378
Integration: octopusagile (documentation, issues) 
First occurred: 5 September 2021, 19:31:19 (1764 occurrences) 
Last logged: 7:30:59

Unmatched consumption 2021-03-27T22:30:00Z / cost 2021-01-03T23:00:00Z
Unmatched consumption 2021-03-27T23:00:00Z / cost 2021-01-03T23:30:00Z
Unmatched consumption 2021-03-27T23:30:00Z / cost 2021-01-04T00:00:00Z
Unmatched consumption 2021-03-28T00:00:00Z / cost 2021-01-04T00:30:00Z
Unmatched consumption 2021-03-28T00:30:00Z / cost 2021-01-04T01:00:00Z

This error originated from a custom integration.

Logger: OctopusAgile
Source: custom_components/octopusagile/OctopusAgile/Agile.py:373
Integration: octopusagile (documentation, issues) 
First occurred: 5 September 2021, 18:30:01 (93013 occurrences) 
Last logged: 7:31:20

UTC Unmatched consumption 2021-09-05T22:00:00+01:00 / cost 2021-06-14T21:30:00Z
UTC Unmatched consumption 2021-09-05T22:30:00+01:00 / cost 2021-06-14T22:00:00Z
UTC Unmatched consumption 2021-09-05T23:00:00+01:00 / cost 2021-06-14T22:30:00Z
UTC Unmatched consumption 2021-09-05T23:30:00+01:00 / cost 2021-06-14T23:00:00Z
UTC Unmatched consumption 2021-09-06T00:00:00+01:00 / cost 2021-06-14T23:30:00Z


This error originated from a custom integration.

Logger: custom_components.octopusagile
Source: custom_components/octopusagile/__init__.py:408 
Integration: octopusagile (documentation, issues) 
First occurred: 5 September 2021, 18:30:21 (16 occurrences) 
Last logged: 8:00:00

Expecting value: line 1 column 1 (char 0)

**Comment by BottlecapDave** [comment]
Those errors look like they're coming from a different integration (Octopus Agile)

**Comment by mdeakin99** [comment]
Opps.  My bad!

Who needs enemies when you have testers like me 😉

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by mdeakin99** [comment]
Will update you with any errors next time I reboot

**Comment by BottlecapDave** [comment]
No problem :) I'll keep this ticket open until you return :)

**Comment by mdeakin99** [comment]
I can confirm I now see current/next energy price.  Thats now working.

I need to wait for the 'meters' to update with consumption values.  They are not in the correct format though for the 'Energy Dashboard' so will raise an issue for that.  You can decide if that's important or not though :)

**Comment by BottlecapDave** [comment]
I've only just my meters updating, and it looks like Octopus only update the data once a day :( Not sure if that's just with my meter (v1) or all meters. I've reached out to them for clarity.

I'm thinking of adding a sensor for the previous day accumulated so I can at least get _something_ useful out. Will close this ticket now that prices are coming through.
