### ISSUE TITLE
Completely stopped working

### ISSUE THREAD

**Issue by danielsmith89** [BottlecapDave/HomeAssistant-OctopusEnergy#100]
**Describe the bug**

I’m not sure if this maybe an Octopus outage or what, but the integration currently isn’t loading at all for me, despite it working fine a few hours ago.

**To Reproduce**

**Home Assistant Version**

2022.12.1

**Integration Version**

4.7.1

**Home Assistant Logs**
`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/octopus_energy/api_client.py:160 
Integration: Octopus Energy (documentation, issues) 
First occurred: 17:54:11 (1 occurrences) 
Last logged: 17:54:11

Error setting up entry Octopus Energy for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/octopus_energy/__init__.py", line 41, in async_setup_entry
    await async_setup_dependencies(hass, entry.data)
  File "/config/custom_components/octopus_energy/__init__.py", line 95, in async_setup_dependencies
    account_info = await client.async_get_account(config[CONFIG_MAIN_ACCOUNT_ID])
  File "/config/custom_components/octopus_energy/api_client.py", line 152, in async_get_account
    "gas_meter_points": list(map(lambda mp: {
  File "/config/custom_components/octopus_energy/api_client.py", line 157, in <lambda>
    "agreements": list(map(lambda a: {
  File "/config/custom_components/octopus_energy/api_client.py", line 160, in <lambda>
    "tariff_code": a["tariff"]["tariffCode"] if "tariffCode" in a["tariff"] else None,
TypeError: argument of type 'NoneType' is not iterable
`

**Comment by BottlecapDave** [comment]
Hello. This seems to be an issue with the API where is sometimes doesn't return the expected data. I've personally never seen it, so it's hard to track down tthe cause. Without the tariff, the integration wouldn't work properly.

Has anything changed in your account that could have caused this issue? Has it rectified itself?

**Comment by danielsmith89** [comment]
> Hello. This seems to be an issue with the API where is sometimes doesn't return the expected data. I've personally never seen it, so it's hard to track down tthe cause. Without the tariff, the integration wouldn't work properly.
> 
> 
> 
> Has anything changed in your account that could have caused this issue? Has it rectified itself?

Hi, nothing has changed in my account as far as I can see. Oddly the saving sessions sensor has started working again now, but the points sensor and all the meter sensors are still not working.

**Comment by lozzd** [comment]
I am also seeing current rate and previous rate as `unknown`

```
Logger: custom_components.octopus_energy.api_client
Source: custom_components/octopus_energy/api_client.py:262
Integration: Octopus Energy (documentation, issues)
First occurred: 8:30:11 AM (1 occurrences)
Last logged: 8:30:11 AM

Request failed: 502; <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx</center> </body> </html>
```

looks like an API issue then I guess?

**Comment by dmelliott20** [comment]
I also started having this issue a few days ago…

**Comment by ademobile** [comment]
I've been having the same issue too for the past few days (maybe since the update?)
<img width="897" alt="Screenshot 2022-12-12 at 08 28 15" src="https://user-images.githubusercontent.com/25222110/206997552-1ba2c2e0-da82-4a45-b3da-574bb759fb36.png">

**Comment by ademobile** [comment]
For a test I rolled back to 4.6.4 and its working fine, so I am guessing (I know!) that the issue was introduced since that version.

**Comment by lozzd** [comment]
Interesting - my 502 issue might be separate then. Mine started working on its own at 7:30 this morning... Presumably after someone at Octopus finally spotted an issue on their end. My rates are back.

**Comment by ademobile** [comment]
> Interesting - my 502 issue might be separate then. Mine started working on its own at 7:30 this morning... Presumably after someone at Octopus finally spotted an issue on their end. My rates are back.

More intresting, mine was still not working at 8:05, thats when I applied 2022.12.3 update to home assistant. I then started to play with older versions and they worked. After seeing your post, I tried the latest version again and I am now working too. Fingers crossed it was an Octopus issue.

**Comment by danielsmith89** [comment]
> > Interesting - my 502 issue might be separate then. Mine started working on its own at 7:30 this morning... Presumably after someone at Octopus finally spotted an issue on their end. My rates are back.
> 
> 
> 
> More intresting, mine was still not working at 8:05, thats when I applied 2022.12.3 update to home assistant. I then started to play with older versions of this integration and they worked. After seeing your post, I tried the latest version again and I am now working too. Fingers crossed it was an Octopus issue.

I've just updated to 2022.12.3 and it's all working for me again now (on the latest version of this integration).

**Comment by BottlecapDave** [comment]
Glad to see this rectified itself. 500+ errors returned are on Octopus Energy's side. I'll see if I can improve the error messages to make this clearer.
