### ISSUE TITLE
Support Business Tarriff "Shape Shifters"

### ISSUE THREAD

**Issue by RobinWhitfield** [BottlecapDave/HomeAssistant-OctopusEnergy#1002]
### Describe the feature

The new(ish) business tariff [Shape Shifters](https://octopus.energy/smart/shape-shifters/) does not appear to be supported by the integration.

`Exception: Failed to retrieve rates for tariff 'E-1R-BUS-12M-FIXED-SHAPE-SHIFTER-24-08-01-BAND3-M'`

### Expected behaviour

Integration functions in a similar manner to home smart tarrifs

### Use Case

Using Home Assistant with Octopus Energy for Business with the Shape Shifters tarrif.

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. It doesn't look like the rates or product are available via the OE API. I've raised this in the OE forums and awaiting a response. Is there any chance you could follow the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq/#ive-been-asked-for-my-meter-information-in-a-bug-request-how-do-i-obtain-this) and provide the meter information from the diagnostics so I could get a little more information for the ticket?

**Comment by RobinWhitfield** [comment]
`"data": {
    "id": "**REDACTED**",
    "octoplus_enrolled": true,
    "electricity_meter_points": [
      {
        "mpan": "**REDACTED**",
        "meters": [
          {
            "active_from": {
              "__type": "<class 'datetime.date'>",
              "isoformat": "2024-03-11"
            },
            "active_to": null,
            "serial_number": "**REDACTED**",
            "is_export": false,
            "is_smart_meter": true,
            "device_id": "**REDACTED**",
            "manufacturer": "1063 - Landis and Gyr",
            "model": "00050204",
            "firmware": "38040404"
          }
        ],
        "agreements": [
          {
            "start": "2023-11-18T00:00:00+00:00",
            "end": "2024-09-18T23:00:00+00:00",
            "tariff_code": "E-1R-BUS-12M-FIXED-GREEN-BAND3-23-11-10-M",
            "product_code": "BUS-12M-FIXED-GREEN-BAND3-23-11-10"
          },
          {
            "start": "2024-09-18T23:00:00+00:00",
            "end": "2025-09-18T23:00:00+00:00",
            "tariff_code": "E-1R-BUS-12M-FIXED-SHAPE-SHIFTER-24-08-01-BAND3-M",
            "product_code": "BUS-12M-FIXED-SHAPE-SHIFTER-24-08-01-BAND3"
          }
        ]
      }
    ],
    "gas_meter_points": []
  `}``
  
  The integration was working OK with the standard business tarrif before we switched.

**Comment by BottlecapDave** [comment]
Thanks for the information.

> The integration was working OK with the standard business tarrif before we switched.

Unfortunately the integration relies on certain data being available on start up in order to correctly set up certain sensors. Part of this is retrieving rate information to determine how many unique rate periods are available (e.g. off peak and peak). This information is not being supplied by OE so the integration is failing. I'll post an update so that the integration defaults to a single rate if rate information cannot be retrieved so at least other parts will continue to work. Of course, anything that relies on rate information will continue to fail until OE updates their end to expose the tariff via their API.

**Comment by jmhunter** [comment]
We have the same issue with the same type of tariff.

In our case, the Octopus mobile app also crashes when we try to view the tariff information for import (our export tariff is still fine) - it seems as though this impacts the native Octopus mobile app, too, at least for us.

I emailed Octopus at the weekend and haven't yet heard back but will share any useful info as/when I get it..

**Comment by RobinWhitfield** [comment]
This tariff appears to have been added to the API on Monday morning, and the integration picked it up and is now working as expected.

**Comment by BottlecapDave** [comment]
Thanks for letting me know. I can also see it being reported back manually, so closing this issue.
