### ISSUE TITLE
Unknown intelligent provider

### ISSUE THREAD

**Issue by RPCHome** [BottlecapDave/HomeAssistant-OctopusEnergy#1003]
### Provider name

FORD

### Features

- [X] Ability to bump charge
- [X] Ability to set the charge limit/target
- [X] Ability to set the time the charge will be at its target for
- [X] Ability to turn smart charge on/off
- [X] Ability to see planned dispatches

**Comment by BottlecapDave** [comment]
Hello. There is already an issue covering this, but it was accidently closed.  This support will be added in the next release. I hope to do a beta release over the weekend which will include this.

**Comment by BottlecapDave** [comment]
This is now available in [v13.0.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v13.0.0).
