### ISSUE TITLE
Entry migration error when starting HA 2024.10.0

### ISSUE THREAD

**Issue by CharlieRiesner** [BottlecapDave/HomeAssistant-OctopusEnergy#1007]
### Describe the bug

When HA 2024.10.0 starts up with this plugin installed (version 12.2.1), I get an error in the logs and the Integration shows a migration error in the UI

### Reproduction steps

Update to HA 2024.10.0 with version 12.2.1 of the Octopus plugin installed.

### Expected behaviour

The plugin to be loaded successfully.

### Tariff Code

Not sure, FAQ for finding this would be great!

### Integration Version

12.2.1

### Home Assistant Version

2024.10.0

### Fresh Install?

After upgrading

### Home Assistant Logs

2024-10-02 20:23:57.576 ERROR (MainThread) [homeassistant.config_entries] Error migrating entry A-82FA4A23 for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 933, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 100, in async_migrate_entry
    config_entry.version = CONFIG_VERSION
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in __setattr__
    raise AttributeError(
AttributeError: version cannot be changed directly, use async_update_entry instead

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by CharlieRiesner** [comment]
After downgrading HA to 2024.9.3 and allowing it to completely start up, the integration loaded successfully. I have now upgraded back to 2024.10.0 and the integration has loaded successfully again.

I did update to version 12.2.1 of the integration after doing the 2024.10.0 update, so perhaps there is something strange with upgrading from older versions of the plugin to latest on 2024.10.0. 

I was running a very outdated version 11.something when I did the initial upgrade to 2024.10.0 which is what prompted me to update the integration.

**Comment by BottlecapDave** [comment]
Thanks for bringing this to my attention. I'll try and reproduce and fix the migration issue. Glad you found a workaround.

**Comment by pensivealbatross** [comment]
I have the same problem having upgraded HA: 2024.7.3 > 2024.10.1
Also upgraded at the same time:
Octopus Energy: v11.2.2 > v12.2.1
HACS: 1.34.0 > 2.0.1

Running in docker

`2024-10-06 12:56:10.353 ERROR (MainThread) [homeassistant.config_entries] Error migrating entry A-19C10BC1 for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 933, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 100, in async_migrate_entry
    config_entry.version = CONFIG_VERSION
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in __setattr__
    raise AttributeError(
AttributeError: version cannot be changed directly, use async_update_entry instead`

**Comment by karpilin** [comment]
same issue here

**Comment by adamfmk** [comment]
same issue here - did a batch of upgrades on HA, HACS and this add-on, looking like I need to restore, as something else has broken a number of pages and core features in the HA upgrade!

Logger: homeassistant.config_entries
Source: config_entries.py:933
First occurred: 7 October 2024 at 09:59:27 (1 occurrences)
Last logged: 7 October 2024 at 09:59:27

Error migrating entry <Octopus Account ID> for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 933, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 100, in async_migrate_entry
    config_entry.version = CONFIG_VERSION
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in __setattr__
    raise AttributeError(
AttributeError: version cannot be changed directly, use async_update_entry instead

**Comment by BottlecapDave** [comment]
A fix for this can be found in the beta for the next release (v13.0.0-beta.3). This has breaking changes, so if you use it please read the release notes for beta 1, 2 and 3 to ensure nothing else changes unexpectedly foe you.

If you don't want to use a beta version, then assuming nothing showstopping is raised, this will be released properly early next week.

**Comment by Russetjack** [comment]
Same issue for me after doing some updates yesterday. Struggling to resolve at the moment

**Comment by BottlecapDave** [comment]
The fix for this issue is now available in [v13.0.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v13.0.0).
