### ISSUE TITLE
Allow Min/Max rates to be defined using a Helper (and therefore adjusted from a HA dashboard)

### ISSUE THREAD

**Issue by fraserallanuk** [BottlecapDave/HomeAssistant-OctopusEnergy#1018]
### Describe the feature

Hello,

It would be great if the
[Minimum/Maximum Rates
](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/setup/target_rate/#minimummaximum-rates) attributes could be set by a HA helper. This means that one could adjust these values quickly and easily from the HA dashboard using a card.

### Expected behaviour

Quickly adjust the valves of the Minimum and Maximum Rates from any HA dashboard, or even from an automation.

### Use Case

as above

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by ragg987** [comment]
The add-in has a Action (was called Service) that can update the Target sensor. You could call that after your change of min or max via an automation.

I've done something similar where I have an input helper that holds the Target duration. Then I have an automation that kicks in when the helper state changes and calls the Action to update the Target sensor. Note these on-the-fly updates are not persistent and will not survive a system restart.

Action is called octopus_energy.update_target_config and it's use for an automation is documented quite well in the help docs: [https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/services/](url)

**Comment by BottlecapDave** [comment]
As mentioned by @ragg987 there is already an action exposed that allows you to update the settings of target rate sensors. As he also mentioned there is an example of updating the sensor via helpers in the [docs](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/services/#automation-example). Because of this there are no plans to to expose the settings via helpers.
