### ISSUE TITLE
Error setting up entry A-[account number] for octopus_energy after upgrade to 13.0.0

### ISSUE THREAD

**Issue by Alibloke** [BottlecapDave/HomeAssistant-OctopusEnergy#1023]
### Describe the bug

After upgrading to 13.0.0 the integration no longer loads

### Reproduction steps

Upgrade to 13.0.0, restart home assistant

### Expected behaviour

Integration should load

### Tariff Code

SILVER-23-12-06

### Integration Version

13.0.0

### Home Assistant Version

2024.10.2

### Fresh Install?

After upgrading

### Home Assistant Logs

2024-10-15 13:14:56.363 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry A-[account number] for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 139, in async_setup_entry
    await async_setup_dependencies(hass, config)
  File "/config/custom_components/octopus_energy/__init__.py", line 357, in async_setup_dependencies
    should_mock_intelligent_data = debug_override.mock_intelligent_controls if debug_override is not None else False
                                                                               ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'debug_override' where it is not associated with a value

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry you're seeing this issue. Am I right in saying you don't have any electricity meters? I'm just trying to work out why this issue didn't appear in the beta testing.

**Comment by Alibloke** [comment]
No problem.  I wondered if might be related as I did have both gas + electricity with Octopus, but now have moved away to another provider for electricity.

**Comment by BottlecapDave** [comment]
No problem. I'm just preparing a beta with the fix, which it would be good for you to try _just in case_ there is other gotchas in this scenario that need fixing.

**Comment by BottlecapDave** [comment]
A beta (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v13.0.1-beta.1) is now available with hopefully the only fix you need :)

**Comment by BottlecapDave** [comment]
https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/compare/v13.0.1-beta.1...v13.0.1-beta.2 will hopefully get you a little further.

**Comment by BottlecapDave** [comment]
Let me know after a bit of testing if everything is working as should and I'll release the fix properly.

**Comment by ragg987** [comment]
I don't know if this is the same error, however I am seeing the same symptoms and the add-in is failing. Definitely related to an update, was working a few hours ago today prior to the upgrade.
HAOS core 2024.10.2

![image](https://github.com/user-attachments/assets/cec72cca-8231-483c-9098-b43d71098510)

Currently backing up the broken one to see if i can restore to an earlier system...

**Comment by ragg987** [comment]
Update: restored backup of  HAOS 2124.10.1 and Octopus 12.2.1 and it is working fine.

**Comment by BottlecapDave** [comment]
@ragg987 please check the attached beta. If that doesn't work, then please check the logs upon failure (as the error message says in your screenshot) and post them here, as without them there's nothing I can do to fix the issue.

The integration can naturally fail to set up if it can't connect to the OE APIs when loading (which happens from time to time as the APIs can be a bit flakey at times)

**Comment by ragg987** [comment]
All working today - I suspect mine was an OE API issue rather than an integration issue. Sorry for the false alarm.

**Comment by Alibloke** [comment]
@BottlecapDave Seems good so far, no issues thanks
