### ISSUE TITLE
Rolling target rate sensor with "always" evaluation period never turning on

### ISSUE THREAD

**Issue by BottlecapDave** [BottlecapDave/HomeAssistant-OctopusEnergy#1030]
### Describe the bug

When setting up a rolling target rate sensor with "always" evaluation period, the sensor never turns on

### Reproduction steps

Create a rolling target rate sensor with "always" evaluation period

### Expected behaviour

The sensor should turn on for at least 30 minutes while rate information is suitable

### Tariff Code

N/A

### Integration Version

13.0.2

### Home Assistant Version

2024.10.0

### Fresh Install?

Not specified

### Home Assistant Logs

N/A

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by billmichell** [comment]
Thank you for writing this up.

**Comment by BottlecapDave** [comment]
This has now been fixed as part of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v13.0.3
