### ISSUE TITLE
Peak / Off Peak Rates

### ISSUE THREAD

**Issue by shirehorse99** [BottlecapDave/HomeAssistant-OctopusEnergy#1033]
### Describe the feature

can you add peak and off peak cost sensors

### Expected behaviour

would be of great help to some of us

### Use Case

I can use the off peak sensor rate to calculate ev costings with my ev session sensor. we only have next and current rates - would like the actual cost rates as sensors

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [ ] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello and thanks for raising this. This isn't currently supplied as not all tariffs are created equally and therefore not all tariffs have an off peak (or have three rates like cosy or more like agile). This is not currently high on my list as it can be done with a template helper using the following to get the off peak value (assuming you're on a tariff with two rates)

```
{% if states('sensor.octopus_energy_electricity_xxx_yyy_current_rate') < states('sensor.octopus_energy_electricity_xxx_yyy_next_rate_rate') %}
{{ states('sensor.octopus_energy_electricity_xxx_yyy_current_rate') }}
{% else %}
{{ states('sensor.octopus_energy_electricity_xxx_yyy_next_rate') }}
{% endif %}
```

If you, or anyone else, would like to contribute a solution before I get to it, we'd need the following sensors:

* `sensor.octopus_energy_electricity_{{METER_SERIAL_NUMBER}}_{{MPAN_NUMBER}}_off_peak_rate` - shows the off peak electricity rate
* `sensor.octopus_energy_electricity_{{METER_SERIAL_NUMBER}}_{{MPAN_NUMBER}}_standard_rate` - shows the standard electricity rate
* `sensor.octopus_energy_electricity_{{METER_SERIAL_NUMBER}}_{{MPAN_NUMBER}}_peak_rate` - shows the peak electricity rate

The above sensors should only be available where the users tariff supports it. This should follow the same rules as the [consumption variants](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/entities/electricity/#variants). They should probably be disabled by default as not everyone will need them. The docs would need updating to reflect the new sensors.

**Comment by shirehorse99** [comment]
thanks Dave, its a bit above my level sorry -im using the ohme integration to get EV consumption and would like your off peak rate to be the cost, that's my reasoning to get the cost of ev charge costings.

**Comment by BottlecapDave** [comment]
Sorry I thought you were after the raw rates with how you were describing things.

If you're wanting to calculate the cost, then you can look at [cost trackers](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/setup/cost_tracker/) which track a given kwh entity and provide total, peak and off peak variations at a daily, weekly and monthly level. If you're using [this integration](https://github.com/dan-r/HomeAssistant-Ohme), then I think you want to track the energy usage sensor.

**Comment by shirehorse99** [comment]
Morning Dave,

Thanks for your reply on this - I think this is exactly what I need - excellent!

Keep up the good work fella - your integration is superb

Mark

On 20 Oct 2024, at 05:51, David Kendall ***@***.***> wrote:

﻿

Sorry I thought you were after the raw rates with how you were describing things.

If you're wanting to calculate the cost, then you can look at cost trackers<https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/setup/cost_tracker/> which track a given kwh entity and provide total, peak and off peak variations at a daily, weekly and monthly level. If you're using this integration<https://github.com/dan-r/HomeAssistant-Ohme>, then I think you want to track the energy usage sensor.

**Comment by shirehorse99** [comment]
That’s exactly what I need Dave, thank you . Keep up the great work fella , your integration is superb , fair play

**Comment by BottlecapDave** [comment]
Thanks for the update. I'll close this ticket then as it seems what you were after is already available.
