### ISSUE TITLE
Add end date/time for "Next joined event"

### ISSUE THREAD

**Issue by p6sfrx725z28knfy** [BottlecapDave/HomeAssistant-OctopusEnergy#104]
While the ability to see when the next (subscribed) Saving Session is useful, with todays event being 2 hours compared to 1 hour for the previous events it seems that an end time for the next joined event would also be useful :)

        In the latest release https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v4.7.0, you can find the following sensors

```
* `octopus_energy_saving_session_points` - Supplies the points earned through the saving sessions
* `octopus_energy_saving_sessions` - Binary sensor to indicate if a saving session that the account has joined is active. Also supplies the list of joined events including future events.
```

You will still need to opt in manually to the events, but hopefully these sensors will help you in your automations

_Originally posted by @BottlecapDave in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/92#issuecomment-1336438998_

**Comment by BottlecapDave** [comment]
I'll see what I can do for the next update.

**Comment by BottlecapDave** [comment]
This is now available in the release https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v5.1.0

**Comment by p6sfrx725z28knfy** [comment]
> This is now available in the release https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v5.1.0

Great stuff, many thanks :)
