### ISSUE TITLE
Missing entity sensor.octopus_energy_cost_tracker from custom_components/octopus_energy/services.yaml:185,185,215

### ISSUE THREAD

**Issue by Andyphillips27** [BottlecapDave/HomeAssistant-OctopusEnergy#1043]
### Describe the bug

Thank you guys, great work on this integration by the way. It's awesome 
 
Problem; I've noticed in more recent versions of the Octopus integration that Watchman keeps finding  missing entity sensor.octopus_energy_cost_tracker from custom_components/octopus_energy/services.yaml:185,185,215

There are three references to this is the services.yaml file. Could this be fixed in a future release please?

### Reproduction steps

Navigate to custom_components/octopus_energy/services.yaml:185,185,215 you will see the missing entries in three places 

missing entity sensor.octopus_energy_cost_tracker

line 185 (twice) and once on 215

### Expected behaviour

To not find missing sensor in the services.yaml 

### Tariff Code

N/A

### Integration Version

13.0.2

### Home Assistant Version

2024.10.4

### Fresh Install?

After upgrading

### Home Assistant Logs

Watchman log:

-== Watchman Report ==- 

-== Congratulations, all 6 services from your config are available!

-== Missing 1 entity(ies) from 188 found in your config:
+--------------------------------+---------+--------------------------------------------------------------+
| Entity ID                      | State   | Location                                                     |
+--------------------------------+---------+--------------------------------------------------------------+
| sensor.octopus_energy_cost_tra | missing | custom_components/octopus_energy/services.yaml:185,185,215   |
| cker_                          |         |                                                              |
+--------------------------------+---------+--------------------------------------------------------------+

-== Report created on 26 Oct 2024 07:21:54
-== Parsed 25 files in 27.94s., ignored 0 files 
-== Generated in: 0.20s. Validated in: 0.00s.

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by Andyphillips27** [comment]
![2024-10-26_07-24-09](https://github.com/user-attachments/assets/7d0b07cf-77bd-45eb-8b80-b5e37b008dc6)

**Comment by BottlecapDave** [comment]
Hello. This file is a description of the services available by the integration. The highlighted areas are examples of the sensors that should be used with these services. I'd argue that Watchman shouldn't be analysing files contained within custom_integrations, or at the very least the services.yaml file within custom_integrations. It looks like you can tell Watchman to ignore this folder.

**Comment by Andyphillips27** [comment]
Thanks
