### ISSUE TITLE
Change from BST to GMT - event_current_date_rates and event_next_day_rates sensor update incorrectly

### ISSUE THREAD

**Issue by ChequeM8** [BottlecapDave/HomeAssistant-OctopusEnergy#1049]
### Describe the bug

On Sunday 27th October the clocks go back 1 hour from BST to GMT in the UK.

event.octopus_energy_electricity_XXXXXXXXX_XXXXXXXXXX_current_day_rates

This sensor contains rates for slots 0100-0130 and 0130-0200 twice as expected for the clock changes:

![image](https://github.com/user-attachments/assets/98da2f5c-10cd-44c0-bacb-aad54a8326a3)

When the sensors are updated after 16:00, the 2300-2330 and 2330-0000 slots are not added to the current_day_rates, they are added to next_day_rates. This adds slots from the 27/10/2024 to the next_day_rates which are for 28/10/2024.  Any code that uses dates to select slots from the sensor attributes then fails or produces nulls on the 27th and misses the data on the 28th as it's the wrong day.

event.octopus_energy_electricity_XXXXXXXXX_XXXXXXXXXX_next_day_rates

![image](https://github.com/user-attachments/assets/e0a5ecac-ae7b-4af6-90e8-5c65bec3cadc)

### Reproduction steps

Please see above.

### Expected behaviour

The current and next day rates sensors should not mix dates.  
Current day rates should have 48 slots on the 27/10/2024 to cater for the clocks changing.  
When the rates come through after 16:00, the 2300-2330 and 2330-0000 slots should be added to the current day rates making 50 slots altogether.  
The next day rates should start at 0000 as normal and contain 46 slots with the correct 28/10/2024 date until updated after 16:00 when there will be 48 slots.

### Tariff Code

N/A

### Integration Version

13.0.2

### Home Assistant Version

Core 2024.10.3 Supervisor 2024.10.3 Operating System 13.2 Frontend 20241002.3

### Fresh Install?

Not specified

### Home Assistant Logs

N/A

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry you're seeing this issue. This should rectify itself over the next couple of days, but I'll try and fix it for the next time the clocks change.

**Comment by BottlecapDave** [comment]
This has been fixed in [v13.1.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v13.1.0). This should fix the issue for next year, but time will tell :)

**Comment by ChequeM8** [comment]
Thank you Dave, much appreciated!
