### ISSUE TITLE
Gas rate sensor no longer working

### ISSUE THREAD

**Issue by craigrouse** [BottlecapDave/HomeAssistant-OctopusEnergy#105]
**Describe the bug**

After the last update, the gas rate sensor suddenly stopped working, showing "unknown" as the value for the current gas rate, and breaking my energy dashboard (I use the value from current rate for the gas calulcations). I believe it's a side effect of this change: https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/commit/11f275f63aba585aabb66a9d3c180e35817f0434

**To Reproduce**

Install the integration and check the current gas rate. I'm on the gas tracker tariff, in case it helps.

**Expected behavior**

Gas rate should have a value, not "unknown"

**Home Assistant Version**

2022.12.3

**Integration Version**

4.7.1

**Fresh Install?**

Was this from a fresh install or after an upgrade?

**Home Assistant Logs**

Are there any related logs available in Home Assistant? It is suggested you set your [log level](https://www.home-assistant.io/integrations/logger/) to `debug` and then check the "Full Home Assistant Log" from the `logs page`.

**Comment by dalgibbard** [comment]
![Screenshot_20221212-203554](https://user-images.githubusercontent.com/1159620/207149265-d10eb306-472f-4fda-b796-3fdc540bc30c.png)

Looks the same for electricity current rate too

**Comment by dalgibbard** [comment]
![Screenshot_20221212-204135](https://user-images.githubusercontent.com/1159620/207150448-83cdadb6-6819-40c5-9f7f-c6de91a73419.png)
![Screenshot_20221212-204148](https://user-images.githubusercontent.com/1159620/207150458-bde7d63a-b64e-452c-aece-2765257b37c7.png)

**Comment by eugeneniemand** [comment]
This is what I'm seeing on all of them 
![image](https://user-images.githubusercontent.com/6813309/207184794-7b53346b-6276-44e2-bdd0-cfdce3746230.png)

**Comment by BottlecapDave** [comment]
Sorry to hear you're having issues. Are you seeing anything in your logs? It looks like the API is having some issues at the moment based on https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/100

**Comment by BottlecapDave** [comment]
The change mentioned results in the gas rate refreshing if it fails to retrieve a value initially, whereas before if it failed to retrieve a rate, it would not refresh for up to 24 hours

**Comment by craigrouse** [comment]
@BottlecapDave All I can say is that I rolled back, and it started working immediately. I'd left it in the broken state for 3 days, and it never successfully retrieved a gas rate. I checked the logs (with debug logging enabled) and didn't see anything strange - it appeared to be retrieving rates just fine.

**Comment by BottlecapDave** [comment]
That is odd. I've been running the latest release for weeks and have been having my sensor update fine. I know there were a few days where the API was being flakey. Were there anything in your logs? Was the data available in the OE dashboard?

**Comment by dalgibbard** [comment]
Mine is looking good again today, so maybe a blip :)

**Comment by BottlecapDave** [comment]
Closing due to latest comment.
