### ISSUE TITLE
No Export Data

### ISSUE THREAD

**Issue by stefanwest1** [BottlecapDave/HomeAssistant-OctopusEnergy#1051]
### Describe the bug

For about a week now, I’ve had no export data. All entities under the export meter show as unavailable. They’re showing in the octopus app. I’m running 13.0.3, but issue was present on previous version also. 

### Reproduction steps

Have tried reconfiguring the addon

### Expected behaviour

Export data

### Tariff Code

Agile

### Integration Version

13.0.3

### Home Assistant Version

2024.10.4

### Fresh Install?

Not specified

### Home Assistant Logs

[home-assistant_octopus_energy_2024-10-28T10-27-03.737Z.log](https://github.com/user-attachments/files/17541008/home-assistant_octopus_energy_2024-10-28T10-27-03.737Z.log)

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry that you're having issues. Looking at your logs, it looks like OE is only reporting a single import meter for your account which is why the integration is no longer providing export meter information. You'll need to contact them to get this fixed I'm afraid.
