### ISSUE TITLE
Update from 13.0.3 to 13.1.0 breaks IOG target setting?

### ISSUE THREAD

**Issue by mt104** [BottlecapDave/HomeAssistant-OctopusEnergy#1068]
### Describe the bug

When after updating from v13.0.3 to v13.1.0 I can no longer set the IOG target percentage to add. I *think* the entity IDs for target add percent and target complete time changed too.

I updated Home Assistant Core to 2024.11.0 a few days earlier, so that may be related.

### Reproduction steps

Update this integration to 13.1,0 and HA Core to 2024.11.0.

### Expected behaviour

Updating IOG target add percent should result in the Octopus mobile app showing the new percentage, but instead the update fails and the app continues to show the old value.

### Tariff Code

Shows "Unknown" in the Tariff attribute of current_rate, and current_rate often shows as Unavailable.

### Integration Version

13.1.0

### Home Assistant Version

2024.11.0

### Fresh Install?

After upgrading

### Home Assistant Logs

Not available right now as the integration is currently failing to connect.

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by MJWMJW2** [comment]
Noticed similar here. 

I don’t believe it is related to 2024.11.0 as I have 2024.10.4. Automation show time out. 


Logger: custom_components.octopus_energy.api_client
Source: custom_components/octopus_energy/api_client/__init__.py:1050
integration: Octopus Energy ([documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy), [issues](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues))
First occurred: 7 November 2024 at 22:55:53 (63 occurrences)
Last logged: 16:48:13

Failed to connect. Timeout of ClientTimeout(total=None, connect=None, sock_read=20, sock_connect=20, ceil_threshold=5) exceeded.

**Comment by mt104** [comment]
I believe this issue is a duplicate of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/1067

I'll close this one and follow the existing issue.
