### ISSUE TITLE
Failed to serialize to JSON / Bad Data

### ISSUE THREAD

**Issue by ColinRobbins** [BottlecapDave/HomeAssistant-OctopusEnergy#1071]
### Describe the bug

On startup, the following is displayed in the logs.
Everything seems to work OK.

### Reproduction steps

Restart HA

### Expected behaviour

No error in the logs

### Tariff Code

N/A

### Integration Version

13.1.1

### Home Assistant Version

2024.11.1

### Fresh Install?

Not specified

### Home Assistant Logs

Logger: homeassistant.helpers.storage
Source: helpers/storage.py:543
First occurred: 19:37:02 (1 occurrences)
Last logged: 19:37:02

Error writing config for octopus_energy.A-XXX_intelligent_device: Failed to serialize to JSON: /config/.storage/octopus_energy.A-XXX_intelligent_device. Bad data at $.data=<custom_components.octopus_energy.api_client.intelligent_device.IntelligentDevice object at 0x7f59e67e30>(<class 'custom_components.octopus_energy.api_client.intelligent_device.IntelligentDevice'>

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and thanks for raising this. I'm surprised it continued working tbh with this error. I've fixed it in v13.1.2
