### ISSUE TITLE
Free Electricity Session Event

### ISSUE THREAD

**Issue by MalcolmSpencer** [BottlecapDave/HomeAssistant-OctopusEnergy#1072]
### Describe the feature

Would it be possible to have an event for the Free Sessions similar to the 'octopus_energy_all_octoplus_saving_sessions' event so that automation can be triggered

### Expected behaviour

Same as 'octopus_energy_all_octoplus_saving_sessions' but triggered when there is a new free event is found

### Use Case

Trigger additional automations when a new free event is detected

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [ ] I am willing/able to help contribute to the solution of this feature

**Comment by MalcolmSpencer** [comment]
I have found 'octopus_energy_all_octoplus_free_electricity_sessions' seems to work but its not documented in the events section.

So it looks like this just needs a documentation update.

**Comment by BottlecapDave** [comment]
Thanks for bringing this to my attention. It is now been updated in the docs
