### ISSUE TITLE
Add Cost tracker to device

### ISSUE THREAD

**Issue by Moohan** [BottlecapDave/HomeAssistant-OctopusEnergy#1073]
### Describe the feature

I don't know if this is possible, but it would be great to add the 'cost trackers' to the device they relate to. This would simplify adding them to an area as well as marking them visible when navigating via the device rather than just the octopus integration.

### Expected behaviour

The battery notes integration does this:
![Screenshot_20241110-103412](https://github.com/user-attachments/assets/6e64073b-3398-4cf9-b862-411aef7394bb)

### Use Case

Cost Tracker will always (?) be associated with a single device, so this just makes the link more explicit and a nicer user experience.

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello and thanks for the feedback. I'm sure it's possible, but not sure if it's a quick addition. I'll add it to the list, but not sure when I'll get to it. Happy for someone to submit a pull request with the change.

**Comment by BottlecapDave** [comment]
This was a quick fix by the looks of it and will be available in the next release

**Comment by BottlecapDave** [comment]
This should be completed as part of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v13.3.0
