### ISSUE TITLE
Won't install JSON Decode Error

### ISSUE THREAD

**Issue by pholcroft** [BottlecapDave/HomeAssistant-OctopusEnergy#1080]
### Describe the bug

I after a year of no issues, I have been having trouble with this add-on for the last month. I tried uninstalling and installing again, but I can't even get it to load anymore. It won't start up. It looks like it's having issues with some data it's loading. I'm not sure from where. If I could see what the data was it can't decode, the issue might become apparent. Is it possible to enable logging of this?

### Reproduction steps

Install using HACs

### Expected behaviour

It loads.

### Tariff Code

Agile

### Integration Version

v13.1.3

### Home Assistant Version

2024.11.1

### Fresh Install?

Not specified

### Home Assistant Logs

Logger: homeassistant.setup
Source: setup.py:416
First occurred: 07:02:07 (1 occurrences)
Last logged: 07:02:07

Error during setup of component octopusagile
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopusagile/__init__.py", line 73, in setup
    data = json.load(f)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3659 (char 3658)

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. Sorry that you're having issues but the logs you've provided is not associated with this integration. Your logs are referencing octopusagile, whereas this is octopus_energy :)

If you have any issues with this integration, feel free to raise a new ticket.
