### ISSUE TITLE
Unable to initiate plugin:   Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by Womble-1** [BottlecapDave/HomeAssistant-OctopusEnergy#1082]
### Describe the bug

Copied v into the custom_componets dir. 
When I go to add/configure the integration I get the following error ```Config flow could not be loaded: {"message":"Invalid handler specified"}```

### Reproduction steps

Configure the integration
I have seen the same with 13.1.1 and 13.1.3. 

### Expected behaviour

Config input

### Tariff Code

na

### Integration Version

13.1.3

### Home Assistant Version

Core 2024.11.1 Supervisor 2024.11.2 Operating System 13.2 Frontend 20241106.2

### Fresh Install?

Not specified

### Home Assistant Logs

Logger: homeassistant.config_entries
Source: config_entries.py:3249
First occurred: 23:04:17 (1 occurrences)
Last logged: 23:04:17

Error occurred loading flow for integration octopus_energy: No module named 'custom_components.octopus_energy.api_client_home_pro'

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry you're having this issue. I've just installed 13.1.3 on my test instance with no existing configuration and had no issues configuring the integration. The error you're posting suggests that something hasn't been copied over correctly in your instance. Please try copying again and making sure that you restart HA after copying and before you attempt to configure the integration.

**Comment by Womble-1** [comment]
You were spot on. I was missing some of the files.   100% my fault.   Thanks for taking the time to review.
