### ISSUE TITLE
Gas meter readings in m3 instead of kWh

### ISSUE THREAD

**Issue by nevado** [BottlecapDave/HomeAssistant-OctopusEnergy#109]
Hi, I have a SMETS1 smart meter and for some reason my gas usage is getting returned as m3 units in HA instead of kWh. So for example yesterday I had approx 50 kWh gas usage according to Octopus, but HA is showing 50 m3 consumed which is off by quite a large factor!

Can't see any obvious way to change this, any suggestions please? I've ticked the 'SMETS1' configuration box.

Just upgraded to v5.0.0 and no change.

Thanks for the great work btw!

**Comment by BottlecapDave** [comment]
HI I'm sorry to hear you're having issues. I have an SMETS1 sensor which was reporting back as m3, despite the [docs ](https://developer.octopus.energy/docs/api/#consumption)stating it should come back as kWh. I contacted Octopus Energy and stated the docs were wrong, but I guess this is not the case.

The sensor originally was setup to always return m3 as at the time that was all the energy dashboard supported, and changing it will result in a breaking change for some people.

I'll look into fixing the returned value so it's closer to what it should be in m3 (converting from m3 to kWh and vice versa can have minor discrepensies).

**Comment by Rill189** [comment]
I also have this issue. My m3 yesterday and the day before have read m3 in negative values.`

**Comment by Rill189** [comment]
Looking at the data, even with a V 1 smart meter the intergration is able to show me KWh used but the entity is displaying m3.

Can I change this so I can pull KWh instead?

**Comment by BottlecapDave** [comment]
@Rill189  The m3 negative values is a different issue (which I see that you've already commented on), unless you're seeing the negative values on the entity itself.

With the fix in the next release, the value provided by Octopus will be associated with the correct measurement (kwh or m3) in the attributes. The other measurement will then be calculated from this measurement.

Because the native measurement is coming from Octopus, I need to ensure the sensor is always reported as m3 so that I do not bring on another breaking change for those with gas sensors that report in kWh (change in measurement would cause long term statisitcs to stop).

**Comment by BottlecapDave** [comment]
This is now available in the latest release (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v5.1.0). 

The calculated kwh from m3 can be a little off from what Octopus Energy report in their app. They must be using different values for the calculation (https://octopus.energy/blog/statement-questions/), but don't disclose what those values are. Calorific value is the value in particular (which can differ according to https://www.valdaenergy.com/help-and-faqs/what-is-a-calorific-value-when-converting-gas-units-to-kwh).

I'm also thinking in the future I might break out the data into two separate sensors (kwh and m3) so users can decide which one they care about.

**Comment by BottlecapDave** [comment]
A new sensor is available which displays gas in `kwh`. There is also an attribute on both of the gas sensors that determine if the value comes straight from your meter or is calculated/estimated.
