### ISSUE TITLE
Timings on the "previous electric rate" sensor are 30 minutes late

### ISSUE THREAD

**Issue by ColinRobbins** [BottlecapDave/HomeAssistant-OctopusEnergy#110]
**Describe the bug**

The sensors for "current electric rate" and "previous electric rate" are out of sync by 30 minutes.
The timings shown in the "previous rate" sensor are late by 30 minutes.

**To Reproduce**

View the two sensors in `History`
![error](https://user-images.githubusercontent.com/13466873/209082155-1c219791-8c81-40e2-a4ab-34844eaf3cfe.png)

**Expected behavior**

The "previous" sensor should accurately reflect the timings of the rates.

**Home Assistant Version**

2022.12.6

**Integration Version**

v5.0.0

**Fresh Install?**

Was this from a fresh install or after an upgrade?
UPgrade

**Home Assistant Logs**

Are there any related logs available in Home Assistant? 
Nothing relevant

**Comment by BottlecapDave** [comment]
Sorry to hear you're seeing this issue. What tariff are you on? This can be found within the attributes of the sensor

**Comment by ColinRobbins** [comment]
> What tariff are you on?

tariff_code: E-1R-INTELLI-VAR-22-10-14-B

**Comment by BottlecapDave** [comment]
I've just looked at the data and this looks correct

```
{
	"count": 3,
	"next": null,
	"previous": null,
	"results": [
		{
			"value_exc_vat": 9.5238,
			"value_inc_vat": 9.99999,
			"valid_from": "2022-12-22T23:30:00Z",
			"valid_to": "2022-12-23T05:30:00Z"
		},
		{
			"value_exc_vat": 39.1482,
			"value_inc_vat": 41.10561,
			"valid_from": "2022-12-22T05:30:00Z",
			"valid_to": "2022-12-22T23:30:00Z"
		},
		{
			"value_exc_vat": 9.5238,
			"value_inc_vat": 9.99999,
			"valid_from": "2022-12-21T23:30:00Z",
			"valid_to": "2022-12-22T05:30:00Z"
		}
	]
}
```

It might be a misunderstanding of what the previous sensor does? As per the docs

> `sensor.octopus_energy_electricity_{{METER_SERIAL_NUMBER}}_{{MPAN_NUMBER}}_previous_rate` - The rate of the previous 30 minute period that energy consumption was charged at (including VAT).

The sensor is meant to be staggered by 30 minutes to the current sensor, so I think this is by design. It's main use is with the agile tariff.

Out of curiosity, what is your use case?

**Comment by ColinRobbins** [comment]
Thanks for the explanation.
I don’t have a use case as such, it was more of an observation.
I’ll close it.
