### ISSUE TITLE
Retrieve Agile rates even when on a Fixed tariff

### ISSUE THREAD

**Issue by SingingDwarf** [BottlecapDave/HomeAssistant-OctopusEnergy#1101]
### Describe the feature

I would like the system to retrieve details of the upcoming Agile rates and store in sensors, even though I am on a fixed tariff. This would allow me to compare the current cost to me vs the cost if I were on Agile.

Currently, the previous, current and next_day_rates sensors just show the fixed price from my current tariff.

### Expected behaviour

previous_day_rates, current_day_rates and next_day_rates to show current fixed price

New sensors required to show the same for the Agile tariff.

### Use Case

I am on a fixed rate tariff, but would like to compare against the Agile tariff.

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. If you're after comparing the cost against another tariff, you're going to be after tariff comparisons - https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/setup/tariff_comparison/

**Comment by SingingDwarf** [comment]
Many thanks for the tip - had forgotten that this was possible
