### ISSUE TITLE
Tariff Comparison Cost tracker using different calorific value

### ISSUE THREAD

**Issue by jwt99412** [BottlecapDave/HomeAssistant-OctopusEnergy#1110]
### Describe the bug

I have a tariff comparison sensor set up to compare my gas tariff (tracker) to the standard capped tariff. I have noticed when looking at the sensor attributes that the comparison tracker seems to be using a different calorific value to the one I have set up for the main sensor. See below:
![Screenshot 2024-12-10 at 09 53 32](https://github.com/user-attachments/assets/d969de5c-e1b2-42ae-86c6-e440c6a51411)
![Screenshot 2024-12-10 at 09 53 54](https://github.com/user-attachments/assets/023c3c26-ab82-45f3-a167-1bf6e9432784)
Comparison sensor:
![Screenshot 2024-12-10 at 09 45 01](https://github.com/user-attachments/assets/175f3000-a16b-4728-b68b-bf4828ed4c73)
![Screenshot 2024-12-10 at 09 45 35](https://github.com/user-attachments/assets/0453de46-16dd-46f1-a427-7f81c057b683)

### Reproduction steps

Opened the two sensor entities and looked at the cost calculation attributes. The main entity is using the correct 39.1 calorific value. The comparison entity is using 40.0 which is the default value used by the integration.

### Expected behaviour

Expected both sensors to be using the same value to make a good comparison between the baseline and comparison cost trackers. I entered the calorific value (39.1) in the main integration setup so expected the comparison to use that.

### Tariff Code

G-1R-SILVER-24-07-01-A

### Integration Version

13.2.1

### Home Assistant Version

2024.11.3 (Core) 2024.11.4 (Supervisor)

### Fresh Install?

After upgrading

### Home Assistant Logs

No log information gathered. Investigated by looking at entity attributes.

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry you're having an issue with this. It could be the sensor has restored the old calorific value instead of the one provided when the entity is setup. I'll take a look when I get a chance to see what's going wrong.

**Comment by jwt99412** [comment]
There is no hurry just wanted to bring it to your attention in case it was me not understanding how it works. :)

**Comment by BottlecapDave** [comment]
This should be fixed as part of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v13.3.0. you might need to wait for the underlying data to be updated before you see the correct calorific value.
