### ISSUE TITLE
Future prices event for the tariff comparison feature

### ISSUE THREAD

**Issue by airampg** [BottlecapDave/HomeAssistant-OctopusEnergy#1114]
### Describe the feature

First off, thank you so much for this integration. We are really thankful to have a project such as this one help us reduce our carbon footprint and energy bills. 

In response to the agile prices for the last couple of days, and since [Octopus has confirmed that it is fine to switch between smart tariffs as much as you want](https://www.facebook.com/groups/1058082791870255/posts/1335940214084510/), we switched to Cosy for the time being. This happened instantly but then we were left without a HA way of checking the Agile prices, to find the right time to switch back. 

### Expected behaviour

Have an event sensor that parses the data from the API e.g. https://api.octopus.energy/v1/products/{{Product Code}}/electricity-tariffs/{{Tariff code}}/standard-unit-rates/?period_from=YYYY-MM-DDThh:mm, and produces a event.octopus_energy_electricity_{{METER_SERIAL_NUMBER}}_{{MPAN_NUMBER}}_{{current/next}}_day_rates_{{TARIFF COMPARISON NAME}} that can then be used to see what prices will be for the next day and give an insight on whether it is worth switching for the following day or not. This would be part of the "tariff comparison" feature.

### Use Case

It would allow users to see the prices for the following day of the tariff of choice. 

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. It looks like someone might have ticked that they read the documentation when they hadn't ;)

The feature you're requesting already exists in the form of [tariff comparisons](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/setup/tariff_comparison/). This allows you to get the cost of your consumption against another tariff, which you can then plot in a graph or build an automation against.

**Comment by BottlecapDave** [comment]
Sorry. Just read the final comment

> This would be part of the "tariff comparison" feature.

Sounds like you have read the docs and I can't read.

There are no plans to expand this feature with "future rates" as I feel the rate information alone isn't enough to determine if a tariff is right for you as it's all dependent on you consumption habits. The rates are already available at a delay via the [event entity](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/setup/tariff_comparison/#previous-consumption-override-day-rates), which you're free to do what you want with. I'm not wanting the integration to put more unnecessary strain on the OE APIs, which already have their shakey moments.
