### ISSUE TITLE
Requesting diagnostics causes hass data to be polluted with wrong mpan/serial_number

### ISSUE THREAD

**Issue by timocov** [BottlecapDave/HomeAssistant-OctopusEnergy#1120]
### Describe the bug

[`async_get_diagnostics`](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/custom_components%2Foctopus_energy%2Fdiagnostics.py#L45-L123) that is used to get diagnostics uses `account_info` object that can be either retrieved from the API (new object) or [passed down from `async_get_device_diagnostics` function](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/custom_components%2Foctopus_energy%2Fdiagnostics.py#L134-L135), in which case the object will be modified and because it is used by the reference it will be updated in `hass.data` as well. This causes (at least) wrong requests to Octopus, but it is possible that some part of integration might stop working because of that (sorry I'm from mobile right now and it's really hard to work with the codebase/perform any deep analysis).

I tried adding `copy.deepcopy(account_info)` before the any modification and it seems fixed the issue.

Also I'm not sure, but it is possible that there are other places that might modify this object in a wrong way? Again, apologies I can't validate it right now (it's just a thought to check other possible places) as I'm away from my pc right now.

### Reproduction steps

1. Enable debug logs
1. Go to an octopus device and request diagnostics
1. Go to logs and observe 404 message similar to this:

```
2024-12-13 14:35:39.386 INFO (MainThread) [custom_components.octopus_energy.api_client] Response 404 for 'https://api.octopus.energy/v1/electricity-meter-points/2/meters/1/consumption?page_size=1' received
```

As you can see here both mpan and serial_number values are wrong and no longer valid.

### Expected behaviour

No data is modified, requests are made with original/correct data.

### Tariff Code

N/A

### Integration Version

13.2.1

### Home Assistant Version

2024.12.2

### Fresh Install?

Fresh install

### Home Assistant Logs

```
2024-12-13 14:35:39.386 INFO (MainThread) [custom_components.octopus_energy.api_client] Response 404 for 'https://api.octopus.energy/v1/electricity-meter-points/2/meters/1/consumption?page_size=1' received
```

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry you've encountered this issue. I'll fix it for the next release.

**Comment by BottlecapDave** [comment]
This should be fixed as part of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v13.3.0.
