### ISSUE TITLE
Requesting to add Indra Smart Pro 7.5kW Charger

### ISSUE THREAD

**Issue by svithanauk** [BottlecapDave/HomeAssistant-OctopusEnergy#1125]
### Provider name

Indra Smart Pro 7.5kW

### Features

- [X] Ability to bump charge
- [X] Ability to set the charge limit/target
- [X] Ability to set the time the charge will be at its target for
- [X] Ability to turn smart charge on/off
- [X] Ability to see planned dispatches

**Comment by BottlecapDave** [comment]
Hello. Can you please provide the exact provider name reported via the integration in the repair notice? Can you also please provide screenshots in the app showing each of the highlighted features?

**Comment by grahambro** [comment]
See image below![image](https://github.com/user-attachments/assets/f223114f-7cd9-4174-b94a-ea93fcbbc810)

**Comment by grahambro** [comment]
See image from HA ![image](https://github.com/user-attachments/assets/c7026696-72c7-492a-be2a-8f2391560245)

**Comment by craigarthur** [comment]
Just noticed this integration was available today and have also switched to it and getting the same "You have an intelligent provider of "INDRA" which is not recognised and therefore a reduced feature set has been enabled. Click on "Learn More" with instructions on what to do next."

**Comment by BottlecapDave** [comment]
Thanks you for supplying the screenshots. I'll try and get this integration enabled in the next release

**Comment by BottlecapDave** [comment]
This should now be available in [v13.4.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v13.4.0).

**Comment by grahambro** [comment]
Perfect thank you, hope you had a good Christmas
