### ISSUE TITLE
Break out the totals  into peak and off peak costs / kWh

### ISSUE THREAD

**Issue by Annaka007** [BottlecapDave/HomeAssistant-OctopusEnergy#113]
The entities show the totals for kWh and Costs, would it be possible to add  more entities that show the peak and off-peak separately from the totals ie the build up.

**Expected behavior**
for example :- 
  Peak kWH = 2 ,   Off-Peak kWH = 4 ,   Total kWH = 6
  Peak Cost = 24p ,   Off-Peak kWH = 48p ,   Total kWH = 72p    

This would make it so much easier to understand the total cost build up and usage and how the totals are calculated.
Apologise if there is an easy way to already do this, but I'm still learning

**Comment by BottlecapDave** [comment]
Hello, sorry for the late response. I'm afraid I'm not planning to add this in the future as peak/off peak is not a universal term for all tariffs and gets quite complicated.

**Comment by BottlecapDave** [comment]
Hi @Annaka007. After you raised this issue, I had a few more requests. This feature is now available in the latest release (v7.1.0) for previous consumption sensors. These sensors are disabled by default, but can be enabled to provide this functionality.
