### ISSUE TITLE
After 13.3.0 update, the integration reports a "Octopus Mini not valid for gas meter" warning

### ISSUE THREAD

**Issue by agherzan** [BottlecapDave/HomeAssistant-OctopusEnergy#1130]
### Describe the bug

I've updated the integration to 13.3.0. Since this update, a warning is produced:

```
Octopus Mini not valid for gas meter
Octopus Mini has been configured for account "[...]", but it's not available for gas meter [...]. If this is expected, you can ignore this notice, otherwise click "Learn More" with instructions on what to do next.
```

Also, I see an extra gas meter device created by the integration (the second one in the listing below). Removing it manually brings it back after a restart:

```
Gas Meter
1063 - Landis and Gyr
47720101
Octopus Energy

Gas Meter
E6VG470
<unknown>
Octopus Energy
```

The new device (E6VG470 above) only advertises two entities:

```
Current Rate Gas ([...]) 0.061672 GBP/kWh
Current Standing Charge Gas ([...]) £0.29
```

The new entities use different tariff codes: E6S16459292161. The old entities use E6S18721282261 as the tariff code. The values (readings) are identical.

### Reproduction steps

Update to 13.3.0

### Expected behaviour

No warning and no superfluous devices

### Tariff Code

E6S18721282261 vs E6S16459292161

### Integration Version

13.3.0

### Home Assistant Version

Core 2024.12.4 Supervisor 2024.12.0 Operating System 14.0 Frontend 20241127.8

### Fresh Install?

After upgrading

### Home Assistant Logs

Nothing relevant

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry that you're recieving this error. The integration just exposes any meter which has a valid tariff that OE reports back. 

The tariff codes that you've mentioned don't look like normal tariff codes, which suggest this is an error on OE side, which would require you to contact them to get it fixed. I assume you don't see these meters on the OE website?

If you turn on debug mode, following the instructions in the faq, reload the integration and then turn off debug mode, you should get some logs with the raw response returned by OE. You can then remove any personal identifiable information and upload here and I can see if there's anything obvious. But I feel, this is an OE issue that you'll need to contact them about.

**Comment by agherzan** [comment]
Thanks for coming back to me. It's curious that other people don't hit this and that I've been facing it exactly after an update. I'll try to debug a bit when I get a chance. I was hoping for a short "know issue", "here's a workaround", "see you later". :)

**Comment by BottlecapDave** [comment]
What version did you update from? The latest version didn't change anything in this area. It might have been because an update results in a reload, which is when new devices are discovered. You could try rolling back to the previous version to see if the sensors go away.

**Comment by agherzan** [comment]
I think you are right. The downgrade didn't help. I contacted Octopus and will return when I get more details.

**Comment by drmckean** [comment]
Those aren’t tariff codes. Those are GSME Serial Numbers.

**Comment by agherzan** [comment]
> Those aren’t tariff codes. Those are GSME Serial Numbers.

Interesting. I was wondering if I got that right. What is that exactly?

**Comment by drmckean** [comment]
I’m assuming that you have had your gas meter replaced at some point. 
The Octopus API will report both GSMEs for your MPRN. 
However, since only one of them is current, only one entity will report the correct data. 
Disable the entity that refers to the no longer used meter.

**Comment by agherzan** [comment]
Makes sense and I was just about to do that but this disappeared by:
1. Updating to 13.4.0
2. Remove the problematic device
3. Reload the plugin

No traces of the warning or the device anymore. Thanks anyway for your support.
