### ISSUE TITLE
Minimum Rate Issue on target sensor

### ISSUE THREAD

**Issue by dmelliott20** [BottlecapDave/HomeAssistant-OctopusEnergy#1132]
### Describe the bug

I'm not sure if this is a bug or whether i am misreading how this is supposed to work.
I have a maximum hours target sensor setup for my export meter on agile export tariff for 1.5 hours with a minimum rate of 0.16p set. So today, one of the half hourly rates is over 16p so i was expecting to get 1 x 30 minute time period to trigger on the sensor. As you can see this hasn't happened, am I expecting the wrong behaviour?

![image](https://github.com/user-attachments/assets/4c9cf18d-7fba-4c0f-9de4-608971517179)

### Reproduction steps

create a sensor with the same settings as in the attached spreadsheet

### Expected behaviour

i expected to get 1 x 30 minute slot where the sensor turned on 

### Tariff Code

E-1R-AGILE-OUTGOING-19-05-13-F

### Integration Version

13.1.3

### Home Assistant Version

2024.12.0

### Fresh Install?

Not specified

### Home Assistant Logs

none

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by dmelliott20** [comment]
No It didn’t….

![IMG_2545](https://github.com/user-attachments/assets/21242092-b261-4673-ae39-8fe911584051)


if it’s going to come on the target times attributes get populated with the actual half hours it’s going to be on

**Comment by BottlecapDave** [comment]
> if it’s going to come on the target times attributes get populated with the actual half hours it’s going to be on

I couldn't see your target times attribute on your original screenshot (or your new screenshot), which is why I asked. 

If you could make sure you're on the latest stable release, as there has been some changes which could result in the target rate sensor not updating correctly.

If the sensor is still not updating correctly, please follow the FAQ and supply the diagnostic information for your account.

**Comment by dmelliott20** [comment]
Ah yeah the attribute isn’t visible anyway on that page. 

Will do - thanks again.

**Comment by dmelliott20** [comment]
The target time entry is now appearing even if it’s blanks so that’s a definite change in behaviour post update. Will close this and reopen with diag data if it reoccurs.

Thanks again.
