### ISSUE TITLE
Import Targets get "Export" entity name

### ISSUE THREAD

**Issue by usbrit** [BottlecapDave/HomeAssistant-OctopusEnergy#116]
I have created both import and export targets (I have both meters) but both get named Export (Octopus Energy Target Export 3i_import)

Can we either name as an import Target or remove the Export text from the name?

Using version 5.0.0

Don't see this addressed in the upgrade notes for 5.1.0 but haven't upgraded yet, so sorry if this is already fixed.

**Comment by andynash** [comment]
Also seeing this (in 5.1.0), not sure yet whether it affects functionality?

I only have an import meter, but all import targets are configured with export in the entity ID and name.

**Comment by BottlecapDave** [comment]
I plan to fix this over the weekend and do a new release (breaking change)

**Comment by andynash** [comment]
> I plan to fix this over the weekend and do a new release (breaking change). Sorry for the delay.

Thanks! In the meantime, I've successfully updated the entity IDs an names in .storage/core.entity_registry, but obviously that is unwise, YMMV and I'm not sure yet that they work properly 😁

**Comment by BottlecapDave** [comment]
This has now been resolved in the latest version (v5.2.0). Luckily it was just the name, so no breaking change 🎉
