### ISSUE TITLE
Target rates not picking correct slots

### ISSUE THREAD

**Issue by th4rius** [BottlecapDave/HomeAssistant-OctopusEnergy#117]
Describe the bug

I have configured a target sensor for the Agile Outgoing tariff. I might be missing something so apologies in advance. 
Set hours to 7, continuous and 12:00 to 19:00. The sensor will come on regardless if it is highest or lowest rate.
To be honest I was only testing this to see if it works with any tariff as the description says it will look for the lowest rate which doesn't work for export. For outgoing would need the highest rate. I have tried it with intermittent option with same results.
When I don't specify the time range it will just go off and never turns on.

To Reproduce

Create a target rate sensor for Agile Outgoing tariff.

Expected behavior

Sensor to come on when price of export is highest or close to highest. This of course if it is able to track highest prices too.

Home Assistant 2022.12.4

v5.1.0

**Comment by BottlecapDave** [comment]
Hello, sorry you're having issues. 

As you've said you set the sensor to 7 hours between 12:00 and 19:00, it will just be on constanlty between 12:00 and 19:00.

If you set the hours to something like 1, then based on https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/61 and continous to on, then it should come on for only 1 hour when it's the highest combined between 12:00 and 19:00. If intermittent was on, then it would come on the two 30 minute periods that are the highest between 12:00 and 19:00.

I think this is something I need to spend some time and update the docs with better explainations, but hope this explaination helps :)

**Comment by th4rius** [comment]
Ok thanks for the explanation. And great work on this module. I have tested both cont and intermittent and it seems to work. However it is picking the lowest price.
What determines in the code to pick lowest or highest? Is it the is_export attribute? 
Mine shows false on that one even though it is definitely an export tariff. Not sure why.

**Comment by th4rius** [comment]
This is now working for me. The export attribute is now showing true and it is tracking highest prices.
Thanks for support.

**Comment by BottlecapDave** [comment]
The "export" part is determined by the meter you assign to the sensor. I'm limited in how these meters are displayed by Home Assistant, but will try and make this better. Did you do anything for the export attribute to start displaying?

**Comment by th4rius** [comment]
That attribute is set by Octopus and the tarrif as you mentioned. Mine was not set to true because my export tariff had an issue and the team had to run something in the background to fix. After that it changed to true. 
On the another note. The targets are working but it would be good if I could select rolling option but also select just one highest price in the time range. At the moment it will find the highest but then it will find another within the set time range and turn on again. This happens if I set 0.5h and let's say 6-10am. It will pick one at 6.30 and then another at 9 maybe. Tried both int and cont options.
So if I could tick another box saying only one half hour within the time range that would be good.

**Comment by BottlecapDave** [comment]
> At the moment it will find the highest but then it will find another within the set time range and turn on again. This happens if I set 0.5h and let's say 6-10am. It will pick one at 6.30 and then another at 9 maybe

This is where you would uncheck `Re-evaluate multiple times a day`. With this unchecked, it will find the highest 0.5h slot between 6 and 10 and not come on any other time until the next day.
