### ISSUE TITLE
Export meter not appearing 

### ISSUE THREAD

**Issue by mdeakin99** [BottlecapDave/HomeAssistant-OctopusEnergy#118]
Hi

Since installing this awesome Integration,  I have got solar and now have an Export meter which appears in the Octopus app.

I have tried clicking on Configure and re-entering the API key by I still have two devices in the integration,  was expecting another device to appear.

Totally possible I am doing something wrong or understanding incorrectly.  Any help appreciated

**Comment by BottlecapDave** [comment]
Hello.

You should just need to reboot Home Assistant or reload the integration (You'll need to select "octopus energy" within the integrations if you've set up target sensors to achieve this)

**Comment by mdeakin99** [comment]
Hi

I have done several reboots since the new export meter appeared in the Octopus app.

To make sure I understand what I should see,  should it change from two devices to three devices listed under the Integration?

Mark

On 8 Jan 2023, at 18:53, David Kendall ***@***.***> wrote:

﻿

Hello.

You should just need to reboot Home Assistant or reload the integration (You'll need to select "octopus energy" within the integrations if you've set up target sensors to achieve this)

**Comment by mdeakin99** [comment]
Damn it.  No sooner had I sent that email, it's now appeared as a third device.

Sorry

On 8 Jan 2023, at 19:30, Mark Deakin ***@***.***> wrote:

﻿
Hi

I have done several reboots since the new export meter appeared in the Octopus app.

To make sure I understand what I should see,  should it change from two devices to three devices listed under the Integration?

Mark

On 8 Jan 2023, at 18:53, David Kendall ***@***.***> wrote:

﻿

Hello.

You should just need to reboot Home Assistant or reload the integration (You'll need to select "octopus energy" within the integrations if you've set up target sensors to achieve this)

**Comment by BottlecapDave** [comment]
I was about to say I believe you'll have the same number of devices, but you should have additional sensors, but it appears you'll have additional devices as well. I think it depends on the users setup.

Glad that they're coming through for you.
