### ISSUE TITLE
sensors not showing up

### ISSUE THREAD

**Issue by skingun** [BottlecapDave/HomeAssistant-OctopusEnergy#12]
Installed integration using HACS and rebooted. Sensors not showing up.

**Comment by BottlecapDave** [comment]
I'm sorry to hear that. Are you seeing anything in the logs? What tarrif are you on?

I'm also surprised to hear you installed this via HACS, as I haven't actively added it. Are you sure it's this integration you're after?

**Comment by skingun** [comment]
I'm on Octopus 12M Fixed February 2020 v1.

Pretty sure it's this one:

![image](https://user-images.githubusercontent.com/34143011/134816605-565fb54d-3810-4df5-918d-cb57efadc2d7.png)

I'll try a manual approach. Quite new to HA and still finding my way around.

**Comment by BottlecapDave** [comment]
Yeah that looks like this integration. Are you seeing any errors in the Home Assistant logs? (Configuration -> Logs). You're after errors that have been raised by this integration. Sorry for the basic questions, but I assume you've configured the integration after installing and rebooting your home assistant instance

**Comment by skingun** [comment]
I see an error.

![image](https://user-images.githubusercontent.com/34143011/134817336-2a170e72-83a3-4ee1-87e2-8b0b894b2f65.png)

This is after rebooting HA and configuring the integration.  However, when I click on configure it's now saying @Error - config flow could not be loaded'.

**Comment by BottlecapDave** [comment]
hmm that's not a helpful error message (my fault, not yours). If you click on that second error message, you might be able to get more information. It suggests it failed to get the rates, which I know there's an issue surrounding duel tarriffs (see https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/11)

 That configuration page is expected as it's a limitation with what you can do with the Home Assistant frontend to support multiple configurations.

**Comment by skingun** [comment]
Here's the information from the log:

Logger: custom_components.octopus_energy
Source: custom_components/octopus_energy/__init__.py:77
Integration: Octopus Energy (documentation, issues)
First occurred: 18:25:38 (1 occurrences)
Last logged: 18:25:38
Unexpected error fetching rates data: No active exception to reraise

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/octopus_energy/__init__.py", line 77, in async_update_data
    raise
RuntimeError: No active exception to reraise

My electricity and gas are on different tarrifs.  I don't have a smart gas meter so will only be using this for electricity but hope to have a smart gas meter in the future. 

If the problem here is to do with the dual tarrif, is there a way to remove the gas part?

**Comment by BottlecapDave** [comment]
Hmmm ok. Looking at the code it looks like it can't find an active agreement associated with your electricity meter. I might need to add some more debugging around that area to work out why.

**Comment by skingun** [comment]
How odd.  I'll watch this space!  :)

**Comment by BottlecapDave** [comment]
I've created a new release. When you get a chance, if you could install the latest version and report back the errors in the log file, I'll hopefully be able to see what's going wrong.

**Comment by skingun** [comment]
Tried the new release. 

There was a __pythoncache__ hiding in the cutom_components folder.  Had to SSH in to see it. It wasn't showing in File editor.

Unfortunately it's still not working. Here are the log details from the error:

This error originated from a custom integration.

Logger: custom_components.octopus_energy
Source: custom_components/octopus_energy/__init__.py:79
Integration: Octopus Energy (documentation, issues)
First occurred: 21:25:35 (1 occurrences)
Last logged: 21:25:35

Unexpected error fetching rates data: Unable to find active agreement: [[{'tariff_code': 'E-1R-F_FIXD_190809_200930_DD-A-DD', 'valid_from': '2019-11-04T00:00:00Z', 'valid_to': '2020-03-27T00:00:00Z'}, {'tariff_code': 'E-1R-FIX-12M-20-02-12-A', 'valid_from': '2020-03-27T00:00:00Z', 'valid_to': '2021-01-04T00:00:00Z'}]]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/octopus_energy/__init__.py", line 79, in async_update_data
    raise Exception(f'Unable to find active agreement: {all_agreements}')
Exception: Unable to find active agreement: [[{'tariff_code': 'E-1R-F_FIXD_190809_200930_DD-A-DD', 'valid_from': '2019-11-04T00:00:00Z', 'valid_to': '2020-03-27T00:00:00Z'}, {'tariff_code': 'E-1R-FIX-12M-20-02-12-A', 'valid_from': '2020-03-27T00:00:00Z', 'valid_to': '2021-01-04T00:00:00Z'}]]

**Comment by jimdhope** [comment]
I'm also having issues seeing the sensors in HA. Any help would be greatly appreciated. I get the following two Error:

1) Logger: homeassistant.components.sensor
Source: helpers/update_coordinator.py:161 
Integration: Sensor (documentation, issues) 
First occurred: 10:40:11 PM (1 occurrences) 
Last logged: 10:40:11 PM

Error while setting up octopus_energy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/octopus_energy/__init__.py", line 89, in async_update_data
    hass.data[DOMAIN][DATA_RATES] = await client.async_get_rates(product_code, tariff_code)
  File "/config/custom_components/octopus_energy/api_client.py", line 48, in async_get_rates
    valid_from = as_utc(parse_datetime(item["valid_from"]))
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 133, in parse_datetime
    return ciso8601.parse_datetime(dt_str)
TypeError: argument 1 must be str, not None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/octopus_energy/sensor.py", line 40, in async_setup_entry
    await async_setup_default_sensors(hass, entry, async_add_entities)
  File "/config/custom_components/octopus_energy/sensor.py", line 56, in async_setup_default_sensors
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 161, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: argument 1 must be str, not None

2) This error originated from a custom integration.

Logger: custom_components.octopus_energy
Source: util/dt.py:133 
Integration: Octopus Energy (documentation, issues) 
First occurred: 10:40:11 PM (1 occurrences) 
Last logged: 10:40:11 PM

Unexpected error fetching rates data: argument 1 must be str, not None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/octopus_energy/__init__.py", line 89, in async_update_data
    hass.data[DOMAIN][DATA_RATES] = await client.async_get_rates(product_code, tariff_code)
  File "/config/custom_components/octopus_energy/api_client.py", line 48, in async_get_rates
    valid_from = as_utc(parse_datetime(item["valid_from"]))
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 133, in parse_datetime
    return ciso8601.parse_datetime(dt_str)
TypeError: argument 1 must be str, not None

Hope you can help been trying to get Octopus into HA for a while now

**Comment by BottlecapDave** [comment]
As suspected, the error indicates that  Octopus aren't giving us an active agreement. I could fall back to the most recent agreement, but this might not give the most accurate rates. I'll need to contact Octopus to see what they suggest.

> Tried the new release. There was a '**pythoncache**' hiding in the 'cutom_components' folder. Had to SSH in to see it. It wasn't showing in File editor. Unfortunately it's still not working. Here are the log details from the error:
> 
> Logger: custom_components.octopus_energy Source: custom_components/octopus_energy/**init**.py:79 Integration: Octopus Energy (documentation, issues) First occurred: 21:25:35 (1 occurrences) Last logged: 21:25:35
> 
> Unexpected error fetching rates data: Unable to find active agreement: [[{'tariff_code': 'E-1R-F_FIXD_190809_200930_DD-A-DD', 'valid_from': '2019-11-04T00:00:00Z', 'valid_to': '2020-03-27T00:00:00Z'}, {'tariff_code': 'E-1R-FIX-12M-20-02-12-A', 'valid_from': '2020-03-27T00:00:00Z', 'valid_to': '2021-01-04T00:00:00Z'}]] Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data return await self.update_method() File "/config/custom_components/octopus_energy/**init**.py", line 79, in async_update_data raise Exception(f'Unable to find active agreement: {all_agreements}') Exception: Unable to find active agreement: [[{'tariff_code': 'E-1R-F_FIXD_190809_200930_DD-A-DD', 'valid_from': '2019-11-04T00:00:00Z', 'valid_to': '2020-03-27T00:00:00Z'}, {'tariff_code': 'E-1R-FIX-12M-20-02-12-A', 'valid_from': '2020-03-27T00:00:00Z', 'valid_to': '2021-01-04T00:00:00Z'}]]

**Comment by BottlecapDave** [comment]
This looks like a different unrelated issue where rates don't have a `valid_from` specified. I've therefore moved it to https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/13.

> I'm also having issues seeing the sensors in HA. Any help would be greatly appreciated. I get the following two Error:
> 
>     1. Logger: homeassistant.components.sensor
>        Source: helpers/update_coordinator.py:161
>        Integration: Sensor (documentation, issues)
>        First occurred: 10:40:11 PM (1 occurrences)
>        Last logged: 10:40:11 PM
> 
> 
> Error while setting up octopus_energy platform for sensor Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data return await self.update_method() File "/config/custom_components/octopus_energy/**init**.py", line 89, in async_update_data hass.data[DOMAIN][DATA_RATES] = await client.async_get_rates(product_code, tariff_code) File "/config/custom_components/octopus_energy/api_client.py", line 48, in async_get_rates valid_from = as_utc(parse_datetime(item["valid_from"])) File "/usr/src/homeassistant/homeassistant/util/dt.py", line 133, in parse_datetime return ciso8601.parse_datetime(dt_str) TypeError: argument 1 must be str, not None
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform await asyncio.shield(task) File "/config/custom_components/octopus_energy/sensor.py", line 40, in async_setup_entry await async_setup_default_sensors(hass, entry, async_add_entities) File "/config/custom_components/octopus_energy/sensor.py", line 56, in async_setup_default_sensors await coordinator.async_config_entry_first_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 161, in async_config_entry_first_refresh raise ex homeassistant.exceptions.ConfigEntryNotReady: argument 1 must be str, not None
> 
>     1. This error originated from a custom integration.
> 
> 
> Logger: custom_components.octopus_energy Source: util/dt.py:133 Integration: Octopus Energy (documentation, issues) First occurred: 10:40:11 PM (1 occurrences) Last logged: 10:40:11 PM
> 
> Unexpected error fetching rates data: argument 1 must be str, not None Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data return await self.update_method() File "/config/custom_components/octopus_energy/**init**.py", line 89, in async_update_data hass.data[DOMAIN][DATA_RATES] = await client.async_get_rates(product_code, tariff_code) File "/config/custom_components/octopus_energy/api_client.py", line 48, in async_get_rates valid_from = as_utc(parse_datetime(item["valid_from"])) File "/usr/src/homeassistant/homeassistant/util/dt.py", line 133, in parse_datetime return ciso8601.parse_datetime(dt_str) TypeError: argument 1 must be str, not None
> 
> Hope you can help been trying to get Octopus into HA for a while now

**Comment by skingun** [comment]
Thank you.

**Comment by BottlecapDave** [comment]
@LFishwick If you try the latest release, this will have the fix in to at least get you some prices. However, it's interesting that you say you're on the Octopus Go plan and that's not even mentioned in the agreements. Therefore I'll need to find out from Octopus Energy where you get this information from.

**Comment by LFishwick** [comment]
@BottlecapDave The fix has meant I now have entities being listed, with some prices shown and 2 each for gas and electricity consumption so definitely coming along. Going to see what it pulls down now in terms of data. Could it be my Go product is showing as an older one?

**Comment by BottlecapDave** [comment]
I've just had a response from Octopus Energy from someone called `phil.steele`. The response was as follows

```
Hi Dave,
Thanks for your email and good to hear you're working on the Home Assistant integration. Could you ask anyone with no active tariff reported to send a new email to agile@octopus.energy and I'll take a look to see if there's an issue on their accounts.
The Go tariff should be listed as the active tariff via the API - so again any issues via the agile email address and we can check.
Phil
```

It looks like this may not be the expected behaviour, so could I please ask anyone that isn't seeing the correct tariffs to email Octopus Energy as above?

Thanks

**Comment by LFishwick** [comment]
So a little bit of a further dig through. Despite only having one property with Octopus, I have moved address and had a smart meter installed at the address. It would appear as though this is being listed as different properties in your api call? The MPAN and MPRN / serial numbers pulled up for the entities are not matching what I can find on the developer dashboard. If I go and change a line in api_client.py to be properties[1] rather than [0] it finds the right ones. I'm guessing that is to do with it thinking there is more than one property associated to the account?

**Comment by BottlecapDave** [comment]
Now that is an interesting development. I'll update the logic to get the first property that hasn't been moved out of. I wonder if other people have experienced this have also moved house. @skingun @jamiedevivoo ?

**Comment by BottlecapDave** [comment]
I've created a new release (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v2.0.0) which now uses the first property that hasn't been moved out of. This should resolve your issue without your hack @LFishwick.

It would also be good to know if this fixes @skingun and @jamiedevivoo

**Comment by BottlecapDave** [comment]
As I haven't heard any news about this issue, I'm going to close it for now. If it's still an issue, please reopen the ticket.
