### ISSUE TITLE
Feature Request: Next Rate Sensor

### ISSUE THREAD

**Issue by sembeeuk** [BottlecapDave/HomeAssistant-OctopusEnergy#125]
Would it be possible to add a sensor for the next half hour? There is already current and previous, but next half hour would be useful. You could glance at the dashboard when looking to start something high consumption and notice that if you wait 10 minutes it is cheaper, or for use in automations.

**Comment by BottlecapDave** [comment]
Hello - This should now be available within the latest release (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v5.3.0).

**Comment by sembeeuk** [comment]
Thanks for doing that so promptly.
