### ISSUE TITLE
Upcoming saver sessions

### ISSUE THREAD

**Issue by djdarlo** [BottlecapDave/HomeAssistant-OctopusEnergy#131]
**Describe the feature**

Would it be possible to extract a list of upcoming saver sessions. I would ideally like to be able to force charge my battery prior to these sessions. 

**Expected behavior**

A service to pull back an array of upcoming saver sessions containing start date/time and end date/time.

**Comment by BottlecapDave** [comment]
Hello, you can currently retrieve the next saving session, as long as you've signed up for it. This is available as an attribute on `binary_sensor.octopus_energy_saving_session`. Based on the data I've seen so far, they only show one session in advance at a time. Would this help achieve what you are wanting to do?

**Comment by djdarlo** [comment]
Cool. I can see the data in the attributes box. Next joined event start and end. Need to work out to parse it, check it once a day maybe then set the batteries. :)

**Comment by BottlecapDave** [comment]
If you're still needing some help, you should be able to setup a binary template sensor using the following logic

```
{% set dateTimestamp = state_attr('binary_sensor.octopus_energy_saving_session', 'next_joined_event_start') %}
{% if dateTimestamp != None and (dateTimestamp - timedelta(hours = 24)) < now() %}
True
{% else %}
False
{% endif %}
```

As the data you've requested is available, I'll close this issue.

**Comment by djdarlo** [comment]
Thank-you - where would I put this code?  Still finding my way around HA :)
