### ISSUE TITLE
Saving Session state 'On' for 30 minutes instead of 60

### ISSUE THREAD

**Issue by MrNorm** [BottlecapDave/HomeAssistant-OctopusEnergy#132]
Thank you for this great integration. I've really enjoyed having it connected to my HA instance.

I've recently started taking part in the saving sessions but I had an issue which I can't seem to figure out.

I signed up for a session on 23rd January between 17:00 and 18:00, which is reflected in the state

![image](https://user-images.githubusercontent.com/64325/214270467-85255bbd-6a21-4e78-8031-d4ef77bf57a6.png)

But the state of the entity only enters 'On' halfway through the session

![image](https://user-images.githubusercontent.com/64325/214270571-db0fd4f0-c2ec-4764-94ee-d5f93871fcf8.png)

Is there anything I'm doing wrong with this integration? 

Thanks

**Comment by BottlecapDave** [comment]
This is very odd as the logic is very simple (loops through all joined sessions and checks if now fall between any).  I've personally never seen it not come on for the entire session. How long before the session started did you join?

**Comment by MrNorm** [comment]
Very strange! I did it the morning of. How regularly does the integration refresh? I wonder if perhaps I had external factors for this (e.g. internet connectivity issues)

**Comment by BottlecapDave** [comment]
It updates the saving sessions every 30 minutes. I'm not sure how soon after you've opted in Octopus Energy set this value. I assume you didn't have any related errors in your logs?

**Comment by BottlecapDave** [comment]
Another thought was do you remember if you restarted your HA instance around 5pm? There was a bug reported where attributes were not being restored correctly which might have caused the issue?

**Comment by MrNorm** [comment]
Hmm OK it was on the day but several hours prior to the session starting. 

I think you're on to something on the restarting point. I was tweaking the automations prior to the session starting so I suspect I restarted to refresh everything.

Happy to close as we've had a session since then without any issues and I suspect this was caused due to a restart
