### ISSUE TITLE
Incorrect Cost shown on Energy Dashboard

### ISSUE THREAD

**Issue by carlchurchman** [BottlecapDave/HomeAssistant-OctopusEnergy#133]
Since the latest version of the Octopus Energy integration, the cost is showing as double that actual cost on the Energy Dashboard. The KW/H for electricity and cubic meters for gas is showing as correct but the cost is double

Octopus Energy Integration:

![image](https://user-images.githubusercontent.com/76684215/214638051-2d335689-9e67-4555-9ab8-d86d16e80bac.png)

![image](https://user-images.githubusercontent.com/76684215/214638414-07f3a2a9-2b1c-4449-8541-87e959ba4cf2.png)

Energy Dashboard:

![image](https://user-images.githubusercontent.com/76684215/214638618-459444df-532b-442f-8942-db2f9e85f579.png)

**Comment by BottlecapDave** [comment]
This is odd and I'm not sure if it's an issue with the energy dashboard or the entity as the entity is showing the correct price. Did you do any home assistant restarts on the day which might have caused home assistant to count the price twice? 

Also how is the price calculated on the energy dashboard? I've not seen this and I have the `sensor.octopus_energy_electricity_xxx_xxx_previous_accumulative_cost` sensor added under the option `Use an entity tracking the total costs` which I think Home Assistant just reads but does nothing special with.

**Comment by carlchurchman** [comment]
Yes I did restart home assistant after upgrading the Octopus integration, it is odd that the KW/h valve was correct but the cost has doubled. Since I reported the issue the energy dashboard has been reporting the correct usage and cost so maybe it was some weird glitch, I am using the sensor.octopus_energy_electricity_xxx_xxx_previous_accumulative_cost on the energy dashboard to calculate cost.

**Comment by BottlecapDave** [comment]
This might be a qwerk with the way the energy dashboard works. Upon restarts, I restore the last known state of the sensor.

The calculated price depends on which sensor you add. If you use the current price sensor then it multiplies the energy value by that value, which is not ideal as the data is accumulative and a day old. With the way you've set it up, it was my understanding that it just took that value as is as. But the sensor must be added under the option `Use an entity tracking the total costs` which is the third one down (from memory).

I'll close this issue, but if you see it again feel free to reopen it
