### ISSUE TITLE
Attributes are missing for a short time after HA restart

### ISSUE THREAD

**Issue by lozzd** [BottlecapDave/HomeAssistant-OctopusEnergy#135]
**Describe the bug**

Since having ported the rates card, I've noticed by accident (since the card breaks) that certain attributes under the `current_rate` sensor are unavailable for a while after HA restarts (or the integration is restarted). 
E.g. the entire `rates` section is missing - this is the entire list of attributes under the `current_rate` sensor:

```
mpan: XXXXXXXXX
serial_number: XXXXXXXXXXX
is_export: false
is_smart_meter: true
unit_of_measurement: GBP/kWh
device_class: monetary
icon: mdi:currency-gbp
friendly_name: Octopus Energy Electricity XXXXXX XXXXXXXXXXX Current Rate
```

**To Reproduce**

Restart Home Assistant or the integration

**Expected behavior**

I'm not sure if this is new in HA 2023.2.X or I just never noticed it before, and I'm not sure if this is expected or not - just seeking clarification on that!

**Home Assistant Version**

2023.2.1

**Integration Version**

Latest

Thanks!

**Comment by BottlecapDave** [comment]
The state of entities are restored using HAs restore entity feature. Some attributes are loaded when the sensor is loaded as the information is available (e.g. serial number). Others are not populated until the data is loaded, which should be within a minute of HA starting up. I'll take a look to see if there's something I'm missing (the dev docs are missing a few features).

**Comment by BottlecapDave** [comment]
I think I've found the culprit. Doing some testing, and then it will be in the next release.

**Comment by BottlecapDave** [comment]
This fix should now be present in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v5.4.0.

**Comment by lozzd** [comment]
Confirmed! Just restarted to install the update and the rates were there instantly. Thanks!

**Comment by lozzd** [comment]
welp, had to roll back due to #140 - the current_rate sensor stops updating altogether

**Comment by BottlecapDave** [comment]
Sorry that this caused such an issue. This should now be resolved within https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v5.4.1

**Comment by BottlecapDave** [comment]
Closing as this should now be resolved.
