### ISSUE TITLE
Energy Cost Not Calculated

### ISSUE THREAD

**Issue by fibilt** [BottlecapDave/HomeAssistant-OctopusEnergy#139]
I am not able to get the cost when I set up the gas consumption with “use an entity with current price”.

My electricity is set up exactly as the gas, but for some reason, the gas cost is always £0. My energy (gas) dashboard configuration and energy dashboard information:

<img width="630" alt="Screenshot 2023-02-05 at 09 41 17" src="https://user-images.githubusercontent.com/49229847/216811893-b034e1cd-21ca-421b-bb13-51fa0e759de2.png">

I am using "Octopus Energy Gas G4P21843641700 621077107 Previous Accumulative Consumption" for gas usage and "Octopus Energy Gas G4P21843641700 621077107 Current Rate" to track cost  using the option "Use an entity with current price".

Am I missing something?

**Comment by BottlecapDave** [comment]
I usually add the "previous total cost" entity under the option of "use an entity tracking the total costs" as the current rate will be a day out in relation to the consumption (not an issue on fixed rate tariffs). 

However I'd expect it to be higher than zero. Does the entity have a value? If not do you have any errors in your Home Assistant logs? Also what tariff are you on (this should be in the attributes of your gas sensors)?

**Comment by fibilt** [comment]
> 
Thanks for your support here.

If I use option "use an entity tracking the total costs" it works, but I realised that cost is higher than what it should be. "Use static price" option also works (tested it today).

Re your question, yes the entity has a value (PFA), and no errors are reported in my HA logs. The only error I can see is when I try to use entity "Octopus Energy Gas G4P21843641700 621077107 Previous Accumulative Consumption (kWh)" that I get an unexpected unit of measurement warning (see screenshot attached).

My tariff is Occupier Flexible Octopus October 2021 v1.

Please let me know if further information is required.

<img width="1133" alt="Screenshot 2023-02-05 at 17 47 52" src="https://user-images.githubusercontent.com/49229847/216836216-3abaac3a-eda5-4ee2-b6c2-6511c174e7fd.png">
<img width="276" alt="Screenshot 2023-02-05 at 17 50 27" src="https://user-images.githubusercontent.com/49229847/216836378-d31d3ed0-56f1-4fae-a328-f608fcf73350.png">

**Comment by fibilt** [comment]
I have created a template sensor that reads the previous gas consumption in kWh value from the octopus sensor but I get the same unexpected unit of measurement when I select it as the gas consumption sensor in the energy dashboard.

Am I only the only one facing this issue? I run HA on docker btw.

Any help would be really appreciated!

**Comment by BottlecapDave** [comment]
Hmm very odd, this should have the correct measurement. I'll take a look at some point within the next week.

**Comment by fibilt** [comment]
cool thanks. Let me know if you need any further information.

**Comment by fibilt** [comment]
I think you are right. Since the last update, cost calculations seem to be correct. I have been monitoring energy cost on a daily basis and so far so good.

And yes, I have a crontab rule set up to reboot my HA server every day at 5am. Not sure I understand why this can be causing the issue though.

**Comment by BottlecapDave** [comment]
Ok. Are you happy for me to close this issue?
