### ISSUE TITLE
Additional sensors

### ISSUE THREAD

**Issue by tomukasteris** [BottlecapDave/HomeAssistant-OctopusEnergy#14]
Hello,

Electricity does have current rate sensor but gas doesn't. Can it be setup for Gas as well?

Can it be setup to pull standing charge for Electricity and Gas?

If all those are configured could you please add calculation on Python to calculate how much did cost per day for gas and electricity including standing charge? Something like this total cost so far Today, so far this Week, so far this Month?

**Comment by BottlecapDave** [comment]
Gas sensors should automatically be picked up assuming you have an active agreement with your gas meter (according to Octopus). Do you have any errors appearing in your Home Assistant logs?

In regards to cost, I will see if I can add this as an attribute on the current daily consumption sensors. I'll need to think about week and monthly costs.

**Comment by addrum** [comment]
I'm also only getting a current rate sensor for electricity but none for gas. No errors in HA logs. Screenshot of sensors that have been populated below. Note I'm not on a smart meter for either yet but was just curious if this would work anyway if that makes a difference.
![Screenshot 2022-01-07 154302](https://user-images.githubusercontent.com/2855069/148568457-bc66f1f7-72ac-400a-93c7-fdff681a236b.png)

**Comment by BottlecapDave** [comment]
A current gas rate sensor is now available in 3.1.0.

A previous day consumption cost sensor was added in 3.0.0, which includes the daily standing charge cost in both the value and as a separate attribute on the sensor. If you'd like a week/month calculation, then you will need to calculate this yourself. You could use something like https://www.home-assistant.io/integrations/utility_meter/ to achieve this.

If you have any other issues, let me know.
