### ISSUE TITLE
Rates attribute not updating

### ISSUE THREAD

**Issue by hotnuts21** [BottlecapDave/HomeAssistant-OctopusEnergy#140]
**Describe the bug**

The rates have not updated since I updated to the latest version today.  I noticed the current rate was wrong and it's still displaying the rate it was 13.40 this afternoon. 

**To Reproduce**

Unsure. 

**Expected behavior**

Correct rate to show

**Home Assistant Version**

2023.2.2

**Integration Version**

5.4.0

**Fresh Install?**

Upgrade but I've only been using homeassistant for a week.

**Home Assistant Logs**

This error is appearing in the log
2023-02-05 13:45:55.765 ERROR (MainThread) [custom_components.octopus_energy.api_client] Request failed (https://octopus.energy/api/v1/tracker/E-1R-AGILE-FLEX-22-11-25-D/daily/past/1/0): 503; {"error": "We're currently unable to retrieve tracker data"}

Further info and screenshots. 
![216845894-b8ded6f4-a1bf-4dfe-978b-567ee9bea21b](https://user-images.githubusercontent.com/5470425/216848748-5ebae009-ed6a-4137-b9e5-d2f12dabc1d9.png)
![Screenshot_20230205-212611](https://user-images.githubusercontent.com/5470425/216848749-a62f94f4-ba32-4dca-a8ab-8ec05730893f.png)

**Comment by hotnuts21** [comment]
`{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.2.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "5.15.76-v8",
    "supervisor": "2023.01.1",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "rpi_gpio": {
      "version": "2022.7.0",
      "requirements": [
        "RPi.GPIO==0.7.1"
      ]
    },
    "sonoff": {
      "version": "3.3.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "octopus_energy": {
      "version": "5.4.0",
      "requirements": []
    },
    "dwains_dashboard": {
      "version": "3.3.0",
      "requirements": []
    },
    "localtuya": {
      "version": "5.0.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.30.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "octopus_energy",
    "name": "Octopus Energy",
    "config_flow": true,
    "documentation": "https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/",
    "issue_tracker": "https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues",
    "ssdp": [],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@bottlecapdave"
    ],
    "version": "5.4.0",
    "iot_class": "cloud_polling",
    "is_built_in": false
  },
  "data": {
    "electricity_meter_points": [
      {
        "mpan": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "is_export": false,
            "is_smart_meter": true
          }
        ],
        "agreements": [
          {
            "valid_from": "2022-12-09T00:00:00+00:00",
            "valid_to": null,
            "tariff_code": "E-1R-AGILE-FLEX-22-11-25-D"
          }
        ]
      }
    ],
    "gas_meter_points": []
  }
}`

**Comment by oymyakon** [comment]
Hi I am getting the same problem.
Can you help me with a cure?
My error:-
This error originated from a custom integration.

Logger: custom_components.octopus_energy.api_client
Source: custom_components/octopus_energy/api_client.py:264
Integration: Octopus Energy (documentation, issues)
First occurred: 10:06:33 (24 occurrences)
Last logged: 10:17:44

Request failed (https://octopus.energy/api/v1/tracker/E-1R-AGILE-FLEX-22-11-25-E/daily/past/1/0): 503; {"error": "We're currently unable to retrieve tracker data"}

**Comment by BottlecapDave** [comment]
It looks like my assumption with Octopus Energy naming was incorrect when trying to fix tracker based tariffs. I will try and fix as soon as possible, but in the meantime I suggest moving back to the previous update.

**Comment by hotnuts21** [comment]
Ive got more errors in the log this morning, if these help.

> Request failed (https://octopus.energy/api/v1/tracker/E-1R-AGILE-FLEX-22-11-25-D/daily/past/1/0): 503; {"error": "We're currently unable to retrieve tracker data"}
> 10:13:34 AM – (ERROR) Octopus Energy (custom integration) - message first occurred at February 5, 2023 at 1:43:55 PM and shows up 2460 times
> Error doing job: Task exception was never retrieved
> 10:00:55 AM – (ERROR) Octopus Energy (custom integration) - message first occurred at February 5, 2023 at 2:00:56 PM and shows up 41 times
> Unexpected error fetching rates data: 'NoneType' object is not subscriptable
> 5:02:27 AM – (ERROR) Octopus Energy (custom integration)
> Failed to retrieve account
> 5:02:27 AM – (ERROR) Octopus Energy (custom integration)
> Request failed (https://api.octopus.energy/v1/graphql/): 504; <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html>
> 5:02:27 AM – (ERROR) Octopus Energy (custom integration)

**Comment by hotnuts21** [comment]
Confirm a full delete and reinstall of the integration has got it working again, I went back to 5.3.1.

Thanks

**Comment by BottlecapDave** [comment]
I'm sorry that this caused such an issue. This should now be resolved in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v5.4.1

**Comment by BottlecapDave** [comment]
Closing issue as this should now be resolved.
