### ISSUE TITLE
Can't configure Energy dashboard with new meters

### ISSUE THREAD

**Issue by jgclark** [BottlecapDave/HomeAssistant-OctopusEnergy#142]
(It's probably a configuration issue, not a bug, but I've been trying for days to fix it, and have so far failed.)

At the start of the month my meters were changed and now have SMETS2 ones. At that point I decided to start using your Integration, a year after starting to use HA. It has given me 2 devices + 12 entities, all of which look sensible.
But a week on, the Energy Dashboard graphs are still like this:
![Octopus Energy dashboard@2x](https://user-images.githubusercontent.com/1671754/217676145-05d49a76-d028-4287-b186-ed3cac785276.jpg)

The config for the Electricity part of the dashboard is:
![Dashboard Elec config@2x](https://user-images.githubusercontent.com/1671754/217676156-642c2c43-2814-4efa-b349-9c7e7231c6fe.jpg)

The Gas one is similar.

But here's the history from Octopus' own website:
![Octopus G+E from website@2x](https://user-images.githubusercontent.com/1671754/217676192-f280fe51-61c9-41ef-bc97-a28ec10baa07.jpg)

And the history from looking at the entities themselves shows that the Gas data in HA is OK (similarly look OK for Electricity):
![Octopus G+E HA History@2x](https://user-images.githubusercontent.com/1671754/217676110-2c770eee-ddcc-4f54-a15b-590a36bf7f67.jpg)

So the issue is how to best configure Energy Dashboard?

**Home Assistant Version** 2023.2.2
**Integration Version** 5.4.1
**Fresh Install?** Yes

**Comment by BottlecapDave** [comment]
I usually assign the total previous consumption entity to the option `Use an entity to track total costs`, especially if you're on a variable rate that can change from day to day.

I'm not sure why the energy dashboard is not reporting the data as it's working fine on my instance, but I have yet to update to 2023.2.x. Do you have any other errors appearing in your logs? I assume you've changed the names of the entities as they're not the default names? Also do you have any errors appearing in `developer-tools/statistics`?

**Comment by jgclark** [comment]
Thanks for the quick response. I've left it a day to see what happens, and the good news is I now have sensible-looking bargraph usage data in the dashboard. _But only for the most recent 2 out of the 9 previous days_.

Now picking up on your points:
> I usually assign the total previous consumption entity to the option Use an entity to track total costs, especially if you're on a variable rate that can change from day to day.

AFAICT I don't have a "total" entity to use with 'Use an entity to track total costs'. All the money entities are either costs that go up and down or rates. What should 'total' ones be called?

> I'm not sure why the energy dashboard is not reporting the data as it's working fine on my instance, but I have yet to update to 2023.2.x. Do you have any other errors appearing in your logs? 
I turned on logs as suggested in FAQ, but my device then ran too slowly, even on an RPi4 with a lot of RAM.

> I assume you've changed the names of the entities as they're not the default names? 
Yes. Here's a significant issue, which is largely beyond your ctronol. The entity names are so long that I can never see the end of the name in any of the HA screens other than Developer Tools. 

> Also do you have any errors appearing in developer-tools/statistics?
One. "sensor.gas (m3): There is no state available for this entity". 
I pressed FIX ISSUE on this before I submitted this issue; interesting that it's back again. I've tried it again, and the issue has disappeared, but no change to the dashboard display.

Any further ideas why the first week of data is present somewhere in HA but isn't being displayed?

**Comment by BottlecapDave** [comment]
> AFAICT I don't have a "total" entity to use with 'Use an entity to track total costs'. All the money entities are either costs that go up and down or rates. What should 'total' ones be called?

Interesting, as outlined in the readme, you'll be after `sensor.octopus_energy_electricity_{{METER_SERIAL_NUMBER}}_{{MPAN_NUMBER}}_previous_accumulative_cost` or `sensor.octopus_energy_gas_{{METER_SERIAL_NUMBER}}_{{MPRN_NUMBER}}_previous_accumulative_cost`

This does go up/down but on a daily basis which is what the energy dashboard is after.

> I turned on logs as suggested in FAQ, but my device then ran too slowly, even on an RPi4 with a lot of RAM.

I have them turned on a RPi4 as well, but is fine. However I don't have a lot of intensive integrations.

> Any further ideas why the first week of data is present somewhere in HA but isn't being displayed?

I'm not too sure tbh. I wonder if there's any logging around the energy dashboard that might provide some insight. Looks like other users have had issues (https://community.home-assistant.io/t/energy-dashboard-not-showing-historical-data/353494) which might help with the investigation?
