### ISSUE TITLE
Log errors, does not update sensors and unknown values

### ISSUE THREAD

**Issue by neildsb** [BottlecapDave/HomeAssistant-OctopusEnergy#143]
Log errors, does not update sensors and unknown values

![image](https://user-images.githubusercontent.com/91122872/217799650-44a1955d-04c7-4b30-b4ed-aa252a582679.png)

Home Assistant 2023.2.3
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

This error originated from a custom integration.

Logger: custom_components.octopus_energy.api_client
Source: custom_components/octopus_energy/api_client.py:361
Integration: Octopus Energy (documentation, issues)
First occurred: 11:18:49 am (6 occurrences)
Last logged: 11:19:52 am

Request failed (https://api.octopus.energy/v1/products/TESLA-IMPORT-12M-FIX-22-07-28): 404; {"detail":"Not found."}
Request failed (https://api.octopus.energy/v1/products/TESLA-EXPORT-12M-FIX-22-07-28): 404; {"detail":"Not found."}

This error originated from a custom integration.

Logger: custom_components.octopus_energy.api_client
Source: custom_components/octopus_energy/api_client.py:268
Integration: Octopus Energy (documentation, issues)
First occurred: 11:18:49 am (8 occurrences)
Last logged: 11:19:52 am

Request failed (https://api.octopus.energy/v1/products/TESLA-IMPORT-12M-FIX-22-07-28/electricity-tariffs/E-1R-TESLA-IMPORT-12M-FIX-22-07-28-E/standard-unit-rates?period_from=2023-02-09T00:00:00Z&period_to=2023-02-11T00:00:00Z): 404; {"detail":"Not found."}
Request failed (https://api.octopus.energy/v1/products/TESLA-EXPORT-12M-FIX-22-07-28/electricity-tariffs/E-1R-TESLA-EXPORT-12M-FIX-22-07-28-E/standard-unit-rates?period_from=2023-02-09T00:00:00Z&period_to=2023-02-11T00:00:00Z): 404; {"detail":"Not found."}
Request failed (https://api.octopus.energy/v1/products/TESLA-EXPORT-12M-FIX-22-07-28/electricity-tariffs/E-1R-TESLA-EXPORT-12M-FIX-22-07-28-E/standard-unit-rates?period_from=2023-02-08T00:00:00Z&period_to=2023-02-09T00:00:00Z): 404; {"detail":"Not found."}
Request failed (https://api.octopus.energy/v1/products/TESLA-IMPORT-12M-FIX-22-07-28/electricity-tariffs/E-1R-TESLA-IMPORT-12M-FIX-22-07-28-E/standard-unit-rates?period_from=2023-02-08T00:00:00Z&period_to=2023-02-09T00:00:00Z): 404; {"detail":"Not found."}

**Comment by BottlecapDave** [comment]
Hello, sorry to see you're having issues.

I don't think I can fix this issue, as I'm just using the data that is being returned by Octopus. The fact it can't even find the product suggests a configuration issue. Have you only just started using the integration or switched tariffs? You might need to contact them directly.

**Comment by neildsb** [comment]
thanks Dave, it has been working without any problems previously, however my tariff changed on the 3rd Feb, I will reach out to Octopus

**Comment by Garrycollins1978** [comment]
I do am getting this same error, with the same log errors too, i suspect there is an issue there side.

**Comment by cholek3** [comment]
Similar issue. I have copied and pasted my API key, so there is no error there. My account was just switched from Bulb to Octopus, so I will wait a bit before trying again.
```
Last logged: 13:20:54

Request failed (https://api.octopus.energy/v1/products/BULB-CRED-VAR-V1/electricity-tariffs/E-1R-BULB-CRED-VAR-V1-M/standard-unit-rates?period_from=2023-02-18T00:00:00Z&period_to=2023-02-20T00:00:00Z): 404; {"detail":"Not found."}
Request failed (https://api.octopus.energy/v1/products/BULB-CRED-VAR-V1/electricity-tariffs/E-1R-BULB-CRED-VAR-V1-M/standard-unit-rates?period_from=2023-02-18T00:00:00Z&period_to=2023-02-20T00:00:00Z): 502; <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx</center> </body> </html>
Request failed (https://api.octopus.energy/v1/products/BULB-CRED-VAR-V1/electricity-tariffs/E-1R-BULB-CRED-VAR-V1-M/standard-unit-rates?period_from=2023-02-18T00:00:00Z&period_to=2023-02-20T00:00:00Z): 401; {"detail":"Invalid API key."}
```

**Comment by Garrycollins1978** [comment]
> 

This is the exact same issues for myself, the API key is corretc but in the logs it says the same as yours. wil keep trying.

2023-02-21 09:39:18.519 ERROR (MainThread) [custom_components.octopus_energy.api_client] Request failed (https://api.octopus.energy/v1/products/BULB-CRED-VAR-V1): 404; {"detail":"Not found."}
2023-02-21 09:39:18.648 ERROR (MainThread) [custom_components.octopus_energy.api_client] Request failed (https://api.octopus.energy/v1/products/BULB-CRED-VAR-V1/electricity-tariffs/E-1R-BULB-CRED-VAR-V1-G/standard-unit-rates?period_from=2023-02-21T00:00:00Z&period_to=2023-02-23T00:00:00Z): 404; {"detail":"Not found."}
2023-02-21 09:39:18.651 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved

**Comment by neildsb** [comment]
thanks, its looking good for me.
