### ISSUE TITLE
Plotting Rates with Apex Charts

### ISSUE THREAD

**Issue by fboundy** [BottlecapDave/HomeAssistant-OctopusEnergy#145]
Not exactly a feature request but an example of how to plot up Agile rates in ApexCharts which may be of interest:

      type: custom:apexcharts-card
      header:
        show: true
        show_states: true
        colorize_states: true
        title: Agile Export Rates
      graph_span: 1d
      stacked: false
      span:
        start: day
      yaxis:
        - min: 0
          max: 35
          decimals: 1
      series:
        - entity: >-
            sensor.octopus_energy_electricity_{{METER_SERIAL_NUMBER}}_{{MPAN_NUMBER}}_current_rate
          type: column
          name: ''
          color: yellow
          opacity: 1
          stroke_width: 0
          unit: W
          show:
            in_header: false
            legend_value: false
          data_generator: |
            return entity.attributes.rates.map((entry) => {
               return [new Date(entry.from), entry.rate];
             });
          offset: '-15min'
![image](https://user-images.githubusercontent.com/5152701/218256490-514b49ea-1c71-4903-9e98-6c45fb1d243c.png)

**Comment by BottlecapDave** [comment]
Added to my to-do list. We already have a community plugin for displaying agile rates in a table, so will add this in a similar location (or new location)

**Comment by fboundy** [comment]
Great . I also have a couple of template sensors that will extract Eco7 Day and Night rates and times from the attributes if you think these would be generally useful:

```
  - sensor:
      - name: "Eco7 Day Rate"
        unique_id: eco7_day_rate
        state: >-
          {{state_attr('sensor.octopus_energy_electricity_19m1337498_1610032016836_current_rate', 'rates') | map(attribute='rate') | list | max}}
          
      - name: "Eco7 Night Rate"
        unique_id: eco7_night_rate
        state: >-
          {{state_attr('sensor.octopus_energy_electricity_19m1337498_1610032016836_current_rate', 'rates') | map(attribute='rate') | list | min}}

      - name: "Next Eco7 Start"
        unique_id: next_eco7_start
        state: >-
          {% set min_rate = state_attr('sensor.octopus_energy_electricity_19m1337498_1610032016836_current_rate', 'rates') | map(attribute='rate') | list | min %}
          {% set x = state_attr('sensor.octopus_energy_electricity_19m1337498_1610032016836_current_rate', 'rates') | selectattr('rate', 'eq', min_rate) | list %}
          {{x | map(attribute='from') | list | min }}        
          
      - name: "Next Eco7 End"
        unique_id: next_eco7_end
        state: >-
          {% set min_rate = state_attr('sensor.octopus_energy_electricity_19m1337498_1610032016836_current_rate', 'rates') | map(attribute='rate') | list | min %}
          {% set x = state_attr('sensor.octopus_energy_electricity_19m1337498_1610032016836_current_rate', 'rates') | selectattr('rate', 'eq', min_rate) | list %}
          {{x | map(attribute='to') | list | max }}        
```

**Comment by plandregan** [comment]
I have this Apex chart cost vs power
Happy to share code

![Screen Shot 2023-03-19 at 12 21 44](https://user-images.githubusercontent.com/109735958/226174817-f6392fe5-0bc4-496b-9ca8-02e84ebd2170.png)

**Comment by plandregan** [comment]
type: custom:apexcharts-card
experimental:
  color_threshold: true
header:
  show: true
  floating: true
  title: Cost vs Power
graph_span: 24h
show:
  last_updated: true
  loading: true
apex_config:
  legend:
    show: false
  chart:
    zoom:
      type: x
      enabled: true
      autoScaleYaxis: false
    toolbar:
      show: true
      autoSelected: zoom
    xaxis.type: datetime
  fill:
    type: gradient
    gradient:
      shadeIntensity: 0.1
      opacityFrom: 0.3
      opacityTo: 1
      inverseColors: true
series:
  - entity: sensor.octopus_energy_electricity_***************************_current_rate
    transform: return x * 100;
    type: area
    name: GBP/kWh
    yaxis_id: pence
    color: lightblue
    group_by:
      func: avg
      duration: 5m
    stroke_width: 2
    extend_to: now
    show:
      extremas: false
      header_color_threshold: true
  - entity: sensor.givtcp_grid_power
    transform: return x /1000;
    type: line
    invert: true
    name: Power
    yaxis_id: kwh
    group_by:
      func: avg
      duration: 5m
    color: red
    stroke_width: 2
    extend_to: now
yaxis:
  - id: pence
    min: 0
    max: 35
    opposite: false
  - id: kwh
    min: 0
    max: 10
    opposite: true

**Comment by BottlecapDave** [comment]
> @BottlecapDave could I please request enabling statistics for these sensors? This is so the rates can be recorded indefinitely and plotted more cheaply than life data. Currently only one entity shows up in the Developer Tools/Statistics section.
> 
> Guidelines from HA: https://www.home-assistant.io/more-info/statistics/ https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

@andrzej-r I've moved your issue to a separate ticket. Please raise a separate ticket in the future if you're having issues instead of hijacking another unrelated issue. It makes it very hard to track what needs fixing otherwise and your issue will be potentially ignored

**Comment by BottlecapDave** [comment]
After too long, these examples can now be found in the new [community contributions document](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/community.md)

**Comment by BottlecapDave** [comment]
@plandregan a user is having [issues](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/discussions/264) with the code you provided due to formatting. Is there any chance you could update us on the formatting of the card?

**Comment by plandregan** [comment]
[Load vs cost chart.txt](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/11768082/Load.vs.cost.chart.txt)

**Comment by BottlecapDave** [comment]
Thanks .Another user put in a code review to fix the issue
