### ISSUE TITLE
Possible to have a Current joined event start/end/duration remaining ?

### ISSUE THREAD

**Issue by p6sfrx725z28knfy** [BottlecapDave/HomeAssistant-OctopusEnergy#148]
**Describe the feature**

While I have been using the upcoming saving session functionality from #131 to schedule automations, I noticed that the next joined event details vanish as soon as the event starts.. which I guess make sense.

But while I know from the binary sensor that a saving session is active, I couldn't see the end time anywhere and wondered if it could be useful to have equivalent start/end/duration (remaining) values for a currently active event as you have kindly added for the next joined event? :)

Thanks

**Expected behavior**

```
Current joined event start:                               '2023-02-30T09:00:00+00:00'
Current joined event end:                                 '2023-02-30T10:00:00+00:00'
Current joined event duration in minutes:                 '27:03'
```

**Comment by BottlecapDave** [comment]
Hello. I'll add this to my to-do list.

**Comment by BottlecapDave** [comment]
While I'm not sure when the next event will be, this has been updated in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v6.5.0
