### ISSUE TITLE
Local variable 'valid_from' referenced before assignment

### ISSUE THREAD

**Issue by stretch-c** [BottlecapDave/HomeAssistant-OctopusEnergy#15]
I have just installed the custom component and have tried to set this up. However it returns errors in the log as below.

![Log](https://user-images.githubusercontent.com/52446911/135738180-ba518bfb-ea9c-4ff7-85f7-4a3cd07cf2a9.PNG)

When looking into the "Unexpected error fetching rates data: local variable 'valid_from' referenced before assignment" entry the traceback is as per below:

> Logger: custom_components.octopus_energy
>Source: custom_components/octopus_energy/api_client.py:49
>Integration: Octopus Energy (documentation, issues)
>First occurred: 4:09:58 (1 occurrences)
>Last logged: 4:09:58
>
> 
> Unexpected error fetching rates data: local variable 'valid_from' referenced before assignment
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
>     self.data = await self._async_update_data()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
>     return await self.update_method()
>   File "/config/custom_components/octopus_energy/__init__.py", line 89, in async_update_data
>     hass.data[DOMAIN][DATA_RATES] = await client.async_get_rates(product_code, tariff_code)
>   File "/config/custom_components/octopus_energy/api_client.py", line 85, in async_get_rates
>     results = self.process_rates(data, period_from, period_to)
>   File "/config/custom_components/octopus_energy/api_client.py", line 49, in process_rates
>     if valid_from < period_from:
> UnboundLocalError: local variable 'valid_from' referenced before assignment

I'm not sure if this is to do with something I have missed or if it is infact an issue? The integration seemed to setup fine with my details from the UI.

I did notice that there was a problem with valid_from in issue #13 but the issue I'm having seems to be different to what was reported there and I'm using your latest files which I believe you already had the fix for that issue in?

Thanks!

**Comment by BottlecapDave** [comment]
Sorry about that. I'm still trying to find the tariff where this is occuring, so finding it hard to test. I've updated the culprit code which should now be working.

**Comment by stretch-c** [comment]
Hi Dave,

No problem at all, absolutely no need to apologise!

Thanks for looking into this so quickly and coming up the fix. I have just tried the updated code and this has now worked and has created 6 entities.

Thanks again!

**Comment by BottlecapDave** [comment]
No problem and glad to hear it's working. I'll close this issue for now.
