### ISSUE TITLE
Create Agile Outgoing sensor

### ISSUE THREAD

**Issue by craigbeat** [BottlecapDave/HomeAssistant-OctopusEnergy#150]
Similar to the Agile rates for consumption, could you also please add the rates for Agile Outgoing with similar behaviour so it can be used to trigger energy export on Solar PV / Battery systems?

**Comment by BottlecapDave** [comment]
Hello, when you say the agile rates for consumption, what are you referring to? The "current rate" sensors of the "target rate" sensors?

**Comment by BottlecapDave** [comment]
or do you mean the accumulative consumption sensors?

**Comment by craigbeat** [comment]
Sorry, I meant that, at the moment you get the agile costs to consume electricity / gas, but there are no export rates, if that makes sense?

**Comment by BottlecapDave** [comment]
You _should_ already be retrieving export rates as well, as the integration creates sensors for each import/export meter. The attribute of the rate sensor will have `is_export` set to `true`. You can also setup target rate sensors to come on when the highest prices are available within a 24 hour period.

If you're not seing this, and you have just switched to Agile, then you'll need to restart HA. Ive seen some instances where it's taken a while for the API to reflect tariff changes.

If you still can't see it, then can you please paste the diagnostics JSON file that can be downloaded from the electricity meter device within Home Assistant?

**Comment by craigbeat** [comment]
Ah, you are correct - I was looking for the term 'outgoing' in the sensor name, but having gone through all the sensors, I've found the ones that match the outgoing rates. Thanks for building this integration! I'll close this ticket.
