### ISSUE TITLE
Extract values from the rates array? 

### ISSUE THREAD

**Issue by jamesking420** [BottlecapDave/HomeAssistant-OctopusEnergy#151]
Hello, 

I wondered if you might be able to add some documentation to show how to retrieve specific values from the 'rates' array as a sensor template or similar? Context here: 

https://community.home-assistant.io/t/template-query-with-array/537252

Thanks! 

James

**Comment by jamesking420** [comment]
```
{% set dt_required = (as_datetime((as_timestamp(now())/1800)|round(0,'floor')|int * 1800)) %}
{{ state_attr('sensor.octopus_energy_electricity_14e0453806_1900013341923_current_rate', 'rates')
          | selectattr('from', 'equalto', dt_required ) | map(attribute='rate') | first}}
```
This works

**Comment by BottlecapDave** [comment]
Glad you managed to find your answer. The timing at which the entities are updated is dependent on Home Assistant and so is out of my control. Out of curiosity, why do you need the update so accurately?

**Comment by BottlecapDave** [comment]
Ok Cool. Are you happy for me to close the issue?

**Comment by jamesking420** [comment]
Yes absolutely, apologies, thought I had done so.
