### ISSUE TITLE
Incorrect Gas Tariff Being Pulled

### ISSUE THREAD

**Issue by duffjp** [BottlecapDave/HomeAssistant-OctopusEnergy#155]
**Describe the bug**

For my account the incorrect value for the Gas Tariff (Unit Rate) is pulled in to Home Assistant.  

**To Reproduce**

Setup integration as normal with my API key from Octopus developer website.
Execute CURL commands manually from command prompt to interrogate the Octopus APIs (Account Details and then the Tariff Details based on the info in Account Details)

**Expected behavior**

Octopus API and App states my gas tariff Unit Rate should be 6.00p/kWh
Integration is typically reporting a varying rate between 6-7p/kWh

**Home Assistant Version**

2023.2.5

**Integration Version**

v5.4.1

**Fresh Install?**

Checking the logs of my rates, this issue appeared to start on 28th Jan.

**Home Assistant Logs**

Are there any related logs available in Home Assistant? Please follow the instructions as outlined in the [readme](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy#increase-home-assistant-logs).
Logs don't appear to show the detail of the tariff that is being read, to compare with my settings.

**Comment by BottlecapDave** [comment]
Good morning. What tariff is being reported by Home Assistant and when you run the curl commands manually?

**Comment by duffjp** [comment]
Hi Dave,

When I download the Diagnostic info from the Integration, it tells me the tariff is:

```
    "gas_meter_points": [
      {
        "mprn": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "consumption_units": "m\u00b3"
          }
        ],
        "agreements": [
          {
            "valid_from": "2022-10-11T23:00:00+00:00",
            "valid_to": "2023-10-11T23:00:00+00:00",
            "tariff_code": "G-1R-SILVER-2017-1-H"
```

I can't see the command you use to query the tariff.  However, the gas response that comes through at the moment for Gas is 0.063525 GBP/kWh

When I curl, my account tells me:

`              "tariff_code": "G-1R-SILVER-2017-1-H",
              "valid_from": "2022-10-12T00:00:00+01:00",
              "valid_to": "2023-10-12T00:00:00+01:00"`

When I query that tariff, I use this curl command and the first response I get is:

```
curl -u <APIKEY> "https://api.octopus.energy/v1/products/SILVER-2017-1/gas-tariffs/G-1R-SILVER-2017-1-H/standard-unit-rates/" | json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11763  100 11763    0     0  48815      0 --:--:-- --:--:-- --:--:-- 49012
{
  "count": 2494,
  "next": "https://api.octopus.energy/v1/products/SILVER-2017-1/gas-tariffs/G-1R-SILVER-2017-1-H/standard-unit-rates/?page=2",
  "previous": null,
  "results": [
    {
      "value_exc_vat": 5.71,
      "value_inc_vat": 5.9955,
      "valid_from": "2023-02-27T00:00:00Z",
      "valid_to": "2023-02-28T00:00:00Z"
```

**Comment by BottlecapDave** [comment]
This should be resolved in the latest release (v6.0.1)

**Comment by duffjp** [comment]
Fantastic, thank you so much.  I will monitor over the coming few days and confirm back 👍

**Comment by BottlecapDave** [comment]
@duffjp Did the fix work for you?

**Comment by duffjp** [comment]
Hi Dave,

Yes, that appears to have fixed the issue thank you.  My only hesitation in answering is that since the update, the gas price has been generally lower than 6p/kwh (the cap on my tariff), which made me question what would happen if/when the rate goes back up (the new tracker has a 10p/khw cap).  I'm happy to close and raise a new item if it turns out not to be quite right
