### ISSUE TITLE
Unexpected Unit of Measurement in Energy Dashboard

### ISSUE THREAD

**Issue by Daverover66** [BottlecapDave/HomeAssistant-OctopusEnergy#158]
**Describe the bug**

After updating to the latest version of the integration today, I tried to use the kWh gas consumption sensor in the Energy Dashboard and got this error:

**_The following entities do not have an expected unit of measurement (either of GJ, kWh, MJ, MWh, Wh for an energy sensor or either of CCF, ft³, m³ for a gas sensor):
sensor.octopus_energy_gas_{{meter_serial_number}}_{{MPAN_number}}_previous_accumulative_consumption_kwh (kWh)_**

The sensor

 **_sensor.octopus_energy_gas_{{meter_serial_number}}_{{MPAN_number}}_previous_accumulative_consumption_** 

still provides usage in m3.

**To Reproduce**

In the Energy Dashboard, under "Gas Consumption" select the kWh consumption sensor

**Expected behavior**

I was expecting to see the gas consumption bubble in the Energy Flow card show consumption in kWh

**Home Assistant Version**

2023.2.5

**Integration Version**

6.0.0

**Fresh Install?**

Upgrade from previous version

**Home Assistant Logs**

None

**Comment by BottlecapDave** [comment]
Have you configured the Energy Dashboard to use the m3 version before? If so, it appears HA likes to hold onto the old value according to https://community.home-assistant.io/t/energy-dashboard-allow-gas-as-kwh/339891/24?

**Comment by Daverover66** [comment]
I was, and still am, using m3 data for gas consumption, yes.

Looks like I'd have to delete historic m3 data to use a kWh sensor. I'm using MariaDB so will have a look to see how that might be done.

Everything else on my Energy dashboard is kWhs so I'd like gas to be the same.

Thanks.

**Comment by BottlecapDave** [comment]
Did this resolve your issue @Daverover66?

**Comment by anothermort** [comment]
> Did this resolve your issue @Daverover66?

Same issue as @Daverover66 but have never had a Gas meter set up until now. Could it be a default in HA latest only just set it up recently?

**Comment by BottlecapDave** [comment]
This looks like a partial feature within HA where part of it supports the current entity and part of it doesn't. I've updated the device class which should now support this as part of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v6.1.1

**Comment by anothermort** [comment]
Excellent thank you

**Comment by AlecRust** [comment]
It looks like this was fixed for gas, but I'm getting it on electricity:

<img width="363" alt="image" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/247634/0e5986d1-3fa8-4460-b7a8-2c14581a6b3c">

After following: https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/energy_dashboard.md#for-electricity
