### ISSUE TITLE
Being Migrated from Bulb to Octopus causes plugin to fail because product type is unknown. 

### ISSUE THREAD

**Issue by mretallack** [BottlecapDave/HomeAssistant-OctopusEnergy#159]
**Describe the bug**

I was one of the people who where on Bulb and now have been moved to Octopus. It appears that they way this plugin works, it creates the Product code from the Tariff code by first extracting the bits from the traffic code: 

`REGEX_TARIFF_PARTS = "^([A-Z])-([0-9A-Z]+)-([A-Z0-9-]+)-([A-Z])$"`

Currently the tariff code I am getting is: E-1R-BULB-CRED-VAR-V1-H

However when this gets used, Home Assistant generates an error because the product code (BULB-CRED-VAR-V1) does not exist.  I have confirmed this by using the api to list products and the BULB-CRED-VAR-V1 one does not exist in the list.

This feels like an issue at Octopus's end not including the BULB-CRED-VAR-V1 product in its list, but the plugin cannot currently handle this situation. 

**To Reproduce**

Setup as per instructions using an account that has been migrated from Bulb. 

**Expected behavior**

Should start pulling data correctly.

**Home Assistant Version**

2022.12.3

**Integration Version**

v6.0.0

**Fresh Install?**

From an upgrade.

**Home Assistant Logs**

No useful logs except what has been included above, I will include a better log once my installation has been updated.

**Comment by BottlecapDave** [comment]
This has been raised in the Octopus Energy forums https://forum.octopus.energy/t/bulb-cred-var-v1-tariff-not-found/7106/3 and has been mentioned that it's being looked into

**Comment by BottlecapDave** [comment]
I've had word that Bulb based products should be available now. Anyone able to confirm?

**Comment by BottlecapDave** [comment]
Any update on this @mretallack ?

**Comment by mretallack** [comment]
@BottlecapDave , Looks to be working now. Thanks
