### ISSUE TITLE
Missing export sensors

### ISSUE THREAD

**Issue by coleburg** [BottlecapDave/HomeAssistant-OctopusEnergy#160]
**Describe the bug**

Many of the sensors for export are missing

**Home Assistant Version**

Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

**Integration Version**

v6
**Fresh Install?**

after upgrade

**Comment by coleburg** [comment]
![image](https://user-images.githubusercontent.com/13885439/221813965-b24da7a4-933a-435a-b9f3-3069b6fee9ee.png)

**Comment by BottlecapDave** [comment]
As highlighted in the changelog for the latest release, the name of "export" based sensors have been renamed to include the term "export".

**Comment by BottlecapDave** [comment]
Is this resolved @coleburg?

**Comment by coleburg** [comment]
yup, all displaying perfectly now.  thank you

**Comment by coleburg** [comment]
yup, all displaying perfectly now.  thank you
