### ISSUE TITLE
Half hour rates not updating at xx:01 or xx:31 after v6.0.0 update

### ISSUE THREAD

**Issue by th4rius** [BottlecapDave/HomeAssistant-OctopusEnergy#161]
I see few sensor names changed with added export to them. Thank you!

However before this release the rates (in my case export current rate) used to automatically update at most one minute past new half hour. 

What I am seeing is the rates update depending on either when the integration was reloaded or HA restarted. So if I reload at 14:44 then it will assume that as a start of 30 minute. The next update of rates then will be at 15:14 which is not ideal as I need to know the new rate at 15:00 not 14 minutes later.

If I check next export rate sensor at 15:00 the correct rate shows (The 15:00-15:30). But as described above the current rate needs to kick in at 15:00. The times specified are just an example. I believe there is a bug in the new export sensors introduced in v6.0.0.

**Comment by BottlecapDave** [comment]
hmm this is probably a bi-product of the addition of price cap configurations. I'll take a look and see what I can do.

**Comment by JLM701** [comment]
Hi. I also have exactly the same problem. I don't know if this will help but I see that, in my case, the time was 6 minutes out 3 days ago, yesterday 7 and today it's about 8 minutes out. I hope this helps. J

**Comment by th4rius** [comment]
@BottlecapDave thanks. It is really annoying as I have to time my restarts. 

Also on another thing I have noticed. Because the names changed the export previous rate which showed my whole year gain form export clearly stopped working due to change and the new entity has started counting from zero. I understand you can't guarantee it but if possible no more entity changes as this breaks my calculations of returns etc.

**Comment by BottlecapDave** [comment]
@th4rius I'm not planning any more entity name changes. This one was due to multiple issues around people not realising the entities exist or being able to find them. I always highlight breaking changes in the version (major change) and notes and so it will be up to users to decide if the breaking change is worth it for them. If you change the name back, you might be able to receive the old stats (but that's just a guess).

I'm aiming to fix this issue within the next week.

**Comment by BottlecapDave** [comment]
Managed to find some time this evening. This should be resolved in the latest release (v6.0.1)

**Comment by th4rius** [comment]
Awesome! And as always thank you for your support @BottlecapDave. 
I will test once release is out.

**Comment by BottlecapDave** [comment]
The release is already out, so waiting to be tested :)

**Comment by th4rius** [comment]
Fixed. Thanks 🙂
