### ISSUE TITLE
Octopus MINI data Energy screen

### ISSUE THREAD

**Issue by nraimo1** [BottlecapDave/HomeAssistant-OctopusEnergy#162]
sensor.octopus_energy_electricity_{{METER_SERIAL_NUMBER}}_{{MPAN_NUMBER}}_current_consumption

isn't showing up on the energy screen it needs its sensor data changing to allow this.

Data is showing when I look at entries and data coming in so just a misnamed sensor

sensor.octopus_energy_electricity_{{METER_SERIAL_NUMBER}}_{{MPAN_NUMBER}}_current_demand
shows fine!

THank you keep up great work

**Comment by BottlecapDave** [comment]
Hello. I am using the current consumption sensor on my dashboard without issues. 

What error are you seeing? It can take a while for HA to display the data.

**Comment by nraimo1** [comment]
The current consumption sensor not showing on the energy dashboard AT ALL.. 

Current Demand shows on the energy dashboard and YES the sensor data shows the graph for usage however as its not using the current demand sensor which is the CURRENT live demand minute to minute it seems to be totalling days usage on far right for grid pull... if this is correct by the way PLEASE feel free to close this thread.

Also, I tweeted this service on Twitter for you 'raimonick' 
![image](https://user-images.githubusercontent.com/120395727/222690632-e4069b2b-e251-4739-bcef-8b724dbbada5.png)

**Comment by BottlecapDave** [comment]
As you can see, I have the current consumption set up and working in the energy dashboard.

<img width="888" alt="energy dashboard 2" src="https://user-images.githubusercontent.com/14993950/222807695-6fa6a1a2-2346-43d9-9992-2e0ddca56304.png">
<img width="983" alt="energy dashboard 1" src="https://user-images.githubusercontent.com/14993950/222807702-27b224cc-4010-431a-a385-9b6b89626e20.png">

Do you have any errors appearing in your logs? 
Do you have data coming through correctly when looking at the history of the current consumption entity? If so, this may be an issue with HA. Did you use the current demand entity in the energy dashboard first? If so, this might be a similar issue to https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/158#issuecomment-1446269103 where HA holds onto the unit of measurement of the first entity that's set up.

**Comment by BottlecapDave** [comment]
did you resolve your issue @nraimo1?
