### ISSUE TITLE
Enhancement: Binary sensor to indicate smart meter working/fault

### ISSUE THREAD

**Issue by wyx087** [BottlecapDave/HomeAssistant-OctopusEnergy#166]
**Describe the feature**

A binary sensor set to TRUE or FALSE to indicate whether the smart meter is working (or there may be a fault) based on information collected by this integration. For each smart meter device (electric, gas) 

This integration has access to previous day's half-hourly data from Octopus servers, the same data is used for billing. IF smart meter connection develops a fault, the data from Octopus will stop updating. This will require manual intervention by contacting Octopus support to fix smart meter. So having a sensor to base automations upon will help cut down missing smart meter data. 

Reason for bring this up is because my smart meter stopped submitting readings. I only noticed after a saving session. I raised the issue after it had stopped working for 2 weeks. It took almost 2 months to go from stop working to working. I am still missing first month of usage data. Octopus GO T&C states if smart meter data cannot be retrieved, I am liable to pay at SVT, meaning I'll be £100 worse off. So knowing smart meter stopped working and notifying Octopus at earliest opportunity will help greatly. 

**Expected behavior**

One extra binary sensor for each device. 

If it's a fault sensor: 
TRUE when a fault is detected with data, for example consumption data from Octopus is 3 days out of date. 
FALSE when smart data is updated at expected time. 

If it's a sensor to indicate smart meter is working: 
FALSE when a fault is detected with data, for example consumption data from Octopus is 3 days out of date. 
TRUE when smart data is updated at expected time.

**Comment by wyx087** [comment]
Hello. 
Since v9 update, that attribute disappeared. None of other date-time attributes in previous_accumulative sensor seems to suggest when smart meter data was last uploaded to Octopus. 

Could you shine a light on where that attribute have gone? 
Thanks

**Comment by BottlecapDave** [comment]
As per the docs and breaking changes, the new attribute is last_evaluated.

**Comment by wyx087** [comment]
last_evaluated changes to when HA was last restarted. Doesn’t appear to be persistent like previous attribute.

**Comment by BottlecapDave** [comment]
It will change when you restart HA, as it will retrieve the data and evaluate. If you don't restart HA, then it'll be when it successfully retrieves data and re-evaluates the state. For instance, mine is marked at 12pm today.

**Comment by BottlecapDave** [comment]
I'm going to close this feature request as this can now be achieved using automations against the event entities (`event.octopus_energy_electricity_xxx_xxx_previous_consumption_rates` or `event.octopus_energy_gas_xxx_xxx_previous_consumption_rates`). This can then be taylored to the individual around how long to wait and what to do in the situation.
