### ISSUE TITLE
No 'current' consumption sensors for import, export or gas

### ISSUE THREAD

**Issue by jefft4** [BottlecapDave/HomeAssistant-OctopusEnergy#168]
Hi,

Installed the integration via HACS, followed integration set-up; all seemed well but I only have 'previousaccumulativeconsumption' values, nothing 'current'.  Your set-up instructions refer to using the 'current' values for HA's energy dashboard.  Am I misinterpreting something, or is the integration not loading all the sensors for me?

Thanks!

**Versions**
HA 2023.3.2
Fresh install - both HA and the integration.

**Octopus info**
One account, one property, active.
Two elec meters - xx280 is import (flexible), xx580 is export (agile) and one gas meter (flexible).

**Log** attached; I don't see any 'current' sensors being created, although there are 'current' rates there.
[halog.octopus.txt](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/10951180/halog.octopus.txt)

**Comment by BottlecapDave** [comment]
Hello, and thanks for using the integration.

As per the readme, the "current" sensors are only available for users who have access to an Octopus Home Mini, as the data is delayed when sent to OE. Therefore for the instructions, you'll want to follow https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy#i-dont-have-an-octopus-home-mini to add your "previous consumption" sensors.

**Comment by jefft4** [comment]
Ah, I misunderstood that dependency. Thanks!
