### ISSUE TITLE
Expose gas rates

### ISSUE THREAD

**Issue by BottlecapDave** [BottlecapDave/HomeAssistant-OctopusEnergy#17]
Like electricity, we should expose gas rates

**Comment by kinnectus** [comment]
Is there an ETA on this, as gas rates are available on the API?

I use Postman to verify the numbers HA gets:

{{base_url}}/v1/products/{{product_code}}/gas-tariffs/{{gas_tariff_code}}/standard-unit-rates/

I get values that seem to corroborate what my Octopus Energy dashboard shows...

`
{
"count": 2,
    "next": null,
    "previous": null,
    "results": [
        {
            "value_exc_vat": 3.81,
            "value_inc_vat": 4.0005,
            "valid_from": "2021-09-30T23:00:00Z",
            "valid_to": null
        },
        {
            "value_exc_vat": 3.15,
            "value_inc_vat": 3.3075,
            "valid_from": "2021-09-25T23:00:00Z",
            "valid_to": "2021-09-30T23:00:00Z"
        }
    ]
}
`

**Comment by BottlecapDave** [comment]
A gas rate sensor now exists in 3.1.0, as per this original ticket. Closing.
