### ISSUE TITLE
Target Rates Crossing Midnight Do Not Create Target Times with Negative Offset.

### ISSUE THREAD

**Issue by StephenMilner** [BottlecapDave/HomeAssistant-OctopusEnergy#173]
**Describe the bug**

When I set a target rate that starts either before midnight or on midnight I don't get any target times in the attributes for the rate sensor if I have a negative offset.

**To Reproduce**

Configure an existing Target Rate Sensor (with a negative offset) start change from 00:30 to 00:00

**Expected behavior**

I expect Target Times to be visible in the attributes of the sensor:

Example attributes with a start time of 00:30:

Name
nightcharge
Hours
2.5
Type
Intermittent
MPAN
xxxxxxxx
Rolling target
true
Start time
00:30
End time
06:00
Offset
-00:02:30
Is target export
false
Target times
- value_inc_vat: 18.858 valid_from: '2023-03-16T02:30:00+00:00' valid_to: '2023-03-16T03:00:00+00:00' tariff_code: E-1R-AGILE-FLEX-22-11-25-M - value_inc_vat: 19.32 valid_from: '2023-03-16T03:00:00+00:00' valid_to: '2023-03-16T03:30:00+00:00' tariff_code: E-1R-AGILE-FLEX-22-11-25-M - value_inc_vat: 18.48 valid_from: '2023-03-16T03:30:00+00:00' valid_to: '2023-03-16T04:00:00+00:00' tariff_code: E-1R-AGILE-FLEX-22-11-25-M - value_inc_vat: 19.95 valid_from: '2023-03-16T04:00:00+00:00' valid_to: '2023-03-16T04:30:00+00:00' tariff_code: E-1R-AGILE-FLEX-22-11-25-M - value_inc_vat: 19.761 valid_from: '2023-03-16T04:30:00+00:00' valid_to: '2023-03-16T05:00:00+00:00' tariff_code: E-1R-AGILE-FLEX-22-11-25-M 
Next time
16 March 2023, 02:25:00
Current duration in hours
0
Next duration in hours
2.5

Same Target Rate Sensor configure to start 00:00

Name
nightcharge
Hours
2.5
Type
Intermittent
MPAN
xxxxx
Rolling target
true
Start time
00:00
End time
06:00
Offset
-00:02:30
Is target export
false
Target times
Current duration in hours
0
Next duration in hours
0

Same Target configure to start at 00:00 without the negative offset.

Name
nightcharge
Hours
2.5
Type
Intermittent
MPAN
xxxxx
Rolling target
true
Start time
00:00
End time
06:00
Offset
00:00:00
Is target export
false
Target times
- value_inc_vat: 18.858 valid_from: '2023-03-16T02:30:00+00:00' valid_to: '2023-03-16T03:00:00+00:00' tariff_code: E-1R-AGILE-FLEX-22-11-25-M - value_inc_vat: 19.32 valid_from: '2023-03-16T03:00:00+00:00' valid_to: '2023-03-16T03:30:00+00:00' tariff_code: E-1R-AGILE-FLEX-22-11-25-M - value_inc_vat: 18.48 valid_from: '2023-03-16T03:30:00+00:00' valid_to: '2023-03-16T04:00:00+00:00' tariff_code: E-1R-AGILE-FLEX-22-11-25-M - value_inc_vat: 19.95 valid_from: '2023-03-16T04:00:00+00:00' valid_to: '2023-03-16T04:30:00+00:00' tariff_code: E-1R-AGILE-FLEX-22-11-25-M - value_inc_vat: 19.761 valid_from: '2023-03-16T04:30:00+00:00' valid_to: '2023-03-16T05:00:00+00:00' tariff_code: E-1R-AGILE-FLEX-22-11-25-M 
Next time
16 March 2023, 02:30:00
Current duration in hours
0
Next duration in hours
2.5

Current time/date 16:55 15/03/2023
I have rates populated through to 22:30 16/03/2023

**Home Assistant Version**

HA 2023.3.4
Frontend 20230309

**Integration Version**

v6.0.1

**Fresh Install?**

Results from after update HA

**Home Assistant Logs**

I have enable debug logging and nothing obvious visible

**Comment by BottlecapDave** [comment]
Sorry that this caused an issue. This should be fixed in the latest release - https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v6.2.0

**Comment by StephenMilner** [comment]
> Sorry that this caused an issue. This should be fixed in the latest release - https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v6.2.0

Absolutely no need to apologise. I’m very grateful for this integration. 

As a developer it’s almost impossible to think of every edge case for testing. 

Keep up the great work. If I hadn’t used someone else’s reference code already for octopus, I would have used yours. Apologies.
