### ISSUE TITLE
Home Mini most recent half-hourly gas data

### ISSUE THREAD

**Issue by googanhiem** [BottlecapDave/HomeAssistant-OctopusEnergy#175]
Forgive me if this has already been discussed (I couldn't find it in search). 

Just got a Home Mini and love how integration brings electricity data into hass.  I've been playing around with the graphql API and haven't figured a way to get it to show the gas data (the basic v1 API is limited to the previous day), wondering if anyone else has had any luck?

The Octopus app does show half-hourly gas data coming from the Home mini, so it may be possible.

**Comment by BottlecapDave** [comment]
I was working on this as you raised it, and is now available in the latest release https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v6.1.1

**Comment by googanhiem** [comment]
Thanks!
My nagging didn't change the outcome, but at least I can pretend I played a part in this wonderful integration. Ha
