### ISSUE TITLE
Enhancement: Master Config Flow button

### ISSUE THREAD

**Issue by plandregan** [BottlecapDave/HomeAssistant-OctopusEnergy#180]
Can we have a button on teh Integration, to access the master ConfigFlow, to add a new Target entity. 
Using the link in documentation is ok, if at home, but if away, would be better a relative link, instead of the literal one.

So when showing the list of targets, add a (Add Target) button there would be ace

This new Target feature is pretty awesome, set me the cheapest 2hr lot of 4 slots for a dishwasher for example. Saves me each day reading the prices, fining the 4 cheapest near each other

**Comment by BottlecapDave** [comment]
Hello and thanks for using the integration however I'm not entirely sure what you're asking. The integrations structure below within HA is limited by what HA provides and cannot be changed.

![image](https://user-images.githubusercontent.com/14993950/226729644-bff7d98b-30ee-4c39-b633-5117069667f8.png)

The record titled "Octopus Energy" is the account, and all other entries are target rates. You can add multiple target rates by clicking the plus button on this screen and adding "Octopus Energy" again to go through that flow.

Does this answer your request?

**Comment by plandregan** [comment]
Hi Dave.

I didn't see any plus on the screen. Unless you need the one down bottom
right to add a whole new integration

**Comment by BottlecapDave** [comment]
Sorry yes, I meant the "add integration" button. Doing so will give you the option to add new target rate sensors. As mentioned this is due to a limitation in what custom integrations can do with the UI, and how they operate.
