### ISSUE TITLE
Cant Edit the Target fully once created

### ISSUE THREAD

**Issue by plandregan** [BottlecapDave/HomeAssistant-OctopusEnergy#181]
When you create a new target, you can enter the hours needed, intermittent or continous and the time window if needed.
However if you try and edit later, you cant change the continuious to intermittant .

**To Reproduce**

Create a target entity using the config flow.
Click in on it and hit configure (To edit it)

**Expected behavior**

SHould be able to edit all aspectes of it, ie swap from internittant to continuious and vice versa

**Home Assistant Version**

Home Assistant 2023.3.5
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230309.1 - latest

**Integration Version**

6.2.0

**Fresh Install?**

Upgrade

**Home Assistant Logs**

N/A

**Comment by BottlecapDave** [comment]
Hello.

This was intentional as I felt if you wanted to change the type you should just delete the old target rate and create a new one as you've probably made a mistake. I'll make a note to support changing other aspects, but this will be low down on the list as there's a workaround.

**Comment by BottlecapDave** [comment]
This should now be achievable in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v6.5.0
