### ISSUE TITLE
Rates not in local format

### ISSUE THREAD

**Issue by plandregan** [BottlecapDave/HomeAssistant-OctopusEnergy#187]
Looking at the attribute data of the target sensor created for my battery charging. I can see it is 1hr early.
The price in the attribute matches that 1hr later in the octopus App and the lovlace card displaying all the data.
the 1st in the list 21:30 20.37p, is actually the 22:30 slot in the lovlace, octopus App and webpage.

![Screen Shot 2023-03-27 at 16 51 18](https://user-images.githubusercontent.com/109735958/227995100-f7da1b55-ac68-45d1-a1d6-d7b153c44874.png)
![Screen Shot 2023-03-27 at 16 51 34](https://user-images.githubusercontent.com/109735958/227995084-3cf8df7d-b9cc-4031-a293-be7136e8e20b.png)

The attribute data matches that in the  Octopus App
![Screen Shot 2023-03-27 at 16 53 42](https://user-images.githubusercontent.com/109735958/227995652-d38efeca-ea20-4012-a984-512ab929db43.png)

Home Assistant 2023.3.6
Supervisor 2023.03.2
Operating System 9.5
Frontend 20230309.1 - latest

**Fresh Install?**

No

**Comment by plandregan** [comment]
Closed as not a bug just cosmetic

**Comment by BottlecapDave** [comment]
Technically the sensors are correct as they are reported back and displayed in UTC format (the +00:00 bit at the end) as this is what Octopus Energy reports them as. I'll look at changing them to be in local format, but tbh it will be down on my list.

**Comment by andynash** [comment]
> looks to me like 1 is built into the target sensor anyway.

It is now it seems 👍 I either wasn't aware of it yet or it hadn't been added when I posted.
 
> and in the case of 2 wouldn't you just use the local timestamp filter timestamp_local ... so something like: `{{ as_timestamp(state_attr('binary_sensor.octopus_energy_target_agile_best_3hrs','next_time')) | timestamp_local }} ` converts the next_time attribute from UTC into my local timezone (+1)

Yep, this works as a workaround, however when viewing the attributes in the sensor (which is something I'm currently doing multiple times a day for various reasons), I need to mentally add an hour. If others in the family want to e.g. check when the car will be charging then this could cause confusion.

As the value is exposed in the UI I do think in principle it should be in local time if possible. However I'm more than happy with Dave setting priorities as he sees fit, as he has already done in this case. Hopefully at some point it will make it to the top of the list 😁

**Comment by rupisaini** [comment]
triggering will become more complicated to store attribute values in local time. Linux system clock with in UTC mode. and any data time when you display in linux get converted to local time at the time of display. 

Maybe you can use "Next time" to display next trigger time in local time
