### ISSUE TITLE
Entity is currently unavailable

### ISSUE THREAD

**Issue by djdarlo** [BottlecapDave/HomeAssistant-OctopusEnergy#199]
I have been using this integration for a few weeks now without any issue but today I am seeing a message saying "entity is currently unavailable".  I have rechecked by API key (it hasn't changed) but re-configured the integration anyway.

In the logs I can see the following....

Logger: homeassistant.components.sensor
Source: custom_components/octopus_energy/sensor.py:153
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 12:30:18 PM (1 occurrences)
Last logged: 12:30:18 PM

Error while setting up octopus_energy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/octopus_energy/sensor.py", line 129, in async_setup_entry
    await async_setup_default_sensors(hass, entry, async_add_entities)
  File "/config/custom_components/octopus_energy/sensor.py", line 153, in async_setup_default_sensors
    if len(account_info["electricity_meter_points"]) > 0:
TypeError: 'NoneType' object is not subscriptable

**Comment by BottlecapDave** [comment]
what version of the integration are you using? I've added some more robust checks in the latest version. This implies it's failed to retrieve you account information

**Comment by djdarlo** [comment]
6.2 at the moment. I’ll try upgrading now and let you know.

D

**Comment by BottlecapDave** [comment]
Glad to hear it :)
