### ISSUE TITLE
octopus energy spain

### ISSUE THREAD

**Issue by rauloraulon** [BottlecapDave/HomeAssistant-OctopusEnergy#224]
works with octopus energy spain?

**Comment by BottlecapDave** [comment]
Hello. As a UK resident, I've only tested within the UK. If OE Spain uses the same APIs and require the same account details (account number and API key), then it _should_ work. The only thing I can say is, try it and report back :)

**Comment by BottlecapDave** [comment]
Hello @rauloraulon - did you get a chance to try the integration and see if it works in Spain?

**Comment by rauloraulon** [comment]
Hello
The integration doesn´t work with my spanish credential.

**Comment by BottlecapDave** [comment]
That's a shame. Is there any indication what was wrong?

**Comment by pgm83** [comment]
FWIW when i was in Spain access to the API was blocked, I had to use a VPN.

**Comment by rauloraulon** [comment]
I can´t get the api key because  i can´t sign in with my
spanish credentials.

**Comment by BottlecapDave** [comment]
Closing as not currently supported and little information available on how to support.
