### ISSUE TITLE
Install link is broken

### ISSUE THREAD

**Issue by rwb196884** [BottlecapDave/HomeAssistant-OctopusEnergy#227]
I clicked the link to install and this happened, and there are no installation instructions.

![image](https://user-images.githubusercontent.com/12090617/235313294-5387dcc2-bbeb-41ad-ad1e-3c3e8b370185.png)

**Comment by BottlecapDave** [comment]
Hello. Have you following the [instructions](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy#how-to-install) and installed manually or via HACS and restarted your instance before following the integration link?

**Comment by ceemjay** [comment]
I am having the same problem and followed those instructions too.

I have also tried adding a repository and get the follwing - https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy is not a valid add-on repository (maybe that shouldn't work though!)

Thanks

**Comment by BottlecapDave** [comment]
If you are installing via HACS, then it's available via the store. To install as per HACS instructions

* Go to your HACS installation within Home Assistant
* Go to `Integrations`
* Click `Explore & download repositories`
* Search for `Octopus Energy` and click the entry
* Click `Download`

I have just tried to install the repository via custom repositories using the latest version of HACS (associated with category of `integration`) and got correctly the error message of `Repository 'bottlecapdave/homeassistant-octopusenergy' exists in the store.`

<img width="454" alt="Capture" src="https://user-images.githubusercontent.com/14993950/235353420-a6790015-f75f-48a0-91b2-db45cbdc4c38.PNG">

If you are not using HACS, then you'll need to manually install the integration as per the [instructions](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy#how-to-install) and restart your HA instance

**Comment by ceemjay** [comment]
Working now - thanks.

Can you advise of the format of data to be entered in the "The hours you
require field" - it is not clear to me from the documentation. I am really
new to Octopus Energy and struggling to get to grips with their tariffs and
understand the full capabilities of your integration.

Thanks for putting this all together.

**Comment by BottlecapDave** [comment]
Hours are recorded in decimal representation (e.g. 0.5 = 30 minutes, 1 = 1 hour). I'll update the error message and docs to be more explicit.

**Comment by BottlecapDave** [comment]
Are you ok @rwb196884 and @ceemjay to close this issue?
