### ISSUE TITLE
Incorrect Gas Tracker rate today (5th May 2023)

### ISSUE THREAD

**Issue by Dazula** [BottlecapDave/HomeAssistant-OctopusEnergy#230]
Great integration btw.  Today I noticed that the gas tracker rate was incorrect, not sure where this is data is coming from as is reading as 0.146 £/Kw when it should be 0.04305 for my region.

Before you added Gas Tracker I used a simple lookup to https://api.octopus.energy/v1/products/SILVER-22-07-22/gas-tariffs/G-1R-SILVER-22-07-22-B/standard-unit-rates/ which returns 0.04305 £/Kw for today. (Same as my Octopus Account)

I have tried a restart hoping this might refresh the data with no change.   I just thought might be of interest. 

Running 2023.4.6 of HA and latest version Octopus Energy

edited to add...    So maybe the link is down...

Logger: custom_components.octopus_energy.api_client
Source: custom_components/octopus_energy/api_client.py:466 
Integration: Octopus Energy ([documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/), [issues](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues)) 
First occurred: 08:06:52 (1 occurrences) 
Last logged: 08:06:52

Failed to send request (https://api.octopus.energy/v1/products/SILVER-FLEX-22-11-25/gas-tariffs/G-1R-SILVER-FLEX-22-11-25-B/standard-unit-rates?period_from=2023-05-05T00:00:00Z&period_to=2023-05-06T00:00:00Z): 404; {"detail":"Not found."}

**Comment by BottlecapDave** [comment]
Hello and sorry that you're having issues. Unfortunately some tracker tariffs aren't available via the normal API and so based on feedback on the OE forums, it falls back onto a different API if the data isn't available. Is this behaviour that you've only just started noticing or have you only just started using the integration?

**Comment by BottlecapDave** [comment]
Another thing to consider is that the tracker API doesn't account for any government caps. You might need to configure these within your account in the integration to enforce the cap. 

The product/tariff is returned from your account so this is the correct thing to look up (unless OE have configured your account wrong)

**Comment by Dazula** [comment]
Thanks.  I did wonder if that might be the case with the end point. I am on agile and gas tracker, so I look at best kw price between the two for heating etc.  I have been using my own simple code to get gas and electricity prices before I came across your integration. The tariff gas tracker end point I use seems to have been by pure luck has been reliable so far. 

Is there a way I can check if the price entity you provide has valid data (sorry I am no expert on HA) but have been using it with octopus now reliably for over 3 years so rarely need to touch the code apart from tariff changes.

**Comment by BottlecapDave** [comment]
> Is there a way I can check if the price entity you provide has valid data

What do you mean by "has valid data". Any data that comes from OE APIs is treated as valid data, so in your case because your tariff can't go through the normal means, I go through the API that powers https://octopus.energy/tracker-demo-detail/?context=1&code=G-1R-SILVER-FLEX-22-11-25-C&consumption=12000&type=gas&inapp=false

If you're saying this is different to what it says in your OE dashboard, it would be interesting to know where it's getting this data from

**Comment by BottlecapDave** [comment]
Also out of interest what does your price say today?

**Comment by Dazula** [comment]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/76919589/236681052-eaf5b7e4-f961-4017-a37c-76589dac287a.png">

Here was the incorrect data from my first post.

**Comment by Dazula** [comment]
Price today is correct at 0.0429 

By valid data that its **Current** and **Up to date** (on on day change with tracker).  ie., if it was showing  £0.05 in HA and that it could not be updated (End point down) how could I tell?

**Comment by BottlecapDave** [comment]
Gas and electricity rates are retrieved at minimum every 30 minutes are retrieved for the current day. If the rates could not be retrieved then you'd have errors in your HA logs indicating there was a server error or similar. I'll look at adding a new attribute on the data to indicate when it was last retrieved to make this easier.

**Comment by AaronIsFab** [comment]
You'll find it happens after bank holidays, the early retrieval on the next day or so tends to show 14p then it updates about lunchtime to the correct 4p number. I've observed this on my manual API pulls but that seems to be the trigger when they 'pause' the rates for weekend and BH days

**Comment by BottlecapDave** [comment]
I'm going to close this issue as there is limited data to go on and a potential reason mentioned above. If there is any more information that could point to this reasoning, please reopen.
