### ISSUE TITLE
New Previous Accumulative Peak/Offpeak wrong way round

### ISSUE THREAD

**Issue by AaronIsFab** [BottlecapDave/HomeAssistant-OctopusEnergy#240]
**Describe the bug**

Cumulative and cost for peak/offpeak are represented the wrong way around.
As an example, my 4 for now are:

[sensor.octopus_energy_electricity_####_previous_accumulative_consumption_off_peak] - 0.045

[sensor.octopus_energy_electricity_####_previous_accumulative_consumption_peak] - 25.951

[sensor.octopus_energy_electricity_####_previous_accumulative_cost_off_peak] - 0.02

[sensor.octopus_energy_electricity_####_previous_accumulative_cost_peak] - 1.95

~26 units at offpeak rate (7.5p) gives £1.95 offpeak total.
0.045 units at peak rate (38p) gives £0.02

**To Reproduce**

Enable the disabled entities and view current states when retrieved.

**Expected behavior**

Peak to reflect peak, offpeak to reflect offpeak (They need swapping around)

**Home Assistant Version**

2023.5.1

**Integration Version**

v7.1.2

**Fresh Install?**

Upgrade

**Home Assistant Logs**

N/A as believe this is just incorrect allocation of numbers to entities.

**Comment by BottlecapDave** [comment]
Hello and sorry that you saw this. My testing involved days with full data which missed this scenario. I've updated the tests and fixed the issue in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v7.1.3.

Thanks!
