### ISSUE TITLE
Add support for a target to be active at the end of a cheap time

### ISSUE THREAD

**Issue by plord12** [BottlecapDave/HomeAssistant-OctopusEnergy#242]
**Describe the feature**

I would like to control my immertion heater ... since the water cools over time, I want to turn the heater on as late as possible during the cheap tariff time.

**Expected behavior**

For example, if the integration determines the cheapest tariff is 01:00 to 07:00 and the configuration is for the target to run for 1 hour, then switch on time should be 06:00 and switch off 07:00.

As far as I can see, the target offset is relative to the start of the period, which isn't really whats needed for this case.

**Comment by BottlecapDave** [comment]
Hi @plord12 and thanks for using the integration. I've added your request to the backlog.

**Comment by BottlecapDave** [comment]
This is now available in the latest release (v7.3.0)
