### ISSUE TITLE
Incorrect API calls when backfilling Octopus Home Mini data

### ISSUE THREAD

**Issue by adds68** [BottlecapDave/HomeAssistant-OctopusEnergy#246]
**Describe the bug**

Hi, we're seeing some 400 errors from the Octopus Home Mini API, when we've looked into this, we have noticed it's customers who have the HA plugin enabled.

**To Reproduce**

The Home Mini goes offline and then the HA plugin then tries to backfill the data at minutely intervals.

The Home mini stays offline for more than a week, however HA is still trying to backfill the data in minutely intervals, which is not a valid request causing a 400 error.

**Expected behavior**

When calling the API, we have these rules in place for time ranges:

```
Any time range one day or greater can only be a minumum interval of minutes or hours
Any time greater than one week must be in a minumum interval of hours
```

So if no data has been retrieved from the Home mini api in over a week, the HA plugin should begin to request this data at an hourly resolution.

I suspect the code that needs updating is:

https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/950a47042596bffdd53d02b1a47d87c35160d919/custom_components/octopus_energy/binary_sensor.py#L33 ?

**Home Assistant Version**

N/A

**Integration Version**

N/A

**Fresh Install?**

N/A

**Home Assistant Logs**

N/A

**Comment by BottlecapDave** [comment]
This has been restricted as part of [v7.2.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v7.2.0). It might take a while for you to see results as people upgrade their versions.
