### ISSUE TITLE
Moved from Outgoing Fixed / Agile to Flux Outgoing / Import but rates still show old agile rates

### ISSUE THREAD

**Issue by UK-JustinSmall** [BottlecapDave/HomeAssistant-OctopusEnergy#254]
**Describe the bug**

Attempting to see current and previous rate information after today swapping over from agile to flux tariff

Pulling back following but it relates to old tariff and not the new one. Will this correct itself tomorrow though?

sensor.octopus_energy_electricity_XXX_YYYY_current_rate

sensor.octopus_energy_electricity_XXX_YYYY_export_current_rate

sensor.octopus_energy_electricity_XXX_YYYY_export_previous_accumulative_cost

sensor.octopus_energy_electricity_XXX_YYYY_export_previous_rate

**Comment by BottlecapDave** [comment]
Hello.

This will depend on how quickly the change is relfected through their APIs, which I'm not sure of tbh. The account information (which holds the tariffs) is refreshed every 30 minutes, as is rate information, so it should take a maximum of 1 hour for the change to come through after the APIs report the correct data. 

You can try "forcing" the account/rate information by reloading the integration or restarting your HA instance, but again this won't necessarily work if the API is still returning the old information.

**Comment by UK-JustinSmall** [comment]
That did the trick, thank you :-)
