### ISSUE TITLE
Failed to send request

### ISSUE THREAD

**Issue by holdestmade** [BottlecapDave/HomeAssistant-OctopusEnergy#257]
**Describe the bug**

Recent errors in log, seems to work ok though

**Home Assistant Version**

2023.5.4

**Integration Version**

7.3.0

**Fresh Install?**

Neither

**Home Assistant Logs**

This error originated from a custom integration.

Logger: custom_components.octopus_energy.api_client
Source: custom_components/octopus_energy/api_client.py:474
Integration: Octopus Energy (documentation, issues)
First occurred: 10:30:39 (2 occurrences)
Last logged: 11:30:49

Failed to send request (https://octopus.energy/api/v1/tracker/E-1R-FLUX-EXPORT-23-02-14-M/daily/past/1/0): 400; {"non_field_errors": ["Invalid tariff type."]}

This error originated from a custom integration.

Logger: custom_components.octopus_energy.api_client
Source: custom_components/octopus_energy/api_client.py:521
Integration: Octopus Energy (documentation, issues)
First occurred: 10:17:40 (2 occurrences)
Last logged: 11:23:08

Failed to send request (https://octopus.energy/api/v1/tracker/G-1R-VAR-22-11-01-M/daily/past/1/0): 400; {"non_field_errors": ["Invalid tariff type."]}

**Comment by BottlecapDave** [comment]
This is a known issue if it fails to retrieve data from the normal APIs. This will be made better in the future
