### ISSUE TITLE
Agile Octopus current rate not updating 

### ISSUE THREAD

**Issue by richardproctor90** [BottlecapDave/HomeAssistant-OctopusEnergy#258]
I am on octopus agile and while the list of attributes for the current rate contain all of the information the rate just stays the same and  never updates 

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/40702168/f437fd3b-beb9-4feb-b5e6-f90d14a03c81)

**Comment by BottlecapDave** [comment]
Sorry to hear you're having issues. Do you have any logs in your HA instance that might indicate why this is happening. I also assume that you've changed the name of the sensor (as what is displayed is not the default name) and that you've shown the electricity current rate sensor?

**Comment by jamesog** [comment]
Same issue here. I noticed this in the logs:

```
2023-06-01 09:00:25.717 ERROR (MainThread) [custom_components.octopus_energy.api_client] Failed to send request (https://octopus.energy/api/v1/tracker/E-1R-AGILE-FLEX-22-11-25-A/daily/past/1/0): 400; {"non_field_errors": ["Invalid tariff type."]}
```

There's also a lot more of

```
2023-06-03 13:30:12.266 ERROR (MainThread) [custom_components.octopus_energy.api_client] Octopus Energy server error (https://api.octopus.energy/v1/products/AGILE-FLEX-22-11-25/electricity-tariffs/E-1R-AGILE-FLEX-22-11-25-A/standard-unit-rates?period_from=2023-06-01T23:00:00Z&period_to=2023-06-02T23:00:00Z): 502; <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html> 
```

logged lately. I've seen them from time to time but the last few days there's a lot of it. I don't know if this would affect fetching the tariff info so thought I'd mention just in case.

**Comment by BottlecapDave** [comment]
The server errors reported by OE do not help this situation. I've released a new version which should improve the retrieving of data and make it more recoverable in the event of failures. This is available in v7.4.2.

However @richardproctor90 reported that the correct up-to-date rates were available in the attributes of the sensor, but the sensor itself wasn't reflecting this

**Comment by jamesog** [comment]
That looks to have solved my issue; thanks!

**Comment by zav13r** [comment]
Hi @BottlecapDave . Not sure if the cause is the same as Richard, but my agile rates are not updating either (nor in attributes of the sensor). I have Home Mini and the Octopus dashboard is correct. I see this in the log:

This error originated from a custom integration.

This error originated from a custom integration.

Logger: custom_components.octopus_energy.coordinators.electricity_rates
Source: helpers/debounce.py:67
Integration: Octopus Energy (documentation, issues)
First occurred: 24 June 2023 at 16:12:06 (20 occurrences)
Last logged: 12:22:42

Debouncer call ignored as shutdown has been requested.

**Comment by BottlecapDave** [comment]
Hi @zav13r  - That error is related to background updates when your HA instance shuts down/restarts. I don't believe there is anything I can do for this, but it should not effect the updating of your rates. If you [turn on debugging](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging), let your instance run for at least a day and then disable debugging and post the results here then I might be able to assist further with what's happening.

**Comment by BottlecapDave** [comment]
I'm guessing also by the fact you're saying the state nor attributes are updating that the value in `rates` (indicating all prices) are all in the past for current rate sensor and that the value of `rate` (the current price) is also in the past?

**Comment by zav13r** [comment]
> I'm guessing also by the fact you're saying the state nor attributes are updating that the value in `rates` (indicating all prices) are all in the past for current rate sensor and that the value of `rate` (the current price) is also in the past?

That is correct, yes. In my case, it is possible there is just a delay. Home Mini only recently received and added so I'll give it a few days and add here if the problem persists, in case it is related to OP issue.

**Comment by zav13r** [comment]
> I'm guessing also by the fact you're saying the state nor attributes are updating that the value in `rates` (indicating all prices) are all in the past for current rate sensor and that the value of `rate` (the current price) is also in the past?

Interestingly, the previous accumulation sensors show the correct rates for the previous period, but all three of my current sensors show unknown, after reinstalling the integration. No data showing after 24 hours. Octopus dashboard shows all stats correctly.

I have debugging enabled now so once I figure out what to do with that, I can upload some logs!

**Comment by zav13r** [comment]
Still seeing these too (no HA restarts or shutdowns):

This error originated from a custom integration.

Logger: custom_components.octopus_energy.coordinators.electricity_rates
Source: helpers/debounce.py:67
Integration: Octopus Energy (documentation, issues)
First occurred: 24 June 2023 at 16:12:06 (44 occurrences)
Last logged: 19:38:24

Debouncer call ignored as shutdown has been requested.
