### ISSUE TITLE
Trouble getting started with target rate sensors

### ISSUE THREAD

**Issue by EPicLURcher** [BottlecapDave/HomeAssistant-OctopusEnergy#265]
**Describe the bug**

I cannot seem to get target rate sensors to work - i don't seem to have the binary sensors as shown in the example. Maybe this is user error on my part - can we have some full examples of exactly what we need to configure to get this

**Comment by BottlecapDave** [comment]
Hello. What part of the process are you having issues with? If you "add the integration" following the link a second time after you've added your account, you will be presented with the option to setup a target rate sensor.

**Comment by EPicLURcher** [comment]
I was adding the integration the second time manually - user error. It works fine when following the link

I have the sensor created now
