### ISSUE TITLE
Feature Request: Most expensive hours

### ISSUE THREAD

**Issue by irata-coder** [BottlecapDave/HomeAssistant-OctopusEnergy#267]
Please would it be possible to create a target rate sensor which calculates when the most expensive hours are, just like the current cheapest but inversed.

The scenario is, when the electricity cost falls within X hours of peak prices (either continuous or intermittent) then this would trigger an automation to conserve energy.   A threshold trigger doesn't work as the peak prices vary throughout the year and it would trigger during most of the day.

This feature is to trigger an automation when the prices (and therefore carbon intensity) is highest for a defined period of hours.  This automation then sheds load away from the grid.

A tick box when adding a new sensor, defaulting to cheapest otherwise most expensive, could provide this option.  

I have tried to create a cheapest sensor with 24-x hours, then flipping the state, however it remains unknown when <(24-x) hours remains until the next rate update from octopus populates enough future rate hours.

**Comment by BottlecapDave** [comment]
Hi and thanks for the feature request. I'll add it to the backlog.

**Comment by BottlecapDave** [comment]
> I have tried to create a cheapest sensor with 24-x hours, then flipping the state, however it remains unknown when <(24-x) hours remains until the next rate update from octopus populates enough future rate hours.

I don't believe this should happen as long as you don't tick the `Re-evaluate multiple times a day` box and set to `intermittent`. If you want the most expensive 8 hours, then if you set the hours to 16 this should find the cheapest 16 hours throughout the day and effectively turn off during the most expensive hours. Or course in this scenario you could have it triggering every 30 minutes depending on how spread out the expensive hours is.

**Comment by BottlecapDave** [comment]
Yeah the solution I gave you isn't perfect as the intermittent will literally filter out the cheapest periods instead of a combined cheapest period. I'll keep your request in the backlog.

**Comment by BottlecapDave** [comment]
Hello. This is now available in the latest release https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v8.0.0. This is achieved via https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/setup_target_rate.md#invert-target-rates
