### ISSUE TITLE
Octopus Home Mini

### ISSUE THREAD

**Issue by ColinRobbins** [BottlecapDave/HomeAssistant-OctopusEnergy#268]
**Describe the feature**
Integrate the Octopus Home Mini

**Expected behaviour**
The Octopus Home Mini provides up-to-date data on electric and gas usage to the Octopus App.
https://octopus.energy/blog/octopus-home-mini/

If integrated, this could pass data into the HA Energy dashboard.

Current integrations provide the data, but data is delayed from the previous day.

I have *no idea* if this is possible - not sure if Octopus expose the data.

**Comment by BottlecapDave** [comment]
This is already a feature - https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/setup_account.md#home-mini
