### ISSUE TITLE
No Gas Meter Data

### ISSUE THREAD

**Issue by pwhitea** [BottlecapDave/HomeAssistant-OctopusEnergy#269]
PLEASE DO NOT DELETE AND FILL IN!

_Please provide a clear and concise description of what the bug/issue is._

Following setup, electric tariff and consumption data working fine.  However for gas I see tariff data (/KwH + Standing Charge) however no consumtion data coming through.  Have re-installed three times and same each time.  I can see gas consumption in the Octopus app and on website so data is present in ther octopus cloud. 

I have performed a curl test as below as described in Octopus API URL and I am seeing gas consumption data coming through as can be seen below:

curl -u "XXXXXXX:" "https://api.octopus.energy/v1/gas-meter-points/XXXXX/meters/XXXX/consumption/"

Output from curl:

{"consumption":0.079,"interval_start":"2023-06-08T
08:30:00+01:00","interval_end":"2023-06-08T09:00:00+01:00"},{"consumption":0.014,"interval_start":"2023-06-08T08:00:00+01:00","interval_end":"2023-06-08T08:
30:00+01:00"},{"consumption":0.038,"interval_start":"2023-06-08T07:30:00+01:00","interval_end":"2023-06-08T08:00:00+01:00"},{"consumption":0.0,"interval_sta
rt":"2023-06-08T07:00:00+01:00","interval_end":"2023-06-08T07:30:00+01:00"},{"consumption":0.0,"interval_start":"2023-06-08T06:30:00+01:00","interval_end":"
2023-06-08T07:00:00+01:00"},{"consumption":0.371,"interval_start":"2023-06-08T06:00:00+01:00","interval_end":"2023-06-08T06:30:00+01:00"},{"consumption":0.0
,"interval_start":"2023-06-08T05:30:00+01:00","interval_end":"2023-06-08T06:00:00+01:00"},{"consumption":0.096,"interval_start":"2023-06-08T05:00:00+01:00",
"interval_end":"2023-06-08T05:30:00+01:00"},{"consumption":0.23,"**interval_start":"2023-06-08T04:30:00+01:00","interval_end":"2023-06-08T05:00:00+01:00"},{"c
onsumption":0.0,"interval_start":"2023-06-08T04:00:00+01:00","interval_end":"2023-06-08T04:30:00+01:00"},{"consumption":0.0,"interval_start":"2023-06-08T03:
30:00+01:00","interval_end":"2023-06-08T04:00:00+01:00"},{"consumption":0.0,"interval_start":"2023-06-08T03:00:00+01:00","interval_end":"2023-06-08T03:30:00
+01:00"},{"consumption":0.0,"interval_start":"2023-06-08T02:30:00+01:00","interval_end":"2023-06-08T03:00:00+01:00"},

**To Reproduce**

Simply just install and no data coming through

**Expected behavior**

Expect to see Gas consumption data

**Home Assistant Version**

2023.6.1

**Integration Version**

7.4.2
**Fresh Install?**

Fresh Install, howevver did not work with last version of HA

**Home Assistant Logs**

No logs being produced

**Comment by BottlecapDave** [comment]
Hi and welcome to the integration.

Previous consumption data for gas is usually populated a little later in the day compared to electricity. The previous consumption sensors only look at the previous day, so if no data is available then it won't update.

As per your curl command, the only data that is available is for 3 days ago so this will not be picked up by the integration today. Do you see consumption data in the Octopus app for yesterday that has not come from a Home Mini (if you have one)?

**Comment by pwhitea** [comment]
Hey,

Dont have a Home Mini as running a british gas smart meter.  I did leave the intergration running in the week for 5 days and still no data came through - at the time the gas consumption was 3 days behind for some reason in the octopus app, currently it seems to be catching up.  So assuming that it does catch-up and I have data within the 24hr window will that resolve the issue you think?  I have only just transferred to octopus so meters have only just transferred and as I have a SMETS 1 meter I asuming the DCC sync is taking a while!

**Comment by BottlecapDave** [comment]
Correct, once your meter has caught up and is only a day behind then it will start appearing in the integration. I'm not sure how big the delay is on SMETS1 meters, so there might be a chance it never catches up because it's always more than 24 hours behind.
