### ISSUE TITLE
HACS Install

### ISSUE THREAD

**Issue by Gadgit83** [BottlecapDave/HomeAssistant-OctopusEnergy#27]
Hiya, great work, looking forward to trying this! Just wondering if you had considered submitting to the Home Assistant Component Store to make installation and updating one click easier?

https://hacs.xyz/docs/publish/start

**Comment by BottlecapDave** [comment]
I hadn't considered, but I'll take a look at some point in the future.

**Comment by dunxd** [comment]
I added this repository to HACS and it installed fine that way.  I think it even picks up updates - I am on 2.0 and have been using this for over a month now.

**Comment by BottlecapDave** [comment]
Glad to hear that you can use it with HACS already. I'll still take a look at getting it listed at some point in the future.

**Comment by Gadgit83** [comment]
Same here, installed no problem by manually adding to HACS

**Comment by fak316** [comment]
how do you install this via HACS? I've added the custom repo to HACS and I can see it as installed as an integration in my HACS. But when I go to Home Assistant -> Settings -> Integrations I'm unable to find anything called OctopusEnergy. So I can't figure out how to configure it with my Octopus Account etc. 

 Thanks!

**Comment by BottlecapDave** [comment]
HI @fak316. I've just started looking into the HACS configuration. I believe after you've added the custom repository, you then need to download the repository via HACS (which I believe you've done). For it to appear in the integrations section of Home Assistant, you need to restart your instance first.

**Comment by Smart2TDad** [comment]
Hi, I’ve the same issue as @fak316.  I’ve download the repository via HACS, I can see the custom component in the file system and restarted HA.  It doesn’t appear in the integrations list for some reason.  It can see that HA is loading it as it’s flagging a warning about the non-tested component in the logs.  Can you help?
Thanks.

**Comment by BottlecapDave** [comment]
Sorry to hear you're having issues @Smart2TDad. What you've done is all that should be required. Are you able to add the following in your `configuration.yaml` file?

```
logger:
  default: debug
  logs:
    custom_components.octopus_energy: debug
```

As this will hopefully provide more insight into why the integration is not appearing.

**Comment by BottlecapDave** [comment]
Also this integration is now installable directly via HACS

**Comment by Smart2TDad** [comment]
Thanks David. I tried this a few days ago as I saw someone else had had that suggestion.
I added the debugger lines into the config and it worked after I did that.
________________________________

**Comment by BottlecapDave** [comment]
Ok Thanks @Smart2TDad. Now that your issue has been resolved and it's available in HACS I'm going to close this issue.
