### ISSUE TITLE
Using utility meter shows incorrect usage.

### ISSUE THREAD

**Issue by chinedu40** [BottlecapDave/HomeAssistant-OctopusEnergy#288]
**Describe the bug**

I am using an octopus home mini and the current consumption sensor with Utility meter to try to track my peak and Offpeak usage. My tariff is intelligent octopus. Despite having the correct automations to switch tariffs, the current consumption sensor consistently underreports usage (I have compared it with a Shelly EM device) both using the statistics graph and also when added to the energy dashboard.

Interestingly an another home assistant instance, when the current consumption sensor is added directly to the energy dashboard it reports correctly.

**To Reproduce**

Set up utility meter with default options. When asked for tariff create peak and offpeak. 

**Expected behavior**

For the current consumption sensor to accurate track usage when used with utility meter

**Home Assistant Version**

2023.5.1

**Integration Version**

7.4.3

**Fresh Install?**

No

**Home Assistant Logs**

No relevant logs that I could see

**Comment by BottlecapDave** [comment]
Hello and sorry that you are encountering issues.

I've got a utility meter setup on my intstance and it appears to be working fine. You mentioned you used the default options, which might be causing your issues. You need to have `delta values` set to true because of the nature of the data.

**Comment by chinedu40** [comment]
Thanks a lot for the quick reply. I’ll make this change and report back

**Comment by chinedu40** [comment]
Thanks @BottlecapDave, this is now working as expected!
