### ISSUE TITLE
Trigger based on current rate

### ISSUE THREAD

**Issue by d1964b** [BottlecapDave/HomeAssistant-OctopusEnergy#289]
PLEASE DO NOT DELETE AND FILL IN!

Problem starting automation based on state value

**To Reproduce**

I've created an automation with the trigger:
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/31854979/59c8d556-34b4-4745-90ee-00bf2490dfe4)

**Expected behavior**

I expected the automation to activate when the current price drops below 0

**Home Assistant Version**

2023.6.3

**Integration Version**

7.4.4

**Fresh Install?**

Fresh install

**Home Assistant Logs**

nothing in logs I can see

**Comment by BottlecapDave** [comment]
Hello. If you are having issues with automations triggering and you can see the history of the current price going below zero, then this would be a HA issue.

You can look at the traces of automations to work out why automations don't trigger. Below is exclusive so the value would need to be -0.01 before it would trigger. It also won't retrigger if if drops below 0 and then updates to another value that is still below 0 (see https://www.home-assistant.io/docs/automation/trigger/#numeric-state-trigger)

Did the history of the sensor show the correct price?

**Comment by d1964b** [comment]
Hi , Thanks for the quick response. It was the fact that the prior value was also below 0 that was the root of the problem so the threshold was never crossed. User error !
