### ISSUE TITLE
Day / Week and Month costs are all zero

### ISSUE THREAD

**Issue by Aryankids** [BottlecapDave/HomeAssistant-OctopusEnergy#291]
PLEASE DO NOT DELETE AND FILL IN!

**Describe the bug**

The integration's installation and setup went ahead very smoothly. I used the suggested sensors to create the dashboard. 
Whilst the very same sensors report correctly on my own dashboard (another card), these are not working as expected on the HA Energy dashboard. They report the cost as zero!

The only way that I could get this to work is to change the view to Year (please see attached) apart from that either consumptions are missing (and there are some costs  OR) the costs are missing whilst there are some consumptions!
Please see attached

**To Reproduce**

**Expected behavior**

to see the actual costs per day (last day)

**Home Assistant Version**

Home Assistant 2023.6.3
Supervisor 2023.06.4
Operating System 10.3
Frontend 20230608.0 - latest

**Integration Version**

7.4.4

**Fresh Install?**

Yes, fresh install 

**Home Assistant Logs**

Nothing to report :( 
<img width="977" alt="Screenshot 2023-07-02 at 21 31 56" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/12873849/7b788a3b-28b9-4926-abc6-f0bdb3489c7c">
<img width="948" alt="Screenshot 2023-07-02 at 21 32 20" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/12873849/50984ed6-e2ff-4200-a8ca-cfb847ffe4de">
<img width="1125" alt="Screenshot 2023-07-02 at 21 48 01" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/12873849/36a6db5d-8d38-4bcc-bb9a-535192017da3">

**Comment by BottlecapDave** [comment]
Hello and sorry that you're having issues. Unfortunately if the data is being displayed in the year view and present on the entity itself, then that suggests it's a HA issue not an integration issue. The only thing I can suggest is to double check the docs and make sure the pricing entities have been set in the correct modes.
