### ISSUE TITLE
Since Updating to v7.4.4 Agile Prices are no Longer Showing, Error "There are no rates assigned to that entity"

### ISSUE THREAD

**Issue by poolitman** [BottlecapDave/HomeAssistant-OctopusEnergy#292]
PLEASE DO NOT DELETE AND FILL IN!

**Describe the bug**
Since Updating to the latest version (v7.4.4) Agile Prices are no longer showing on the card. Instead it shows "There are no rates assigned to that entity" "Please check integration or chosen entity".
I haven't changed anything, I clicked the update button and restarted Home assistant when told to do so.

_Please provide a clear and concise description of what the bug/issue is._

**To Reproduce**

_Please provide steps to reproduce the behavior_

**Expected behavior**

_Please provide a clear and concise description of what you expected to happen._

**Home Assistant Version**

_Please provide the version of Home Assistant you are running_

**Integration Version**

_Please provide the version of the integration the bug/issue was discovered within._

**Fresh Install?**

_Was this from a fresh install of the integration or after an upgrade?_

**Home Assistant Logs**

_Are there any related logs available in Home Assistant? Please follow the instructions as outlined in the [readme](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy#increase-home-assistant-logs)._

**Comment by poolitman** [comment]
The Home Assistant version is 2023.6.3

**Comment by BottlecapDave** [comment]
Thanks for the logs. I'll have a look when I get a chance. I suggest you revert back to the last known good version as it might take me a couple of days to get a fix out.

**Comment by BottlecapDave** [comment]
Hello. This should be fixed as part of [v7.4.5](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v7.4.5)

**Comment by poolitman** [comment]
Thanks that's now sorted
