### ISSUE TITLE
after updating, entities dissapear

### ISSUE THREAD

**Issue by jtetzlaff** [BottlecapDave/HomeAssistant-OctopusEnergy#293]
PLEASE DO NOT DELETE AND FILL IN!

**Describe the bug**

After uptating to latest version, entities dissapeared and only 4 are present, none of which provide current readings (this is used on an account with Octopus Mini

**To Reproduce**

Update to altest version of integration

**Expected behavior**

Being able to read meter values as well as current demand

**Home Assistant Version**

Home Assistant 2023.6.3
Supervisor 2023.06.4
Operating System 10.3
Frontend 20230608.0 - latest

**Integration Version**

v7.4.4

**Fresh Install?**

update

**Home Assistant Logs**

**Comment by jtetzlaff** [comment]
Enabled debug logging, and attempted to reconfigure integration.
[home-assistant_octopus_energy_2023-07-03T10-53-24.572Z.log](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/11936043/home-assistant_octopus_energy_2023-07-03T10-53-24.572Z.log)

**Comment by BottlecapDave** [comment]
Thanks for the logs. I'll have a look when I get a chance. I suggest you revert back to the last known good version as it might take me a couple of days to get a fix out.

**Comment by jtetzlaff** [comment]
sorry for the dumb question. how can i revert to previous version or install the previous one?

**Comment by jtetzlaff** [comment]
Thanks, I've reverted to 7.4.3 and entities are back.

**Comment by BottlecapDave** [comment]
Hello. This should be fixed as part of [v7.4.5](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v7.4.5)
