### ISSUE TITLE
Electric current consumption not being read properly

### ISSUE THREAD

**Issue by spinecho31** [BottlecapDave/HomeAssistant-OctopusEnergy#295]
**Describe the bug**

When adding the "current consumption" entity it doesn't represent what is the house actual current consumption when measured with the Solax inverter.
Monthly electricity bill matches the Inverter data

**To Reproduce**

Need Solax inverter or a way to measure accurately the incoming grid power.
Plot both entities "electric current consumption" and "Local grid used power"
![Screenshot_20230704-051200](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/54399974/d3aaaac9-53ec-40f8-a220-65990e3e736f)

**Expected behavior**
I would expect to see a current consumption to match the current usage of 10KW. As we can see in the graph above "electric current consumption" is registering approx. 250Wh when we should have a consumption of 10KWh

**Home Assistant Version**

2023.6.3

**Integration Version**

v 7.4.4

**Fresh Install?**

Yes

**Home Assistant Logs**

None relevant

**Comment by spinecho31** [comment]
The data in the integration:

![Screenshot_20230704-212326](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/54399974/ba1619c4-1eee-4e02-8dff-e7116a472b58)

Doesn't seem to match the app data:

![Screenshot_20230704-212426](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/54399974/5dc47b05-175d-4ea6-91ec-e7d80034cefe)

Is this what you needed?

**Comment by BottlecapDave** [comment]
Interesting. Sorry to make you jump through hoops, but what does it look like in the energy dashboard? I'm interested in the total reported consumption as well as the vague shape of the bars (the sensor is reported in minutes whereas octopus reports it in 30 minute intervals)

The only thing I can think of is that you have another "device" associated with your import meter which is usually the octopus mini but perhaps is setting else. In this scenario, it's going to be very hard for me to track down as it will be account specific.
