### ISSUE TITLE
Error in logs relating to consumption entities

### ISSUE THREAD

**Issue by mdeakin99** [BottlecapDave/HomeAssistant-OctopusEnergy#3]
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:213
Integration: Sensor (documentation, issues)
First occurred: 13:42:09 (4 occurrences)
Last logged: 13:42:09

Entity sensor.octopus_energy_electricity_d04c17719_latest_consumption (<class 'custom_components.octopus_energy.sensor.OctopusEnergyLatestElectricityReading'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
Entity sensor.octopus_energy_electricity_20j0042018_latest_consumption (<class 'custom_components.octopus_energy.sensor.OctopusEnergyLatestElectricityReading'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
Entity sensor.octopus_energy_gas_g4a50048220401_latest_consumption (<class 'custom_components.octopus_energy.sensor.OctopusEnergyLatestGasReading'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
Entity sensor.octopus_energy_gas_e6s20464742061_latest_consumption (<class 'custom_components.octopus_energy.sensor.OctopusEnergyLatestGasReading'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.

**Comment by BottlecapDave** [comment]
Updated the sensors which should now remove these warnings
