### ISSUE TITLE
Previous Half Rate Not Shown Between Midnight and Half Past

### ISSUE THREAD

**Issue by sembeeuk** [BottlecapDave/HomeAssistant-OctopusEnergy#300]
PLEASE DO NOT DELETE AND FILL IN!

**Describe the bug**

Between the time of midnight (0000) and half past (0030) the previous half hour value is shown as Unknown. 

**To Reproduce**

Watch the integration at midnight. 

**Expected behavior**

The previous half hour rate (from 2330 to 0000) to be shown. 

**Home Assistant Version**

2023.6.3, but looking at the history, it has been happening for some time - I have six weeks of data and it is in all of them, every day. 

**Integration Version**

7.4.5, but it has been happening for a number of weeks going by the logs. Rarely up at midnight to see it!

**Fresh Install?**

Upgrade.

**Comment by BottlecapDave** [comment]
Hello and sorry you're seeing this issue. I know what the cause is and I'll try and fix it when I get an opportunity.

**Comment by BottlecapDave** [comment]
Hello. This has been fixed in the latest release https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v8.0.0. Please also note the behaviour of the sensors has changed for non agile tariffs.
