### ISSUE TITLE
Sanity check/discard insane values?

### ISSUE THREAD

**Issue by dragon2611** [BottlecapDave/HomeAssistant-OctopusEnergy#301]
**Describe the feature**

Could we get some kind of logic to discard silly values coming back from the octopus api?

Occasionally if the signal between the smart meter and the mini is bad it will report some kind of impossible reading.

For instance it’s trying to say I exported 10,236.7 KW today all within 30mins, I don’t have any local generation and I would have probably vaporised half the cables in the area had I actually done that.

I’ve seen it before with the IHD as well

**Expected behavior**
Ideally any values are are so far outside what is physically possible should be discarded or an error should be produced.

**Comment by BottlecapDave** [comment]
Hello and thanks for raising the enhancement. However, I'm reluctant to add this feature as I feel it will cause more bugs to be raised when values don't match the OE dashboard. I feel this is something that should be raised with HA and have them fix it on their end.

**Comment by dragon2611** [comment]
I think OE is doing something to discard readings, Octo aid also shows bad readings.

**Comment by BottlecapDave** [comment]
Closing as not planned
