### ISSUE TITLE
Documentation: Target rate current/average cost

### ISSUE THREAD

**Issue by dan1elhughes** [BottlecapDave/HomeAssistant-OctopusEnergy#302]
**Describe the feature**

It's not super clear to me what the attributes _Overall average cost_ and _Current average cost_ mean.

I have two intuitions:

- The overall average is the average of _all_ sessions of that target since it was configured, and the current is the average for all sessions in the current period (e.g. today)
- The overall average is the average of all of _today's_ sessions, and the current is the average for the current session. (This makes more sense in the context of an intermittent target.)

**Expected behavior**

A mention of these attributes in the docs :-) 🙏

Love the project - thank you so much for all you do here!

I'm happy to PR a change to the docs if you're able to explain in this issue thread what the right answer is :-)

**Comment by BottlecapDave** [comment]
Hi there. You second intuition is the correct one, except to be picky overall is the average for the current search period (defined by the from/to options, which might span over two partial days). It was setup mainly for intermittent rate sensors but can also be beneficial for continuous ones if you've passed the chosen block. It was on my list to add the attributes for the target rate sensors, but tbh I forgot. I'll leave this ticket open until I've updated the docs. Hopefully everything else is clearer for you :)

**Comment by BottlecapDave** [comment]
I've updated the documentation, which can be found in the [target rates docs](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/setup_target_rate.md)
