### ISSUE TITLE
Hour Chunks for Previous Day?

### ISSUE THREAD

**Issue by eximo84** [BottlecapDave/HomeAssistant-OctopusEnergy#304]
PLEASE DO NOT DELETE AND FILL IN!

**Describe the bug**

_Please provide a clear and concise description of what the bug/issue is._

Using the previous days consumption rate my graph isn’t chunked into hours. Instead it’s just one entry on the bar. 

Should this show per hour?

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/25502878/6ff8471d-a757-496e-acb1-b0a0d9c2119c)

**To Reproduce**

_Please provide steps to reproduce the behavior_

No steps

**Expected behavior**

_Please provide a clear and concise description of what you expected to happen._

Chunked data per hour on the day graph

**Home Assistant Version**

_Please provide the version of Home Assistant you are running_

**Integration Version**

_Please provide the version of the integration the bug/issue was discovered within._

Latest

**Fresh Install?**

_Was this from a fresh install of the integration or after an upgrade?_

**Home Assistant Logs**

_Are there any related logs available in Home Assistant? Please follow the instructions as outlined in the [readme](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy#increase-home-assistant-logs)._

**Comment by BottlecapDave** [comment]
As per the [docs](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/energy_dashboard.md#previous-day-consumption) this is already possible. Based on limitations of the data and HA, this has to be done slightly differently.

**Comment by eximo84** [comment]
Sorry I’m confused. The docs are not clear on what sensors to use. The external statistics sensor?

Are they created automatically?

**Comment by BottlecapDave** [comment]
Point 3 within the linked documentation identifies the sensors that needs to be added to the energy dashboard in order to gain hourly breakdowns. These sensors are in a form that are prefixed with `octopus_energy:` instead of `sensor.`. These sensors are automatically generated upon receiving the first data retrieval (which is why it states it can take up to 24 hours to appear).

**Comment by eximo84** [comment]
Ah damn I completely missed the “octopus_energy:” prefix. Damn sensor names are so long with the mpan and serial number it’s hard to see which ones on mobile. 

Seems to be fixed. Thanks for the help. Sorry to bug you 🙂.

**Comment by BottlecapDave** [comment]
No problem. Unfortunately the names have to be long to avoid clashes :( I try and have the important information at the beginning. Any contributions to documentation to make things easier are more than welcome.
