### ISSUE TITLE
Tracker Tomorrow Rates

### ISSUE THREAD

**Issue by gapthorpe** [BottlecapDave/HomeAssistant-OctopusEnergy#310]
Octopus publish the Tracker rates for the next day in advance, roughly available from 11am and can be accessed from the API:
https://api.octopus.energy/v1/products/SILVER-VAR-22-10-21/electricity-tariffs/E-1R-SILVER-VAR-22-10-21-A/standard-unit-rates/?period_from=tomorrowT00:01:00Z&period_to=dayafterT12:00:00Z

It would be great if this could become part of the integration to call this and set the tomorrow value when available.

(And thanks for this awesome integration btw!)

**Comment by BottlecapDave** [comment]
Hello and thanks for the issue.

The integration already calls this endpoint as it's primary source. It then falls back onto an undocumented endpoint to gain tracker information if data isn't available. This is because certain products were not available via this endpoint. However, these products have recently become available so the undocumented endpoint will probably go away in the future.

**Comment by gapthorpe** [comment]
Thanks Dave - it’s more calling with tomorrows date so that it gets the tracker rate for the next day, as well as the current values. 
Thanks

**Comment by BottlecapDave** [comment]
For electricity, rates are retrieved every 30 minutes and already retrieve rates for today and tomorrow. If there are errors reported by OE, then it will attempt again at the next opportunity. For gas, rates are currently only retrieved for today, but this will change in a future update.

**Comment by gapthorpe** [comment]
Thanks, but unfortunately I’m not seeing that at the moment on the tracker tarriff - it’s still showing 16p in HA for the next rate, but calling the API I am getting the correct tomorrow rate of 11p

**Comment by BottlecapDave** [comment]
As per the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/sensors/electricity.md#next-rate), the next rate is for the next 30 minute period, so won't change until ~11:30pm in your scenario.
This sensor was mainly built with agile tariff in mind.

**Comment by gapthorpe** [comment]
Understood - that’s why I was wondering if this could be a potential enhancement for those on Tracker to get the tomorrow values

**Comment by BottlecapDave** [comment]
The data is available (should be present in the `rates` attribute of the current rate sensor). I'll need to consider the change in behaviour as it will be a breaking change for anyone else using the integration, but what you're expecting makes sense (and would be more useful for people outside of agile tariff)

**Comment by gapthorpe** [comment]
Ah I hadn’t spotted in the attributes, can see there thanks!
Understood - and can see how the rates and different requirements across them does make this tricky, but thanks for considering and let me know if anything I can do to help. Thanks!

**Comment by andyvee69** [comment]
For tracker, next 30 minutes isn't really applicable as the rates are a single rate for 24hrs. It really needs to be in 24hr 'blocks', not 30 minute blocks as Agile is

**Comment by andyvee69** [comment]
Also, the endpoint for the current Tracker is

https://api.octopus.energy/v1/products/SILVER-FLEX-22-11-25/electricity-tariffs/E-1R-SILVER-FLEX-22-11-25-G/standard-unit-rates/

**Comment by BottlecapDave** [comment]
> For tracker, next 30 minutes isn't really applicable as the rates are a single rate for 24hrs. It really needs to be in 24hr 'blocks', not 30 minute blocks as Agile is

As mentioned considerations need to be made for other tariffs and how users are currently using the sensors. Fully appreciate 24 hour blocks would be more useful in this scenario.

> Also, the endpoint for the current Tracker is
https://api.octopus.energy/v1/products/SILVER-FLEX-22-11-25/electricity-tariffs/E-1R-SILVER-FLEX-22-11-25-G/standard-unit-rates/

This fully depends on which variation of the tracker tariff you're on. As mentioned, the integration already uses this endpoint if data is available and exposed via attributes.

**Comment by andyvee69** [comment]
Yes, agreed it depends which variant you are on. A lot of people will have switched to Tracker on 1st July when Octopus opened it back up to those on the waitlist, so will be on this variant. Plus a month ago that endpoint didn't exist and the previously posted endpoint was used for both the October and November variants of the tariff. Unit rates should be the same between the two anyway. SC and cap might be different though.

**Comment by deltamelter** [comment]
I think a lot of people, like me, are on agile for electricity and tracker for gas and as OE switched everybody asking for gas tracker for both fuels "accidentally" there maybe quite a few who didn't bother to contact OE to get their agile back.  
Now tracker is open to all.

**Comment by GTunney** [comment]
Have just recently switched to Tracker and also interested in trying to get tomorrows rates to show, maybe something configurable to switch it from Agile to Tracker or another entity for tracker?

**Comment by TheNeutrinoRaged** [comment]
After recent updates the "Next Rate" entity should show you tomorrow's price if you're on tracker.

It updates for me at around 11:00 am these days (I think due to BST, will be 10:00 when the clocks go back) which means between midnight and 11:00 it'll be "Unknown"

**Comment by GTunney** [comment]
> After recent updates the "Next Rate" entity should show you tomorrow's price if you're on tracker.
> 
> It updates for me at around 11:00 am these days (I think due to BST, will be 10:00 when the clocks go back) which means between midnight and 11:00 it'll be "Unknown"
> 
> edit: Here's a screenshot of my entities card ![image](https://user-images.githubusercontent.com/26345725/258116263-3fde4ed8-473a-40c3-a93a-4f945c0af3f4.png)

Thats excellent, how can we force this update through? Mine is still showing todays rate for next rate.

**Comment by TheNeutrinoRaged** [comment]
I take it you're using 7.5.2? I'm using the latest version of develop branch, I've just realised that might be why it works for me but I'm not sure

I installed manually (not using HACS) so it's pretty easy for me two switch between the two, not sure how you can do that if you're using HACS. For manual instlalation it's just  case of downloading [the latest zip from develop](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/archive/refs/heads/develop.zip) and installing it in config/custom_components

**Comment by GTunney** [comment]
That will be why, I've just changed mine over to develop and the next rate is now showing.

Now to work out a clean way to have it showing in pence and not GBP, I could remove the /100 from next_rate.py but I'd need to do that every time it updated.

**Comment by TheNeutrinoRaged** [comment]
[Template sensor is the way to go](https://www.home-assistant.io/integrations/template/)

Something like this but it'll throw errors while the value is Unknown, you might want to add some checks for that

`state:{{(states('sensor.octopus_energy_electricity_21l3661647_2199998207592_next_rate') | float * 100 ) | round(2) }}`

**Comment by GTunney** [comment]
> 

Yup I had something like that already and it was throwing errors as Gas was unknown.

Managed to settle on the below and it's happy, it reports gas as 0.0p for now so it's a lot better.

`Gas: {{ states('sensor.octopus_energy_gas_e6e01661902110_7631670809_next_rate') | float(default=0.0) | multiply(100) | round(2) }}p kW/h`

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/4008830/43965b03-04aa-4ae4-976f-7193155aa962)

**Comment by BottlecapDave** [comment]
This is part of an upcoming release. It's nearing the end (need some more testing), but as this is a breaking change (e.g. change in existing behaviour), I'm trying to combine it with some other breaking changes.

**Comment by GTunney** [comment]
> 

Thanks for all your hardwork @BottlecapDave, looking forward to the official release, I've switched over to dev for now to get tomorrows prices. Only thing I've noticed is it doesn't seem to be updating via the 30 min api calls and I need to reload the integration to get it to update for some reason.

**Comment by BottlecapDave** [comment]
The behavior of the rates has now been changed and release in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v8.0.0

@GTunney I couldn't replicate your issue locally but I've added some additional logging and it might be related to old tracker logic which has been removed. If it continues to be an issue, please raise a new ticket.

**Comment by gapthorpe** [comment]
Amazing and thanks Dave, but I don’t seem to be getting tomorrow gas rates coming through at the moment? Let me know if anything I can help check

**Comment by BottlecapDave** [comment]
@gapthorpe Based on https://api.octopus.energy/v1/products/SILVER-VAR-22-10-21/gas-tariffs/G-1R-SILVER-VAR-22-10-21-A/standard-unit-rates/ (which is probably slightly different to your tariff), gas rates have not been published yet. They seem to be published a little later than electricity rates. Got to love the energy market :)

**Comment by gapthorpe** [comment]
Thanks Dave, unfortunately I am still seeing unknown on my data.

endpoint is:
https://api.octopus.energy/v1/products/SILVER-FLEX-22-11-25/gas-tariffs/G-1R-SILVER-FLEX-22-11-25-A/standard-unit-rates/

I am seeing this in the data:
[{"value_exc_vat":3.73,"value_inc_vat":3.9165,"valid_from":"2023-08-05T23:00:00Z","valid_to":"2023-08-06T23:00:00Z","payment_method":null},

So is this a DST issue for the start time for tomorrows data?

**Comment by andyvee69** [comment]
Same here - tomorrow gas rate showing as unknown but the data is available
via the API

https://api.octopus.energy/v1/products/SILVER-VAR-22-10-21/gas-tariffs/G-1R-SILVER-VAR-22-10-21-G/standard-unit-rates/

**Comment by BottlecapDave** [comment]
As per the [docs](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/sensors/gas.md#next-rate), the sensor is appearing as unknown because it's not different from the current rate (and therefore the next rate is unknown because we don't know when it'll change)

**Comment by gapthorpe** [comment]
Thanks Dave and understood - is there any attribute or way to tell though if it is due to not being available yet, or is just the same? Perhaps an attribute for how far ahead the values are available for which will then tell us if the next tracker rate is set?

Thanks again for your great work on this!

**Comment by TheNeutrinoRaged** [comment]
There's a valid_to attribute for the current rate entity, I've just put an extra line in my entities card to display it
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/26345725/d53b29b3-8ccc-4c6b-9a46-bfec49901c80)

**Comment by jarrodstrachan96** [comment]
I wrote a template sensor to use the current_rate if next_rate is unknown (ie not yet published). I think the logic makes sense, I'm not sure when Octopus publish the next day's rates for tracker tarrifs.

`    energy_today_electricity_rate:
        friendly_name: "Today's Electricity rate"
        value_template: >-
            {% set rate = states('sensor.octopus_energy_electricity_x_current_rate') | float %}
            {{ rate | float(default=0.0) | multiply(100) | round(2)}}
  
    energy_today_gas_rate:
        friendly_name: "Today's Gas rate"
        value_template: >-
            {% set rate = states('sensor.octopus_energy_gas_x_current_rate') | float %}
            {{ rate | multiply(100)}}
        
    energy_tomorrow_electricity_rate:
        friendly_name: "Tomorrow's Electricity rate"
        value_template: >-
            {% if states('sensor.octopus_energy_electricity_x_next_rate') == 'unknown' %} 
            {{ states('sensor.octopus_energy_electricity_x_current_rate') | float(default=0.0) | multiply(100) | round(2)}}
            {% else %}
            {{ states('sensor.octopus_energy_electricity_x_next_rate') | float(default=0.0) | multiply(100) | round(2)}}
            {% endif %}   
  
    energy_tomorrow_gas_rate:
        friendly_name: "Tomorrow's Gas rate"
        value_template: >-
            {% if states('sensor.octopus_energy_electricity_x_next_rate') == 'unknown' %} 
            {{ states('sensor.octopus_energy_gas_x') | float(default=0.0) | multiply(100) | round(2)}}
            {% else %}
            {{ states('sensor.octopus_energy_gas_x_next_rate') | float(default=0.0) | multiply(100) | round(2)}}
            {% endif %}   

![energydash](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/81656574/09e23277-b8fd-4518-9295-88c4a45f27bc)
