### ISSUE TITLE
Gas current consumption data missing

### ISSUE THREAD

**Issue by CarlD21** [BottlecapDave/HomeAssistant-OctopusEnergy#312]
### Describe the bug

Hi, setup gas reading in HA, keep getting the following 

statistics_not_defined
sensor.octopus_energy_gas_g4f74808131700_576923809_previous_accumulative_consumption
Entity unavailable
The state of these configured entities are currently not available:
sensor.octopus_energy_gas_g4f74808131700_576923809_previous_accumulative_consumption (unknown)

### Reproduction steps

The electrical meter reading are working fine, no issues, but cannot get the Gas reading to work 

### Expected behaviour

to see gas usage 

### Integration Version

V7.5.0

### Home Assistant Version

Home Assistant 2023.7.2 Supervisor 2023.07.1 Operating System 10.3 Frontend 20230705.1 - latest

### Fresh Install?

Fresh install

### Home Assistant Logs

2023-07-15 19:01:08.691 WARNING (MainThread) [homeassistant.components.number] custom_components.octopus_energy.intelligent.charge_limit::OctopusEnergyIntelligentChargeLimit is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
2023-07-15 19:20:10.304 WARNING (MainThread) [homeassistant.components.media_player] Error retrieving proxied image from http://192.168.1.62:1400/getaa?s=1&u=x-sonos-http:546914607717de6489ba97ff41422dfaf023ed7a%253aNone%253a13868%253atrack.mp3?sid%3D212%26flags%3D24608%26sn%3D7

**Comment by BottlecapDave** [comment]
Afternoon and sorry that you're having issues. 

Is this error being reported when trying to configure the sensor in the energy dashboard? If so, you might need to wait up to 24 hours as OE can take a while receiving the gas sensor data from your smart meter. 

It is also advised to follow the guide as outlined in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/energy_dashboard.md#previous-day-consumption to get hourly breakdowns. Again it might take up to 24 hours for the outlined sensor to appear.

**Comment by CarlD21** [comment]
Thanks, for responding

I get no update for gas at all, I have set it up with the error, and left for over a week, and no update for the gas

I will review the link, and try to see if this will resolve mu issue.
thanks

**Comment by BottlecapDave** [comment]
Hmm I have had a small number of reports in the past of people not receiving gas because their meters sends the data over 24 hours later, which might be happening in your scenario. Can you see the gas in the octopus energy app or dashboard for the previous day?

**Comment by CarlD21** [comment]
HI,

Only just download the app to my phone, which show Elec usage/cost But No Gas

I am getting reading on my Smart meter for both Gas & Elec , so not sure why I am not getting same reading from the amp or in HA

Carl

**Comment by BottlecapDave** [comment]
That at least gives a clue as to why you're not receiving the data within the integration, as the app uses the same API and data as the integration. Do you get any data within the app (e.g. a couple of days late?) 

Ultimately, this might be an issue that would require HA support.

**Comment by andyblac** [comment]
> Hmm I have had a small number of reports in the past of people not receiving gas because their meters sends the data over 24 hours later, which might be happening in your scenario. Can you see the gas in the octopus energy app or dashboard for the previous day?

This just seemed to happen to me, my energy dashboard is missing my Gas data for the 11th Aug, as it just updated in Octopus' App this morning, what can i do to get the data to the Energy Dashboard ?

**Comment by andyblac** [comment]
the data can be downloaded manually via Octopus' website for here https://octopus.energy/dashboard/new/accounts/A-XXXXX/consumption/home, is there way you could add support for us to manually inject the data into the statics ?, or better yet check there for the data each day that has any missing data and import it automatically?
<img width="607" alt="Screenshot 2023-08-13 at 11 26 53" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/77936/77ecdd37-a9b6-40f1-bb1e-e6c8c0ac7ba3">

**Comment by BottlecapDave** [comment]
There is currently no way of importing the data via the integration, and there is no simple way of working out if data is missing via the HA APIs, and could get into very nasty situations if data never appears (which has happened to some users).

I've created a ticket in the backlog to expose a service that can be called manually to import additional data for a given previous consumption meter.

**Comment by BottlecapDave** [comment]
@femxiii The rate at which the data is updated varies from customer to customer (possibly from smart meter to smart meter). Some users have a delay in receiving their data. You could potentially contact OE for more clarification.

**Comment by BottlecapDave** [comment]
I've added the ability to set the offset for the previous consumption sensors in scenarios where OE are delayed in obtaining your information. This can be found in [v8.3.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v8.3.0), and the docs can be found at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/setup_account.md#previous-consumption-days-offset

I'm still working on a separate service for importing data from adhoc periods (like in the scenario of a day of data being missing), so I'll keep this issue open until that has been added.

**Comment by CarlD21** [comment]
David,

Thanks for the update, But I am still getting the following error when I try to set up the gas reading, what am I doing wrong ??

[cid:b8b95c39-58b8-47c1-9b43-2dfe7392080f]


Carl Dawson
T: (+44) 07958 752 968
***@***.******@***.***>
________________________________

**Comment by BottlecapDave** [comment]
I can't see the error you're receiving (also you might want to remove your phone number from your last message?)

**Comment by CarlD21** [comment]
David

I have attached a copy of the error OE Gas

Carl Dawson


________________________________

**Comment by BottlecapDave** [comment]
It's not coming through in github, unless you mean the original error in the post.

> Only just download the app to my phone, which show Elec usage/cost But No Gas
I am getting reading on my Smart meter for both Gas & Elec , so not sure why I am not getting same reading from the amp or in HA

Here you mentioned that the gas data wasn't available within the app or OE dashboard. If the data is available, but delayed (e.g. you can see up to 3 days ago), then you can use the new feature to change the day offset that the previous consumption sensors look at. If the data isn't available at all, then this integration won't be able to get you your data as it uses the same source.

**Comment by BottlecapDave** [comment]
A [new service](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/setup_account.md#service-octopus_energyrefresh_previous_consumption_data) is now available in v8.4.0 to manually refresh the data for previous consumption data.
