### ISSUE TITLE
Overriding deprecated methods on an instance of NumberEntity

### ISSUE THREAD

**Issue by JRascagneres** [BottlecapDave/HomeAssistant-OctopusEnergy#313]
### Describe the bug

Just a log message saying something is deprecated. Likely already know but I couldn't find an existing issue mentioning it so felt I should open a tracking issue for it.

### Reproduction steps

N/A

### Expected behaviour

N/A

### Integration Version

7.5.0

### Home Assistant Version

2023.7.2

### Fresh Install?

Fresh install

### Home Assistant Logs

Logger: homeassistant.components.number
Source: components/number/__init__.py:114
Integration: Number ([documentation](https://www.home-assistant.io/integrations/number), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+number%22))
First occurred: 03:56:49 (1 occurrences)
Last logged: 03:56:49

custom_components.octopus_energy.intelligent.charge_limit::OctopusEnergyIntelligentChargeLimit is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

**Comment by BottlecapDave** [comment]
Thanks for raising. I saw this in another raised issue, but good to have it tracked separately.

**Comment by BottlecapDave** [comment]
Hello. This has been fixed in the latest release https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v8.0.0
