### ISSUE TITLE
Update to 7.5.0 - and saver session flag

### ISSUE THREAD

**Issue by Jilas** [BottlecapDave/HomeAssistant-OctopusEnergy#316]
### Describe the bug

Had some oddities moving over to this update (as seen in the discussions kept losing data, now found that out to be connection limits).

So this leaves me with odd one, the saver session flag is turned on, where in 7.4.5 is was off.

Not a big issue, but given I had automations linked to it to shutdown the house (thankfully I had remembered to disabled it!) it gave me a moment.

### Reproduction steps

Install 7.5.0 add account, saver is turned on.

Reverting to 7.4.5 the flag turns off.

### Expected behaviour

Saver should be Off

### Integration Version

7.5.0

### Home Assistant Version

2023.7.2

### Fresh Install?

Not specified

### Home Assistant Logs

No logs can provide if there is a specific one needed

**Comment by Jilas** [comment]
I'm confused again (just going to be one of those weeks!!).  So just checked back, and now the flag is off.. looking at the sensor it took from 11:26 unyil 11.57 for the state to change to off.

So reconnected the test HA, it's still on? (and data is currently flowing).  Reloaded it on the production HA, and saver is on again.

By chance is this flag now set as default to on until the update from Octopus, which I'm guessing is on/close to the hour (11.57.45).  And as I was having connection issues and not getting data at that point with both HA's on, this is why it never turned off. 

I'll shut off test and I'll see if it updates the saver session at 13:57 and report back.

**Comment by Jilas** [comment]
It finally reset at 16.53.  needed to reboot for something else the same came back on 17.19 and turned off at 17.30

I've no idea what is going on but any reboot of HA OR just reload of the addon, forces saver on.

Anything I can test it log let me know.

**Comment by apbarratt** [comment]
I too am encountering this issue. I've a number of conditional cards on my dashboards that are based on the saving session binary sensor and it being stuck at 'on' for some reason is causing some oddities. All my light switch cards vanished for instance. ![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/642320/4b2c6f15-8b8e-4ca7-85c7-043ee95c0480)

**Comment by BottlecapDave** [comment]
Looking at the code, it might be an issue in the restore state logic. I might remove that for this sensor as it might be trying to reload an old state when it was on.

**Comment by Jilas** [comment]
> This is very odd, as nothing has changed in the sensor in the last release. I am also not seeing this behaviour myself. It should only turn on if you're within a joined event's time. Is there anything in the `joined_events` attribute of the sensor that might give a clue as to why this is coming on?

![Screenshot_20230719-072349-144.png](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/42086441/f88d498c-99e5-4496-8b61-5a80a05c318c)


In case that helps.

**Comment by Jilas** [comment]
> Looking at the code, it might be an issue in the restore state logic. I might remove that for this sensor as it might be trying to reload an old state when it was on.

> I'm not sure why you can't reproduce it, that's even stranger.  I have it on two instances, which are even different hardware, the test has a minimal configuration.  

Just tried it again, as it's been on all night, after a reload no change (while getting data from octopus). 

So you want any log files, as I can pull that off my test instance, (as it's quieter but having the issue as well).

**Comment by apbarratt** [comment]
I'll have a proper look at states soon, but I would also point out a couple of oddities that might trigger some strangeness.  I just had an export tariff added, so I know strange stuff can show up when tariff changes are happening but it's generally settled down now.  Additionally, the other day when I reloaded the integration (I was already having issues at that point) to see if the export tariff was coming through yet, I gained a second Gas Meter device with no entities.  Very odd.  I'll be interested to see what happens when my gas meter is disconnected at the end of the month (I've now got a heatpump so no need for gas).

**Comment by apbarratt** [comment]
![Screenshot 2023-07-19 at 10 45 31](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/642320/3a7b1928-e2af-4b8d-a0b6-509008c68606)
No next session added, but could you remind me where the list of previous sessions is?  I was certain there used to be an attribute on some entity with a list of joined sessions and I'm not seeing it now :/

**Comment by apbarratt** [comment]
![Screenshot 2023-07-19 at 10 48 42](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/642320/8bd8ae64-016c-4c4e-bea9-4ee5d85b3247)
Yes, here we are, this old card of mine I've got hidden behind one of the problem conditionals right now relies on a `joined_events` attribute that doesn't seem to be showing up anymore :/

**Comment by apbarratt** [comment]
Actually kind of curious as to how that `state_attr` function was ever working given it doesn't have the `binary_sensor.` domain specified :/ But that's off topic.

**Comment by apbarratt** [comment]
Sorry, I'm going blind.  That joined_events attribute is indeed there, but it seems to have been emptied out with no entries now.  It doesn't even have an empty `[]` but then, perhaps yaml doesn't normally show that.
But my guess is Octopus have purged my previous joined sessions array, possibly as part of the various tariff changes I've been through lately, and that's upset the state restore process.

**Comment by Jilas** [comment]
> I'll have a proper look at states soon, but I would also point out a couple of oddities that might trigger some strangeness.  I just had an export tariff added, so I know strange stuff can show up when tariff changes are happening but it's generally settled down now.  Additionally, the other day when I reloaded the integration (I was already having issues at that point) to see if the export tariff was coming through yet, I gained a second Gas Meter device with no entities.  Very odd.  I'll be interested to see what happens when my gas meter is disconnected at the end of the month (I've now got a heatpump so no need for gas).

Increasingly I also got a second gas meter with no entities (deleting and adding the account cleared that). I thought it was due to switching to tracker.

**Comment by Jilas** [comment]
So the saver sessions is now off.  But the state of the entity has changed (not just on to off)![Screenshot_20230719-110708.png](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/42086441/d4b5f236-31f6-4252-b159-f98b60c28bc8)

**Comment by apbarratt** [comment]
That's curious, so it looks like it is indeed that list that's the problem.  Yours had disappeared in your last screenshot too, but now it's back it's managing to figure out the state properly.  So I'd say that's definitely something the logic could be tweaked to handle because we can be sure that if the joined_events list is empty then we can't possibly be in a saving session now :)

**Comment by BottlecapDave** [comment]
I've released a fix that will should fix this issue. This can be found at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v7.5.1

**Comment by apbarratt** [comment]
> I've released a fix that will should fix this issue. This can be found at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v7.5.1

That seems to have done the job for me, thank you muchly!

Did you figure out if it's a recent issue or just a coincidence that a couple of us encountered it at the same time?

**Comment by Jilas** [comment]
> I've released a fix that will should fix this issue. This can be found at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v7.5.1

Thanks for getting out a fix so quickly.  This and all your work is very much appreciated.

**Comment by BottlecapDave** [comment]
I believe this issue (among others) was related to a change I made to be more inline with HA docs. However, I should have taken the "if it aint broke, don't fix it" mentality with this one. The changes were made in a point release of v7.4, which you guys must have missed.

**Comment by Jilas** [comment]
That is the oddity, going back to 7.45 everything was fine straight away, roll forward it failed, I tried this on two instances of HA, with identical results.  Didn't log this until I think 3rd cycle timing backwards and forwards on both instances to be sure it wasn't me.

All made worse when it did appear in 7.5,  the recovery time to clear the varied unpredictably.  I suspect there was/is other things in play at octopus.

Will monitor it, which is easy as I have a bright red conditional card on my dashboard that appears when an event is on. (Very hard to miss!)

Either way.  Thanks your help is appreciated.
