### ISSUE TITLE
Error messages after update to v3.0.0

### ISSUE THREAD

**Issue by 35aportal** [BottlecapDave/HomeAssistant-OctopusEnergy#32]
I updated my custom_components folder with the new v3.0.0 files (just did a simple overwrite of previous files) and the integration appears to be working OK, other than this error message...

Logger: homeassistant.components.sensor
Source: custom_components/octopus_energy/sensor.py:107
Integration: Sensor (documentation, issues)
First occurred: 11:31:45 (1 occurrences)
Last logged: 11:31:45

Error while setting up octopus_energy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/octopus_energy/sensor.py", line 91, in async_setup_entry
    await async_setup_default_sensors(hass, entry, async_add_entities)
  File "/config/custom_components/octopus_energy/sensor.py", line 107, in async_setup_default_sensors
    tariff_code = hass.data[DOMAIN][DATA_TARIFF_CODE]
KeyError: 'TARIFF_CODE'

**Comment by BottlecapDave** [comment]
Hello, sorry you're having issues. I assume you have tried restarting your instance?

**Comment by BottlecapDave** [comment]
I'm struggling to recreate it locally, but I believe [v3.0.1](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v3.0.1) should fix the problem.

**Comment by 35aportal** [comment]
I've made the update now don't see the error - consider it fixed! Thanks for the awesome service.

Merry Christmas & Happy New Year.

**Comment by BottlecapDave** [comment]
Glad to hear that it worked.

Merry christmas and happy new year to you too!
