### ISSUE TITLE
Missing features from Intelligent plugin

### ISSUE THREAD

**Issue by springfall2008** [BottlecapDave/HomeAssistant-OctopusEnergy#320]
**Describe the feature**

In order to be able to replace the intelligent plugin totally it would be good to get the remaining features from the intelligent plugin that are not yet in the Octopus plugin

**Expected behavior**

Here's a snapshot from the Intelligent plug.

We have the vehicle battery size, charge point power and  the expected charge amount in each slot e.g:

chargeKwh: '-2.25'

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/48591903/7d242ca0-1731-445d-8c69-f1dbd6d05399)

**Comment by treforsouthwell-sifive** [comment]
It's used by Predbat (https://github.com/springfall2008/batpred) to plan car charging, currently I need to use the Intelligent Octopus plug as well as your plugin.

The battery size is needed with the target SOC% (which you already supply) to know when the car will be full.
The charge point power is used to know the maximum charging rate
And I use the kWh charge in each slot to know how to map the charging over time.

Predbat will automatically charge your home battery using IO slots (or at least stop it draining too far).

**Comment by BottlecapDave** [comment]
Ok thanks. I've added it to the backlog.

**Comment by BottlecapDave** [comment]
I've added these missing values in the latest release (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v8.1.0). I'm not on intelligent, so I added them a little bit blind. Please let me know if there are any issues.
