### ISSUE TITLE
The previous_accumulative_cost sensor doesn't seem to be updating

### ISSUE THREAD

**Issue by PedroKTFC** [BottlecapDave/HomeAssistant-OctopusEnergy#322]
### Describe the bug

The previous accumulative cost sensor doesn't seem to be updating recently. This is my current value (from developer tools) at the time of writing (it seems at least a day out of date if not two):

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/3314195/1d99352d-aa17-4774-b6c2-1a31eafa34bb)

### Reproduction steps

Just use developer tools to look at state and attributes.

### Expected behaviour

I would expect it to be more recent.

### Tariff Code

See the image.

### Integration Version

Latest (I don't know how to actually find this!)

### Home Assistant Version

2023.7.3

### Fresh Install?

Not specified

### Home Assistant Logs

Nothing in the logs.

**Comment by PedroKTFC** [comment]
Actually, looking at the Octopus data available, it looks like there's no more data available and I'm simply being impatient. Sorry!

**Comment by BottlecapDave** [comment]
Hello. From the screenshot you've posted it looks like it's updated recently. `last_calculated_timestamp` was midnight last night and the `charges` are for yesterday which is what I'd expect for . If you add up all of the charges and add the standing charge, does it add up to the value of the sensor?

> Latest (I don't know how to actually find this!)

If HACS (assuming you installed via it) says you're on the latest, then you're on the latest.
