### ISSUE TITLE
Extract Octopus API access into separate npm module

### ISSUE THREAD

**Issue by colinl** [BottlecapDave/HomeAssistant-OctopusEnergy#325]
I wonder whether you would consider extracting the Octopus comms out to a separate npm module (which would be a dependency of this HA plugin).

That would give your excellent work a larger use base as it could be used directly in non-HA installations of node-red or in other nodejs applications.

**Comment by colinl** [comment]
To clarify, I am particularly talking about the Home Mini access.  Alternatively perhaps you could point me to where the home mini api is documented so that I can do it myself.

**Comment by BottlecapDave** [comment]
Hi there. As the integration is written in python, I'm personally not interested in maintaining the core in multiple languages in addition to this integration which takes up a lot of my time already. With the license, anyone is more than welcome to port the logic to other languages.

> To clarify, I am particularly talking about the Home Mini access. Alternatively perhaps you could point me to where the home mini api is documented so that I can do it myself

The only documentation is their graphql schema (https://api.octopus.energy/v1/graphql/). The part you're interested in is https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/custom_components/octopus_energy/api_client.py#L117 which takes the `deviceId` returned by the meters from the users account https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/custom_components/octopus_energy/api_client.py#L20

**Comment by colinl** [comment]
Understood, thanks for the information.
