### ISSUE TITLE
Can data be 'cached' and only update when present

### ISSUE THREAD

**Issue by JRascagneres** [BottlecapDave/HomeAssistant-OctopusEnergy#336]
**Describe the feature**

It looks like Octopus API has gone a bit haywire, it seems to have missed most of today off of the agile API update meaning that the integration is a bit broken as its missing data. (Basically it seems to only show tomorrow and a bit of today.

https://agileprices.co.uk/?region=D is also affected. I have the API response locally if you want it for future. 

This means we're missing data for like 6 hours today. I know this isn't the fault of the integration but this update seems to have overwritten the data we had meaning there is a lot of "Unknowns". 

**Expected behavior**

Would be nice to not remove the existing data we have for todays rates, and only update the ones that are added to the API. That way if this happens again we don't lose the data.

**Comment by JRascagneres** [comment]
![Untitled](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/3264971/11d5b9d8-3155-4b87-8872-93392b6192d9)

I have the raw API output too if it helps. TLDR: Would be nice to not fall over when the API has bad data. Understand that we can't fix tomorrows data because its borked but it would be nice not to override todays data that we already had stored.

**Comment by deltamelter** [comment]
Even the chart on OE website is affected by this.
Was coming here to ask for similar regarding some kind of caching
Has the API format changed or confused something following month change?
Rates are available on the usual endpoint

**Comment by BottlecapDave** [comment]
Hi there. The integration currently does cache data, but not at a partial level and not between restarts of HA. I'll add it to the list, but can't commit to when I'll get a fix out.

**Comment by JRascagneres** [comment]
> Even the chart on OE website is affected by this. Was coming here to ask for similar regarding some kind of caching Has the API format changed or confused something following month change? Rates are available on the usual endpoint

Yeah its a mess, the API response is a bit broken. There is duplicate data for the same day, I think thats the issue. Today (and yesterdays) data IS available but because todays is duplicated its pushed it to page=2. 

@BottlecapDave Could a quick fix be to use a future page if data is missing? I dunno.

**Comment by JRascagneres** [comment]
I'm struggling to read the code a little on GitHub but I think if the code is changed to iterate here - https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/8296fce0ab7b156e0be5bcb6131bf6f171177be0/custom_components/octopus_energy/api_client.py#L921

Using the "next" response then the issue will be resolved, or at least alleviated.

**Comment by BottlecapDave** [comment]
Closing as the paged data is taken into consideration for rates.
