### ISSUE TITLE
No data for entities

### ISSUE THREAD

**Issue by retr083** [BottlecapDave/HomeAssistant-OctopusEnergy#342]
### Describe the bug

No data showing in entity comes up as unknown.

### Reproduction steps

Reload intergration

### Expected behaviour

Rates should update

### Tariff Code

E-1R-AGILE-FLEX-22-11-25-E

### Integration Version

7.5.2

### Home Assistant Version

2023.7.3

### Fresh Install?

Not specified

### Home Assistant Logs

This error originated from a custom integration.

Logger: custom_components.octopus_energy.coordinators.electricity_rates
Source: helpers/debounce.py:67
Integration: Octopus Energy (documentation, issues)
First occurred: August 1, 2023 at 16:43:47 (54 occurrences)
Last logged: 13:25:41

Debouncer call ignored as shutdown has been requested.

**Comment by BottlecapDave** [comment]
Hi there. Sorry that you're having issues. Which entities are not showing data? Has this worked previously? There was issues with the agile tariff over the past couple of days due to an issue with OE (see https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/discussions/337 and https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/336)

**Comment by retr083** [comment]
> Hi there. Sorry that you're having issues. Which entities are not showing data? Has this worked previously? There was issues with the agile tariff over the past couple of days due to an issue with OE (see https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/discussions/337 and https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/336)

I think that is what the issue is, it was working fine and then stopped a few days ago. It's the Current, Next and Previous rates for both import and export that are affected.

**Comment by GTunney** [comment]
I’m am also getting errors for debouncer and my next day rates for tracker aren’t updating.

**Comment by BottlecapDave** [comment]
Can anyone confirm if this is still occuring with the latest update?
