### ISSUE TITLE
Intelligent Octopus Rates not updating

### ISSUE THREAD

**Issue by JAD92** [BottlecapDave/HomeAssistant-OctopusEnergy#344]
### Describe the bug

My current rate sensor for my electricity meter is not updating with the Intelligent Octopus Slot times, it remains 0.3024714 GBP/kWh at all times. 

I can see the attributes of that sensor reflect the 0.075 GBP/kWh rate overnight, but the sensor itself doesn't update. 

### Reproduction steps

Have installed this add-on through HACS and refreshed a couple times. I've installed older versions and then returned to this version with no change. 

### Expected behaviour

Between 2330 and 0530, the sensor will show the reduced tariff. For other 30 minute slots that the car is scheduled to charge, this sensor will reduce also. 

### Tariff Code

 E-1R-INTELLI-VAR-22-10-14-L

### Integration Version

7.5.2

### Home Assistant Version

2023.7.3

### Fresh Install?

Not specified

### Home Assistant Logs

This error originated from a custom integration.

Logger: custom_components.octopus_energy.coordinators.intelligent_dispatches
Source: helpers/debounce.py:67
Integration: Octopus Energy (documentation, issues)
First occurred: 21:41:40 (4 occurrences)
Last logged: 21:41:46

Debouncer call ignored as shutdown has been requested.

**Comment by BottlecapDave** [comment]
Hi there and sorry you're having issues.

I've had a few reports of this, but failing to recreate it locally and never seen the debounce issue on my local instance. I'm not sure why as its done in the state field of the sensor, which should be called frequently by HA.

**Comment by JAD92** [comment]
Hi, thanks for the reply. Is there anything I can provide that will assist with identifying the issue? A larger log or similar?

This add-on is great and has been rock solid up until I spotted the  price sensor issue when reviewing my energy dashboard one morning.  I figure as it was a cloud based add-on, perhaps there was a cloud issue, but it has persisted. 

For reference, I've got 5 devices showing under this integration/add-on. 

Charger
Electricity Meter (for import)
Electricity Meter (for export)
Gas Meter (disabled as was my previous flexible tariff)
Gas Meter (for my tracker tariff)

I was surprised when I refreshed the devices for an additional gas meter to appear with the new tariff, but figured this was likely due to how Octopus have my account setup within their API?

I'll remove the integration and add back in, rather than my usual downgrade/upgrade and see if it changes anything.

**Comment by JAD92** [comment]
v8 installed and have just spotted the next rate is displaying the expected 0.075 GBP/kWh. I'll keep an eye on it for a couple days - thanks for the continued support/developments.

**Comment by Seaniau** [comment]
It seems I too was having this problem, but having just switched from Flexible to Go and the process wasn't smooth, I wasn't sure if this was an Octopus API issue.

Rates updated immediately after upgrading to v8.

**Comment by JAD92** [comment]
Resolved as of V8, reflected in my live home assistant, and another user. 

Many thanks.
