### ISSUE TITLE
Duplicate Gas Meter started showing today !!

### ISSUE THREAD

**Issue by thorrrr** [BottlecapDave/HomeAssistant-OctopusEnergy#346]
### Describe the bug

I have only 1 gas and 1 electric meter but today i notice and extra duplicate gas show up!
I have not touched it for months so no idea why please can you inform me how to correct it.

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/8170673/21475746-fa8d-4d3f-9b89-517e7ca27636)

### Reproduction steps

Open App

### Expected behaviour

show only 1 of each 

### Tariff Code

0.3109617 GBP/kWh   0.0642 GBP/kWh

### Integration Version

7.5.2

### Home Assistant Version

2023.8

### Fresh Install?

Not specified

### Home Assistant Logs

tried download diagnostics says nothing listed on site

PS I am getting a Octopus Mini today do i just check the box or do i have to do a fresh install?
I have installed it and it running i selected i have Mini in the config but after 20 min still no data or entities showing!

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/8170673/3c8fb7fa-334f-46af-9219-8aa338db54ad)

Its showing 24 old entities  with several disabled 
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/8170673/be52f3e0-d3e5-4dd6-af4d-9eb33ccb4d3e)

**Comment by thorrrr** [comment]
From my HA logs see image below i followed the docs from [HERE](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/energy_dashboard.md)
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/8170673/40fa0ef2-459a-4ab5-afaa-bc1d22f8a3e7)

**Comment by BottlecapDave** [comment]
Hi there. The duplicate gas meter has been reported before and is the subject of an error in the identifers. This will be automatically removed in an upcoming release.

**Comment by BottlecapDave** [comment]
This additional meter should now be removed in the latest release https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v8.0.0
