### ISSUE TITLE
Agile 30 min slots current rate

### ISSUE THREAD

**Issue by holdmybeer1** [BottlecapDave/HomeAssistant-OctopusEnergy#351]
### Describe the bug

I’m about to update to the latest release and looked at the notes. Are you still getting a current rate sensor in 30 min slots in the new version for agile? I use this a lot in automations and notifications and it looked like it was being dropped in the new release. 

### Reproduction steps

.

### Expected behaviour

.

### Tariff Code

Agile

### Integration Version

Latest update - not tried as don’t want to disable my other automations

### Home Assistant Version

.

### Fresh Install?

After upgrading

### Home Assistant Logs

.

**Comment by BottlecapDave** [comment]
Hello. The previous/next rates now represents the period of time where the rate differs from the current rate (and specifies when that rate is applicable from/to). This was to make it more useful for other tariffs that change, but not as frequently. 

In Agile tariffs case, this should act largely the same, however in the rare circumstance where a rate is available for multiple 30 minute slots in a row, the next/previous rate could represent longer than 30 minutes.

**Comment by holdmybeer1** [comment]
Thanks!Sent from my iPhoneOn 5 Aug 2023, at 13:14, David Kendall ***@***.***> wrote:﻿
Hello. The previous/next rates now represents the period of time where the rate differs from the current rate (and specifies when that rate is applicable from/to). This was to make it more useful for other tariffs that change, but not as frequently.
In Agile tariffs case, this should act largely the same, however in the rare circumstance where a rate is available for multiple 30 minute slots in a row, the next/previous rate could represent longer than 30 minutes.

**Comment by JRascagneres** [comment]
@BottlecapDave This doesn't seem great for Agile... Is there a work-around to truly obtain the next rate? I frequently have scenarios where the next rate is equal to the current rate. If it shows the rate in an hours time it's going to be really confusing.

**Comment by BottlecapDave** [comment]
As mentioned for agile, it will largely be the same behaviour (yesterday and today in west midlands only had a single hour block where the rates were the same - https://agileprices.co.uk/). This needed to change to accomdate other tariffs and having different rules for different tariffs for the same sensor leads to complicated logic and is confusing for the end user when trying to work out behaviour (and that behaviour changing when switching tariffs). The sensor is called "next_rate" and so imo it better reflects what the next rate is. If the rate doesn't change, imo that's not the next rate that's just the current rate for a little longer. These sensors can now also better reflect how long these rates are available for, which people have used to display to family members.

If you're wanting to replicate the old behaviour, then you can use a template sensor representing your version of next rate. This can be setup with the current logic

```
{% set current_end = state_attr('sensor.octopus_energy_electricity_xxx_xxx_current_rate', 'valid_to') %}
{% set minutes_remaining =  (current_end - now()).seconds // 60 %}
{% if minutes_remaining > 30 %}
{{ states('sensor.octopus_energy_electricity_xxx_xxx_current_rate') }}
{% else %}
{{ states('sensor.octopus_energy_electricity_xxx_xxx_next_rate') }}
{% endif %}
```
