### ISSUE TITLE
Target rate showing unexpected results

### ISSUE THREAD

**Issue by shiteandstuffandcrap** [BottlecapDave/HomeAssistant-OctopusEnergy#359]
### Describe the bug

I have just set up a target rate sensor set up looking for 30 minute blocks that I eventually hope to use for charging. This morning's (approx) rates :

1:30 13p
2:00 11p
2:30 11p
3:00 12p
3:30 13p
4:30 14p

I expected the target rate sensor to trigger from 2:00 to 3:30 but the log shows 2:00 - 3:00 and then 3:30 - 4:00. 3:30 - 4:00 was more expensive than 3:00 - 3:30

<img width="430" alt="t-log" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/13948095/c60207aa-e51e-4907-a671-3de7a79091da">

### Reproduction steps

Awaiting next cheap slots to confirm

### Expected behaviour

Target sensor should not target higher rates over lower rates

### Integration Version

8.0.0

### Home Assistant Version

2023.8.1

### Fresh Install?

Fresh install

### Home Assistant Logs

None

**Comment by shiteandstuffandcrap** [comment]
ps, sorry about my stupid user name, your integration *rocks* 👌

**Comment by BottlecapDave** [comment]
Hi and sorry that you're having issues. Can you post your tariff and the full configuration for the target rate sensor please.

**Comment by shiteandstuffandcrap** [comment]
Here are the relevant rates if it helps

- valid_from: '2023-08-08T01:00:00+00:00'
  valid_to: '2023-08-08T01:30:00+00:00'
  value_inc_vat: 10.941
  is_capped: false
  is_intelligent_adjusted: false
- valid_from: '2023-08-08T01:30:00+00:00'
  valid_to: '2023-08-08T02:00:00+00:00'
  value_inc_vat: 10.038
  is_capped: false
  is_intelligent_adjusted: false
- valid_from: '2023-08-08T02:00:00+00:00'
  valid_to: '2023-08-08T02:30:00+00:00'
  value_inc_vat: 11.991
  is_capped: false
  is_intelligent_adjusted: false
- valid_from: '2023-08-08T02:30:00+00:00'
  valid_to: '2023-08-08T03:00:00+00:00'
  value_inc_vat: 12.348
  is_capped: false
  is_intelligent_adjusted: false
- valid_from: '2023-08-08T03:00:00+00:00'
  valid_to: '2023-08-08T03:30:00+00:00'
  value_inc_vat: 13.0725

**Comment by BottlecapDave** [comment]
Ok it might be because you have "re-evaluate" checked, as this will always shift the start time to now and so will come on for more than the desired time. This checkbox was more for legacy reasons, but can be useful in some scenarios. 

For charging, what other people do is not have this checked and set the hours to the full number of hours they need per day for a full charge. Some even take advantage of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy#service-octopus_energyupdate_target_config to change the hours dynamically on a daily basis (e.g. if their batteries are 50% set the hours to 2, if they're 75% set the hours to 1)

**Comment by shiteandstuffandcrap** [comment]
I wondered if 're-evaluate' might throw things, I've now disabled it so let's see :)

As for charging, there's so much I need to learn! I asked about adding Agile to an existing auto charging integration (jevburchell/Solis-Modbus-Auto-Charging-using-Solax) as Solcast forms part of my calculations but got a 'Nope' as a reply. I've managed to build an automation to turn on/off charging on my Solis so will have a read through your link above to see if my small brain can make sense of it, thanks Dave

**Comment by shiteandstuffandcrap** [comment]
Happy to confirm that with 're-evaluate' turned off the target sensor returned correct results for the next 24 hours, thanks for your help Dave
