### ISSUE TITLE
Unit of sensor / state class

### ISSUE THREAD

**Issue by rodgers86** [BottlecapDave/HomeAssistant-OctopusEnergy#364]
### Describe the bug

In my logs for four of the octopus sensors I’m continuously getting these errors as pasted in logger section below

In the developer-statistics I pressed fix issue, and get this message 

`The state class of this entity, is not supported. 
Statistics cannot be generated until this entity has a supported state class.

If this state class was provided by an integration, this is a bug. Please report an issue. `

Anybody had these issues and know how to correct?

### Reproduction steps

Errors appear in logs every restart. 

### Expected behaviour

No errors. Not sure why this is happening on these four sensors. 

### Integration Version

8.0.0

### Home Assistant Version

2023.8.1

### Fresh Install?

Not specified

### Home Assistant Logs

`Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:405 
Integration: Sensor (documentation, issues) 
First occurred: 10:30:10 (4 occurrences) 
Last logged: 10:45:10

The unit of sensor.octopus_energy_electricity_20l3146037_1030008919860_current_rate (None) cannot be converted to the unit of previously compiled statistics (GBP/kWh). Generation of long term statistics will be suppressed unless the unit changes back to GBP/kWh or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
The unit of sensor.octopus_energy_electricity_20l3146037_1050002186872_export_current_rate (None) cannot be converted to the unit of previously compiled statistics (GBP/kWh). Generation of long term statistics will be suppressed unless the unit changes back to GBP/kWh or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
The unit of sensor.octopus_energy_gas_e6s10578782261_7511962006_current_rate (None) cannot be converted to the unit of previously compiled statistics (GBP/kWh). Generation of long term statistics will be suppressed unless the unit changes back to GBP/kWh or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
Entity sensor.al7001020100041_solar_to_load from integration alphaess has state class total_increasing, but its state is not strictly increasing. Triggered by state 1.02 (1.12) with last_updated set to 2023-08-10T09:41:35.333578+00:00. Please report it to the custom integration author.
`

**Comment by BottlecapDave** [comment]
Hello and sorry you're seeing issues in the logs. While I can't help with the forth sensor (alphaess ;)), I believe the others are as intended because the rates are not available. This occurs mainly on tracker tariffs because the data is made available so late in the day and so it can't be worked out. 

If I preserve the previous value then this could cause people to complain that the data is not correct, where as I want it to be clear that the data is unavailable. All this means is that stats on the sensors has been paused and is why HA reports it as a warning rather than an error. I consider warnings to be something to raise your attention to, but not necessarily an error/issue.

**Comment by capandcamera** [comment]
I get the same Warning in my log:

```The unit of sensor.octopus_energy_gas_e6e03301062121_536366105_current_rate (None) cannot be converted to the unit of previously compiled statistics (GBP/kWh). Generation of long term statistics will be suppressed unless the unit changes back to GBP/kWh or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this```

Is there a way to suppress this Warning only on boot? - I completely understand and agree with getting the warning if the issue occurs during usage but this error appears every time I restart home assistant

**Comment by BottlecapDave** [comment]
@capandcamera The only way to supress the warning to my knowledge would be to decrease your overall logs (e.g. to `error`) or decrease the logs for `homeassistant.components.sensor.recorder` [to not include warnings](https://www.home-assistant.io/integrations/logger/)
