### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by MJP-76** [BottlecapDave/HomeAssistant-OctopusEnergy#366]
Hi There

Thanks for the great integration

I don't actually have two meters as such but have one account for electricity and one account for my solar FIT that has been added since Octopus took over the bulb 

I would like to be able to see the details from the second account also in HA as with my electricity reading

This a completely second account on their system under my login

I would like to be able to see it as a separate set of entities and not an actual meter, I assume as its FIT it will only have meter readings for previous, current, and an amount paid/earned etc

As I have just been moved from bulb to octopus for my fit I don't have anything in the account yet to even see but could try and pull the data if needed

Does that make sense?

**Comment by BottlecapDave** [comment]
I'm afraid this is not supported, and quite low on my list as the integration would require quite the significant re-write. There is already an [open issue for this](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/223).

I'll therefore close this issue and if you could upvote the linked issue it will help me gauge how many people require the feature.
