### ISSUE TITLE
Sensor to output the highest rate of the day/next day

### ISSUE THREAD

**Issue by jepminer** [BottlecapDave/HomeAssistant-OctopusEnergy#378]
**Describe the feature**

Two new sensors that output the highest price of the day and the highest price of tomorrow

**Expected behavior**

a sensor that updates at 4pm when the new prices come in and outputs the highest price of the respective day, useful for node-red flows.

**Comment by BottlecapDave** [comment]
Hi and thanks for using the integration :)

With the vast number of sensors already available in the integration, I'm trying to be more selective around new ones. I usually introduce new ones if they can't easily be covered via the existing data using other features of HA or perform some sort of action (e.g. intelligent sensors). 

To gain the highest price for the current day, this is available as an attribute on the [current rate sensor](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/sensors/electricity.md#current-rate). This can be exposed as a sensor using [template sensors](https://www.home-assistant.io/integrations/template/) using the following syntax

```
{{ state_attr('sensor.octopus_energy_electricity_xxx_xxx_current_rate', 'current_day_max_rate') }}
```

To gain the highest price for the following day, we can utilise the `all_rates` attribute of the current rate sensor. This attribute always aims to have the previous days rates, the current days rates and the next days rates as this data is used by other sensors. This is a little more complicated, but can be achieved with the following syntax

```
{% set max = namespace(value=0) %}
{% for item in state_attr('sensor.octopus_energy_electricity_xxx_xxx_current_rate', 'all_rates') %}
  {% if loop.index >= 96 and loop.index < 144 and max.value < item["value_inc_vat"] %}
    {% set max.value = item["value_inc_vat"] %}
  {% endif %}
{%- endfor %}

{{ max.value }}
```

We start at index 96 as that is the index for the next days worth of rates. There might be a better way of filtering the rates down, but this only requires a single loop of the data.

Therefore, at the current time I will not be adding the requested sensors as they can be achieved as above.
