### ISSUE TITLE
Query Over Rates

### ISSUE THREAD

**Issue by BlueMoon23** [BottlecapDave/HomeAssistant-OctopusEnergy#38]
Hi,

Thanks for working on this, I installed it using HACS and have got each of the entities, but have a query.

When I put the two electricity entities into HA's Developer page I get the figures for the Octopus Outgoing Rate (i.e. the cost of what I export to the grid), not the incoming rate (i.e. the cost I am charged). 

For example sensor.octopus_energy_electricity_current_rate is giving me 0.1851, when I check my Octopus account, that is the outgoing rate, the import tariff should be 0.3500 at this time (6 Feb 1600-1630).

Am I doing something wrong, or do I have to do anything else to get the correct rates?

**Comment by BottlecapDave** [comment]
This should now be resolved in the latest update. Please check the changelog before you install as there's some breaking changes.

**Comment by BlueMoon23** [comment]
Hi, Thanks for updating. I have looked at the entities and they look to be working for me.

**Comment by BottlecapDave** [comment]
Glad to hear it's working for you.
