### ISSUE TITLE
Accumulated electricity data missing from midnight to 1am

### ISSUE THREAD

**Issue by matt05d** [BottlecapDave/HomeAssistant-OctopusEnergy#382]
### Describe the bug

Accumulated electricity data is in the octopus app between 12-1am but in the home assistant sensors, it sends a last reading at midnight and then a new value at 1am. Home assistant energy dashboard therefore doesn't report any usage for 12-1 and since the 1am seems to be considered the new 0 value, it actually misses energy. Usually this is a negligible amount so I only noticed when I charged the car. 

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/96061510/dc56b1e3-ddfd-4844-95de-ea085e2c1375)
![image](https://github.com/B
![Screenshot_20230818_082349_Octopus](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/96061510/9416bd05-8efb-478f-9986-b83502adfb41)
ottlecapDave/HomeAssistant-OctopusEnergy/assets/96061510/a2af454a-28b5-4f51-9787-fdd92488b5d4)
![Screenshot_20230818_082355_Octopus](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/96061510/5e09cc63-4554-4bb8-95f5-1220e800b4d1)

### Reproduction steps

See accumulated energy graphs in electricity sensor.
See home assistant energy dashboard graphs

### Expected behaviour

Resetted value is 0 at midnight so all data is captured

### Integration Version

8.1.0 and also seen in 8.0.0 before upgrading

### Home Assistant Version

2023.8.1

### Fresh Install?

Not specified

### Home Assistant Logs

na

**Comment by BottlecapDave** [comment]
Hi there and sorry that you're seeing this issue. I believe I've found the issue, which was related due to a check in place required for previous consumption data where it needs at least 1 hours worth of data before the dataset is counted as valid.

I'm just checking that this is indeed the fix, and all going well, will hopefully be out by the weekend.

**Comment by BottlecapDave** [comment]
This should now be fixed in the latest release - https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v8.2.0

**Comment by matt05d** [comment]
Thank you so much for the quick fix Sent from my Galaxy
-------- Original message --------From: David Kendall ***@***.***> Date: 26/08/2023  10:50  (GMT+00:00) To: BottlecapDave/HomeAssistant-OctopusEnergy ***@***.***> Cc: matt05d ***@***.***>, Author ***@***.***> Subject: Re: [BottlecapDave/HomeAssistant-OctopusEnergy] Accumulated electricity data missing from midnight to 1am (Issue #382) 
This should now be fixed in the latest release - https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v8.2.0
