### ISSUE TITLE
Got Electricity data but not Gas

### ISSUE THREAD

**Issue by trullock** [BottlecapDave/HomeAssistant-OctopusEnergy#39]
**Describe the bug**
No data for Gas sensors:
```
previous_accumulative_consumption
previous_accumulative_consumption_cost
previous_accumulative_cost
```

These sensors have attributes relating to my meter (e.g. serial number, MPRN etc) but always have a 0 value

`gas_current_rate` does have a value

**To Reproduce**
Installed and connected to my account.
I have electricity details.
The Octopus API does return data when querying my gas metere

**Expected behavior**
Gas data be present?

**Home Assistant Logs**
Nothing I can see, tell me how to be useful and I'll provide

**Comment by BottlecapDave** [comment]
Hi there, sorry for the late response - Work life is busy at the moment.

Sorry to hear you're having issues with the integration. Did you say there was nothing in your logs to indicate an issue (they would be associated with the integration)? Do you have more than one gas sensor available?

**Comment by BottlecapDave** [comment]
From the home screen of your Home Assistant instance, if you go menu -> Configuration -> Settings -> Log you will get any logs raised by various home assistant integrations. Each entry should say which integration raised the log, and you're looking for any raised by "Octopus Energy (custom integration)"

**Comment by trullock** [comment]
Yeah, nothing in there octopus related :/

**Comment by robjones84** [comment]
Appear to have the same issue.

Checking the integration, its not creating any sensors for the Gas (its a SMETS2 and reports to the API etc if i manually pull them)

<img width="1146" alt="Screenshot 2022-02-21 at 10 41 55" src="https://user-images.githubusercontent.com/38785048/154939371-1fb0a1d0-cd0f-4cf2-9050-c7c8599da20a.png">

**Comment by trullock** [comment]
I have the sensors but they're `0`

**Comment by BottlecapDave** [comment]
Interesting. After digging into why my sensors are zero, I noticed that the Octopus Energy dashboard (https://octopus.energy/dashboard) doesn't have any data past 10th February. I wasn't sure if this was the case for some of you? 
In my testing, it should be pulling data through correctly if it's available, but I will continue to investigate.

**Comment by trullock** [comment]
![image](https://user-images.githubusercontent.com/118878/155902539-0e3c6fdc-639b-4ff6-9dfe-77996f4bdecf.png)
Having changed nothing, I randomly got these blips of data

**Comment by BottlecapDave** [comment]
Is this still not working @trullock?

**Comment by trullock** [comment]
Nope, although it may be an issue with my Octopus account as the data is sketchy on their dashboard too.

Will call them tomorrow and report back

ta

**Comment by trullock** [comment]
I think this is my account. Will reopen if it persists

Apologies
