### ISSUE TITLE
Please can you add the Octopus Intelligent Target charge % and ready time to the Slot sensor

### ISSUE THREAD

**Issue by springfall2008** [BottlecapDave/HomeAssistant-OctopusEnergy#391]
**Describe the feature**

In the Octopus Intelligent Plugin the target charge % is shown as weekDayTargetSoc/ weekendTargetSoc and the planned ready time as weekdayTargetTime/weekendTargetTime.

Could you add this percentage and time please, I think everything else is replicated from the separate Intelligent plugin

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/48591903/d349511d-13fb-4286-a268-3a085ce0daf1)

**Expected behavior**

As above

**Comment by BottlecapDave** [comment]
Hello.

This is already available as part of the [charge limit](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/sensors/intelligent.md#charge-limit) (soc) and [ready time](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/sensors/intelligent.md#ready-time) (target time) sensors.

These have been combined into a single sensor as when discussing with the [developer of that integration](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/discussions/282#discussioncomment-6244917) they stated there is not way within the app to split the targets and it had undesired effects when switching between the integration and the app.

Therefore I will not be repeating the data as attributes within another sensor.

**Comment by springfall2008** [comment]
Thanks Dave, I can’t believe I was so dozy as to miss that!

**Comment by BottlecapDave** [comment]
It's no problem :)
