### ISSUE TITLE
From/To Times not showing up in Target Rate Configuration Wizard 

### ISSUE THREAD

**Issue by Geheee** [BottlecapDave/HomeAssistant-OctopusEnergy#392]
### Describe the bug

Since 8.2.0, it has not been possible to use the default from/to with an Agile tarriff.

My existing target rate sensors therefore have errors.

When I click "configure" to try and modify the to/from to the suggested 11:00/11:00, there is not an input box to do so.

When I create a new target rate, similarly the to/from fields do not appear in the wizard popup.

### Reproduction steps

 - Load 8.2.0 
 - Create new target rate sensor
- No to/from

![Capture](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/130564455/67b44304-093d-4ed4-bcf8-44b46f8a0aac)

### Expected behaviour

To/From field able to be modified/entered

### Tariff Code

G-1R-SILVER-FLEX-22-11-25-B

### Integration Version

8.2.0

### Home Assistant Version

Home Assistant 2023.8.4 Supervisor 2023.08.1 Operating System 10.5 Frontend 20230802.1 - latest

### Fresh Install?

After upgrading

### Home Assistant Logs

The target rate "discharge_time" has become invalid. Click on 'Learn More' with instructions on what to do next.

**Comment by BottlecapDave** [comment]
Hello. Sorry for the late repsonse but I've been away from my computer for a few days.

You can update the times currently, but the docs could do with some tweaking. You'll need to set the fields of `The minimum time to start the device` (`from` time) and `The maximum time to stop the device` (`to` time)

**Comment by Geheee** [comment]
Ah, ok

I thought they referred to some sort of ramp up/ ramp down time

makes sense

**Comment by BottlecapDave** [comment]
No problem. I've updated the docs to hopefully be clearer on the matter.
