### ISSUE TITLE
Unit of measurement for current price not compatible with Energy Dashboard

### ISSUE THREAD

**Issue by mdeakin99** [BottlecapDave/HomeAssistant-OctopusEnergy#4]
Added the 'current price' under 'Grid Consumption' in Energy Dashboard.  Following error displayed.

Unexpected unit of measurement
The following entities do not have the expected units of measurement 'GBP/kWh' or 'GBP/Wh':
sensor.octopus_energy_electricity_current_rate

**Comment by BottlecapDave** [comment]
This should be a quick fix. I'll take a look tonight

**Comment by BottlecapDave** [comment]
This should now be fixed
