### ISSUE TITLE
Next Rate not reporting correctly.

### ISSUE THREAD

**Issue by res2cpu** [BottlecapDave/HomeAssistant-OctopusEnergy#401]
### Describe the bug

I recently updated my Home assistant and the integration and the "Next Rate" entity is now reporting incorrectly, or at lease different from before.

I'm on octopus go with a reduced rate between 00:30-04:30.  The next rate used to report the rate fore the following 30 min as per the below:
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/46848903/cd40c5be-6cf9-467f-b4c0-858605fd2933)

After the update I'm getting the next price change, eg as soon as I hit cheap rate it reports the high rate which starts in 4 hours time and as soon as it hit's the high rate it reports the low rate commencing in 40 hours time:
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/46848903/4a286b34-8d9f-4c8b-b3a1-aa95b09b6e74)

### Reproduction steps

Same on my test install.

### Expected behaviour

Report the rate for the next 30min window.

### Tariff Code

 E-1R-GO-VAR-22-10-14-A

### Integration Version

v8.2.0

### Home Assistant Version

2023.9.1

### Fresh Install?

After upgrading

### Home Assistant Logs

No errors in the logs about Next_Rate

**Comment by BottlecapDave** [comment]
Hello. This was a breaking change introduced in [v8.0.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/CHANGELOG.md#800-2023-08-05), where the behaviour changed to be better equipped for tariffs over than agile. Therefore, it is as expected.

Full details, along with a recommendation of how to create a template sensor to replicate the previous behavior can be found in this [thread](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/351#issuecomment-1666744569). You can also consult the [docs](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/sensors/electricity.md#next-rate) for the new behaviour.

**Comment by res2cpu** [comment]
Gah, missed it when I skimmed the change logs.

Thank you for getting back to me and for your work on the integration.
