### ISSUE TITLE
Reliably determining peak/off-peak from current_rate entity

### ISSUE THREAD

**Issue by NickSutton** [BottlecapDave/HomeAssistant-OctopusEnergy#403]
### Describe the bug

Loving this integration! Thanks for all the hard work on it. I am looking for changes in the ‘…current_rate’ entity to determine peak / off peak status and trigger further automations based on its value.
This works OK but the integration can take anywhere between 5 and 20mins to update this entity which isn’t ideal. 

Can this be improved, or, is there a better way to identify peak/off-peak reliably?

### Reproduction steps

Trigger automation based on changes to the ‘sensor.octopus_energy_electricity_XXXXXX_XXXXXX_current_rate’ sensor and compare the times of when the automation was triggered versus the changes to the meters rate.

### Expected behaviour

Changes reflected within a few minutes or so, if possible?

### Integration Version

8.2.0

### Home Assistant Version

2023.9.1

### Fresh Install?

Not specified

### Home Assistant Logs

n/a

**Comment by BottlecapDave** [comment]
Hello and sorry you're having issues. The rate information is downloaded every 30 minutes and retrieves 3 days worth of data where available (yesterday, today and tomorrow). The current rate sensor is evaluated on the hour and half hour (as this is when rate information typically changes) or when the rate information fails to be calculated for over 30 minutes. 

I have not personally been seeing what you've been describing where the rate information is being delayed in being updated. If you could follow the [faq](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/faq.md#how-do-i-increase-the-logs-for-the-integration) to get some deeper logs (and paste the results here), it will help diagnose your issue. Also what tariff are you on?

**Comment by NickSutton** [comment]
Hey, thanks. That makes sense and explains the situation.. I was getting off-peak periods starting at ten-past the hour for a while but am largely getting on the hour and half-past the hour, I can live with it.

Cheers
