### ISSUE TITLE
Octopus intelligent slot reporting away charging as 'unknown' indicating low rate slots

### ISSUE THREAD

**Issue by springfall2008** [BottlecapDave/HomeAssistant-OctopusEnergy#409]
### Describe the bug

In the slot sensor if I charge my Tesla away from home it shows up as completed dispatches but it looks like they are low rate slots when they are not.

Comparing intelligent plugin:

<img width="579" alt="image" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/48591903/852c1ed9-1bce-4eb2-8de5-3a2b53e91159">

To Octopus plugin:

<img width="579" alt="image" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/48591903/0f723c8b-225c-43be-8507-ae1b9d3cd5db">

### Reproduction steps

Charge a Telsa on IO away from home

### Expected behaviour

Either ignore the away charging or report it in a way that means it's possible to know these are not IO slots.

### Integration Version

8.1.0

### Home Assistant Version

2023.8.1

### Fresh Install?

After upgrading

### Home Assistant Logs

n/a

**Comment by BottlecapDave** [comment]
I've added the location attribute to the slots where available. This can be found in [v8.3.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v8.3.0).
