### ISSUE TITLE
Cumulative Gas Cost Calculation

### ISSUE THREAD

**Issue by sslx123** [BottlecapDave/HomeAssistant-OctopusEnergy#41]
Firstly - thank you so much for developing this integration. Super clean and helpful! Much appreciated.

**Describe the bug**
I have just set up my integration. But I was not sure if the gas calculation was working. It shows previous day gas consumption of some 6.5m³ but previous day gas cost of £0.49. I suspect the calculation was taking the p/kWh (around 3.6p) multiplied directly to the  6.5m³ and added standing charge of some £0.25. But in reality, the gas cost is much higher in particular in winter... 

**To Reproduce**
Initiate the integration and read the gas cost against normal bill cycle

**Expected behavior**
When I was reading the bill, the energy calculation is much more complicated.
Your energy usage is calculated from your gas consumption using a standard industry formula:
Units Consumed (Cubic Metres) × Volume Correction (for temperature & pressure) × Calorific Value (energy in each m3 of gas) ÷ 3.6 (convert from joules) ≈ Usage (in kWh)
So the 6.547m³ need to be converted to some 72kWh (based on the numbers on my bill), then multiplied with the 3.6p, adding standing charge, getting to close to £3 per day, this sounds more like the case in winter... 

The solution that I have is to change the utils.py, make use of your conversion from kWh to m³ but do the opposite way. i.e. I took the m³ reading and multiply Volume Correction, Colorific Value and convert from joules (change the signs in the last bit), then tick the SMET1 box in the integration (so that the conversion kicks in). Let me know your thoughts.

**Home Assistant Logs**
N/A

**Comment by BottlecapDave** [comment]
Thanks for bringing this to my attention. I'll take a look soon.

**Comment by BottlecapDave** [comment]
I've just released a new update, which should have resolved this issue. If it's still not right, please let me know.

**Comment by Phil-m-pinto** [comment]
I have the same problem. Gas appears to be being measured in kWh and not cubic metres. This is causing the wrong price consumed to be showed. 
I'm on the latest release.  
I wonder sslx123, have you solve the problem.

**Comment by BottlecapDave** [comment]
Hi @Phil-m-pinto. 

If you look at the consumption sensor, you should receive the breakdown of how the data is calculated located within the attributes. You can see the recorded kwh and m3 values, along with these broken down on a half an hour basis. In your charges, are you seeing 48 separate charges?

The sensor takes the values from the API, which according to https://developer.octopus.energy/docs/api/#list-consumption-for-a-meter is returned in kwh for SMETS1 meters, and m3 for SMETS2 meters. Therefore, the sensor converts the value to kwh if it needs to before calculating the cost. Defining if you have an SMETS1 sensor is achieved when you set up your initial account as I can't get this information from the API.

However, even though I believe I have an SMETS1 meter (which should be giving me kwh values via the API), the values I recieve match the m3 values reported in the dashboard. I've reached out to Octopus in march for clarification, but have yet to receive a response, so would be interesting to know if you believe you're experiencing the same issue.

**Comment by Phil-m-pinto** [comment]
Hi [BottlecapDave](https://github.com/BottlecapDave)

This is what i see.
 
hope this helps

sensor.octopus_energy_gas_g4p03021661800_7634802007_previous_accumulative_consumption

state_class: total_increasing
mprn: 7634802007
serial_number: G4P03021661800
is_smets1_meter: false
total_kwh: 12.078
total_m3: 1.063
last_calculated_timestamp: 2022-05-02T23:00:00+00:00
charges: 
- from: '2022-05-01T23:00:00+00:00'
  to: '2022-05-01T23:30:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-01T23:30:00+00:00'
  to: '2022-05-02T00:00:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T00:00:00+00:00'
  to: '2022-05-02T00:30:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T00:30:00+00:00'
  to: '2022-05-02T01:00:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T01:00:00+00:00'
  to: '2022-05-02T01:30:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T01:30:00+00:00'
  to: '2022-05-02T02:00:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T02:00:00+00:00'
  to: '2022-05-02T02:30:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T02:30:00+00:00'
  to: '2022-05-02T03:00:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T03:00:00+00:00'
  to: '2022-05-02T03:30:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T03:30:00+00:00'
  to: '2022-05-02T04:00:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T04:00:00+00:00'
  to: '2022-05-02T04:30:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T04:30:00+00:00'
  to: '2022-05-02T05:00:00+00:00'
  consumption_m3: 0.346
  consumption_kwh: 3.931
- from: '2022-05-02T05:00:00+00:00'
  to: '2022-05-02T05:30:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T05:30:00+00:00'
  to: '2022-05-02T06:00:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T06:00:00+00:00'
  to: '2022-05-02T06:30:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T06:30:00+00:00'
  to: '2022-05-02T07:00:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T07:00:00+00:00'
  to: '2022-05-02T07:30:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T07:30:00+00:00'
  to: '2022-05-02T08:00:00+00:00'
  consumption_m3: 0.053
  consumption_kwh: 0.602
- from: '2022-05-02T08:00:00+00:00'
  to: '2022-05-02T08:30:00+00:00'
  consumption_m3: 0.015
  consumption_kwh: 0.17
- from: '2022-05-02T08:30:00+00:00'
  to: '2022-05-02T09:00:00+00:00'
  consumption_m3: 0.063
  consumption_kwh: 0.716
- from: '2022-05-02T09:00:00+00:00'
  to: '2022-05-02T09:30:00+00:00'
  consumption_m3: 0.046
  consumption_kwh: 0.523
- from: '2022-05-02T09:30:00+00:00'
  to: '2022-05-02T10:00:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T10:00:00+00:00'
  to: '2022-05-02T10:30:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T10:30:00+00:00'
  to: '2022-05-02T11:00:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T11:00:00+00:00'
  to: '2022-05-02T11:30:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T11:30:00+00:00'
  to: '2022-05-02T12:00:00+00:00'
  consumption_m3: 0.011
  consumption_kwh: 0.125
- from: '2022-05-02T12:00:00+00:00'
  to: '2022-05-02T12:30:00+00:00'
  consumption_m3: 0.023
  consumption_kwh: 0.261
- from: '2022-05-02T12:30:00+00:00'
  to: '2022-05-02T13:00:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T13:00:00+00:00'
  to: '2022-05-02T13:30:00+00:00'
  consumption_m3: 0.006
  consumption_kwh: 0.068
- from: '2022-05-02T13:30:00+00:00'
  to: '2022-05-02T14:00:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T14:00:00+00:00'
  to: '2022-05-02T14:30:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T14:30:00+00:00'
  to: '2022-05-02T15:00:00+00:00'
  consumption_m3: 0.01
  consumption_kwh: 0.114
- from: '2022-05-02T15:00:00+00:00'
  to: '2022-05-02T15:30:00+00:00'
  consumption_m3: 0.031
  consumption_kwh: 0.352
- from: '2022-05-02T15:30:00+00:00'
  to: '2022-05-02T16:00:00+00:00'
  consumption_m3: 0.011
  consumption_kwh: 0.125
- from: '2022-05-02T16:00:00+00:00'
  to: '2022-05-02T16:30:00+00:00'
  consumption_m3: 0.067
  consumption_kwh: 0.761
- from: '2022-05-02T16:30:00+00:00'
  to: '2022-05-02T17:00:00+00:00'
  consumption_m3: 0.043
  consumption_kwh: 0.489
- from: '2022-05-02T17:00:00+00:00'
  to: '2022-05-02T17:30:00+00:00'
  consumption_m3: 0.016
  consumption_kwh: 0.182
- from: '2022-05-02T17:30:00+00:00'
  to: '2022-05-02T18:00:00+00:00'
  consumption_m3: 0.029
  consumption_kwh: 0.33
- from: '2022-05-02T18:00:00+00:00'
  to: '2022-05-02T18:30:00+00:00'
  consumption_m3: 0.008
  consumption_kwh: 0.091
- from: '2022-05-02T18:30:00+00:00'
  to: '2022-05-02T19:00:00+00:00'
  consumption_m3: 0.285
  consumption_kwh: 3.238
- from: '2022-05-02T19:00:00+00:00'
  to: '2022-05-02T19:30:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T19:30:00+00:00'
  to: '2022-05-02T20:00:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T20:00:00+00:00'
  to: '2022-05-02T20:30:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T20:30:00+00:00'
  to: '2022-05-02T21:00:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T21:00:00+00:00'
  to: '2022-05-02T21:30:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T21:30:00+00:00'
  to: '2022-05-02T22:00:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T22:00:00+00:00'
  to: '2022-05-02T22:30:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0
- from: '2022-05-02T22:30:00+00:00'
  to: '2022-05-02T23:00:00+00:00'
  consumption_m3: 0
  consumption_kwh: 0

unit_of_measurement: m³
device_class: gas
icon: mdi:fire
friendly_name: Gas previous accumulative consumption

AND

sensor.octopus_energy_gas_g4p03021661800_7634802007_previous_accumulative_cost

state_class: total_increasing
mprn: 7634802007
serial_number: G4P03021661800
tariff_code: G-1R-PRC-PROM-21-07-12-H
is_smets1_meter: false
standing_charge: 26.5335p
total_without_standing_charge: £0.88
total: £1.15
last_calculated_timestamp: 2022-05-02T23:00:00+00:00
charges: 
- from: '2022-05-01T23:00:00+00:00'
  to: '2022-05-01T23:30:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-01T23:30:00+00:00'
  to: '2022-05-02T00:00:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T00:00:00+00:00'
  to: '2022-05-02T00:30:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T00:30:00+00:00'
  to: '2022-05-02T01:00:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T01:00:00+00:00'
  to: '2022-05-02T01:30:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T01:30:00+00:00'
  to: '2022-05-02T02:00:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T02:00:00+00:00'
  to: '2022-05-02T02:30:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T02:30:00+00:00'
  to: '2022-05-02T03:00:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T03:00:00+00:00'
  to: '2022-05-02T03:30:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T03:30:00+00:00'
  to: '2022-05-02T04:00:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T04:00:00+00:00'
  to: '2022-05-02T04:30:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T04:30:00+00:00'
  to: '2022-05-02T05:00:00+00:00'
  rate: 7.287p
  consumption: 3.931 kWh
  cost: £0.29
- from: '2022-05-02T05:00:00+00:00'
  to: '2022-05-02T05:30:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T05:30:00+00:00'
  to: '2022-05-02T06:00:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T06:00:00+00:00'
  to: '2022-05-02T06:30:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T06:30:00+00:00'
  to: '2022-05-02T07:00:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T07:00:00+00:00'
  to: '2022-05-02T07:30:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T07:30:00+00:00'
  to: '2022-05-02T08:00:00+00:00'
  rate: 7.287p
  consumption: 0.602 kWh
  cost: £0.04
- from: '2022-05-02T08:00:00+00:00'
  to: '2022-05-02T08:30:00+00:00'
  rate: 7.287p
  consumption: 0.17 kWh
  cost: £0.01
- from: '2022-05-02T08:30:00+00:00'
  to: '2022-05-02T09:00:00+00:00'
  rate: 7.287p
  consumption: 0.716 kWh
  cost: £0.05
- from: '2022-05-02T09:00:00+00:00'
  to: '2022-05-02T09:30:00+00:00'
  rate: 7.287p
  consumption: 0.523 kWh
  cost: £0.04
- from: '2022-05-02T09:30:00+00:00'
  to: '2022-05-02T10:00:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T10:00:00+00:00'
  to: '2022-05-02T10:30:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T10:30:00+00:00'
  to: '2022-05-02T11:00:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T11:00:00+00:00'
  to: '2022-05-02T11:30:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T11:30:00+00:00'
  to: '2022-05-02T12:00:00+00:00'
  rate: 7.287p
  consumption: 0.125 kWh
  cost: £0.01
- from: '2022-05-02T12:00:00+00:00'
  to: '2022-05-02T12:30:00+00:00'
  rate: 7.287p
  consumption: 0.261 kWh
  cost: £0.02
- from: '2022-05-02T12:30:00+00:00'
  to: '2022-05-02T13:00:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T13:00:00+00:00'
  to: '2022-05-02T13:30:00+00:00'
  rate: 7.287p
  consumption: 0.068 kWh
  cost: £0.0
- from: '2022-05-02T13:30:00+00:00'
  to: '2022-05-02T14:00:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T14:00:00+00:00'
  to: '2022-05-02T14:30:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T14:30:00+00:00'
  to: '2022-05-02T15:00:00+00:00'
  rate: 7.287p
  consumption: 0.114 kWh
  cost: £0.01
- from: '2022-05-02T15:00:00+00:00'
  to: '2022-05-02T15:30:00+00:00'
  rate: 7.287p
  consumption: 0.352 kWh
  cost: £0.03
- from: '2022-05-02T15:30:00+00:00'
  to: '2022-05-02T16:00:00+00:00'
  rate: 7.287p
  consumption: 0.125 kWh
  cost: £0.01
- from: '2022-05-02T16:00:00+00:00'
  to: '2022-05-02T16:30:00+00:00'
  rate: 7.287p
  consumption: 0.761 kWh
  cost: £0.06
- from: '2022-05-02T16:30:00+00:00'
  to: '2022-05-02T17:00:00+00:00'
  rate: 7.287p
  consumption: 0.489 kWh
  cost: £0.04
- from: '2022-05-02T17:00:00+00:00'
  to: '2022-05-02T17:30:00+00:00'
  rate: 7.287p
  consumption: 0.182 kWh
  cost: £0.01
- from: '2022-05-02T17:30:00+00:00'
  to: '2022-05-02T18:00:00+00:00'
  rate: 7.287p
  consumption: 0.33 kWh
  cost: £0.02
- from: '2022-05-02T18:00:00+00:00'
  to: '2022-05-02T18:30:00+00:00'
  rate: 7.287p
  consumption: 0.091 kWh
  cost: £0.01
- from: '2022-05-02T18:30:00+00:00'
  to: '2022-05-02T19:00:00+00:00'
  rate: 7.287p
  consumption: 3.238 kWh
  cost: £0.24
- from: '2022-05-02T19:00:00+00:00'
  to: '2022-05-02T19:30:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T19:30:00+00:00'
  to: '2022-05-02T20:00:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T20:00:00+00:00'
  to: '2022-05-02T20:30:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T20:30:00+00:00'
  to: '2022-05-02T21:00:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T21:00:00+00:00'
  to: '2022-05-02T21:30:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T21:30:00+00:00'
  to: '2022-05-02T22:00:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T22:00:00+00:00'
  to: '2022-05-02T22:30:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0
- from: '2022-05-02T22:30:00+00:00'
  to: '2022-05-02T23:00:00+00:00'
  rate: 7.287p
  consumption: 0.0 kWh
  cost: £0.0

unit_of_measurement: GBP
device_class: monetary
icon: mdi:currency-gbp
friendly_name: Gas previous accumulative cost

**Comment by BottlecapDave** [comment]
Thanks for that @Phil-m-pinto. For the period of data you provided (2nd May 2022), what does the octopus energy dashboard state your consumption should be? 12.078 m3, 1.063 m3 or something else? If you toggle your account to be an SMETS1 meter, do you get the values you expect?

Also, side note, you may want to edit your response to not include your sn and mprn numbers (they're not needed)

**Comment by Phil-m-pinto** [comment]
For that. As I believe home assistant is a day out. So looking at the 3rd of may the usage tallies up ok at 1.3 m3. It's just home assistant says it only cost me 10p however, by my calculations it should have cost around £1.28 including the daily charge. Please see a touch screenshots. By the way, I configured both for SMETS1 & 2 and it made no difference. 
![Screenshot_20220506-131258](https://user-images.githubusercontent.com/77551127/167131607-57a9c708-3923-4630-93fe-036c4d885cf5.png)
![Screenshot_20220506-131226](https://user-images.githubusercontent.com/77551127/167131614-3a8453f0-094f-4c94-af79-5fb2fdf02ef7.png)

**Comment by BottlecapDave** [comment]
Based on your screenshots and the data you provided previously, I believe you may have configured the wrong price sensor on the dashboard. The gas sensor is returned as m3 (this is what Octopus Energy provide), but the pricing is done in kWh (gotta love those inconsistencies), so the dashboard might be combining these two values incorrectly.

If you go to `config/energy` within your Home Assistant instance, you should use the sensor in the form of `sensor.octopus_energy_gas_{{METER_SERIAL_NUMBER}}_{{MPRN_NUMBER}}_previous_accumulative_cost` with the option of "Use an entity tracking the total costs". This should result in you having the correct costs against your record gas accumulation

**Comment by Phil-m-pinto** [comment]
> Based on your screenshots and the data you provided previously, I believe you may have configured the wrong price sensor on the dashboard. The gas sensor is returned as m3 (this is what Octopus Energy provide), but the pricing is done in kWh (gotta love those inconsistencies), so the dashboard might be combining these two values incorrectly.
> 
> If you go to `config/energy` within your Home Assistant instance, you should use the sensor in the form of `sensor.octopus_energy_gas_{{METER_SERIAL_NUMBER}}_{{MPRN_NUMBER}}_previous_accumulative_cost` with the option of "Use an entity tracking the total costs". This should result in you having the correct costs against your record gas accumulation

**Comment by BottlecapDave** [comment]
It's no problem :) The energy dashboard is geared towards live data, so by adding the Octopus Energy sensors we're kind of abusing the functionality. I'm hoping that they'll add the functionality to add historic data at some point.

I'll close this ticket for now, as I feel it's now fixed.

**Comment by Phil-m-pinto** [comment]
Hi David

I'm Still having issues. 

I'm not sure what i'm doing wrong. 

In the most part, day to day the figurers are correct. but every few days or so the cost calculations for both electricity and gas are incorrect, but the consumption figures are still correct.
EG:

August 17, 2022
Electricity previous accumulative consumption	6.04 kWh	= £10.50 But should be £2.10
Gas previous accumulative consumption	0.2 m³ = £1.80 But should be £0.43

August 13, 2022
Electricity previous accumulative consumption	7.35 kWh	= £4.92 But should be £2.46
Gas previous accumulative consumption	0.72 m³ = £1.72 But should be £0.86

August 10, 2022
Electricity previous accumulative consumption	6.89 kWh	= £2.92 But should be £2.33
Gas previous accumulative consumption	1.09 m³ = £1.44 But should be £1.60

August 8, 2022
Electricity previous accumulative consumption	7.46 kWh	= £5.52 But should be £2.49
Gas previous accumulative consumption	3.09 m³ = £5.91 But should be £2.81

so on and so on.........

this seem to be happening every few days. 

Configure grid consumption
Electricity previous accumulative consumption
Use an entity tracking the total costs
Electricity previous accumulative cost

Configure gas consumption
Gas previous accumulative consumption
Use an entity tracking the total costs
Gas previous accumulative cost

This has been happening for a while, Any ideas???

Thanks 

Phi

**Comment by BottlecapDave** [comment]
Sorry to hear you're still having issues @Phil-m-pinto. These numbers you're seeing, are they on the entity themselves or within the energy dashboard?

**Comment by BottlecapDave** [comment]
I've also moved your issue to a new issue https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/56 as its a different issue to the original issue of this ticket and is easier to track
