### ISSUE TITLE
Really not working very well for me

### ISSUE THREAD

**Issue by TimWardCam** [BottlecapDave/HomeAssistant-OctopusEnergy#415]
### Describe the bug

(1) Although the electricity meter data does appear to be fetched once a day (at a different time each day) it's shown on the Energy dashboard with the day's consumption/production all taking place at one time, rather than divided into its half hour slots. I'm sure Octopus provide the half hourly information - can I expect it to be displayed?

(2) Gas meter data has only been fetched once in the several days I've had it running, a few days ago now.

(3) The log shows many, many errors relating to this component.

As a usability thing, the sensor names are so long that they get truncated in almost all contexts, and have the same characters to start with, so the only way to find the one you want is to pick one at random, find it's the wrong one, pick the next one ...

### Reproduction steps

Install, and observe behaviour.

### Expected behaviour

(1) Data to be displayed on the Energy dashboard in half hour slots, rather than daily at a random time.

(2) Gas meter data to be collected more than just on one way.

(3) Zero errors in the logs.

A sample from the logs is attached.

[haerrors.txt](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/12688761/haerrors.txt)

### Tariff Code

Sorry, don't know where to find that.

### Integration Version

Downloaded a couple of days ago. Can't find version.

### Home Assistant Version

2023.9.2

### Fresh Install?

Not specified

### Home Assistant Logs

Can't submit if I include the log data here, "body is too long". Attached as a file instead.

**Comment by BottlecapDave** [comment]
Hello and sorry to hear that you're having issues.

> As a usability thing, the sensor names are so long that they get truncated in almost all contexts, and have the same characters to start with, so the only way to find the one you want is to pick one at random, find it's the wrong one, pick the next one .

The ids of the sensors have to be long unfortunately to avoid potential clashes. You are free to change the default names of the sensors to something more managable for your scenario.

1) Unfortunately this is a limitation with HA, the sensors and the loading of historic data. If you follow the [docs](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/energy_dashboard.md#previous-day-consumption), then you can add some different sensors which have the data broken down in hourly chunks.

2) This can occur for a number of reasons, but the main one is OE taking longer than 24 hours to retrieve the data. Does the data appear in the OE online dashboard/app for the sday before? If it takes a few days to appear within the app, then it will miss the window of retrieving the data within the integration. I'm currently working on a [couple of ways](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/312) of improving the experience in this scenario.

3) I'll take a look at the logs and report back.

**Comment by TimWardCam** [comment]
1. Ta. I'll try that - I'd not thought that page relevant to me as it talks about needing an "Octopus Home Mini", and as I've never heard of that I assume I don't have one.

2. I appreciate that Octopus info isn't real time, but on their web site yesterday's numbers, by the half hour, seem always to be available by mid morning at the latest.

Thanks for your help.

**Comment by BottlecapDave** [comment]
I've just read your logs, and these are all warnings not errors. To summaries

`custom integration has not been tested` - warning by HA that I'm not in control of
`Update of sensor x is taking over 10 seconds` - Data is retrieved, cached and shared amonst the entities, however one entity has to request the data initially. If you are getting this warning, then it's either your internet being slow or OE APIs being slow/failing (as they tend to do that often), both of which are out of my control. It could also potentially be a hardware issue on your HA instance.
`Updating sensor took longer than the scheduled update interval` - Same reasons as above
`State attributes for x exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored` - See https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/357 for progress on this one

**Comment by BottlecapDave** [comment]
> I appreciate that Octopus info isn't real time, but on their web site yesterday's numbers, by the half hour, seem always to be available by mid morning at the latest.

If it's appearing in the OE dashboard within 24 hours, then it could either be related to the update warnings you've been getting or something else. If you could follow the [faq](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/faq.md#how-do-i-increase-the-logs-for-the-integration) to get me increased logs (I need all lines that start with `debug`), then it might shed some more light on why you're not getting updates.

**Comment by BottlecapDave** [comment]
> which I think is what the documentation suggests, and that gives me daily, not hourly, graphing for electricity and nothing at all for gas (apart from the one day it got something).

As mentioned in the docs, you're after  different sensors to provide this data (starts with `octopus_energy:` instead of `sensor.octopus_energy`. This is less than ideal, but limitation of loading historic data (HA wasn't really built for it)

**Comment by TimWardCam** [comment]
Trying again ... :-)

**Comment by Leventionz** [comment]
I would recommend getting a home mini for current day half hourly snapshots, good for various dashboards and automations. I got mine within a few weeks of requesting one.

**Comment by TimWardCam** [comment]
I've now got hourly electricity info displayed in the energy dashboard. Gas appears on occasional days but is mostly missing (and I think I've seen it appear for a particular day and later disappear, but I can't swear to that). However I'm not really bothered about gas, it's the electricity I'm mostly interested in.

Some debug log attached in case you're interested in looking at it.

Thanks for your help.

[octopus.log](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/12719691/octopus.log)

**Comment by BottlecapDave** [comment]
Sorry for the late response, but I've only just had a chance to look at the logs. Thank you for supplying them. Nothing is jumping out at me, as the various components look like they're updating at the correct intervals. As it looks like the initial issues are resolved, I'll close this issue.
