### ISSUE TITLE
New install - receiving rate, but not previous day consumption?

### ISSUE THREAD

**Issue by zygote279** [BottlecapDave/HomeAssistant-OctopusEnergy#43]
Hi there,

Just installed this and seems to all work (great work on this!), correctly returns my rate, however both consumption and cost values are returning 0.

Any ideas on how I can diagnose this?

**Comment by BottlecapDave** [comment]
Sorry to hear you're having issues. Do you see anything in your home assistant logs?

**Comment by robjones84** [comment]
I have the same issue.

I can see costs - but nothing showing as consumed in the energy tab.

If i load this as an entity though, it shows the total amount consumed (i.e 50kw for example)

**Comment by robjones84** [comment]
<img width="1693" alt="Screenshot 2022-02-21 at 10 40 09" src="https://user-images.githubusercontent.com/38785048/154939092-8e1efb3d-9e4c-45de-910b-44df1292e94a.png">
<img width="516" alt="Screenshot 2022-02-21 at 10 40 26" src="https://user-images.githubusercontent.com/38785048/154939143-ba3254c7-b3a4-4e67-a141-804dd91a6b6d.png">

**Comment by BottlecapDave** [comment]
Sorry to hear a few of you are having issues with this. I'm hoping it's not an undocumented API change :(

I'm currently in the process of reviewing a PR and adding some much needed and missing unit and integration tests around the integration, so I'll take a look at the issue around the same time.

**Comment by BottlecapDave** [comment]
@robjones84 It looks like your issue is slightly different to @zygote279. Could you please raise a new issue stating you're missing your gas sensors completely?

**Comment by BottlecapDave** [comment]
@zygote279 I posted the following in another thread where someone is not receiving any data in gas sensors, and wondered if it was a similar issue

> Interesting. After digging into why my sensors are zero, I noticed that the Octopus Energy dashboard (https://octopus.energy/dashboard) doesn't have any data past 10th February. I wasn't sure if this was the case for some of you?
In my testing, it should be pulling data through correctly if it's available, but I will continue to investigate.

**Comment by BottlecapDave** [comment]
Is this still not working @zygote279 ?

**Comment by zygote279** [comment]
Hi,

Yes, still getting 0 for both values - unit cost comes through fine, just getting zero for the actual energy use values...

**Comment by BottlecapDave** [comment]
If you go to the Octopus Energy dashboard (https://octopus.energy/dashboard), do you have data for yesterday? Also is this for electricity, gas, or both? Do you just import energy, or do you export energy as well?

**Comment by zygote279** [comment]
Yep, have data for every day including yesterday.

Just use electricity, no gas and just import energy.

Has zero in the energy dashboard also, seems to have connection fine, just not returning data!

**Comment by zygote279** [comment]
Ah, think I've cracked it - noticed that a new pair of entities are  now coming through in the entity viewer and sure enough these have values for £ and kWh, so seems to be working, but has a couple of dud entities.

Any idea why this might have happened? Is there any reason new entities would be created?

Seems to work now, just don't know if it'll create a third pair at some point or a one off quirk!

**Comment by zygote279** [comment]
Working Entity Name: Octopus Energy Electricity 21M0349195 Previous Accumulative Consumption

Zero Entity Name: Octopus Energy Electricity S11R60082 Previous Accumulative Consumption

**Comment by BottlecapDave** [comment]
There was a bug in an old build where the integration could pick up the wrong property if you had moved house. The sensor names will also change again unfortunately in the latest build (v4.0.0) due to support for import/export sensors. Glad you've manage to track down the issue.

**Comment by BottlecapDave** [comment]
Major version changes mean that something will potentially break your integration, and I try and highlight these breakages in the associated changelog.

**Comment by zygote279** [comment]
Ah right, yeah that's fine as long as I know what's causing it, I can update sensors!
