### ISSUE TITLE
Peak/Off Peak Sensor not triggering over the weekend

### ISSUE THREAD

**Issue by ColinSainsbury** [BottlecapDave/HomeAssistant-OctopusEnergy#432]
### Describe the bug

When first installed this feature worked correctly, but over the weekend the state has remained as Off indicating a constant Peak state. Will report back if this returns on Monday. I use Octopus Eco 7 and this new feature is great to trigger on for my electricity expenditure tracking avoiding the need to manage daylight saving.

### Reproduction steps

Monitor status of the Peak/Off Peak - status stuck in Off

### Expected behaviour

Should alternate between On and Off based on time of day and Peak Off Peak status of the tariff.

### Tariff Code

E-2R-VAR-22-11-01-H

### Integration Version

8.3.0

### Home Assistant Version

2023.9.3

### Fresh Install?

After upgrading

### Home Assistant Logs

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/33755825/4f3b6457-c554-4ebb-ba8e-7eb28601719d)

**Comment by ColinSainsbury** [comment]
Triggered fine overnight. Is Peak/Off-Peak signal only sent by OE on weekdays, even for Eco 7?

**Comment by BottlecapDave** [comment]
Hello and sorry you're having issues. The integration pulls rate data every 30 minutes, and it should be re-calculating the state every minute. I'm trying to track down why this can occur sometimes on some sensors and only for some users (e.g. if it's a HA thing or something else)

**Comment by ColinSainsbury** [comment]
Thanks for the reply Dave 

This is the sensor I mean binary_sensor.octopus_energy_electricity_21k01*****_20000534*****_off_peak

It seems to work Mon - Fri but not Sat and Sun. Difficult to know if this is real because I have only been monitoring for the last few days. It could be that something glitched last weekend at the Octopus end.

**Comment by BottlecapDave** [comment]
Yeah all sensors are requested to be re-calculated every minute by HA based on the cached data. Rate information, which powers the mentioned sensor, is refreshed every 30 minutes. 

However as mentioned there have been sporadic reports of various sensors not updating, which I'm trying to track down why this is. Most sensors are setup in a similar way, so I'm sure if I find the fault for one, I'll find it for others. However, because it's not a constant issue, I'm starting to wonder if it's an underlying issue in HA.

**Comment by BottlecapDave** [comment]
I've made some more adjustments in the latest release that will hopefully make this more reliable. Please let me know if you experience it again.

**Comment by ColinSainsbury** [comment]
Dave, really appreciate the follow up. I was planning to let you know that the offpeak sensor worked fine overnight. This was before the update. I have however updated the Home Assistant binaries and performed a full restart this week due to an issue with the HACS Tesla integration.

Long story short. Not sure why it started working, but it did.

**Comment by BottlecapDave** [comment]
Ok thanks for getting back to me. I'll close this issue for now, but if it comes back, just reopen the issue :)
