### ISSUE TITLE
cannot access local variable 'settings' where it is not associated with a value

### ISSUE THREAD

**Issue by jingyitian** [BottlecapDave/HomeAssistant-OctopusEnergy#438]
### Describe the bug

When attempting to add OctopusEnergy account, it shows the following error

cannot access local variable 'settings' where it is not associated with a value

However i can see my meter MPAN number if I am to manually add an entity, so assuming the connection to fuel vendor is successful.

### Reproduction steps

Add integration, fill in API key and Account Number

### Expected behaviour

There is no error message and integration is set up

### Integration Version

v8.3.0

### Home Assistant Version

2023.9.3

### Fresh Install?

Fresh install

### Home Assistant Logs

Unexpected error fetching intelligent_settings data: cannot access local variable 'settings' where it is not associated with a value
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 246, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/intelligent_settings.py", line 51, in async_update_intelligent_settings_data
    if settings is not None:
       ^^^^^^^^
UnboundLocalError: cannot access local variable 'settings' where it is not associated with a value

**Comment by BottlecapDave** [comment]
I believe this was an issue on the `develop` branch (which is noted to be in flux and unstable), not on the latest release based on the line number. However it will be fixed for the next release.

**Comment by jingyitian** [comment]
thanks @BottlecapDave  you are indeed correct. i had thought i used the release but actually the develop branch.
