### ISSUE TITLE
Next Rate for export is 1 hour out (DST issue)

### ISSUE THREAD

**Issue by simeon-simsoft** [BottlecapDave/HomeAssistant-OctopusEnergy#441]
### Describe the bug

My sensor that shows the next 30 minute rate for Outgoing Agile is currently one hour out..  Eg, the time now is 10:50 BST.. its showing me the rate for the period starting at 12:00BST not 11:00 BST

### Reproduction steps

see the valid from times here,, there is no +01:00 which you would expect during BST

Electricity Export Next Half Hour Rate | 0.0302 | state_class: total  serial_number: 1 is_export: true is_smart_meter: true valid_from: 2023-10-06T11:00:00+00:00 valid_to: 2023-10-06T11:30:00+00:00 applicable_rates:  - valid_from: '2023-10-06T11:00:00+00:00'   valid_to: '2023-10-06T11:30:00+00:00'   value_inc_vat: 3.02   is_capped: false   is_intelligent_adjusted: false
-- | -- | --

Electricity Export Next Half Hour Rate
0.0302	state_class: total
mpan: 2200043327337
serial_number: 14P0106564
is_export: true
is_smart_meter: true
valid_from: 2023-10-06T11:00:00+00:00
valid_to: 2023-10-06T11:30:00+00:00
applicable_rates: 
- valid_from: '2023-10-06T11:00:00+00:00'
  valid_to: '2023-10-06T11:30:00+00:00'
  value_inc_vat: 3.02
  is_capped: false
  is_intelligent_adjusted: false

### Expected behaviour

as above, the correct value to match those in the Octopus app

### Tariff Code

E-1R-AGILE-OUTGOING-19-05-13-L

### Integration Version

8.3.0

### Home Assistant Version

2023.10.0

### Fresh Install?

Not specified

### Home Assistant Logs

none

**Comment by BottlecapDave** [comment]
Hello and sorry that you've seen this issue. Unfortunately, with the raw data available, I'm unable to recreate this outcome. I've created tests to cover your scenario at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/tests/unit/utils/test_get_next_rate_information.py#L155 and the 11BST-11:30BST should have been returned.

The only things I can think of is a) HA for some reason presented the wrong time to the integration (unlikely) or b) the rates changed between when you saw your result and when I produced the tests (e.g. the rates between 11BST and 12BST were the same as the rates between 10:30BST and 11BST).

I'll close this issue as I can't recreate it, but if you see it again please comment and reopen this issue providing the following additional information

* rate, valid from and valid to information from `sensor.octopus_energy_electricity_xxx_xxx_current_rate` sensor
* rate, valid from and valid to information from `sensor.octopus_energy_electricity_xxx_xxx_next_rate`
* rate information from `event.octopus_energy_electricity_xxx_xxx_current_day_rates`
