### ISSUE TITLE
Outgoing Agile current rate incorrect

### ISSUE THREAD

**Issue by simeon-simsoft** [BottlecapDave/HomeAssistant-OctopusEnergy#442]
### Describe the bug

My current export rate seems to be stuck on the daily minimum rate.

sensor.octopus_energy_electricity_xx_xx_export_current_rateElectricity Export Current Rate | 0.0083

state_class: total
mpan: 2200043327337
serial_number: 14P0106564
is_export: true
is_smart_meter: true
tariff: E-1R-AGILE-OUTGOING-19-05-13-L
valid_from: 2023-10-06T08:30:00+00:00
valid_to: 2023-10-06T11:00:00+00:00
is_capped: false
is_intelligent_adjusted: true
current_day_min_rate: 0.83
current_day_max_rate: 17.19
current_day_average_rate: 6.132391304347825[sensor.octopus_energy_electricity_xx_xx_export_current_rate](https://home.simeon.uk/developer-tools/state#)
Electricity Export Current Rate
0.0083

### Reproduction steps

observed in the developer tools section

### Expected behaviour

correct rate to be displayed for the current half hour segment

### Tariff Code

E-1R-AGILE-OUTGOING-19-05-13-L

### Integration Version

8.3.0

### Home Assistant Version

2023.10.0

### Fresh Install?

Not specified

### Home Assistant Logs

none

**Comment by BottlecapDave** [comment]
Hello, and sorry you're seeing this issue. Are you on intelligent as well? If so, based on `is_intelligent_adjusted: true`, it looks like the export rates are getting adjusted because you're within an agile period.

**Comment by BottlecapDave** [comment]
I've fixed export rates not being effected by intelligent dispatch data in the latest release, which should fix this issue. Please let me know if this has fixed your issue.

**Comment by simeon-simsoft** [comment]
Thanks. So the behaviour now is that export rates are not linked to Intelligent dispatch periods? Will test and see how it goes. Cheers

**Comment by BottlecapDave** [comment]
Corect the export rates were incorrectly adjusted during an intelligent period to the lowest value of the export rates, as it thought they were "off peak". This has been fixed in v8.4.1.

**Comment by simeon-simsoft** [comment]
I upgraded last night and all looks good with the current and next rates.  Thanks for looking so quickly.

**Comment by BottlecapDave** [comment]
Glad this was the issue :)
