### ISSUE TITLE
FAQ refers to information not present

### ISSUE THREAD

**Issue by realflash** [BottlecapDave/HomeAssistant-OctopusEnergy#448]
### Describe the bug

At https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/850e2051e9f29b30064c43fdd5a60b0122a74188/_docs/faq.md#i-have-sensors-that-are-missing the answer says that information on enabling more logging is above. I suspect it is referencing another FAQ entry that is actually below it.

### Reproduction steps

Go to the URL provided

### Expected behaviour

Logging information is linked rather than referred to by position

### Tariff Code

N/A

### Integration Version

N/A

### Home Assistant Version

N/A

### Fresh Install?

Not specified

### Home Assistant Logs

N/A

**Comment by BottlecapDave** [comment]
Thanks for bringing this to my attention. This has now been resolved.
