### ISSUE TITLE
Unclear how to enable next_day_rates

### ISSUE THREAD

**Issue by realflash** [BottlecapDave/HomeAssistant-OctopusEnergy#449]
### Describe the bug

In https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/sensors/electricity.md#next-day-rates it states that this sensor (although the text says it is an event - is it the new event entity or an event?) is disabled by default. As a new reader (and new user of this integration), I would like to know how to enable it, or what situation causes it to be enabled. 

As per the FAQ (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/faq.md#i-have-sensors-that-are-missing) I did enable debug logging on the component, restarted HA and then downloaded the full log, but there is no mention of this sensor anywhere in the logs so I wasn't able to work out why it is disabled or how to enable it.  

In case it is of relevance, we were not on an agile tariff when the integration was installed. We have moved on to Agile now. That change has been picked up by the integration, and current, previous and next rates have updated accordingly.

### Reproduction steps

Visit the URL above

and

- Enable debug logging
- Restart HA
- Download full logs
- View log. The string `next_day` is not in the log.

### Expected behaviour

1. The documentation should state how to enable the sensor
2. The reason for the sensor being disabled should be in the log as per the FAQ stating that it is

### Tariff Code

E-1R-AGILE-FLEX-22-11-25-H

### Integration Version

8.3.0

### Home Assistant Version

2023.8.4

### Fresh Install?

Fresh install

### Home Assistant Logs

[home-assistant_2023-10-08T11-07-55.078Z.log](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/12840486/home-assistant_2023-10-08T11-07-55.078Z.log)

**Comment by realflash** [comment]
Thanks for updating that. Being somewhat seasoned in HA I had already visited the entity list and seen some disabled entities. It seems my situation is outside the FAQ, as the entities are missing from the full entity list. They are not there to be enabled, and they are not mentioned in the log as to why they aren't there. The entities I am expecting are:

- next_day_rates
- current_day_rates
- previous_day_rates

There might be others missing but these are the ones I am interested in because of my switch to Agile. Is there some situation where entities not relevant to Agile are not registered when installing the integration, and then don't become enabled later when the tariff changes?

Please let me know if you would like me to open a new issue for this.

**Comment by BottlecapDave** [comment]
You will need to update to the latest version of the integration before you'll see those sensors, as you've stated you're currently on 8.3.0
