### ISSUE TITLE
Setting Target Charge and Ready By Time reverts whichever value was initially set

### ISSUE THREAD

**Issue by steelixb** [BottlecapDave/HomeAssistant-OctopusEnergy#455]
### Describe the bug

If I change the target charge and wait for a minute, it's fine. If I change ready by time and wait a minute or so, also fine.

However, if I change one straight after the other, the initial value I set reverts to the value it was before.

### Reproduction steps

1. Set charge, e.g. from 80% to 90% from Home Assistant
2. Observe in the Octopus app to ensure it's now 90%
3. Immediately change time, e.g. from 7:00 to 8:00 from Home Assistant
4. Observe in the Octopus app that the charge has changed back to 80% and only the time has changed from 7:00 to 8:00

### Expected behaviour

Charge and time to remain whatever was last set from Home Assistant

### Integration Version

v8.4.2

### Home Assistant Version

2023.10.1

### Fresh Install?

Not specified

### Home Assistant Logs

-

**Comment by BottlecapDave** [comment]
Sorry that you've hit this issue. I think I've fixed this issue, but I'm not on intelligent so unable to test it. If you're able to test https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v8.4.3-beta1 that would be fantastic

**Comment by steelixb** [comment]
Just tested, can change the time fine, but trying to change the charge gives me an error and doesn't work: 
![Screenshot_20231011_075110_Home Assistant](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/23078066/be0b870e-5d4d-4797-912a-06e25bf24b0e)

**Comment by steelixb** [comment]
Seems to be working great now, thanks!

**Comment by BottlecapDave** [comment]
Closing as this has now been released as part of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v8.4.3
