### ISSUE TITLE
Current energy cost sensor displays $ symbol instead of £

### ISSUE THREAD

**Issue by ecylcje** [BottlecapDave/HomeAssistant-OctopusEnergy#47]
Hi,

My current energy cost sensor icon is displayed as a $ instead of £ symbol.

![Dollar_HA](https://user-images.githubusercontent.com/10866152/161234888-96ad6796-938a-4d49-961e-46bdb850e6dd.png)

sensor.octopus_energy_electricity_{{METER_SERIAL_NUMBER}}_{{MPAN_NUMBER}}_current_rate

Is this my setup or an issue because of:

HomeAssistant-OctopusEnergy-4.1.3\custom_components\octopus_energy\sensor.py (5 hits)
	Line 196:     return "mdi:currency-usd"
	Line 274:     return "mdi:currency-usd"
	Line 447:     return "mdi:currency-usd"
	Line 531:     return "mdi:currency-usd"
	Line 712:     return "mdi:currency-usd"

I have configured everything else in Homeassistant to have GBP £ and it works fine. Until I upgraded octopus_energy recently (today) it was working there as well.

Thanks,

Chris

**Comment by townsmcp** [comment]
@ecylcje have you gone into 'Configuration' -> 'Settings' -> 'General' and set Currency to GBP?

**Comment by ecylcje** [comment]
Sadly yes. I checked in there and it is set to GBP:

 



 

It was working fine before I upgraded octopus_energy versions. My old sensor was just sensor.octopus_energy_electricity_current_rate before it moved to the version with MPAN in. That was displayed nicely with £.

 

Thanks,

 

Chris

**Comment by BottlecapDave** [comment]
Hi, sorry that you are having issues. In your image, are you referrring to the $ icon as it looks like it's reporting in GBP? If not, what version of home assistant are you running?

Thanks,
Dave

**Comment by ecylcje** [comment]
Thanks Dave.

It is just the icon image ($) which I was talking about. On my previous version (of Octopus-energy) it was a £ symbol.

I'm running the latest release of HA (22.03.08) on RPi. Obviously this is in no way critical or a major problem. It was just more a 'weird' issue I thought I would raise.

Thanks so much,

Chris

**Comment by airampg** [comment]
Hi people. I just wanted to let you know that I can also see this problem, with the currency set to GBP and so on. 
I just changed myself to be mdi:currency-gbp, so no biggie, but if it could be quickly fixed on the code it would also be nice for future updates :)

**Comment by BottlecapDave** [comment]
I have updated this in the latest release (v4.2.0)
