### ISSUE TITLE
Previous Accumulated Gas Consumption & Cost not updated for two days

### ISSUE THREAD

**Issue by HarryFlatter** [BottlecapDave/HomeAssistant-OctopusEnergy#473]
### Describe the bug

Previous Accumulated Gas Consumption & Cost not updated for two days. Have tried reloading integration. Historic data from the current consumption entity shows the correct previous consumption, just not the 'Previous' entities.

### Reproduction steps

Display Entities

### Expected behaviour

Data should reflect previous day's gas consumption and cost

### Integration Version

Current

### Home Assistant Version

2023.10.2

### Fresh Install?

Not specified

### Home Assistant Logs

n/a

**Comment by BottlecapDave** [comment]
Sorry that you're receiving this issue. Can you see the data in the OE app or web dashboard for yesterday? If the data takes longer than 24 hours to process, then the sensor won't pick it up.

**Comment by jwt99412** [comment]
I have the same issue since updating to the latest version of the Octopus Integration

**Comment by HarryFlatter** [comment]
Hi David,

 

Many thanks for you e-mail. 

 

The HA sensor eventually updated on HA at 3:52. This was the first update since 21:37 on the 14 Oct.

Is there any reason why this sensor (and its associated cost) doesn’t update at midnight?

 

The OE app is not showing any usage on the ‘Week’ display – all days are blank.

 

The ‘Day’ display was showing an ‘Oops something went wrong’ message but has now updated and agrees with the current consumption sensor on HA

 

Many thanks and kind regards

 

Steve

**Comment by BottlecapDave** [comment]
It doesn't update at midnight because it uses a different API. This is the data that is present in the OE app/web and is used by OE to determine your bill. This data _can_ differ from the data retrieved by the mini, and if there are discrepencies this data will be used over the mini data in the dashboard/bill. Because of this, the data isn't available at midnight as it takes a while for OE to reconcile with your meter and become available

**Comment by HarryFlatter** [comment]
Thanks David.
But it didn't update at all yesterday and only at 21:37 the day before and then today at 15:52. 
Does it really take that long for the OE to reconcile with the meter?
Would it not be possible to update the Previous values with the Mini current data at midnight and then update later if there is an subsequent reconciliation? 
Or am I mis-understanding what is possible?

**Comment by BottlecapDave** [comment]
> But it didn't update at all yesterday and only at 21:37 the day before and then today at 15:52. Does it really take that long for the OE to reconcile with the meter?

It can do unfortunately, and can vary on person to person. This can be seen on the app/website where it can sometimes go days for data to populate. If the data takes longer than 24 hours to become available (e.g. data from 14th becomes available on the 16th), then it will be missed.

> Would it not be possible to update the Previous values with the Mini current data at midnight and then update later if there is an subsequent reconciliation?

That would screw up the history of the sensor as you can't alter historic values within HA.

I have it on my list to try and make these sensors more robust around situations like this.

**Comment by HarryFlatter** [comment]
Appreciate all the effort and understand your response.

We'll look out for some slightly more robust sensors in the future, perhaps.

Again, thanks for your prompt responses.

**Comment by HarryFlatter** [comment]
I see pretty much the same thing.

I guess we'll just have to wait for them to spend a few shekels on the gas side.

**Comment by HarryFlatter** [comment]
There now appears to be an issue with Peak and Off-Peak sensors.

Other than the kWh & £ figures for 'Today' importing, the 'Previous' Peak and Off-Peak kWh & £ sensors for Import & Export don't update and haven't for over a week.
The 'Total' figures do update. It's just the constituent Peak and Off-Peak that are missing.

**Comment by BottlecapDave** [comment]
If there is no consumption data available, then the peak/off peak data will not update. There was a general issue with the peak/off peak sensors, but this was resolved in the latest release (as long as the data is available). Please make sure you're on the latest release via HACS.

**Comment by HarryFlatter** [comment]
Aha! I do apologise, I tend to rely on the 'Settings' update flag for most updates, but forget to actually visit HACS to check for updates there.

The most recent OE update has indeed fixed the Peak and Off-Peak figures for consumption.

However, might there still be an issue with the same figures for 'Export'?

I have a figure in the Total sensor but nothing in either of the Peak or Off-Peak for kWh or £.

**Comment by BottlecapDave** [comment]
Unless export tariff has multiple rates based on time of day, peak/off-peak won't be applicable/populated.

**Comment by HarryFlatter** [comment]
Aha! Again!

I've recently switched from 'Flux' (multiple export rates) to 'Go' which only has one rate. My lack of data in those sensors coincides with the tariff switch.

Thanks for being so on the ball with these issues. :-)

**Comment by pcb1962** [comment]
> I tend to rely on the 'Settings' update flag for most updates, but forget to actually visit HACS to check for updates there.

Here's a simple card you can add to any dashboard which will show itself only when you have HACS updates available:

```
type: conditional
conditions:
  - entity: sensor.hacs
    state_not: '0'
card:
  type: tile
  entity: sensor.hacs
  icon: mdi:download
  name: HACS updates
```

**Comment by HarryFlatter** [comment]
You're a gent  and a scholar!
I'll add that to my general 'Status' dashboard.
Many thanks

**Comment by BottlecapDave** [comment]
You can also follow the instructions in the faq to get updates from HACS appearing in the normal place https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/faq.md#how-do-i-know-when-theres-any-update-available

**Comment by raldred** [comment]
My octopus gas data has been pulling through regularly recently for the previous day maybe octopus fixed something?
