### ISSUE TITLE
Add integration icon to HomeAssistant 'brands' repo

### ISSUE THREAD

**Issue by gitothy** [BottlecapDave/HomeAssistant-OctopusEnergy#48]
Would it be possible to add an icon for this integration in to the following repo:
https://github.com/home-assistant/brands

The below file meets the requirements to be accepted (256px, PNG, interlaced, transparent bg)
![icon](https://user-images.githubusercontent.com/39539635/166128246-b992fe72-0ab8-4db9-ad15-994e7dd463ff.png)

Many thanks in advance

**Comment by BottlecapDave** [comment]
Thanks for bringing this to my attention. I've created my own version (own paranoia sorry) and the code review can be found at https://github.com/home-assistant/brands/pull/3472

**Comment by BottlecapDave** [comment]
This has now been merged into the brands repo, so this should be available soon. So I'll close this issue as it's solved from my end.
