### ISSUE TITLE
Intelligent dispatch attributes - incorrect times

### ISSUE THREAD

**Issue by Pandorion** [BottlecapDave/HomeAssistant-OctopusEnergy#490]
### Describe the bug

Charged the car with Intelligent Octopus and looked at the dispatch slots in Home Assistant. Looking at the attributes for the Octopus Energy Intelligent Dispatching entity I noted that the times didn't seem quite right. Checked the GiveEnergy portal and can see that the times given are an hour different. Looks like a UTC to local time issue (bane of a programmers life).

Looking a little closer at this, I can see the slots are not in date order and the second slot starts at 00:00:00, so it isn't a UTC conversion issues. It looks like it doesn't have the 30 minutes from the previous day - not sure what's happening!

![Screenshot 2023-10-26 at 08 02 05](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/3480079/6e6c8182-fd1b-44c1-90df-569348d9effe)
![Screenshot 2023-10-26 at 08 02 25](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/3480079/d93d8871-72c3-424b-b5a3-1b295334fe3e)

### Reproduction steps

Go Home Assistant Developer Tools and on the States tab, filter by binary_sensor.octopus_energy_intelligent_dispatching

### Expected behaviour

Times should be 1 hour earlier than shown.

### Integration Version

v8.4.4

### Home Assistant Version

2023.10.5

### Fresh Install?

Not specified

### Home Assistant Logs

Not sure logs are relevant here - it's easy to reproduce.

**Comment by BottlecapDave** [comment]
Hello. The dates reported by the integration are in UTC format and are reported as is by OE. There is an open ticket to make the date/times more consistent (as HA converts some to local format and not others).

The completed dispatches are reported by OE, but they seem to drop off the list at varying speeds so I try to catch them and store them locally before they disappear to extend the timeframe. Pending dispatches don't always get transferred to completed (I assume if the car isn't charged). I'm not on intelligent, so this is based on anidotes from other users.

Based on the data from OE, it looks like it charged your car between 1am BST to 2am BST and then 3am BST to 3:30am BST. What does the OE app state (if it can)?

**Comment by Pandorion** [comment]
Here's the meter data from Octopus. The charge actually started at 11:30pm on 25-Oct (the same as the GE portal picture above).

![Screenshot 2023-10-31 at 18 31 13](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/3480079/b2a70509-be90-40cb-8927-efefd365d894)

**Comment by BottlecapDave** [comment]
Thanks for the update. It's probably related to https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/413, for which I'm trying to get some confirmation from OE. Their completed dispatches seem a bit incomplete/broken.

Was the sensor at least on during the right times even if the completed dispatches are incomplete?

**Comment by Pandorion** [comment]
I've just checked back and it looks like I put a 3 day purge on my recorder so don't have the information.

I've extended my retention to 15 days now and so I will keep an eye on it. It's the sensor I am interested in so that I can use in an automation to control my battery for the cheap slots. 

Thanks for your integration.

**Comment by DragonQ** [comment]
I don't think this is an issue with this integration. I did an Octopus API GraphQL query directly and it came back with clearly incorrect "completed dispatch" times.
