### ISSUE TITLE
Initial integration fails

### ISSUE THREAD

**Issue by BJarkowski** [BottlecapDave/HomeAssistant-OctopusEnergy#498]
### Describe the bug

After providing the API Key and Account number the integration failes to start.

### Reproduction steps

1) Choose Octopus integraton to configure
2) Provide API Key and Account Number
3) Not changing any other settings
4) Confirm 
5) Integration shows error message - Failed to set up 

### Expected behaviour

I can access entities

### Integration Version

8.5.0

### Home Assistant Version

2023.10

### Fresh Install?

Not specified

### Home Assistant Logs

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/octopus_energy/__init__.py", line 81, in async_setup_entry
    await async_setup_dependencies(hass, config)
  File "/config/custom_components/octopus_energy/__init__.py", line 153, in async_setup_dependencies
    await async_setup_electricity_rates_coordinator(hass, mpan, serial_number, is_smart_meter, is_export_meter)
  File "/config/custom_components/octopus_energy/coordinators/electricity_rates.py", line 126, in async_setup_electricity_rates_coordinator
    hass.data[DOMAIN][coordinator_key] = DataUpdateCoordinator(
TypeError: DataUpdateCoordinator.__init__() got an unexpected keyword argument 'always_update'

**Comment by BottlecapDave** [comment]
Hi and sorry you're having issues. Forgive me if this comes off as rude, but are you sure you're on 2023.10 of HA? I only ask, because the error you posted implies you're on a version before 2023.09. I'm currently running the integration on 2023.10.5 without this issue.

**Comment by BJarkowski** [comment]
Hi,
thanks for prompt message! You were correct - accidentaly I fetched a doggy version of the Home Assistance which I thought was the latest. After changing the image all seems to be working fine. Thank you!

**Comment by BottlecapDave** [comment]
No problem, and glad it's working for you now :)
