### ISSUE TITLE
Add sensor for detecting saving sessions

### ISSUE THREAD

**Issue by dtpazz** [BottlecapDave/HomeAssistant-OctopusEnergy#499]
**Describe the feature**

This winter (2023) there are plans by Octopus Energy to incentive its customer base to save energy during periods of grid peak demand. New for this year is that OE intend on informing customers at short notice. These are referred to as Surprise Sessions.

See https://octopus.energy/blog/saving-sessions-faqs/?fbclid=IwAR29LZ753eLZVdJRw1wBjIxWrhRV20_T-wvPrWUYnw38kI_iNWh1njvQIA0#surprisesessions

**Expected behavior**

When an account has enrolled in a Octoplus, saving sessions should be recognised by a sensor within the integration allowing home assistant users to benefit from the incentive through managing their energy import/export.

**Comment by BottlecapDave** [comment]
Do you mean these [sensors](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/entities/saving_sessions.md)?

**Comment by BottlecapDave** [comment]
There is also https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/487 to support opting in via home assistant auotmatically

**Comment by dtpazz** [comment]
Ah thanks, I hadnt seen those sensors as I expected them to be shown under the device of Elec meter.

Looks like you're already on it Dave! Great work! Sponsorship coming your way 👍
