### ISSUE TITLE
Gas Meter - Current Accumulative Cost values negative

### ISSUE THREAD

**Issue by alfwro13** [BottlecapDave/HomeAssistant-OctopusEnergy#506]
### Describe the bug

I guess this was caused by a blip when pulling data from octopus but last night my sensor.octopus_energy_gas_[removed]_current_accumulative_cost went negative from 2.69 to -4.69 and then reverted back to 2.69.
At the same time: sensor.octopus_energy_gas_[removed]_current_accumulative_consumption dropped from 34.94 to -71.64 and 1 hour later back to 34.94.
I would not have noticed it if I was not using both sensors with a utility meter and that resulted in additional 106 kwh added to my usage
The same thing happened to: sensor.octopus_energy_gas_[removed]_current_consumption at the same time as the two above it dropped to -106 and then reverted back to 0.

I have octopus home mini device

### Reproduction steps

Not sure how to reproduce it as there was no user interaction involved - it occurred in the middle of the night

### Expected behaviour

gas values should only increase, there should be no case where they drop or usage is negative 

### Tariff Code

G-1R-VAR-22-11-01-J

### Integration Version

8.5.0

### Home Assistant Version

2023.10.5

### Fresh Install?

Not specified

### Home Assistant Logs

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.10.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "6.1.59",
    "supervisor": "2023.10.1",
    "host_os": "Home Assistant OS 11.1",
    "docker_version": "24.0.6",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "scheduler": {
      "version": "v0.0.0",
      "requirements": []
    },
    "holidays": {
      "version": "1.9.6",
      "requirements": [
        "python-dateutil>=2.8.2",
        "holidays>=0.14.2"
      ]
    },
    "energy_meter": {
      "version": "1.0.1",
      "requirements": []
    },
    "solcast_solar": {
      "version": "4.0.12",
      "requirements": [
        "aiohttp>=3.6.2",
        "datetime>=4.3",
        "isodate>=0.6.1"
      ]
    },
    "weatherbit": {
      "version": "1.0.20",
      "requirements": [
        "pyweatherbitdata==1.0.15"
      ]
    },
    "octopus_energy": {
      "version": "8.5.0",
      "requirements": []
    },
    "mold_risk_index": {
      "version": "1.0.1",
      "requirements": []
    },
    "hildebrandglow_dcc": {
      "version": "1.0.3",
      "requirements": [
        "pyglowmarkt==0.5.5"
      ]
    },
    "nextcloudtalk": {
      "version": "2021.12",
      "requirements": [
        "requests"
      ]
    },
    "jellyfin": {
      "version": "1.1.1",
      "requirements": [
        "jellyfin-apiclient-python==1.7.2"
      ]
    },
    "dewpoint": {
      "version": "0.0.1",
      "requirements": [
        "psychrolib==2.1.0"
      ]
    },
    "omada": {
      "version": "0.4.0-beta.1",
      "requirements": []
    },
    "pirateweather": {
      "version": "1.2.3",
      "requirements": [
        "python-forecastio==1.4.0"
      ]
    },
    "webrtc": {
      "version": "v3.5.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "givenergy_local": {
      "version": "0.0.1",
      "requirements": [
        "givenergy-modbus==0.10.1"
      ]
    },
    "frigate": {
      "version": "4.0.0",
      "requirements": [
        "pytz==2022.7"
      ]
    },
    "spook": {
      "version": "1.3.2",
      "requirements": []
    },
    "spook_inverse": {
      "version": "1.3.2",
      "requirements": []
    },
    "mqtt-mediaplayer": {
      "version": "0.0.0",
      "requirements": []
    },
    "daily_schedule": {
      "version": "v1.6.0",
      "requirements": []
    },
    "openweathermap_all": {
      "version": "0.0.1",
      "requirements": [
        "owm2json==0.1.89"
      ]
    },
    "battery_consumption": {
      "version": "1.0.4",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "octopus_energy",
    "name": "Octopus Energy",
    "codeowners": [
      "@bottlecapdave"
    ],
    "config_flow": true,
    "dependencies": [
      "repairs",
      "recorder"
    ],
    "documentation": "https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs",
    "homekit": {},
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues",
    "ssdp": [],
    "version": "8.5.0",
    "zeroconf": [],
    "is_built_in": false
  },
  "data": {
    "id": "**REDACTED**",
    "electricity_meter_points": [
      {
        "mpan": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "is_export": true,
            "is_smart_meter": true,
            "device_id": null,
            "manufacturer": "1063 - Landis and Gyr",
            "model": "00050204",
            "firmware": "38040404"
          }
        ],
        "agreements": [
          {
            "valid_from": "2023-05-07T23:00:00+00:00",
            "valid_to": null,
            "tariff_code": "E-1R-FLUX-EXPORT-23-02-14-J",
            "product_code": "FLUX-EXPORT-23-02-14"
          }
        ]
      },
      {
        "mpan": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "is_export": false,
            "is_smart_meter": true,
            "device_id": "**REDACTED**",
            "manufacturer": "1063 - Landis and Gyr",
            "model": "00050204",
            "firmware": "38040404"
          }
        ],
        "agreements": [
          {
            "valid_from": "2023-05-07T23:00:00+00:00",
            "valid_to": null,
            "tariff_code": "E-1R-FLUX-IMPORT-23-02-14-J",
            "product_code": "FLUX-IMPORT-23-02-14"
          }
        ]
      }
    ],
    "gas_meter_points": [
      {
        "mprn": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "consumption_units": "m\u00b3",
            "is_smart_meter": true,
            "device_id": "**REDACTED**",
            "manufacturer": "1063 - Landis and Gyr",
            "model": "47720101",
            "firmware": "03033254"
          }
        ],
        "agreements": [
          {
            "valid_from": "2023-03-31T23:00:00+00:00",
            "valid_to": null,
            "tariff_code": "G-1R-VAR-22-11-01-J",
            "product_code": "VAR-22-11-01"
          }
        ]
      }
    ]
  }
}

**Comment by BottlecapDave** [comment]
hmm interesting. I guess the APIs had a blip or something. I'll try and add some additional checks. I assume these negatives were in the sensor themselves and not just the energy dashboard?

**Comment by alfwro13** [comment]
yes, I checked all the gas sensors and only the three listed above were affected - this is a screen shot of the current consumption graph
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/10945277/27f162ef-f991-43be-b88f-963fbd11549a)

**Comment by BottlecapDave** [comment]
I've added some defensive code for this in [v9.1.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v9.1.0), which will hopefully fix this issue.
