### ISSUE TITLE
Add rate to saving sessions 

### ISSUE THREAD

**Issue by springfall2008** [BottlecapDave/HomeAssistant-OctopusEnergy#509]
**Describe the feature**

For the octopus saving sessions can the saving rate in pence per kWh be provided? 

This would be great for Predbat and other automations to take advantage of the session 

**Expected behavior**

new attribute in saving session sensor with the rate 
.

**Comment by BottlecapDave** [comment]
Hello. I'm not too sure what rate you are referring to. Can you elaborate?

**Comment by springfall2008** [comment]
Sorry I really mean the ocotopoints that you get per kWh saving

**Comment by Shaun-Harrison** [comment]
To add to this, might be nice if we could have a boolean for if a saving session is active

**Comment by springfall2008** [comment]
> add to this, might be nice if we could have a boolean for if a saving session is active

There is already a saving session sensor which says if it's active and gives the start and end time, we just don't know the rate/points. I don't know if Octopus provide it or not as I can't find the API documentation.

**Comment by Shaun-Harrison** [comment]
ooooh, what is the sensor called for this? I must have missed it

**Comment by springfall2008** [comment]
> ooooh, what is the sensor called for this? I must have missed it

binary_sensor.octopus_energy_saving_sessions

**Comment by BottlecapDave** [comment]
Octopoints per kwh are now available in upcoming and joined saving sessions. This is available in [v9.1.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v9.1.0)
