### ISSUE TITLE
Invalid format - Electricity - BUS-PANELP-12M-FIXED-SEPTEMBER2025

### ISSUE THREAD

**Issue by jaishkp** [BottlecapDave/HomeAssistant-OctopusEnergy#514]
### Describe the bug

Getting the following error when trying to set up:

Invalid format - Electricity - BUS-PANELP-12M-FIXED-SEPTEMBER2025
The tariff "BUS-PANELP-12M-FIXED-SEPTEMBER2025" associated with your Electricity meter is not in an expected format. Click on 'Learn More' with instructions on what to do next.

### Reproduction steps

adding my account information

### Expected behaviour

the intergration to load

### Integration Version

8.5.1

### Home Assistant Version

11.1

### Fresh Install?

Not specified

### Home Assistant Logs

n/a

**Comment by BottlecapDave** [comment]
Hi. Sorry you're having issues. I assume you were part of a company that got acquired by Octopus?

**Comment by jaishkp** [comment]
Hi thanks for the quick reply. No we took the the contract out with octopus. It is a business tariff though is that the problem? 
Also we’re on 3 phase, I don’t know if that makes a difference?

**Comment by BottlecapDave** [comment]
Unfortunately business tariffs don't seem to be available via the APIs that I use nor do they look like they follow the standard convention. So at the moment, it looks like the integration can't support business tariffs I'm afraid.

**Comment by jaishkp** [comment]
That’s a shame, thanks for looking into it.
