### ISSUE TITLE
Unit of Measurement not saving when changed

### ISSUE THREAD

**Issue by FuturamaPhill** [BottlecapDave/HomeAssistant-OctopusEnergy#516]
### Describe the bug

When changing the unit of measurement field for the "current_demand" entity it does not save the state. 

I am trying to change it from W to kW so I can add this sensor into the Home assistant energy dashboard. 

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/39866073/1a35ee41-b6be-4f80-a2bb-50d69a3be48e)

This is the entity that was added after connecting my HomeMini from Octopus

### Reproduction steps

Go into the octoups energy integration, select the devices, select the Electricity Meter, select the current demand sensor, click the cog wheel icon, click the drop down for "Unit of Measuremeant" and change to kW, click update. 

Nothing happens. 

### Expected behaviour

Unit of Measurement should change to kW

### Integration Version

8.5.1

### Home Assistant Version

2023.10.4

### Fresh Install?

Not specified

### Home Assistant Logs

[home-assistant_octopus_energy_2023-11-06T08-40-47.329Z.log](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/13264421/home-assistant_octopus_energy_2023-11-06T08-40-47.329Z.log)

**Comment by BottlecapDave** [comment]
Hello and sorry for the lack of update. However, this should now be fixed in the latest release (v9.0.0).
