### ISSUE TITLE
Ability to add 2nd, 3rd electric tariff  

### ISSUE THREAD

**Issue by alfwro13** [BottlecapDave/HomeAssistant-OctopusEnergy#520]
**Describe the feature**

It would be very useful to have the ability to add more than 1 tariff where the first is the real-deal (i.e. the actual tariff) and the others are simulated (using tariff code). That would be very useful for comparison and answering questions such as would I be better off on i.e. Octopus Agile or Octopus Economy 7 variable  then on my current Flux.

And yes that is currently all possible with whole bunch of helpers, utility meters and rest sensors pulling Agile pricing but it would be so much better if it all was in one place.

**Comment by BottlecapDave** [comment]
This already exists in the form of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/entities/electricity.md#tariff-overrides. There is currently no plans to add the ability for further overrides.
