### ISSUE TITLE
Current Demand (Octopus Mini) - Cannot use within the Energy Dashboard

### ISSUE THREAD

**Issue by owenashurst** [BottlecapDave/HomeAssistant-OctopusEnergy#536]
### Describe the bug

The Current Demand sensor for Octopus Mini's cannot be used within the Energy Dashboard as a "Consumed Energy" option. I can use the Current Accumulative Consumption but that's the overall total consumption and not the real time demand which is what we need for the dashboard to show how much we're currently using at the given time.

![Screenshot 2023-11-16 202225](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/4403436/5dc178a1-31fb-4e0f-90ce-4687fefe53e0)

### Reproduction steps

1. Enter the settings for the Energy Dashboard
2. Under Electricity Grid -> Grid Consumption, click on Add Consumption
3. Observe how you cannot find/select "Current Demand" from the sensor list

### Expected behaviour

I expect to be able to select the Current Demand sensor for my Consumed Energy option so I can see in real-time how much power I am current consuming.

The dropdown offers a documentation page for missing entities:

https://www.home-assistant.io/docs/energy/faq/#troubleshooting-missing-entities

### Integration Version

Latest

### Home Assistant Version

Latest

### Fresh Install?

Not specified

### Home Assistant Logs

N/A

**Comment by BottlecapDave** [comment]
Hi there. You can use the total accumulative consumption sensor as per https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/energy_dashboard.md#current-consumption. The data is updated at the same rate as the demand sensor and is in the correct unit of measurement as reported by OE. The HA dashboard isn't built for displaying real time data.

**Comment by owenashurst** [comment]
> Hi there. You can use the total accumulative consumption sensor as per https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/energy_dashboard.md#current-consumption. The data is updated at the same rate as the demand sensor and is in the correct unit of measurement as reported by OE. The HA dashboard isn't built for displaying real time data.

Ah, so the energy dashboard is meant to be a total of the energy consumption for the current day?

**Comment by BottlecapDave** [comment]
It's meant to give you historic and semi realtime information. It builds up the data for the current day every hour.

If you look at the current accumulative consumption sensors history you can see the data go up gradually every minute when the data is retrieved and recalculated. If you want "relative", you can plot this data on a graph on your normal dashboard

**Comment by BottlecapDave** [comment]
Closing as demand sensor is not supported by energy dashboard due to unit of measurement not supported by HA.
