### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by fboundy** [BottlecapDave/HomeAssistant-OctopusEnergy#539]
### Describe the bug

I'm setting up HA on a new machine. I installed 8.5.2 but the events were missing until I rolled back to 8.5.1

My recollection was that the "rates" attribute had moved to the event entities with 8.4.0 but I don't have them on the new machine. The "all_rates" attribute is still there in the "current_rate" sensor entity.

### Reproduction steps

Rolled back from 8.5.2 to 8.5.1 so both machines on the same version

### Expected behaviour

Expected to have "event" entities but they aren't there in 8.5.2 they are in 8.5.1

### Integration Version

8.5.2

### Home Assistant Version

2023.11.2

### Fresh Install?

Fresh install

### Home Assistant Logs

N/A

**Comment by BottlecapDave** [comment]
Hi. I'm not sure how this is happening, as [nothing has changed](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/compare/v8.5.1...v8.5.2) between those two releases that would have seen that behaviour. The event entities are disabled by default, which could have explained you couldn't see them, but this behaviour was in both versions you specified. Do you see any errors in your logs?

**Comment by fboundy** [comment]
Hi Dave

Events came back when I rolled back to 8.5.1 from 8.5.2.  Was late so will investigate further today.

**Comment by fboundy** [comment]
Re-installed everything with the benefit of sleep and coffee and all is as I expected. Very odd - it was as if I'd gone back in time.
