### ISSUE TITLE
Standing Charge

### ISSUE THREAD

**Issue by liamstears** [BottlecapDave/HomeAssistant-OctopusEnergy#54]
This is a feature request rather than a bug report/issue

I find this integration very helpful for getting my charge rates from Octopus directly however I think its a massive shame that this integration doesn't pull through standing charge rates too

Is there a way standing charge rates for both gas and electricity could be added and pulled through too?

Thanks in advance

**Comment by liamstears** [comment]
My mistake, this imformation is provided just not where I expected it to be, thanks

**Comment by Alllfff** [comment]
> My mistake, this imformation is provided just not where I expected it to be, thanks

Where did you find the info? Thanks
