### ISSUE TITLE
Home Mini setting intermittently forgotten

### ISSUE THREAD

**Issue by jwardle** [BottlecapDave/HomeAssistant-OctopusEnergy#540]
### Describe the bug

I’ve recently been sent a Home Mini device, and have therefore updated my OE integration to tick the box indicating I have one. The real time data flows through as expected usually, however every now and then the integration appears to forget that I have ticked the Home Mini box on the integrations configure view. This results in the home mini related data/entities being disabled when it happens, and I have to go back into the OE integration configuration and tick the Home Mini box again. I usually have to do this every couple of days. 

### Reproduction steps

Install OE integration.
Tick “I have a Home Mini” box during setup.

### Expected behaviour

Home Mini box and therefore entities related to Home Mini remain active without manual intervention

### Integration Version

8.5.2

### Home Assistant Version

2023.11.2

### Fresh Install?

After upgrading

### Home Assistant Logs

None reported in HA logs for OE integration

**Comment by BottlecapDave** [comment]
Hi, I'm not sure why you would be seeing this behaviour. When you go back into the configuration, is the home mini checkbox already ticked, and you have to untick and tick? Or is it unticked when you have previously ticked it?

The fact the entities are in a disabled state, instead of missing, suggests this is a HA level thing. Have you got any errors in your logs?

**Comment by jwardle** [comment]
Hi @BottlecapDave, sorry, should have mentioned when I return to the configure view of OE, the Home Mini box is **not** ticked. I have to tick it again and submit. When I mention the Home Mini related entities are disabled they are actually missing as you said, and no longer exposed by the OE integration. I was looking at the dependent cards that used the entities, rather than the entities themselves at the time.

The only logs I can see for OE are related to delays in fetching data, or record size exceeding limits, e.g.:

```2023-11-18 06:26:01.037 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.octopus_energy_electricity_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-11-18 06:26:01.039 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.octopus_energy_gas_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-11-18 06:26:02.091 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.octopus_energy_electricity_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-11-18 06:26:02.112 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.octopus_energy_gas_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-11-18 06:30:10.967 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.octopus_energy_electricity_current_rate (None) cannot be converted to the unit of previously compiled statistics (GBP/kWh). Generation of long term statistics will be suppressed unless the unit changes back to GBP/kWh or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-11-18 06:30:10.968 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.octopus_energy_gas_current_rate (None) cannot be converted to the unit of previously compiled statistics (GBP/kWh). Generation of long term statistics will be suppressed unless the unit changes back to GBP/kWh or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this```

**Comment by BottlecapDave** [comment]
The related warnings shouldn't effect this. Very odd that the box isn't ticked though, as nothing but the HA frontend changes that config. There should be a record within `.storage/core.config_entries` in the configuration of your HA instance. One of them should have the domain `octopus_energy` and the title `Account`. If you can grab and paste the contents in here (with sensitive data removed), it might shine a light on what's happening. I'm not sure though what could be causing this (a bug in HA? another integration?)

**Comment by jwardle** [comment]
Heres the entry:
```{
        "entry_id": "2c370705c82f24e0481c33e38b8a874b",
        "version": 2,
        "domain": "octopus_energy",
        "title": "Account",
        "data": {
          "Api key": "XXXXXXXXXX",
          "Account Id": "XXXXXXX",
          "supports_live_consumption": false,
          "live_consumption_refresh_in_minutes": 1,
          "calorific_value": 38.8,
          "kind": "account",
          "live_electricity_consumption_refresh_in_minutes": 1,
          "live_gas_consumption_refresh_in_minutes": 1
        }```
        
Could it be there `supports_live_consumption` flag being false? I saw in the release notes that a check for Home Mini support was added recently. Could it be this check that is reverting the configuration I am providing? We do have a Home Mini, and the near real time data is flowing through both the OE app and this integration (when it works).

**Comment by BottlecapDave** [comment]
Is there's no `options` section within that bit of JSON? This is where any updates to the initial configuration are stored (and used to replace the initial values). The additional checks only occur when the integration is initially loaded (or reloaded), and wouldn't effect the underlying configuration values, nor would the check remove entities during use.

**Comment by jwardle** [comment]
Sorry, there was and I prematurely snipped the braces. Comment updated.

**Comment by BottlecapDave** [comment]
hmm yeah those options all look as expected. If you look at the [entities](https://my.home-assistant.io/redirect/integration/?domain=octopus_energy) associated with the integration, do you see the missing entities but with numberic suffixes (e.g. `sensor.octopus_energy_electricity_{{METER_SERIAL_NUMBER}}_{{MPAN_NUMBER}}_current_consumption_2`)?

**Comment by jwardle** [comment]
No I don’t. It doesn’t appear as if they’ve been recreated and new IDs assigned, just activated/inactive.

I’ve edited the file and set the “supports_live_consumption” to true within the data element to see if that works. Will see in a couple of days if it holds.

**Comment by BottlecapDave** [comment]
Whenever you update via the UI, the `supports_live_consumption` value should update within the `options` block, but the `data` block will stay at your initial value. The fact it still states (unless you updated before supplying the result), means that the config isn't changing. This can be confirmed by just reloading the integration if it happens again to see the sensors come back.
