### ISSUE TITLE
Updated to new version 9.0.0 now get no rates chart

### ISSUE THREAD

**Issue by UK-JustinSmall** [BottlecapDave/HomeAssistant-OctopusEnergy#547]
### Describe the bug

getting the following after updating to v9.0.0 and restarting home assistant

![Snag_9323f](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/129121587/82540853-398f-4a36-86e0-df53f06e9b89)

### Reproduction steps

Updated to version 9.0.0

### Expected behaviour

no change to rates charts for Octopus Agile import and export

### Tariff Code

 E-1R-AGILE-FLEX-22-11-25-E

### Integration Version

9.0.0

### Home Assistant Version

Core 2023.11.2

### Fresh Install?

Not specified

### Home Assistant Logs

Not relevant

**Comment by BottlecapDave** [comment]
Hello. This is due to the breaking changes that were outlined in this release, and proposed a month ago. The developer of that card hasn't got round to updating the integration. Any issues with that card should be raised or highlighted on their GitHub.
