### ISSUE TITLE
Version 9.0.0 - detailed energy rates are missing

### ISSUE THREAD

**Issue by springfall2008** [BottlecapDave/HomeAssistant-OctopusEnergy#548]
### Describe the bug

I understood from the deprecation notice that the rate information would be split between previous_rates, current_rates and next_rates but that doesn't seem to be the case. I can't find the half-hourly data for Agile anymore, I need the next 24-48 hours of rates for Predbat?

### Reproduction steps

Install v9.0.0 and look at the sensors

### Expected behaviour

I was expecting the next 24-48 hours of rates to be in the next_rates sensor

### Integration Version

9.0.0

### Home Assistant Version

na

### Fresh Install?

After upgrading

### Home Assistant Logs

na

**Comment by BottlecapDave** [comment]
The data is available in the event entities that were introduced last release. The old all rates information is now spread across the three event entities. Below is an example of one of the sensors with the rate information. The events might take up to 30 mins to populate once enabled for the first time as they'll be waiting for the events to fire to get the data.

As mentioned in the deprecation notice this was to get rid of the warning that many people complained about.

![Screenshot_20231121-085901](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/14993950/94c0bae9-e083-4246-82cc-f09f1c0c4718)

**Comment by Daverover66** [comment]
I have just updated from HA 2023.11.1 to HA 2023.11.2 as well as updating Octopus from previous version to v9.0.0 and none of my entities are there at all. I got this in the logs when HA restarted.

```
Logger: homeassistant.config_entries
Source: config_entries.py:557
First occurred: 09:02:19 (1 occurrences)
Last logged: 09:02:19

Error unloading entry A-E0D4DE23 for sensor
Traceback (most recent call last):
  File "/config/custom_components/octopus_energy/gas/__init__.py", line 63, in calculate_gas_consumption_and_cost
    rate = next(r for r in rate_data if r["start"] == consumption_from and r["end"] == consumption_to)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 557, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 136, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in async_unload_entry
    await platform.async_reset()
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 766, in async_reset
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1046, in async_remove
    await self.async_internal_will_remove_from_hass()
  File "/usr/src/homeassistant/homeassistant/helpers/restore_state.py", line 319, in async_internal_will_remove_from_hass
    self.entity_id, self.extra_restore_state_data
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 891, in extra_restore_state_data
    return SensorExtraStoredData(self.native_value, self.native_unit_of_measurement)
                                 ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/gas/current_accumulative_consumption.py", line 88, in native_value
    consumption_and_cost = calculate_gas_consumption_and_cost(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/gas/__init__.py", line 65, in calculate_gas_consumption_and_cost
    raise Exception(f"Failed to find rate for consumption between {consumption_from} and {consumption_to} for tariff {tariff_code}")
Exception: Failed to find rate for consumption between 2023-11-21 00:00:00+00:00 and 2023-11-21 00:30:00+00:00 for tariff G-1R-SILVER-FLEX-22-11-25-N
```

Entities are now all unavailable for all 3 of my meters, Import, Export and gas.  I have tried numerous reloads and reconfigures of the integration and still nothing.  Everything was working okay before the update.

**Comment by Daverover66** [comment]
"The events might take up to 30 mins to populate once enabled for the first time as they'll be waiting for the events to fire to get the data."

Are these events enabled automatically or do we need to do something?  I'm currently waiting patiently for something to appear after updating to v9.0.0.

Everything else is there except for these events.

The docs say  "This is fired when the current day rates are updated".  Is this the daily update or do they update every half hour when the rate changes?

**Comment by BottlecapDave** [comment]
As per the [docs](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/entities/electricity.md#current-day-rates), the entities that listen for the events are disabled by default. Once enabled, they will display the rate information in the attributes. I will enable these by default in the next release.

The previous, current and next day events should fire every 30 minutes as long as the OE APIs are actually responding. The events should fire regardless of if the entities are enabled, but as nothing is listening for them then they won't appear in the list in the dev tools.

**Comment by Daverover66** [comment]
> As per the [docs](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/entities/electricity.md#current-day-rates), the entities that listen for the events are disabled by default. Once enabled, they will display the rate information in the attributes. I will enable these by default in the next release.
> 
Ah right.  I must have missed that bit in the docs thanks.  I did actually spot that the events were disabled so I enabled them all and now they are there.

However, the entities don't populate the `custom:octopus-energy-rates-card` or the `entity` field in my Apexcharts card?

Not sure if you can suggest a way around that as I suspect it's just a case of those cards not seeing the `rates` attribute.

I'll raise an issue with the card owners if there's no other workaround.  Thanks

**Comment by Daverover66** [comment]
> Apex charts need to be updated. Please see the community section in the docs for updated examples.

Seen and updated thank you.

**Comment by BottlecapDave** [comment]
Closing as the original issue should now be resolved.
