### ISSUE TITLE
Octoplus entities missing in Devices&Services/Octopus Energy

### ISSUE THREAD

**Issue by alfwro13** [BottlecapDave/HomeAssistant-OctopusEnergy#549]
### Describe the bug

I have upgraded to the latest version I have noticed that I can only see the Octoplus entities in the Developer Tools --> States when I specifically look for them by name but when I go to i.e. Devices & Services --> Octopus Energy integration they are nowhere to be seen. 
I'm not sure if that is a bug or it is simply how it was designed?

### Reproduction steps

Open  Devices & Services --> Octopus Energy then browse to Electric Meter and try to find the Saving Session or wheel of fortune entities

### Expected behaviour

saving session entities should be listed with other electric meter entities
wheel of fortune should be listed in both gas and electric meters with all the other entities

### Integration Version

9

### Home Assistant Version

2023.11.2

### Fresh Install?

After upgrading

### Home Assistant Logs

n/a

**Comment by BottlecapDave** [comment]
Hello. This is not how home assistant works. An entity can only belong to one or zero devices. These entities are at an account level and not tied to any particular meter, so are not associated as such. This is by design.

**Comment by BottlecapDave** [comment]
I should add that from the main integration screen, they'll be visible via the entities link either at the high level or associated with the account entry
