### ISSUE TITLE
ValueError since 9.0.0

### ISSUE THREAD

**Issue by fredtj** [BottlecapDave/HomeAssistant-OctopusEnergy#550]
### Describe the bug

Haven't yet checked the UI, but my Home Assistant log is being spammed with the below since upgrading to 9.0.0:

```
homeassistant                      | 2023-11-21 15:23:28.674 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
homeassistant                      | Traceback (most recent call last):
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 616, in state
homeassistant                      |     numerical_value = int(value)
homeassistant                      |                       ^^^^^^^^^^
homeassistant                      | ValueError: invalid literal for int() with base 10: 'unknown'
homeassistant                      | 
homeassistant                      | During handling of the above exception, another exception occurred:
homeassistant                      | 
homeassistant                      | Traceback (most recent call last):
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 619, in state
homeassistant                      |     numerical_value = float(value)
homeassistant                      |                       ^^^^^^^^^^^^
homeassistant                      | ValueError: could not convert string to float: 'unknown'
homeassistant                      | 
homeassistant                      | The above exception was the direct cause of the following exception:
homeassistant                      | 
homeassistant                      | Traceback (most recent call last):
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
homeassistant                      |     await self._async_refresh(log_failures=True, scheduled=True)
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
homeassistant                      |     self.async_update_listeners()
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
homeassistant                      |     update_callback()
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
homeassistant                      |     self.async_write_ha_state()
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
homeassistant                      |     self._async_write_ha_state()
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
homeassistant                      |     state, attr = self._async_generate_attributes()
homeassistant                      |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in _async_generate_attributes
homeassistant                      |     state = self._stringify_state(available)
homeassistant                      |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 749, in _stringify_state
homeassistant                      |     if (state := self.state) is None:
homeassistant                      |                  ^^^^^^^^^^
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 623, in state
homeassistant                      |     raise ValueError(
homeassistant                      | ValueError: Sensor sensor.octopus_energy_gas_e6s07830951656_1474688906_previous_accumulative_consumption_kwh has device class 'energy', state class 'total' unit 'kWh' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' (<class 'str'>)
```

Let me know if you need any further information.

Regards

### Reproduction steps

None

### Expected behaviour

No Error

### Integration Version

9.0.0

### Home Assistant Version

2023.11.2

### Fresh Install?

After upgrading

### Home Assistant Logs

homeassistant                      | 2023-11-21 15:23:28.674 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
homeassistant                      | Traceback (most recent call last):
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 616, in state
homeassistant                      |     numerical_value = int(value)
homeassistant                      |                       ^^^^^^^^^^
homeassistant                      | ValueError: invalid literal for int() with base 10: 'unknown'
homeassistant                      | 
homeassistant                      | During handling of the above exception, another exception occurred:
homeassistant                      | 
homeassistant                      | Traceback (most recent call last):
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 619, in state
homeassistant                      |     numerical_value = float(value)
homeassistant                      |                       ^^^^^^^^^^^^
homeassistant                      | ValueError: could not convert string to float: 'unknown'
homeassistant                      | 
homeassistant                      | The above exception was the direct cause of the following exception:
homeassistant                      | 
homeassistant                      | Traceback (most recent call last):
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
homeassistant                      |     await self._async_refresh(log_failures=True, scheduled=True)
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
homeassistant                      |     self.async_update_listeners()
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
homeassistant                      |     update_callback()
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
homeassistant                      |     self.async_write_ha_state()
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
homeassistant                      |     self._async_write_ha_state()
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
homeassistant                      |     state, attr = self._async_generate_attributes()
homeassistant                      |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in _async_generate_attributes
homeassistant                      |     state = self._stringify_state(available)
homeassistant                      |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 749, in _stringify_state
homeassistant                      |     if (state := self.state) is None:
homeassistant                      |                  ^^^^^^^^^^
homeassistant                      |   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 623, in state
homeassistant                      |     raise ValueError(
homeassistant                      | ValueError: Sensor sensor.octopus_energy_gas_e6s07830951656_1474688906_previous_accumulative_consumption_kwh has device class 'energy', state class 'total' unit 'kWh' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' (<class 'str'>)

**Comment by willenic** [comment]
I also am getting the state of my electricity consumption entity as unknown which is obviously throwing off the energy dashboard. I didn't have any issues on v8.5.2 and the energy dashboard shows tiny or negative values from the point I upgraded yesterday.

**Comment by BottlecapDave** [comment]
@willenic are you seeing the errors that have been highlighted or just oddities in the dashboard?

**Comment by fredtj** [comment]
Apologies, I'm not actually sure if there were issues, but the log certainly didn't contain those messages.
Happy to clear out the data completely if required, I haven't started using the integration to it's fullest as yet (I'm on the waiting list for a Mini), but I thought I would set it up and get it ingesting data anyway.

**Comment by BottlecapDave** [comment]
@fredtj  No I think there's something wrong. I assume you're still getting the errors? Are you comfortable checking the restore_state config under .storage and pasting the value of the offending entities here? I think something has gone wrong with the restore state but want to confirm what so I can try and recreate it locally.

**Comment by fredtj** [comment]
Yes, they're occurring every 60 seconds at the moment.

core.restore_state:
```
    {
      "state": {
        "entity_id": "sensor.octopus_energy_gas_e6s07830951656_1474688906_previous_accumulative_consumption_kwh",
        "state": "unknown",
        "attributes": {
          "state_class": "total",
          "mprn": "1474688906",
          "serial_number": "E6S07830951656",
          "unit_of_measurement": "kWh",
          "device_class": "energy",
          "icon": "mdi:lightning-bolt",
          "friendly_name": "Gas E6S07830951656 1474688906 Previous Accumulative Consumption (kWh)"
        },
        "last_changed": "2023-11-19T10:53:46.716026+00:00",
        "last_updated": "2023-11-19T10:53:46.716026+00:00",
        "context": {
          "id": "01HFKKE3AWAVDJX69JDD9H403C",
          "parent_id": null,
          "user_id": null
        }
      },
      "extra_data": {
        "native_value": null,
        "native_unit_of_measurement": null
      },
      "last_seen": "2023-11-20T20:16:05.167048+00:00"
    },
```
```

**Comment by fredtj** [comment]
The date in last_seen is just 2 minutes before I upgraded to 9.0.0.

**Comment by willenic** [comment]
> @willenic are you seeing the errors that have been highlighted or just oddities in the dashboard?

Haven't had a chance to check I just saw something was up on the dashboard then had a quick look at the entity. It's being evaluated but the state was shown as unknown. Had to shoot out the door to work and I don't have remote access.
![IMG_20231122_080603](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/144794340/8f3c23de-4a2c-474a-84b4-4fd8be298acf)

**Comment by BottlecapDave** [comment]
Thanks for that - confirms my suspicions, I just need to work out how to confirm locally. The inclusion of last updated timestamp and last evaluated is a bug, which I'll also fix.

**Comment by willenic** [comment]
Just checked my logs, nothing other than 

`2023-11-22 18:15:55.860 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.octopus_meter_offpeak (kWh) cannot be converted to the unit of previously compiled statistics (None).`

**Comment by BottlecapDave** [comment]
I've released 9.0.1, which will hopefully resolve this error (I found it difficult to replicate locally).

**Comment by fredtj** [comment]
Thank you for your quick work! I can confirm the error message in the 1st post is no longer shown. 

I am however seeing a further error:

```
home-assistant     | 2023-11-22 21:05:10.303 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.octopus_energy_electricity_z16qk00566_1610022814187_current_rate (GBP/kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
home-assistant     | 2023-11-22 21:05:10.303 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.octopus_energy_gas_e6s07830951656_1474688906_current_rate (GBP/kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
```

Not sure on the frequency of this one, but it certainly isn't every minute.

**Comment by DaveK-Rocketmakers** [comment]
Those warnings are already known and existed before v9. I'm still trying to diagnose why they've started appearing, but I'm not receiving them. I believe they should go away after the next reload once the rate sensors stop recording the rates as attributes.

**Comment by DaveK-Rocketmakers** [comment]
But glad that the suspicion was correct and the original error has been fixed :)

**Comment by BottlecapDave** [comment]
Glad the original issue has been fixed. Those warnings are already known and existed before v9. I'm still trying to diagnose why they started appearing, but I'm also not receiving them locally anymore. I believe they should go away after the next reload once the rate sensors stop recording the rates as attributes. If not, you can follow the link specified to "fix" the statistics.

**Comment by fredtj** [comment]
Excellent, thank you!
