### ISSUE TITLE
Rates no longer display in https://github.com/lozzd/octopus-energy-rates-card

### ISSUE THREAD

**Issue by AGLAISTER** [BottlecapDave/HomeAssistant-OctopusEnergy#551]
### Describe the bug

Since the update to v9.0.0 I can no longer get rates to display using https://github.com/lozzd/octopus-energy-rates-card
I have tried both 
event.octopus_energy_electricity_22e5189315_1100022748419_current_day_rates
and the old 
sensor.octopus_energy_electricity_22e5189315_1100022748419_current_rate which when you click on the sensor shows the expected progression of rates 
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/141528175/06d0bab5-1cd9-4c25-b6cd-4a7fa4ae9acb)

### Reproduction steps

Open up Home assistant dashboard
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/141528175/91f9875c-ac90-4023-9095-7ea10202f970)
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/141528175/9591c79c-112c-471e-bc18-9544ba9790e6)

### Expected behaviour

Rates show correctly

### Integration Version

9.0.0

### Home Assistant Version

2023.11.2

### Fresh Install?

After upgrading

### Home Assistant Logs

No logs provided

**Comment by BottlecapDave** [comment]
Hello. Unfortunately, that is not within the scope of this integration. I believe someone is working on some fixes based on this ticket https://github.com/lozzd/octopus-energy-rates-card/issues/27
