### ISSUE TITLE
Target binary sensor re-evaluates immediatley if the entity is "viewed" since 9.0.0

### ISSUE THREAD

**Issue by TransientWolf** [BottlecapDave/HomeAssistant-OctopusEnergy#554]
### Describe the bug

Have an intermittent sensor set to run at 9pm to identify 10 lowest agile rates between then and 9pm following day.  On previous version I could look at the binary sensor entity and look at the attributes and it would tell me the times it had selected and switch on and off at the appropriate times.  Now if I look directly at the entity in any way it re-assesses  and updates all the times - so if I look at say 11am it then selects all the remaining time periods until 9pm.  The attributes "Last evaluated" shows the current time (ie the time I viewed the entity).  

### Reproduction steps

Set a target sensor and let it evaluate.  Go back later and view the binary sensor in entities and look at attributes and it reevaluates.

### Expected behaviour

The sensor runs at 9pm and selects for the following day and does not re-evaluate until 9pm again the following day.  When I view the entity it reports the selected hours and does not reevaluate first. 

### Integration Version

9.0.0

### Home Assistant Version

2023.11.2

### Fresh Install?

After upgrading

### Home Assistant Logs

.

**Comment by BottlecapDave** [comment]
Hi. Yeah the evaluation has always occured every minute, but the target rate evaluation attribute is what you're after to see if the target times have changed. This was added as some people reported the binary sensor not turning on/off at the right times and this was to try and establish when it was last evaluated.
