### ISSUE TITLE
Being spammed??

### ISSUE THREAD

**Issue by jonathh21** [BottlecapDave/HomeAssistant-OctopusEnergy#556]
### Describe the bug

Since I upgraded today to the latest, my automations that fire on octopus state like new rates are firing every few seconds.

As I have about 5 or 6 automations that fire (including notifications) I have 5 or 6 messages landing every few seconds.

Have a missed something in the docs?

Thanks 

### Reproduction steps

Create a trigger on state or octopus device 

### Expected behaviour

Fire when something material changes.

### Integration Version

Latest 

### Home Assistant Version

2023.11.3

### Fresh Install?

After upgrading

### Home Assistant Logs

Na

**Comment by jonathh21** [comment]
Ps looking at the from/to state data the last evaluated is changing every second or so

**Comment by BottlecapDave** [comment]
Hello. Nothing has changed around the frequency of updates out of the box in the latest release and has always been set to evaluate every minute.

However, with the introduction of the new `last_evaluated` attribute, it looks like HA triggers automations if state or attributes change using the standard state trigger with no from/to. 

I'm seeing my automations trigger every minute not every few seconds like you are seeing.

If you are wishing to [ignore attribute changes](https://www.home-assistant.io/docs/automation/trigger/#state-trigger), you need to set a `to` restriction to `null`. If you use the UI, then you can set the `to` to `Any state (ignore attribute changes)`.

**Comment by jonathh21** [comment]
Yeah so I have 3 automations that fired on ANY state change.

The change as you suggested has calmed them down.

Thanks

**Comment by jonathh21** [comment]
As in like massive amounts of thanks (posted the last one whilst making dinner!)

**Comment by BottlecapDave** [comment]
No problem. Glad it's calmed down.
