### ISSUE TITLE
Current consumption sensor goes negative in energy dashboard

### ISSUE THREAD

**Issue by BottlecapDave** [BottlecapDave/HomeAssistant-OctopusEnergy#558]
### Discussed in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/discussions/553

<div type='discussions-op-text'>

<sup>Originally posted by **MrLemur** November 21, 2023</sup>
I am using the `current_consumption` sensors for both electric and gas. Since updating to v9.0, I get the following charts:
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/17055328/34fa568c-8ea9-4277-9eec-f00640708847)
For reference, this was from yesterday before the update:
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/17055328/92039f31-3e40-4888-8f9f-b9a70f1554e8)

Could this be due to the change to events in the new release?</div>

**Comment by GTunney** [comment]
Just like to say I am also seeing the same issue.

**Comment by malballuk1** [comment]
I have the same issue, as well as no energy incoming or gas readings

![Energy](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/151915692/984e9387-1a88-44b5-9471-4be51a4cbb1c)

**Comment by btrudgill** [comment]
Yep, I am also having the same issue.

**Comment by googanhiem** [comment]
In the same boat, it seems like the numbers are correct.  I did notice a lot of trailing rounding but it could of been like that previously (0.0078 is now 0.007800000454), but don't know why that would confuse the dashboard.

Also, not sure if this is a integration problem or a home assistant change (I update both at the same time).

**Comment by tigattack** [comment]
I'm also seeing this issue. I have a Home Mini too, if that helps at all.

**Comment by thorrrr** [comment]
HI 
Yes  have Home Mini and also no pricing showing 
https://i.imgur.com/MxIZHTh.png

**Comment by BottlecapDave** [comment]
I think I've found the issue. For some reason HA isn't updating the last reset field. Out of interest for the costs @thorrrr do you use the current rate to calculate the price?

**Comment by malballuk1** [comment]
> I think I've found the issue. For some reason HA isn't updating the last reset field, despite me setting it. Just testing the fix. Out of interest for the costs @thorrrr do you use the current rate to calculate the price?

**Comment by thorrrr** [comment]
> I think I've found the issue. For some reason HA isn't updating the last reset field, despite me setting it. Just testing the fix. Out of interest for the costs @thorrrr do you use the current rate to calculate the price?

I am using current consumption

**Comment by malballuk1** [comment]
I can confirm I am using current consumption

**Comment by BottlecapDave** [comment]
What I meant was are you using the current rate to calculate the cost (as you said no price was showing)

**Comment by btrudgill** [comment]
I use the current rate (in p/kwh) to calculate the cost, as I have a dual rate tarrif (octopus intelligent).

I have the same issues as everyone else.

**Comment by thorrrr** [comment]
Hi
It’s been working correctly for months I made no changes not even touched it?!
After update earlier this week I have lost everything I just added the settings from the docs for people with a mini

**Comment by BottlecapDave** [comment]
I've already acknowledged there's an issue from the last update, which was introduced by enabling other HA functionality and there being what looks like a big in the HA implementation.

I only asked a simple question because you can configure the energy dashboard in a number of ways and wanted to make sure there wasn't another underlying issue relating to the calculations of costs.

If it's causing a huge inconvenience, you always have the option of reverting to a previous version until the issue has been resolved.

**Comment by thorrrr** [comment]
Sorry misread I am using use current entity to work out pricing

**Comment by stuartoram** [comment]
FWIW, I'm using current consumption for both electric & gas import meters and seem to only be seeing this issue with gas current consumption.

**Comment by BottlecapDave** [comment]
This fix should now be available in the latest release (v9.0.2). It might take up to 24 hours for everything to stablise due to how the energy dashboard processes data.

**Comment by btrudgill** [comment]
Nice work, thanks for the quick fix

**Comment by thorrrr** [comment]
> This fix should now be available in the latest release (v9.0.2). It might take up to 24 hours for everything to stablise due to how the energy dashboard processes data.

How long does it take to show up in HA

**Comment by btrudgill** [comment]
It’s already in HA. I had a notification in HACS to update to 9.0.1 (after I downgraded), once that was updated I had the notification to update to 9.0.2

**Comment by malballuk1** [comment]
Not showing up for me at the moment

**Comment by BottlecapDave** [comment]
According to the docs, HACS will look every 3 days https://hacs.xyz/docs/basic/updates/, but you can force an update if you go into HACS directly.

**Comment by malballuk1** [comment]
Thanks, got it now, just a waiting game now I assume to get correct figures

Mal

**Comment by BottlecapDave** [comment]
The consumption should start showing on the hour. Cost will probably be negative today. By the end of tomorrow it should be reporting correctly.

**Comment by btrudgill** [comment]
Can confirm, having had the update for a few hours that the consumption graph is starting to look sensible.

**Comment by malballuk1** [comment]
Yes me too

**Comment by stuartoram** [comment]
This still seems to be an issue for me. After updating on Saturday, I got a positive 'spike' in the data at midnight on Sunday and at midnight today I was back to a negative value. 
Anyone else/any suggestions?

**Comment by BottlecapDave** [comment]
Is the octopus app/dashboard stating the correct data? Is the accumulative consumption sensor giving you correct readings? Have you restarted your ha instance after updating the integration?

**Comment by stuartoram** [comment]
> Is the octopus app/dashboard stating the correct data? Is the accumulative consumption sensor giving you correct readings? Have you restarted your ha instance after updating the integration?

Yes to all of those...

**Comment by BottlecapDave** [comment]
Is the last evaluated attribute on the entity updating every minute? Doe hmyou have any errors in your logs?

**Comment by stuartoram** [comment]
I have the refresh rate set to 5 mins for elec & 30 mins for gas and it's evaluating as per that (do you think the latter could be an issue? I set this to avoid hitting the API rate limit as I do use some other API queries outside HA occasionally, especially since gas only provides 30 min readings anyway)
Checked the logs, there are a couple of issues but nothing that appears relevant based on the message and/or timing.

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/88890495/27bc5e40-9aa5-4ee8-b432-23051969e793)
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/88890495/3673cc1a-f370-4955-8418-3509d1e8be68)
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/88890495/b88a202b-07aa-40bb-8a94-1e14c9c8ad5e)
