### ISSUE TITLE
Current Gas Demand (Octopus Mini) - Cannot use within the Energy Dashboard 

### ISSUE THREAD

**Issue by Trickytree1984** [BottlecapDave/HomeAssistant-OctopusEnergy#564]
### Describe the bug

I am using the octopus mini. I have the electricity in the dashboard but I do not have the ability to use gas in the energy dashboard. The only entity that is in m3 (the unit needed in the dashboard), is energy_gas_xxxxxx_xxxxxx_previous_accumulative_consumption. Following the docs, I need energy_gas_xxxxxx_xxxxxx_current_accumulative_consumption. I only have that in kWH, which the energy dashboard does not accept. I can see gas for the day in the octopus app (not in the live view). The KWh usage is updating correctly every 5 mins. I also have Gas xxxxxxx Current Consumption, but only in m3. 

Entities
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/65119891/14429447-2a4b-462a-a8b9-3fba67b4c30f)

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/65119891/1372870a-3942-4be1-87b8-5b86e7d44c89)

### Reproduction steps

N/A

### Expected behaviour

Ability to add to energy dashboard using m3

### Tariff Code

 E-1R-SILVER-FLEX-22-11-25-E

### Integration Version

v9.0.0

### Home Assistant Version

2023.11.3

### Fresh Install?

After upgrading

### Home Assistant Logs

N/A

**Comment by BottlecapDave** [comment]
Hello. Do you have (or have ever had) any other sources specified in the energy dashboard as this will limit future sensors? I've got the option to add kWh based sensors for gas. Based on some HA forum posts it looks like if you ever use M3 then it will force you to only use that.

**Comment by Trickytree1984** [comment]
Thanks for the response. Ah yes I do, I have geo home smart meter integration with m3. Problem is, if I delete that source, I lose all historical data (I disabled the sensors for electric to stop double counting). Looks like I'll have to reset this somehow and work out  how to import the historical data

**Comment by BottlecapDave** [comment]
Theres a ticket to provide an M3 variant, but it's low down on my list. I also have the consistency issue with naming between current and previous sensors when introducing it.

**Comment by Trickytree1984** [comment]
ok thanks i might be able to create a template senor for M3 i suppose.

**Comment by Trickytree1984** [comment]
I used the below template sensor to revers it to m3

sensor:
  - platform: template
    sensors:
      gas_cubic_metres:
        value_template: "{{ (states('sensor.octopus_energy_gas_xxxxxx_xxxxxxx_current_accumulative_consumption') | float * 3.6) / (1.02264 * state_attr('sensor.octopus_energy_gas_xxxxxx_xxxxxxx3_current_accumulative_consumption', 'calorific_value') | float) }}"
        unit_of_measurement: 'm³'

**Comment by Trickytree1984** [comment]
as above

**Comment by BottlecapDave** [comment]
Thanks for sharing the template. I'll try and introduce the sensor at the next major release (but no promises when that'll be)
