### ISSUE TITLE
New current detailed prices not sorted

### ISSUE THREAD

**Issue by njhcarroll** [BottlecapDave/HomeAssistant-OctopusEnergy#566]
### Describe the bug

The new current day rates event is not sorted with last two slots in list being for previous day. 
makes a mes of dashboard rates card. 
eg
  - start: "2023-11-25T21:30:00+00:00"
    end: "2023-11-25T22:00:00+00:00"
    value_inc_vat: 0.235935
    is_capped: false
  - start: "2023-11-25T22:00:00+00:00"
    end: "2023-11-25T22:30:00+00:00"
    value_inc_vat: 0.22491
    is_capped: false
  - start: "2023-11-25T22:30:00+00:00"
    end: "2023-11-25T23:00:00+00:00"
    value_inc_vat: 0.2205
    is_capped: false
  - start: "2023-11-24T23:00:00+00:00"
    end: "2023-11-24T23:30:00+00:00"
    value_inc_vat: 0.22407
    is_capped: false
  - start: "2023-11-24T23:30:00+00:00"
    end: "2023-11-25T00:00:00+00:00"
    value_inc_vat: 0.228165
    is_capped: false
mpan: "1023458287650"
serial_number: 19L3983005
tariff_code: E-1R-AGILE-FLEX-22-11-25-A
friendly_name: Electricity XXxxxx xxxxxx Current Day Rates

### Reproduction steps

Waited 24h for next download. Same issue

### Expected behaviour

Should be in directed order from earliest to latest

### Integration Version

V9.0.2 or latest (can’t see on phone)

### Home Assistant Version

Latest update

### Fresh Install?

After upgrading

### Home Assistant Logs

None

**Comment by BottlecapDave** [comment]
Hello. I haven't personally seen this issue so not sure why tomorrows rates are being included in this sensor (based on your example) and should be in order earliest to latest. I assume you're on an agile tariff?

**Comment by BottlecapDave** [comment]
Ignore the last question, I can see your tariff in the report

**Comment by njhcarroll** [comment]
Hi Yes.  It did seem odd but has repeated over yesterday and today.I’m on an agile tariff.Not sure if this screenshot helps.Best regardsNickOn 24 Nov 2023, at 17:44, David Kendall ***@***.***> wrote:﻿
Hello. I haven't personally seen this issue so not sure why tomorrows rates are being included in this sensor (based on your example) and should be in order earliest to latest. I assume you're on an agile tariff?

**Comment by BottlecapDave** [comment]
I'm failing to recreate this issue locally. I've switched my local instance to your tariff and I'm not seeing what you're seeing (see attached screenshots). Is the timezone/locale of your HA instance set to `(GMT +00:00) London`? Can you post a screenshot of the entities in question from the developer tools?

<img width="500" alt="Screenshot 2023-11-25 102017" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/14993950/0e78452a-91da-4b1f-ac80-eb4d1d1c3412">
<img width="500" alt="Screenshot 2023-11-25 102738" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/14993950/3b243c2c-c80c-481e-b223-24186accb312">

**Comment by njhcarroll** [comment]
I've checked my timezone/locale and it is GMT +00:00 London.

I hope the following screenshots give what you are looking for.  As you can see, I'm still seeing last two days of Saturday at end of current rates

![Pasted Graphic](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/14128500/91e4dca6-cde0-46dc-b435-dc33b1558804)

![Pasted Graphic 1](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/14128500/e36aa11b-7814-4263-bd5a-37d99c3e826b)

**Comment by BottlecapDave** [comment]
That's very odd. What's weirder is your current day rates sensor contained the next day rates (based on the updated timestamp of the sensor). Silly question, I assume you're not firing the `octopus_energy_electricity_currentday_rates` manually anywhere, or using any integrations that are interacting with the sensors?

**Comment by njhcarroll** [comment]
Hi David It’s all very weird. I am using predbat but have inactivated the octopus feed and am using a feed from octopus url for now. The only other connections to the sensors at the moment are 1) from the dashboard agile prices card. 2) in my config.yaml, I have created a sensor to flag negative pricingI’m not firing the rates manually (at least that I know of). I have restarted HA a few times but not sure if that fires a refresh of the rates. Best regardsNickSent from my iPhoneOn 26 Nov 2023, at 10:35, David Kendall ***@***.***> wrote:﻿
That's very odd. What's weirder is your current day rates sensor contained the next day rates (based on the updated timestamp of the sensor). Silly question, I assume you're not firing the octopus_energy_electricity_currentday_rates manually anywhere, or using any integrations that are interacting with the sensors?

**Comment by njhcarroll** [comment]
As you say - can't see how the code should fail but frustratingly, I still get the sort issue for just the current day electricity.  Past and next day are fine as is gas....
Just wondering if the solution could be to deinstall and reinstall?

**Comment by BottlecapDave** [comment]
I've added some additional sorting steps in [v9.1.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v9.1.0) to try and fix your issue. If you could let me know, that would be great :)

**Comment by njhcarroll** [comment]
I deleted my configs, updated to v9.1.0 and happily all sorted!  Many thanks for all your time on this. It really is a great app.  Now a proud sponsor :)

**Comment by BottlecapDave** [comment]
Glad that's worked. Still not sure why it wasn't sorted in the first place for you, but 🤷‍♂️

**Comment by BottlecapDave** [comment]
And thank you for the sponsorship - very much appreciated

**Comment by njhcarroll** [comment]
Ok - the re-install has fully sorted it out.  All sensors working as they should :)

**Comment by BottlecapDave** [comment]
If it stops again, first thing I suggest is going to the `events` tab of the `developer tools`. You should only have one thing listening to `octopus_energy_electricity_current_day_rates`. In addition, you should use the tools to listen to `octopus_energy_electricity_current_day_rates`. This should trigger around the 30 minute mark, should only fire once and should have the rates in the correct order.

**Comment by njhcarroll** [comment]
Thanks - Will keep a watch out and try this out if necessary
