### ISSUE TITLE
Missing octopoints and wheel of fortune sensors

### ISSUE THREAD

**Issue by btrudgill** [BottlecapDave/HomeAssistant-OctopusEnergy#572]
### Describe the bug

I have the intelligent octopus tariff for both electricity and gas, I am part of the octoplus scheme and have the wheel of fortune in my octopus account, however I cant see any of it in home assistant.

I keep up to date with my custom components (currently on 9.0.2), and only can see charger, electricity meter, gas meter and their associated entities. None of the entities are the octopoints or wheel of fortune sensors.

I have checked the configuration page and can’t see how to enable those devices?

### Reproduction steps

Unknown how to reproduce other than having same configuration detailed in previous section

### Expected behaviour

Based on the documents, I am expecting to see octopoints and wheel of fortune sensors

### Integration Version

9.0.2

### Home Assistant Version

2023.11.3

### Fresh Install?

After upgrading

### Home Assistant Logs

If logs are helpful I will provide on request.

**Comment by BottlecapDave** [comment]
Hello.

Where are you looking for these sensors? Please note they will not be attached to any device within HA, because they are not associated or extend any device. You will need to look under the entities filter within the integration pane to see them.

**Comment by btrudgill** [comment]
Yep, sorry they are under the entities section.
I assumed they (at least the wheel of fortune) would be associated with the electricity and gas account devices.

Are there any entities that can be used to toggle the wheel of fortune events or does it have to be manually done? Same with the savings sessions?

**Comment by BottlecapDave** [comment]
Please review the docs https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/services.md around available services and how you can utilise them.

I'm going to close this issue as the entities are available.
