### ISSUE TITLE
Not working since update 

### ISSUE THREAD

**Issue by djdarlo** [BottlecapDave/HomeAssistant-OctopusEnergy#574]
### Describe the bug

Since I updated to the latest version the target sensors don’t seem to be updating themselves. I have a few sensors. One which runs from midnight to 6am. Usually after the release of the latest rates around 4pm this triggers the calculation of the next blocks. This hasn’t happened today. 

### Reproduction steps

Target sensor not updating

### Expected behaviour

Target sensors update after daily refresh 

### Integration Version

Latest

### Home Assistant Version

Latest 

### Fresh Install?

After upgrading

### Home Assistant Logs

NA

**Comment by BottlecapDave** [comment]
Hello. Can you confirm that you're not seeing the expected behaviour as outlined in the [FAQ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/faq.md#why-wont-my-target-rates-update)?

**Comment by djdarlo** [comment]
I don’t think so. These have been working fine before. I’ve just
reconfigured them and it’s recalculated them now but in the past this was
automatic.

D

**Comment by BottlecapDave** [comment]
Nothing has changed with those sensors during the last few releases, bar some name changes in attributes. 

As mentioned in the FAQ, is `last_evaluted` updating roughly every minute?

Has `target_times_last_evaluated` attribute updated within the last 24 hours?

Do you have rate information for the required timeframe (midnight to 6am) available?

**Comment by djdarlo** [comment]
This is a bit of a strange one and I think maybe related to an upgrade of
Home Assistant I performed at a similar time to the Octopus integration.  A
few observations:-

- A dashboard I can previously setup to show the attributes of the target
hours was showing UNKNOWN for all the attributes eg. start time, end time,
hours etc.
- To remedy this I had to go and re-type/re-select the attribute to get it
to show the value which was already present as I could see it in the
attributes box of the entity.
- One of my automations was referencing the hour attribute - looking at the
debug it said this variable did not exist - again re-typing/re-selecting
the variable in the automation fixed this.  It is as though the upgrade
knocked out the pointers to the variable in the target hours setup.
- The target sets were not refreshing themselves until I reconfigured them
all - exact same values - through the interface.

Definitely a head scratching one but I think down to the Home Assistant
upgrade not your integration.  Think it is sorted now though ;)

**Comment by BottlecapDave** [comment]
Ok glad to hear, and that is very odd. It does seem like HA sometimes loses track of entities. I've been doing everything to the book (according to their docs) to my knowledge (hense why I add the new evaluated attributes.

I'll close this ticket for now, but comment here if you see the same behaviour again.
