### ISSUE TITLE
Octopus Integration Day Rates Sensor Attributes Data Type Inconsistency Crashes Dependencies

### ISSUE THREAD

**Issue by ChequeM8** [BottlecapDave/HomeAssistant-OctopusEnergy#581]
### Describe the bug

When starting Home Assistant the Rates Start and End attributes of the rates array sensors such as:

event.octopus_energy_electricity_XXXXXXXXXX_YYYYYYYYYYYY_current_day_rates

appear to be String data types.  Exactly on the hour and every half hour, they switch to Datetime data types breaking any code that relies on date or string manipulation.  After rebooting Home Assistant they become Strings again until the next half hour period.

### Reproduction steps

When restarting HA this template code produces a list of import rates between two dates:

```
{# Strings #}
{% set run_time_start = today_at("00:00:00").strftime("%Y-%m-%dT%H:%M:%S") %}
{% set run_time_end = (today_at("00:00:00") + timedelta(days = 1)).strftime("%Y-%m-%dT%H:%M:%S") %}

{# Rates #}
{% set all_import_rates = state_attr('event.octopus_energy_electricity_XXXXXXXXXX_YYYYYYYYYYYY_current_day_rates','rates') 
| rejectattr('start', 'lt', run_time_start) 
| rejectattr('start', 'gt', run_time_end) 
| sort(attribute='value_inc_vat, start') 
| list %}

{{all_import_rates}}
```

Exactly on the hour or half hour this then produces an error:
TypeError: '<' not supported between instances of 'datetime.datetime' and 'str'
The code then needs changing to:

```
{# Dates #}
{% set run_time_start = today_at("00:00:00") %} 
{% set run_time_end = run_time_start + timedelta(days = 1) %}

{# Rates #}
{% set all_import_rates = state_attr('event.octopus_energy_electricity_XXXXXXXXXX_YYYYYYYYYYYY_current_day_rates','rates') 
| rejectattr('start', 'lt', run_time_start) 
| rejectattr('start', 'gt', run_time_end) 
| sort(attribute='value_inc_vat, start') 
| list %}

{{all_import_rates}}
```
After rebooting Home Assistant this then produces an error:
TypeError: '<' not supported between instances of 'str' and 'datetime.datetime'
The code then needs changing back again.

### Expected behaviour

When starting Home Assistant the Rates Start and End attributes of the rates array sensors should start as data type Datetime and remain consistant.

### Tariff Code

E-1R-FLUX-IMPORT-23-02-14-G

### Integration Version

v9.0.2

### Home Assistant Version

Core 2023.11.3 Supervisor 2023.11.3 Operating System 11.1 Frontend 20231030.2

### Fresh Install?

Not specified

### Home Assistant Logs

Nothing in logs

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs)
- [X] I confirm that I cannot find my solution within the [FAQ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs/faq.md)

**Comment by BottlecapDave** [comment]
Wow that was a pain to find. Event sensors work a little different to other sensors. This should now be fixed in [v9.1.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v9.1.0).
