### ISSUE TITLE
Target Rate Sensors - Overall Max Cost Rounding

### ISSUE THREAD

**Issue by MJWMJW2** [BottlecapDave/HomeAssistant-OctopusEnergy#587]
### Describe the bug

Within the attributes of Target Rate sensors, I believe due to improvements made in 
https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/481

Overall max cost is now listed in GBP.  However this value is rounded.  Extracting this to then use for further automation can inadvertently capture prices outside of those desired.

For example, if we had the following three prices
0.16511
0.16512
0.16999

Using a 1 hour Intermittent target, the Overall max cost is reported as 0.17, therefore if we extract this value to use in an automation, we will inadvertently also capture the 0.16999 slot

### Reproduction steps

Create a Target capturing multiple slots, and examine the created attribute,
```
- value_inc_vat: 0.170205
  start: '2023-11-29T02:00:00+00:00'
  end: '2023-11-29T02:30:00+00:00'
  tariff_code: E-1R-AGILE-FLEX-22-11-25-H
  is_capped: false
- value_inc_vat: 0.17094
  start: '2023-11-29T02:30:00+00:00'
  end: '2023-11-29T03:00:00+00:00'
  tariff_code: E-1R-AGILE-FLEX-22-11-25-H
  is_capped: false
Overall average cost
0.17
Overall min cost
0.16
Overall max cost
0.18
```

Overall max costs are rounded

### Expected behaviour

Full value of cost is displayed in GBP, eg
0.170205

### Tariff Code

E-1R-AGILE-FLEX-22-11-25-H

### Integration Version

v9.1.0

### Home Assistant Version

2023.11.2

### Fresh Install?

After upgrading

### Home Assistant Logs

NA

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs)
- [X] I confirm that I cannot find my solution within the [FAQ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs/faq.md)

**Comment by BottlecapDave** [comment]
Hi. When I get a chance I'll have a look at improving this accuracy

**Comment by BottlecapDave** [comment]
Hello. I just started looking at this today, and I could be missing something but I believe the value is already accurate (see attached screenshot of the attributes). If you're referring to the UI when you look at the attributes, then I believe this is HA doing this as I haven't explicitly asked for any representation.
<img width="1153" alt="Screenshot 2023-12-09 155451" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/14993950/b6fd622b-d3e0-49dc-91aa-1acf37451289">

Was it the UI you were seeing this or somewhere else?

**Comment by MJWMJW2** [comment]
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/79329672/086481b0-5332-4c1d-938a-3d8fcc36e7dc)


It was in the extended attributes of the entity.  Screenshot is from the prior version.  I could grab a backup update and check again.  I'd not gone via developer tools, states, which I think your screenshot is from.

I pull the value of the Max cost in to a template sensor:

```
sensor:
  - platform: template
    sensors:
      octopus_energy_max_cost_2h:
        friendly_name: "Electricity Max Cost 2 hour"
        unit_of_measurement: "p"
        unique_id: daa93bf2-6abb-11ee-b962-0242ac120005
        value_template: >-
          {{ (state_attr('binary_sensor.octopus_energy_target_2_hour_target', 'overall_max_cost') | regex_findall_index('-?\\d+\\.\\d+', 0) | float | round(2)) + 0.01 }}```

**Comment by BottlecapDave** [comment]
That would be the issue. In your template you're rounding the value (see `round(2)`. In the latest version, the attribute value is a float so you don't need to anything funky (like removing `p` delimiters) to it to use the value.

**Comment by MJWMJW2** [comment]
Genius!  

Of course!  It used to be in pence, now in pounds, so the round is rounding to 2 dp of the GBP value.  

Added an extra parenthesis, and working perfectly now, thank you Dave!

```
{ (state_attr('binary_sensor.octopus_energy_target_2_hour_target', 'overall_max_cost') + 0.01) }}
```

**Comment by MJWMJW2** [comment]
Here's the shot from the attributes, this is what mislead me:
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/79329672/a305054c-5f56-49db-88b1-97c4d768d757)

**Comment by BottlecapDave** [comment]
Yeah I think HA UI is adjusting attributes for the front end. They do this for other things like times to local time. Unfortunately, they only do this for top level items, which is why the items in the collection are unaffected. I'm guessing they're rounding based on your profile settings.
