### ISSUE TITLE
View Ahead In Time For Saving Session Entity (Upcoming)

### ISSUE THREAD

**Issue by joshaspinall** [BottlecapDave/HomeAssistant-OctopusEnergy#589]
### Describe the feature

Allow the saving session entity to be viewed into the future, assuming the API allows, to show when a saving session is taking place.

### Expected behaviour

When selecting the entity, show on the graph view into the future for an upcoming savings session.

### Use Case

Enable automations to be created & actioned based on this.

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hi. This is is already available in various ways. The [saving session events entity](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/entities/octoplus.md#saving-session-events) already exposes available and joined events (past, present and future) as provided by the API.

There are also various [events](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/events.md#new-saving-session) available that you can listen to if that's more of your thing along with [services](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/services.md#join_octoplus_saving_session_event) for joining events automatically.

There is also the attributes on the [saving session entity](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/entities/octoplus.md#saving-sessions) which can be used for monitoring the next upcoming saving session
