### ISSUE TITLE
Current Accumulative Consumption for export

### ISSUE THREAD

**Issue by MatterSec** [BottlecapDave/HomeAssistant-OctopusEnergy#590]
### Describe the feature

Like the very helpful recent 'current_accumulative_consumption' being added, a way to see the "current_accumulative_export" for today would be helpful. Currently using the previous which doesn't match up the days with current vs previous together. 

### Expected behaviour

Add feature for current_accumulative_export for electricity 

### Use Case

Can see in the energy usage dashboard that it displays the current_accumulative_consumption and current_accumulative_export on the same day.

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs) and confirmed it does not already exist
- [ ] I am willing/able to help contribute to the solution of this feature

**Comment by MatterSec** [comment]
> Hello. I've not been able to confirm if this data is available via the API and I don't have export to confirm. Can you see today's export consumption in the app (not live demand)

Hi, Doesn't appear so,  shows  "Your data's on its way" for Export.  Hopefully they add the feature in the future

**Comment by BottlecapDave** [comment]
You'd have to contact octopus directly
