### ISSUE TITLE
Todays rates are above 65p (4.30-5pm, Dec 1st, East of England) but integration appears capped at 40p!

### ISSUE THREAD

**Issue by L81ker** [BottlecapDave/HomeAssistant-OctopusEnergy#595]
### Describe the bug

I use the rates card, and also the apex chart card, both of these pick up the rates from this integration. The prices today will hit over 65p at 4.30pm, but it appears that the rates are 'limited' at 40p,. neither rates chart shows anything above 40p. If this is a simple change in config, I haven't found it. The apex chart is set to accept up to 100p, but still 'flat tops' at 40p.

screenshots ; 

rates card integration:
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/105645866/7e5514a2-42f7-48ca-96be-b83b5c0b03bd)

apex chart card:
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/105645866/e3c4aeea-038c-4ac1-9ec0-5335a3a8089d)

Agile 'my account' todays rates: 
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/105645866/7837983e-e56f-40a2-b15d-21921fd011e1)

### Reproduction steps

I can see that there is "is capped=true", on the current rates sensor. Here is all that data except my meter and account info. As I'm on Agile, I don't believe that my rates are capped generally, but this may be an expected behaviour on odd high price days in some cases, I do not believe it should be applied to my account. 

Is there a way to use this differently, so that a sensor or event is set when the rates are capped., but still show the agile prices, or to configure it to 'ignore'

Apologies in advance if this isn't a bug, but I was unable to find clear documentation about the <is_capped> flag. My understanding is that on agile, I'm exposed to peak pricing (https://octopus.energy/smart/agile/) "_Agile prices can spike up to 100 p/kWh any time_"

Happy to email full logs and other info if you need it., really appreciate this integration and how useful it is, and this doesn't prevent me using it for finding cheap slots to charge my battery with. It does stop me creating price-included alarms for other house members not to use high-energy devices when the prices are really high.

s_export: false
is_smart_meter: true
tariff: E-1R-AGILE-FLEX-22-11-25-A
start: 2023-12-01T08:30:00+00:00
end: 2023-12-01T10:30:00+00:00
is_capped: true
is_intelligent_adjusted: false
current_day_min_rate: 0.18186
current_day_max_rate: 0.4
current_day_average_rate: 0.308765
price_cap: 40
data_last_retrieved: 2023-12-01T09:30:27.690517+00:00
last_evaluated: 2023-12-01T09:41:37.690949+00:00
unit_of_measurement: GBP/kWh
device_class: monetary
icon: mdi:currency-gbp
friendly_name: Electricity 23M0069064 1012948919967 Current Rate

### Expected behaviour

I expected the full days rates to be shown, on agile, and not 'clipped' to 40p.

### Tariff Code

E-1R-AGILE-FLEX-22-11-25-A

### Integration Version

V9.1.0

### Home Assistant Version

2023.11.3

### Fresh Install?

Not specified

### Home Assistant Logs

There are other errors in the log, but not related to the price capping, these repeat in my log and are similar for gas, sharing for completeness but are _not_ related to this issue.

2023-12-01 09:44:32.111 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.octopus_energy_electricity_<meterinfo>_previous_accumulative_cost_override fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1155, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 696, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 957, in async_device_update
    await self.async_update()
  File "/config/custom_components/octopus_energy/electricity/previous_accumulative_cost_override.py", line 129, in async_update
    [rate_data, standing_charge] = await asyncio.gather(
                                   ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 768, in async_get_electricity_standing_charge
    async with client.get(url, auth=auth) as response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1169, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.octopus.energy:443 ssl:default [Try again]

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs)
- [X] I confirm that I cannot find my solution within the [FAQ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs/faq.md)

**Comment by BottlecapDave** [comment]
Hello. If the data states is capped is true, then it means you've setup a manual price cap when you configured the integration. If you make sure you're on the latest version and then configure your account in the integration page and remove the price cap it should be removed when the prices next refresh

**Comment by BottlecapDave** [comment]
The attribute's meaning is mentioned in the [docs for the sensor](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/entities/electricity.md#current-day-rates). I'll update them to link to what "configured price cap" refers to

**Comment by pcb1962** [comment]
the price cap Agile is currently 100p

**Comment by pcb1962** [comment]
I see, so we shouldn't set the 100p cap in the integration, thanks for the clarification.

**Comment by L81ker** [comment]
> There are two different price caps. The one set by OE that is applied to the data that comes from the API (100p) and the one set by the user when the integration is set up (in the example 40p). The latter feature was added as there were some APIs that were not returning the data capped to the governments cap, but in most cases shouldn't need to be set. If the is_capped attribute is set to true, then the integration has been setup with a manual price cap.

I didnt spot that when I updated from the earlier one, is the fix to remove and reinstall, and then I would see that price cap on/off selection? 

Thanks for super fast response too.
