### ISSUE TITLE
Stopped logging as statistic - not showing on Energy Dashboard anymore

### ISSUE THREAD

**Issue by adammccormack162** [BottlecapDave/HomeAssistant-OctopusEnergy#596]
### Describe the bug

Since 4am on the 30th November - my Octopus stats dont appear to be getting logged as a statistic (checked the statistic editor under the developer menu)

No idea what changed specificaly at this time.

The entity is still updated with the value from the API - just the statistic option that the dashboard uses isnt getting anything new.

Have checked other statistics (temperature sensors etc.) and theyre all writing as expected

### Reproduction steps

No idea how to get it to reproduce if nobody else is having the issue :-/

### Expected behaviour

Entity to update statistic so it can be displayed in the energy dashboard

### Tariff Code

E-1R-SILVER-FLEX-22-11-25-B

### Integration Version

v9.1.0

### Home Assistant Version

2023.11.3 - tried upgrading to the 2023.12 beta this morning too

### Fresh Install?

Not specified

### Home Assistant Logs

Diagnostic Data:

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.12.0b1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "6.1.58-haos-raspi",
    "supervisor": "2023.11.6",
    "host_os": "Home Assistant OS 11.2.rc2",
    "docker_version": "24.0.7",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "magicmirror": {
      "version": "1.3.0",
      "requirements": []
    },
    "bestway": {
      "version": "0.0.1",
      "requirements": []
    },
    "eufy_security": {
      "version": "7.7.4",
      "requirements": [
        "websocket-client==1.4.2",
        "aiortsp==1.3.7"
      ]
    },
    "hyperhdr": {
      "version": "0.0.6",
      "requirements": [
        "hyperhdr-py==0.0.3"
      ]
    },
    "webrtc": {
      "version": "v3.5.0",
      "requirements": []
    },
    "meross_lan": {
      "version": "4.4.1",
      "requirements": []
    },
    "average": {
      "version": "2.3.1",
      "requirements": [
        "colorlog==6.7.0"
      ]
    },
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "alexa_media": {
      "version": "4.7.9",
      "requirements": [
        "alexapy==1.27.8",
        "packaging>=20.3",
        "wrapt>=1.14.0"
      ]
    },
    "switch_manager": {
      "version": "1.3.2",
      "requirements": []
    },
    "presence_simulation": {
      "version": "3.2",
      "requirements": []
    },
    "auto_backup": {
      "version": "1.4.1",
      "requirements": []
    },
    "octopus_energy": {
      "version": "9.1.0",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "octopus_energy",
    "name": "Octopus Energy",
    "codeowners": [
      "@bottlecapdave"
    ],
    "config_flow": true,
    "dependencies": [
      "repairs",
      "recorder"
    ],
    "documentation": "https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs",
    "homekit": {},
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues",
    "ssdp": [],
    "version": "9.1.0",
    "zeroconf": [],
    "is_built_in": false
  },
  "data": {
    "id": "A-BB4E7AB3",
    "electricity_meter_points": [
      {
        "mpan": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "is_export": false,
            "is_smart_meter": true,
            "device_id": "**REDACTED**",
            "manufacturer": "118F - Aclara",
            "model": "00000107",
            "firmware": "00070602"
          }
        ],
        "agreements": [
          {
            "start": "2023-06-30T23:00:00+00:00",
            "end": null,
            "tariff_code": "E-1R-SILVER-FLEX-22-11-25-B",
            "product_code": "SILVER-FLEX-22-11-25"
          }
        ]
      }
    ],
    "gas_meter_points": [
      {
        "mprn": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "consumption_units": "m\u00b3",
            "is_smart_meter": true,
            "device_id": "**REDACTED**",
            "manufacturer": "123E - Flonidan",
            "model": "00000300",
            "firmware": "04080605"
          }
        ],
        "agreements": [
          {
            "start": "2023-06-30T23:00:00+00:00",
            "end": null,
            "tariff_code": "G-1R-SILVER-FLEX-22-11-25-B",
            "product_code": "SILVER-FLEX-22-11-25"
          }
        ]
      }
    ]
  }
}

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs)
- [X] I confirm that I cannot find my solution within the [FAQ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs/faq.md)

**Comment by BottlecapDave** [comment]
If the entity is still updating its value and nothing changed in your environment, this feels like a HA issue. Do you have any errors in your logs?

**Comment by DanDon** [comment]
I'm now having the same issue.

I'm on Octopus Home Mini and the stats have all stayed the same since 9:30pm yesterday and therefore the Energy Dashboard is blank for gas and electric since then and all the accumulative sensors have the same value from 12 hours ago. 

Changed nothing and have not updated anything ... just stopped working. Rebooting the HA or even the HA OS VM does nothing. Still not getting any updates.

`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:927
First occurred: 09:00:45 (2 occurrences)
Last logged: 09:00:45

Update of sensor.octopus_energy_gas_g4k00752561916_7714551508_previous_accumulative_consumption_kwh is taking over 10 seconds
Update of sensor.octopus_energy_electricity_20k0003901_2700002150674_previous_accumulative_cost is taking over 10 seconds`

**Comment by BottlecapDave** [comment]
@DanDon you're issue sounds different if the sensors are not updating either. Is your issue related to previous or current accumulative consumption sensors? If previous, do you see the data in the app for yesterday (the default look behind). If current, do you see the data in the app for today?

**Comment by BottlecapDave** [comment]
Also @DanDon what does the `last_evaluated` attribute state on the sensors. These should update every minute. There is also a `data_last_retrieved` attrbute that will state when the API was last successfully contacted.

**Comment by adammccormack162** [comment]
> If the entity is still updating its value and nothing changed in your environment, this feels like a HA issue. Do you have any errors in your logs?

Nope... no errors in the logs (well relating to statistics or the octopus plugin, only a couple of other addons that have issues at the moment)

Yeah, i did wonder if it was something direct with HA - hence the upgrade to the beta release... but given all the other statistic based items are updating - it only seems to be the Octopus energy ones :-/

**Comment by BottlecapDave** [comment]
With no errors and the fact the sensors themselves are updating their state there's very little for me to go on. Are these for current or previous accumulative consumption/cost?

**Comment by DanDon** [comment]
Seems like there was a complete outage of the integration from 10pm 1st Dec through to 9am on 2nd Dec and it has been fine since??

There is now a big gap in the Energy Dashboard for that time and nothing in the logs or any reason why. Didn't change anything for it to just start working again at 8am either? 🤷🏼

**Comment by BottlecapDave** [comment]
@DanDon There might have been an outage with the API (but that would have had errors in your logs), or the API was returning no data for that period at that point in time. I only report what the API tells me at the time. The energy dashboard works in real time and the HA entities doesn't support loading data historically so I can't back port the data.

**Comment by BottlecapDave** [comment]
@adammccormack162 Glad you've manged to find the culprit. @DanDon If you're still having issues, please raise a separate ticket.
