### ISSUE TITLE
Wheel of fortune octoplus points

### ISSUE THREAD

**Issue by alfwro13** [BottlecapDave/HomeAssistant-OctopusEnergy#598]
### Describe the bug

When spinning the wheel of fortune on octopus website as a minimum you get 8 points.
When using the service: octopus_energy.spin_wheel_of_fortune you get no points

### Reproduction steps

Use the service: octopus_energy.spin_wheel_of_fortune to spin the wheel

### Expected behaviour

This should work the same as the website ie minimum 8 points is given

### Tariff Code

E-1R-AGILE-FLEX-22-11-25-J

### Integration Version

V9.1.0

### Home Assistant Version

2023.11.3

### Fresh Install?

After upgrading

### Home Assistant Logs

N/a

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs)
- [X] I confirm that I cannot find my solution within the [FAQ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs/faq.md)

**Comment by alfwro13** [comment]
I think you can get additional spins for manually submitting meter reading.

**Comment by BottlecapDave** [comment]
Only if you havent submitted a meter reading for the month and I don't think it applies to smart meters

**Comment by BottlecapDave** [comment]
From my limited investigation, it looks like it takes an authorization path that is different to the standard API, so this might not be possible. I'll confirm properly next month.

I'll update the docs stating this issue and update the service to require an explicit override if the user has joined octopoints to state they understand that they won't get them via this service. I've raised a question in the octopus energy forums asking why the current endpoint doesn't do this automatically.

**Comment by BottlecapDave** [comment]
Based on comments in the HA forums it looks like this isn't going to get resolved anytime soon :( The endpoint that the was referenced uses cookie based authentication that is specific to the web, which would require a brand new way of authenticating. Therefore I'm afraid at the moment, this is a *won't fix*. I've updated the docs to include a disclaimer.

**Comment by MattHadfield113** [comment]
@BottlecapDave shame this wont be resolved, do you have a link to the OE forum post so we can throw some weight behind adding this endpoint?

**Comment by BottlecapDave** [comment]
The related post can be found at https://forum.octopus.energy/t/why-does-wheel-spins-via-graphql-not-award-octopoints/8783

**Comment by MattHadfield113** [comment]
Hi @BottlecapDave - Me and my friend who are both using the integration have noticed that this suddenly seems to be giving points instead of account credit, have Octopus changed this?

**Comment by BottlecapDave** [comment]
Not that in aware of and there's not been any kind of notification, but if it is that would be great

**Comment by danieltwagner** [comment]
@MattHadfield113 are you still receiving points? I just realized today that no points are granted with the automation and disabled it as I'd rather spin manually on the web :)
