### ISSUE TITLE
Please clarify *which* Octopus Energy this can be used with

### ISSUE THREAD

**Issue by dfludwig** [BottlecapDave/HomeAssistant-OctopusEnergy#60]
Hi - Since it appears that Octopus Energy operates in multiple countries, each with different web infrastructure/reporting capabilities, it might be helpful in the documentation to indicate which locals are supported.  I presume you are focused on the UK location, "https://octopus.energy/", and not (at least currently) on the US location, "https://octopusenergy.com/".  Thanks!

**Comment by BottlecapDave** [comment]
Hi @dfludwig. You are correct that this integration has been tested against the UK version of Octopus Energy. I couldn't find any documentation for a US version of the API, so I'm not sure if it uses the same one or a different one.
