### ISSUE TITLE
Allow startup when graphql endpoint is down

### ISSUE THREAD

**Issue by plord12** [BottlecapDave/HomeAssistant-OctopusEnergy#604]
### Describe the bug

This morning I see -

```
2023-12-05 08:05:44.682 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry A-4555ADB9 for octopus_energy
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/octopus_energy/__init__.py", line 83, in async_setup_entry
await async_setup_dependencies(hass, config)
File "/config/custom_components/octopus_energy/__init__.py", line 127, in async_setup_dependencies
account_info = await client.async_get_account(config[CONFIG_MAIN_ACCOUNT_ID])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/octopus_energy/api_client/__init__.py", line 400, in async_get_account
await self.async_refresh_token()
File "/config/custom_components/octopus_energy/api_client/__init__.py", line 386, in async_refresh_token
token_response_body = await self.__async_read_response__(token_response, url)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/octopus_energy/api_client/__init__.py", line 1136, in __async_read_response__
raise ServerError(msg)
custom_components.octopus_energy.api_client.ServerError: DO NOT REPORT - Octopus Energy server error (https://api.octopus.energy/v1/graphql/): 502; <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html> 
```

and the plugin fails to start.

Presumably an Octopus issue, but since other parts of the API are working, I wondered if the plugin can at least partially startup without graphql ?

### Reproduction steps

Wait until graphql endpoint is down and try starting the plugin.

### Expected behaviour

Other, non graphql, data should be available.

### Tariff Code

xx

### Integration Version

v9.1.0

### Home Assistant Version

2023.11.3

### Fresh Install?

Not specified

### Home Assistant Logs

See above

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs)
- [X] I confirm that I cannot find my solution within the [FAQ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs/faq.md)

**Comment by JonSilver** [comment]
Here too

**Comment by plord12** [comment]
> Here too

Thanks for confirming its not just me.

(I did send a message to Octopus to request local API access to the octopus mini ... worth a try!)

**Comment by jtetzlaff** [comment]
same here, data seems to have stopped coming about 4am.

It looks fine on the app via Octopus Mini so it looks like a 'them' problem.
I tried refreshing api key and re-configuring but that fails aswell.

**Comment by jtetzlaff** [comment]
tweeted them, looks like it worked and it's fixed again.

**Comment by plord12** [comment]
Octopus back again :-)

Might still be worth considering if the plugin can start without graphql.

**Comment by BottlecapDave** [comment]
It cannot. Most of the data comes from their graphql API.
