### ISSUE TITLE
`next_time` of Continuous Target Rate is `None` when `on`

### ISSUE THREAD

**Issue by lwfitzgerald** [BottlecapDave/HomeAssistant-OctopusEnergy#609]
### Describe the bug

When `on`, the `next_time` attribute of a Continuous Target Rate binary sensor entity is `None`.

Target Rate configuration:
Hours: `1.5`
Mode: `Continuous`
Minimum start time: `06:00`
Maximum end time: `17:30`

### Reproduction steps

1. Add target rate sensor with above configuration
2. Wait until the binary sensor entity turns `on`
3. Note that the `next_time` attribute of the binary sensor entity is `None`

### Expected behaviour

That the `next_time` attribute is populated with the next cheapest period start time.

### Tariff Code

E-1R-AGILE-FLEX-22-11-25-C

### Integration Version

9.1.0

### Home Assistant Version

2023.11.2

### Fresh Install?

Fresh install

### Home Assistant Logs

Log at 06:00 when sensor was on:
```
2023-12-05 06:00:58.769 DEBUG (MainThread) [custom_components.octopus_energy.target_rates.target_rate] Updating OctopusEnergyTargetRate dishwasher_early
2023-12-05 06:00:58.770 DEBUG (MainThread) [custom_components.octopus_energy.target_rates.target_rate] calculated: True
```

<img width="568" alt="image" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/90507/86229e5d-d67b-495b-ae73-ce961c06d872">

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs)
- [X] I confirm that I cannot find my solution within the [FAQ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs/faq.md)

**Comment by BottlecapDave** [comment]
Hello. This is by design as per the [docs](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/setup_target_rate.md#attributes), this is only populated if there are further periods for the current 24 hour period. Because you have a continuous sensor target rate all periods will be a single block and therefore this will not be set when on. 

It will only be set if 1) the target rate sensor has yet to come on during the 24 hour period or 2) you have an intermittent sensor and have not entered the final period.

**Comment by lwfitzgerald** [comment]
Apologies, I missed a rather important detail - 
`Re-evaluate multiple times a day`: `True`
<img width="568" alt="image" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/90507/2224cad9-40d9-456a-9723-d56fb0cb48bb">

Given this setting, I expected that there _would_ be additional periods in the day (and you can see there are in the above screenshot).

**Comment by BottlecapDave** [comment]
I'ev updated the docs. Even in this case, it won't be populated until the target times have been re-evaluated.

**Comment by lwfitzgerald** [comment]
I think it would also be worth clarifying this behaviour in the `Rolling Target` / `Re-evaluate multiple times a day` doc section as well. It's not obvious that "rolling" / re-evaluation only occurs after the next cheapest period has passed.

**Comment by BottlecapDave** [comment]
I will update the docs
