### ISSUE TITLE
Next time on a target rate sensor is incorrect when using an offset

### ISSUE THREAD

**Issue by andrey-yantsen** [BottlecapDave/HomeAssistant-OctopusEnergy#611]
### Describe the bug

The `Next time` value seems to be calculated by applying the offset twice. See the attached screenshot.
<img width="451" alt="image" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/629281/67465f2c-81f9-4336-bb58-2b2783420250">

### Reproduction steps

Created a target sensor with a duration of 1.5 hours and an offset of 50 minutes.

### Expected behaviour

The `offset` is applied only once in the `Next time` value.

### Tariff Code

E-1R-AGILE-FLEX-22-11-25-H

### Integration Version

9.1.0

### Home Assistant Version

2023.11.3

### Fresh Install?

Fresh install

### Home Assistant Logs

n/a

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs)
- [X] I confirm that I cannot find my solution within the [FAQ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs/faq.md)

**Comment by andrey-yantsen** [comment]
And just to clarify: the sensor itself switches on at the expected time. But the `next time` attribute is incorrect 🤷

**Comment by BottlecapDave** [comment]
Hello. This has now been fixed in the latest release (v9.2.0)

**Comment by andrey-yantsen** [comment]
Thank you, David!
