### ISSUE TITLE
Previous gas data not updating. 

### ISSUE THREAD

**Issue by Lawdie** [BottlecapDave/HomeAssistant-OctopusEnergy#618]
### Describe the bug

Since the 25th Nov all "Gas Previous Accumulative Consumption (kWh)" and "Gas Previous Accumulative Cost" havn't updated. Electricity and other Gas entities are working as expected such as real time and unit rates

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/16335903/0f6282b5-8017-46da-baa3-3da091cb4cfe)

### Reproduction steps

Look at values of specific entities 

### Expected behaviour

Gas data gets updated daily with previous days data

### Tariff Code

G-1R-SILVER-VAR-22-10-21-N

### Integration Version

v9.1.0

### Home Assistant Version

2023.11.6

### Fresh Install?

Not specified

### Home Assistant Logs

No logs currently, just enabled debug logging on HA 

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. 

The previous consumption data looks for data based on the configured offset (by default this is the previous day). If the data takes longer than the configured offset to appear, then it will not appear in Home Assistant. For example if yesterdays data doesn't become available until 1am tomorrow morning, then it will not appear in Home Assistant. Based on this, is yesterdays data available in the [octopus energy web dashboard](https://octopus.energy/dashboard/new/accounts/consumption/home) for today? If it is, do you have any errors in your HA logs related to the integration?

**Comment by Lawdie** [comment]
> Hello.
> 
> The previous consumption data looks for data based on the configured offset (by default this is the previous day). If the data takes longer than the configured offset to appear, then it will not appear in Home Assistant. For example if yesterdays data doesn't become available until 1am tomorrow morning, then it will not appear in Home Assistant. Based on this, is yesterdays data available in the [octopus energy web dashboard](https://octopus.energy/dashboard/new/accounts/consumption/home) for today? If it is, do you have any errors in your HA logs related to the integration?

So it looks to be an issue with my meter, noticed my last bill was an estimate however the website was showing consumption data. 

Contacted Ocotopus who said my meter isn't talking to them but the home mini was which is why they have data visble on the website. They can't use home mini data for billing purposes however which would maybe explain why the fields aren't updating if its based on actual billed useage.
