### ISSUE TITLE
cannot always see current accumulative cost

### ISSUE THREAD

**Issue by djdarlo** [BottlecapDave/HomeAssistant-OctopusEnergy#622]
### Describe the bug

In my setup of the integration I can see the below...

sensor.octopus_energy_electricity_21l4060654_1580000447951_current_accumulative_cost

Which shows me today's current cost however in my brothers and friends I cannot see it.

### Reproduction steps

install integration - look for sensor

### Expected behaviour

find sensor

### Tariff Code

NA

### Integration Version

9.1.0

### Home Assistant Version

latest

### Fresh Install?

Not specified

### Home Assistant Logs

NA

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. As per the [docs](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/entities/electricity/#home-mini-entities) these entities are only available for accounts that have an octopus mini associated with them. Does your brother and friend have an octopus home mini? And if so, have they configured their integration to state as such?

**Comment by djdarlo** [comment]
My bad. They don’t. That would explain it.

D
