### ISSUE TITLE
Not picking up next day rates

### ISSUE THREAD

**Issue by slopemad** [BottlecapDave/HomeAssistant-OctopusEnergy#624]
### Describe the bug

The integration has been working fine, 9.1.0 has been in a while.  For some reason, tonight it isn't picking up tomorrow's rates even though I am able to pick them up directly through the API myself.

I have restarted HA, restarted the integration, etc.

This is the contents of the event.octopus_energy_electricity_zxxnxxxxxx_xxxxxxxxxxxxx_next_day_rates sensor:

event_types:
  - octopus_energy_electricity_next_day_rates
event_type: octopus_energy_electricity_next_day_rates
rates: []
mpan: 'xxxxxxxxxxxxx'
serial_number: ZxxNxxxxxx
tariff_code: E-1R-AGILE-FLEX-22-11-25-G
friendly_name: Electricity ZxxNxxxxxx xxxxxxxxxxxxx Next Day Rates

### Reproduction steps

Nothing done to reproduce.  No next day electricity rates becoming available in the integration.

### Expected behaviour

next day rates expected

### Tariff Code

E-1R-AGILE-FLEX-22-11-25-G

### Integration Version

9.1.0

### Home Assistant Version

2023.9.2

### Fresh Install?

Not specified

### Home Assistant Logs

2023-12-11 17:46:36.640 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Failed to retrieve new electricity rates for xxxxxxxxxxxxx/ZxxNxxxxxx, so using cached rates
2023-12-11 17:46:36.641 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Finished fetching ELECTRICITY_RATES_xxxxxxxxxxxxx_ZxxNxxxxxx data in 0.000 seconds (success: True)
2023-12-11 17:46:36.981 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Failed to retrieve new electricity rates for xxxxxxxxxxxxx/ZxxNxxxxxx, so using cached rates
2023-12-11 17:46:36.981 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Finished fetching ELECTRICITY_RATES_xxxxxxxxxxxxx_ZxxNxxxxxx data in 0.000 seconds (success: True)

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by alfwro13** [comment]
Looks like you beat me to it  #625 
I'm seeing the same issue

**Comment by slopemad** [comment]
They have since come through, but it is very odd that it was failing for a while.

**Comment by ToastedBreadCrumbs** [comment]
I updated all today and still can’t see tomorrows rate :(

**Comment by alfwro13** [comment]
mine updated as well after 7PM but I have seen this issue multiple times in the last probably 2 -3 weeks

**Comment by Stephens-ely** [comment]
Am seeing same behaviour - Mine eventually updated at 20:30

**Comment by BottlecapDave** [comment]
Sorry you've experienced this. I have an issue which is reworking how data is retrieved the API which will hopefully make it better in times like this when the API is being flakey/slow

**Comment by ToastedBreadCrumbs** [comment]
No worried, thanks for all the work you’re putting in this! I’m just happy it works again :)

**Comment by alfwro13** [comment]
Strangely enough same problem today. The next day rates event entity was last updated at 13:00:
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/10945277/61296641-b194-4e4e-bdd1-27d8e7996790)

**Comment by Stephens-ely** [comment]
Similar picture for me as well. Is there any thing I can supply from my log files to help??

**Comment by BottlecapDave** [comment]
Any errors that are not timeout of sever errors as that is a failure on OE APIs side

**Comment by Stephens-ely** [comment]
[home-assistant_2023-12-12T17-32-10.213Z.log.zip](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/13651491/home-assistant_2023-12-12T17-32-10.213Z.log.zip)

Not sure if any of this helps - quite a few 502 errors but other bits might help - logs from 16:00 until now

**Comment by alfwro13** [comment]
I have switched to v9.2.0beta and rates updated 15 minutes later.

**Comment by Webreaper** [comment]
Hi all, I'm new to this, but also don't seem to be getting next-day rates. I was going to upgrade to 9.2 beta, but from the HACS versioning it looks like I'm already on v10.0.2 - which I presume doesn't have this issue. Am I misunderstanding?

**Comment by BottlecapDave** [comment]
@Webreaper Sorry for the late response. If you are having issues, please open a new issue.

**Comment by Webreaper** [comment]
Thanks. I figured it out once I dug into the attributes of the price entity. Apologies for the noise!
