### ISSUE TITLE
Add average, min, max cost to "current day rates", "next day rates"

### ISSUE THREAD

**Issue by EPicLURcher** [BottlecapDave/HomeAssistant-OctopusEnergy#628]
### Describe the feature

Add an average, min and max cost attribute to the "_current_day_rates" & "_next_day_rates" events

This seems to exist on the "current_rate" sensor, but it might make more sense to have it on the day_rates - but only works for current day - next day average is not currenlty calculated

### Expected behaviour

Would show the average unit cost for the day, as well as max and min in that period

### Use Case

I would like to be able to pull out these attributes for reports / notifications / comparisons

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello thank you for the suggestion. I'll add it to the list.

**Comment by BottlecapDave** [comment]
This should now be available in the latest release ([v10.0.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v10.0.0))
