### ISSUE TITLE
Error DEVICE_CLASS_GAS

### ISSUE THREAD

**Issue by jeeves2001** [BottlecapDave/HomeAssistant-OctopusEnergy#63]
I have recently installed this plugin via HACS running on a Docker version of Home Assistant. There are no sensors showing up and there is the following entry in the error log: 
--- 
Logger: homeassistant.setup
Source: setup.py:311
First occurred: 17:23:39 (1 occurrences)
Last logged: 17:23:39

Unable to prepare setup for platform octopus_energy.sensor: Platform not found (cannot import name 'DEVICE_CLASS_GAS' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).
--- 

When the smart meter was installed they were unable to install a gas meter, so this could be the cause of the issue?

Is it possible to work around this as I'd like to be able to use this integration for electricity only? 

I really apreciate your efforts in building such a plugin for the community!

**Comment by BottlecapDave** [comment]
Hello, sorry for the late response. This issue is not about you not having gas, but just happened to occur with the gas sensors. However, I'm curious why your instance is getting this issue as no one else has reported this issue. The code in the mentioned error, as been marked as deprecated but does not to appear to have been removed yet. What version of Home Assistant are you on? I'll see if I can move off the deprecated code soon and hopefully fix your issue.

**Comment by BottlecapDave** [comment]
The latest release (v4.5.0) has replaced this class with the non-deprecated one. Would be good to know if this solved your issue?

**Comment by jeeves2001** [comment]
> Hello, sorry for the late response. This issue is not about you not having gas, but just happened to occur with the gas sensors. However, I'm curious why your instance is getting this issue as no one else has reported this issue. The code in the mentioned error, as been marked as deprecated but does not to appear to have been removed yet. What version of Home Assistant are you on? I'll see if I can move off the deprecated code soon and hopefully fix your issue.

Well, I owe you an apology! I have updated Home Assistant to the latest version and it that has resolved the issue. Thank you again for looking into this.

**Comment by BottlecapDave** [comment]
No problem and glad it's working for you now :)
