### ISSUE TITLE
Electricity "current accumulative consumption" broken

### ISSUE THREAD

**Issue by AlecRust** [BottlecapDave/HomeAssistant-OctopusEnergy#639]
### Describe the bug

Thanks for the excellent integration!

I have an Octopus Home Mini and setup the integration about 6 months ago, including the Energy Dashboard.

As of a couple months ago the Energy Dashboard sensors seemed to become `Unknown`. The gas side of things seems to have recovered in more recent versions of this integration, but basically all my electricity sensors are still `Unknown`.

Today I deleted the integration and set it up from scratch, but no change.

My electricity Energy Dashboard configuration looks like this:

<img width="417" alt="Screenshot 2023-12-17 at 13 25 46" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/247634/ba20c4b5-3295-434c-a5e3-bc525898a1fc">

<img width="450" alt="Screenshot 2023-12-17 at 13 32 50" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/247634/7827a4a1-85f7-4db5-8035-a24ab1e87ea3">

Gas is fine:

<img width="415" alt="Screenshot 2023-12-17 at 13 26 52" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/247634/71151aa8-7508-46ef-bb1d-5d8ddbc0f669">

On the main generated HA dashboard, most of the electricity sensors are `Unavailable`. The sensors that do have a value are "flat lining" and haven't changed in a long time.

<img width="419" alt="Screenshot 2023-12-17 at 13 28 14" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/247634/f1ddcf52-6f3c-4568-a186-961661b3b882">

Gas sensors seem fine though:

<img width="416" alt="Screenshot 2023-12-17 at 13 30 32" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/247634/a36cb34b-93ff-414c-b75b-7f01147d8b10">

I've looked at the half dozen or so sensors that are disabled by default by this integration, but none of them look to be the "current accumulative consumption" and "current accumulative cost" I need for electricity on the Energy Dashboard.

There was also some entity "data fixes" I had to apply in HA in the entities list, but resolving these didn't resolve the issue, neither has setting the integration up from scratch today.

Final screenshot from Energy Dashboard, showing the gas sensors working as expected by the electricity showing nothing:

<img width="889" alt="Screenshot 2023-12-17 at 13 34 36" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/247634/d27ac20d-423e-49ee-88b8-8b166c972daa">

Any ideas what I can do to fix or help debug this?

### Reproduction steps

1. Install and configure integration including "I have a Home Mini"
2. Setup Energy Dashboard
3. Electricity sensors not working

### Expected behaviour

Electricity sensors work as they did.

### Tariff Code

G-1R-VAR-22-11-01-H

### Integration Version

Running 9.1.0 but had the issue since 8.x

### Home Assistant Version

2023.12.3

### Fresh Install?

Fresh install

### Home Assistant Logs

I don't see any related HA logs (other than perhaps "taking over 10 seconds" warnings) but here is my electricity meter diagnostics:

```json
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.12.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "6.1.63-haos",
    "supervisor": "2023.11.6",
    "host_os": "Home Assistant OS 11.2",
    "docker_version": "24.0.7",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "octopus_energy": {
      "version": "9.1.0",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "octopus_energy",
    "name": "Octopus Energy",
    "codeowners": [
      "@bottlecapdave"
    ],
    "config_flow": true,
    "dependencies": [
      "repairs",
      "recorder"
    ],
    "documentation": "https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs",
    "homekit": {},
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues",
    "ssdp": [],
    "version": "9.1.0",
    "zeroconf": [],
    "is_built_in": false
  },
  "data": {
    "id": "A-67BF768A",
    "electricity_meter_points": [
      {
        "mpan": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "is_export": false,
            "is_smart_meter": true,
            "device_id": "**REDACTED**",
            "manufacturer": "106C - EDMI Metering Europe",
            "model": "10E2A100",
            "firmware": "0314BA00"
          }
        ],
        "agreements": [
          {
            "start": "2023-05-31T23:00:00+00:00",
            "end": null,
            "tariff_code": "E-1R-VAR-22-11-01-H",
            "product_code": "VAR-22-11-01"
          }
        ]
      }
    ],
    "gas_meter_points": [
      {
        "mprn": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "consumption_units": "m\u00b3",
            "is_smart_meter": true,
            "device_id": "**REDACTED**",
            "manufacturer": "123E - Flonidan",
            "model": "00000300",
            "firmware": "04080605"
          }
        ],
        "agreements": [
          {
            "start": "2023-07-20T23:00:00+00:00",
            "end": null,
            "tariff_code": "G-1R-VAR-22-11-01-H",
            "product_code": "VAR-22-11-01"
          }
        ]
      }
    ]
  }
}
```

I've also enabled debug logging on the integration and can provide those logs when they're collected.

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by AlecRust** [comment]
Ah, there's no electricity data in my Octopus app, so I guess the issue likely lies outside of this integration.

Pretty strange the electricity meter has stopped reporting. I've power cycled the Home Mini, and plugged in the In-home Display in the hope that fixes the issue, but it stays in "Waiting for current data" mode.

I do still receive emails of my usage that contains electricity data though. So I guess the meter is sending to Octopus, but not the Home Mini or IHD. Don't suppose you've bumped into this before?

**Comment by pcb1962** [comment]
If you setup the Bright app on your phone that will tell you whether your
meter is reporting to the DCC - who are responsible for forwarding the data
to Octopus.

**Comment by AlecRust** [comment]
Thanks @pcb1962 I've setup that app using the GUID from the bottom of my IHD, and it's showing gas meter data, but no electricity meter data. Does this suggest the electricity meter is not reporting to Data Communications Company (DCC) ?

**Comment by AlecRust** [comment]
Octopus have surprisingly quickly responded to my enquiry, confirming they're unable to connect to my electricity smart meter. Whatever the issue is, it's unrelated to this integration.

**Comment by pcb1962** [comment]
> Does this suggest the electricity meter is not reporting to Data Communications Company (DCC) ?

Yes, the company behind the Bright app connect directly to the DCC so it's a useful tool for checking whether the hop from meter to DCC is broken. If Bright can't see your data then Octopus probably can't either.
