### ISSUE TITLE
Target Sensor calculation 

### ISSUE THREAD

**Issue by Rhysgh** [BottlecapDave/HomeAssistant-OctopusEnergy#651]
### Describe the bug

It looks like there may be a bug in its calculation, see images. 

Current rates sensor has data untill - 

- start: '2023-12-20T22:30:00+00:00'
  end: '2023-12-20T23:00:00+00:00'
  value_inc_vat: 0.02772

this can also be seen in the UI on the dashboard. 

with target sensor set 09:00 - 22:30 for 0.5 I would assume the 22:30 slot to be the one chosen but its missed. 

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/57257743/b7fe7003-3a22-4d36-812b-fd42489ef23f)

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/57257743/15e1ebf5-1649-4bcd-a5e2-29500094ecb7)

at the moment I cant get into vs code so i cant remove the error for agile times and test 23:30.. 

### Reproduction steps

as above

### Expected behaviour

as above

### Tariff Code

agile

### Integration Version

9.2.1

### Home Assistant Version

latest

### Fresh Install?

Not specified

### Home Assistant Logs

n/a

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. 22:30 has been set as the end time, whereas the slot you're referring to starts at 22:30 so wouldn't be picked.

**Comment by Rhysgh** [comment]
I assumed that but i cant choose 23:30 because of error handling 
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/57257743/c28f8446-b1d9-4116-a566-b9a6665e5ba5)

**Comment by Rhysgh** [comment]
im an idiot, i just realised it ..
