### ISSUE TITLE
No setup option for once a day targets

### ISSUE THREAD

**Issue by corvus2606** [BottlecapDave/HomeAssistant-OctopusEnergy#66]
**Describe the bug**

Documentation refers to a Limit to once a day checkbox to only run a target once, however no such checkbox is visible in the setup dialogues

**To Reproduce**

when opening the workflow to create a new target sensor, no option to set for once a day

**Expected behavior**

there should be a checkbox as described in documentation

**Home Assistant Version**

2022.9.7

**Integration Version**

4.4.0

**Fresh Install?**

fresh install

**Home Assistant Logs**

**Comment by BottlecapDave** [comment]
Sorry about this - this feature hadn't been released. It should now be available in the latest version.
