### ISSUE TITLE
I'm probably missing something but...

### ISSUE THREAD

**Issue by johnthomas22** [BottlecapDave/HomeAssistant-OctopusEnergy#662]
### Describe the feature

If I've understood this right, I can set up target rate sensors to switch on when the cheapest X hours occurs during a 24 hour period. (I'm on Agile, so 16:00 to 16:00.)

I want to use the sensors to trigger EV charging. But with a 7.3kW home charge-point, the amount of time needed depends on the charge level of the car's drive battery.

`Battery Level | Required kWh | Hours
10% | 58.5 | 8
20% | 52.0 | 7
30% | 45.5 | 6
40% | 39.0 | 5
50% | 32.5 | 4
60% | 26.0 | 4
70% | 19.5 | 3
80% | 13.0 | 2
90% | 6.5 | 1
` 

### Expected behaviour

So I don't even know if this is possible with HA templates, but I need the target sensor to accept the number of hours required as a parameter I think. 

The only way I can think of implementing this at the moment is having a 1, 2, 3, 4, 5, 6, 7 & 8 hour sensor, with a corresponding set of on, and off automations.  (Ideally the sensors need to be intermittent, so I use all the cheapest 30 minute periods.)

### Use Case

The amount of time required to charge an EV is dependent on the state of charge of the drive batteries and is different every time the car is parked. So I can't know in advance how long a target rate sensor should be set for. 

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. Your suggestion is not possible with OE entities. However, I believe what you're after is actually the [update config service](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/services/#octopus_energyupdate_target_config) where you can update the target number of hours on the fly. A number of users have used this to adjust their targets for batteries as well.

**Comment by johnthomas22** [comment]
Thanks, great suggestion.
