### ISSUE TITLE
Flux Peak Rate not reporting correct value

### ISSUE THREAD

**Issue by jwt99412** [BottlecapDave/HomeAssistant-OctopusEnergy#666]
### Describe the bug

Since swapping over from fixed to Flux Import and Export, I have noticed that the peak import rate value is being reported as 0.34 p/kWh rather than 0.391 p/kWh (correct up to 31/12). All the other rates are as per the rate tariff published by Octopus. I appreciate you may just be reporting data sent to you by Octopus so it might be something at their end.
![Screenshot 2024-01-01 at 14 48 01](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/135855523/50c02f68-99df-4e53-93a4-b2a743a1d9a0)

### Reproduction steps

As per the screenshot look at the history plot for the current rate. This anomaly is reproduced in the previous and next rate sensors also.

### Expected behaviour

Expect the current rate to track the published Octopus tariff.

### Tariff Code

sensor.octopus_energy_electricity_15k0018408_1012419776440_current_rate

### Integration Version

9.2.1

### Home Assistant Version

2023.12.3

### Fresh Install?

After upgrading

### Home Assistant Logs

I don't have any logs but if necessary I could enable debug logging. However this appears to be an issue which persists so not sure there is an event other than the rate should change to the peak rate value at 4:00pm and change back to the mid rate at 7:00pm

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. Can you please submit your tariff in the form of `E-1R-xxx` so I can take a closer look? Also have you previously set any [pricing caps](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/setup/account/#pricing-caps) which might be doing this? This can be confirmed by looking at the [attributes](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/entities/electricity/#current-rate) of your current rate sensor during the period which will be true if a manual pricing cap has been set.

**Comment by jwt99412** [comment]
![Screenshot 2024-01-02 at 10 36 13](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/135855523/bc701d92-2f7f-4dbe-81d3-1390a5c46ebb)
Sorry didn't know how to get the correct tariff string but it is in here. There seems to be a price cap defined but I haven't explicitly set it. Maybe I have just swapped over from the standard flexible tariff and it is a hold over. I have the Octopuswatch app on my phone and it correctly shows the peak rate as 40.9p/kWh (as of 1 Jan)

**Comment by jwt99412** [comment]
After re reading your comment above I went back to the configuration of the integration and found the optional caps in there. I don't recall setting them up in there myself. Should I blank them to remove the cap?

**Comment by jwt99412** [comment]
![Screenshot 2024-01-02 at 10 55 36](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/135855523/ffab70bf-368d-4cf9-b885-198f8b8c4a73)
price cap removed and it is now showing the correct maximum in the attribute. Thanks for the pointer I am new to all this. I will close the thread :)

**Comment by BottlecapDave** [comment]
Glad this was the issue. You would have set them yourself (they're blank by default), but it was probably over a year ago :)
