### ISSUE TITLE
Gas Previous Accumulative Cost Override Fails

### ISSUE THREAD

**Issue by mth211** [BottlecapDave/HomeAssistant-OctopusEnergy#670]
### Describe the bug

Gas Previous Accumulative Cost Override Fails - all other sensors update as expected but gas fails and just repeats previous values

### Reproduction steps

Unknown - nothing changed on config side and all other sensors are reporting back a-ok

### Expected behaviour

Change in value every day

### Tariff Code

G-1R-VAR-22-11-01-J (this is previous rate setting)

### Integration Version

9.2.1

### Home Assistant Version

2023.12.4

### Fresh Install?

Not specified

### Home Assistant Logs

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:698
First occurred: 1 January 2024 at 18:30:55 (4712 occurrences)
Last logged: 09:46:39

Update for sensor.octopus_energy_gas_AAAA_BBBB_previous_accumulative_cost_override fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 698, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await self.async_update()
  File "/config/custom_components/octopus_energy/gas/previous_accumulative_cost_override.py", line 123, in async_update
    is_old_data = (result is not None and (self._next_refresh is None or result.last_retrieved >= self._last_retrieved)) and (self._next_refresh is None or current >= self._next_refresh)
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'datetime.datetime' and 'NoneType'

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
This should now be resolved in v10.0.1
