### ISSUE TITLE
Deprecated constants log error in Home Assistant 2024.1

### ISSUE THREAD

**Issue by jamespreedy** [BottlecapDave/HomeAssistant-OctopusEnergy#673]
### Describe the bug

See below logs - various constants used in the custom component will be depreciated in a future version of Home Assistant.
I appreciate this is something that everyone will see, but if I can help with any additional logs etc, please let me know - I'll be happy to help how I can.

```
Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 7:57:45 am (26 occurrences)
Last logged: 7:57:48 am

ENERGY_KILO_WATT_HOUR was used from octopus_energy, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues
VOLUME_CUBIC_METERS was used from octopus_energy, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfVolume.CUBIC_METERS instead, please create a bug report at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues
```

### Reproduction steps

Reboot Home Assistant 2024.1.x or later, and check the system logs - error should have appeared as below.

### Expected behaviour

Would expect to not see the errors.

### Tariff Code

n/a

### Integration Version

v9.2.1

### Home Assistant Version

2024.1.x

### Fresh Install?

After upgrading

### Home Assistant Logs

```
Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 7:57:45 am (26 occurrences)
Last logged: 7:57:48 am

ENERGY_KILO_WATT_HOUR was used from octopus_energy, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues
VOLUME_CUBIC_METERS was used from octopus_energy, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfVolume.CUBIC_METERS instead, please create a bug report at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues
```

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Thank you for raising. This should be resolved in the latest release ([v10.0.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v10.0.0))
