### ISSUE TITLE
Octopus Intelligent Dispatching doesn't change to 'Off' when switch:octopus_energy_a_xxxxx_intelligent_smart_charge is turned off

### ISSUE THREAD

**Issue by liquidv** [BottlecapDave/HomeAssistant-OctopusEnergy#675]
### Describe the bug

Octopus Intelligent Dispatching doesn't change to 'Off' when switch:octopus_energy_a_xxxxx_intelligent_smart_charge is turned off
Issue started 2nd January 2024 and still on going, only changes to 'Off' when 05:30 morning. Coincides with offpeak slot ends.

### Reproduction steps

Turn on: switch:octopus_energy_a_xxxxx_intelligent_smart_charge
Turn off: switch:octopus_energy_a_xxxxx_intelligent_smart_charge

Watch dispatching not disappear

### Expected behaviour

binary_sensor.octopus_energy_a_xxxxxx_intelligent_dispatching should 'turned off' after flicking the smart charge switch.

### Tariff Code

E-1R-INTELLI-VAR-22-10-14-C

### Integration Version

9.2.1

### Home Assistant Version

2024.1.0

### Fresh Install?

Not specified

### Home Assistant Logs

n/a

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by liquidv** [comment]
![history](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/122752718/9611c310-725a-4eec-8739-aa0ebfe2c20a)

**Comment by BottlecapDave** [comment]
Hello. This behaviour is documented in the docs and has been te behaviour since v8.3.0. The off peak periods to my knowledge apply regardless if you have smart charging turned on which is why they're not filtered out.

**Comment by liquidv** [comment]
Hi Dave, thanks for the reply.
I know the on period applies between 23:30-05:30 regardless if the switch is on or off, however as per picture shown when the switch is off, dispatching still shows 'on' status between the hours of 20:00-23:30 even though it's not meant to be?

**Comment by liquidv** [comment]
Probably an Octopus API issue, can't see it being an issue with Integration

**Comment by BottlecapDave** [comment]
Sorry I mistook your issue. The sensor goes on/off if you're within a pending dispatch or within the off peak time. There's a chance either the API is continuing to return pending dispatches even though you've turned it off or after you've turned it off it's failing to get the updated pending dispatches and therefore working off an old schedule. If it happens again, could you please check the pending_dispatches attribute of the sensor and report back if this has values or not?

**Comment by liquidv** [comment]
Funny enough it isn't doing it again tonight, but I did update to your latest Integration before the dispatch slot so not sure if that fixed it or was an issue with Octopus.... 

If it happens again I will post. Thanks
