### ISSUE TITLE
Octopus Integration won't start - intelligent dispatch issue

### ISSUE THREAD

**Issue by pgit2345** [BottlecapDave/HomeAssistant-OctopusEnergy#679]
### Describe the bug

Don't have an EV/charger, but do have a GivEnergy battery on Intelligent Octopus Flux. 

Got this error on startup of the integration since upgrading HA and Octopus integration

  File "/config/custom_components/octopus_energy/intelligent/__init__.py", line 220, in get_intelligent_features
    if provider.upper() in FULLY_SUPPORTED_INTELLIGENT_PROVIDERS:
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'upper'

### Reproduction steps

Restart integration, fails with error. Entities no longer show on dashboard. 

### Expected behaviour

It should start (not sure what else to say!)

### Tariff Code

E-1R-INTELLI-FLUX-IMPORT-23-07-14-E

### Integration Version

v10.0.0

### Home Assistant Version

11.3 (core 2024.1.1, super 2023.12.0)

### Fresh Install?

After upgrading

### Home Assistant Logs

Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 7:18:17 PM (4 occurrences)
Last logged: 7:24:42 PM

Error setting up entry A-5*****2D for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 91, in async_setup_entry
    await async_setup_dependencies(hass, config)
  File "/config/custom_components/octopus_energy/__init__.py", line 219, in async_setup_dependencies
    planned_dispatches_supported = get_intelligent_features(intelligent_device["provider"]).planned_dispatches_supported if intelligent_device is not None else True
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/intelligent/__init__.py", line 220, in get_intelligent_features
    if provider.upper() in FULLY_SUPPORTED_INTELLIGENT_PROVIDERS:
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'upper'

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by pgit2345** [comment]
I should add I also see a charger entity with items such as ready time. All entities disabled of course, as the integration can't start. Think it assumes I have a car charger, which I don't!

**Comment by pgit2345** [comment]
Rolled back to v9.2.1 of the integration for now, integration starts and entities showing on dashboard again, updating again etc.

**Comment by BottlecapDave** [comment]
Hello. Sorry that you've received this issue. Those entities should only appear if it manages to get intelligent device information from the API. Do those entities still exist on v9.2.1?

**Comment by pgit2345** [comment]
![Screenshot_20240105_205002_Home Assistant](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/139350802/2313a7d2-0d7a-4c11-8923-a9a1390f9620)

Yeah, the device and the entities (some disabled) still seem to exist. But at least it's working for now!

**Comment by BottlecapDave** [comment]
Ok. That looks like another bug. They should be removed and the issue fixed in the next release.

**Comment by BottlecapDave** [comment]
This should now be resolved in v10.0.1.
