### ISSUE TITLE
Gas current usage unavailable 

### ISSUE THREAD

**Issue by darrenaf** [BottlecapDave/HomeAssistant-OctopusEnergy#683]
### Describe the bug

Gas current usage in kwh is missing from list of entities and meters now show as unavailable

### Reproduction steps

Check list of entities

### Expected behaviour

Usage in kwh should be showing

### Tariff Code

SILVER-FLEX-22-11-25

### Integration Version

Latest

### Home Assistant Version

Latest

### Fresh Install?

After upgrading

### Home Assistant Logs

Na

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by darrenaf** [comment]
Have now rectified this issue myself.  The entities have been renamed with kwh being added to the name and the ID changed.

**Comment by BottlecapDave** [comment]
Hello. Glad you've managed to find the solution. This name change was highlighted in the changelogs of the updates.
