### ISSUE TITLE
Gas Current Consumption change in display

### ISSUE THREAD

**Issue by Nabys** [BottlecapDave/HomeAssistant-OctopusEnergy#684]
### Describe the bug

Ever since 9.2.1 the gas Current Consumption has changed how it is displayed. Before updating to 9.2.1, the gas Current Consumption would step from one level to the next in a graph. But since updating to 9.2.1, it is displayed as the briefest of spikes which often don't show up at all. 

This was on HA 2023.12. 

The screenshot shows behaviour from before and after updating to 9.2.1. I did not update from 9.2.0. I have reverted back to 9.1.0 to check if that was the last one that worked correctly. 

![IMG_6440](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/96481020/89b7c43c-2193-4cfc-b15c-2ca6ae361611)

### Reproduction steps

Updated to 9.2.1 and looked at the graphs in HA. 

### Expected behaviour

The Gas Current Consumption steps from one level to the next, instead of spiking to a level and immediately dropping back to zero. 

### Tariff Code

-

### Integration Version

9.2.1

### Home Assistant Version

2023.13.x

### Fresh Install?

After upgrading

### Home Assistant Logs

-

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by Nabys** [comment]
I can confirm that 9.1.0 was still working as intended. Below screenshot is from today after reverting back to 9.1.0 yesterday evening. 


![IMG_6517](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/96481020/5ff79fb5-1c00-404f-bdeb-f7c396244444)

**Comment by BottlecapDave** [comment]
Hello. This is very odd as the sensor hasn't changed between those versions. However Ill see if I can fix this issue in the future. I think I just need to make sure the underlying data has updated since the last check.

**Comment by BottlecapDave** [comment]
Out of interest, how often do these sensors update their underlying data (based on config)? Have you changed it from the different 2 minutes?

**Comment by Nabys** [comment]
Hi Dave,

By my knowledge I haven't amended any settings. I don't know how to. If you point me in the direction where I can check, I'm more than willing to go and have a look to confirm.

**Comment by BottlecapDave** [comment]
Hello. This should now be fixed in the latest release (v10.0.3).
