### ISSUE TITLE
sensor.octopus_energy_gas_e6xxxxxxxxx_75xxxxxxx_current_accumulative_consumption

### ISSUE THREAD

**Issue by UK-JustinSmall** [BottlecapDave/HomeAssistant-OctopusEnergy#688]
### Describe the bug

Saying

This entity is no longer being provided by the octopus_energy integration. If the entity is no longer in use, delete it in settings.

sensor.octopus_energy_gas_e6xxxxxxx_75yyyyyyyy_current_accumulative_consumption

### Reproduction steps

Added sensor to dashboard used to work fine last few days getting no value back.

### Expected behaviour

Gas usage shown

### Tariff Code

Gas tracker

### Integration Version

V10.0.1

### Home Assistant Version

Core 2023.12.1 Front end 20231208.2

### Fresh Install?

Not specified

### Home Assistant Logs

Na

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. The name of this entity has changed in a recent update which is why you're getting this issue. It now has a _kwh suffix. This was highlighted in the changelogs.
