### ISSUE TITLE
Failed to retrieve smart meter consumption data

### ISSUE THREAD

**Issue by BNWEIN** [BottlecapDave/HomeAssistant-OctopusEnergy#690]
### Describe the bug

Seeing the following error in my logs regularly 

Failed to retrieve smart meter consumption data - using cached version. Next attempt at 2024-01-08 11:16:58.870590+00:00
Failed to retrieve smart meter consumption data - using cached version. Next attempt at 2024-01-08 11:26:03.720610+00:00
Failed to retrieve smart meter consumption data - using cached version. Next attempt at 2024-01-08 11:26:25.870528+00:00
Failed to retrieve smart meter consumption data - using cached version. Next attempt at 2024-01-08 11:28:03.720610+00:00
Failed to retrieve smart meter consumption data - using cached version. Next attempt at 2024-01-08 11:28:25.870528+00:00

### Reproduction steps

Review the logs

### Expected behaviour

Not have these errors in the logs

### Tariff Code

Wasnt able to find this? 

### Integration Version

10.0.2

### Home Assistant Version

2023.12.4

### Fresh Install?

Not specified

### Home Assistant Logs

Failed to retrieve smart meter consumption data - using cached version. Next attempt at 2024-01-08 11:16:58.870590+00:00
Failed to retrieve smart meter consumption data - using cached version. Next attempt at 2024-01-08 11:26:03.720610+00:00
Failed to retrieve smart meter consumption data - using cached version. Next attempt at 2024-01-08 11:26:25.870528+00:00
Failed to retrieve smart meter consumption data - using cached version. Next attempt at 2024-01-08 11:28:03.720610+00:00
Failed to retrieve smart meter consumption data - using cached version. Next attempt at 2024-01-08 11:28:25.870528+00:00

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. These are not errors, but warnings and is as designed to provide transparency as per the [faq](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq/#how-often-is-data-refreshed). This can occur for a multitude of reasons like the API being unavailable, poor internet connection or in the case of the home mini you're reaching [API rate limits](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/setup/account/#refresh-rate-in-minutes). You can also set the log levels of the integration to above warnings if you don't want to see this visability, but might cause confusion if data doesn't update.
