### ISSUE TITLE
Saving sessions greyed out

### ISSUE THREAD

**Issue by Wright55** [BottlecapDave/HomeAssistant-OctopusEnergy#695]
### Describe the bug

The binary sensors for both gas and electricity saving sessions are greyed out. When clicking on these I receive - This entity is no longer being provided by the octopus_energy integration. If the entity is no longer in use, delete it in settings.
Relatively new to Octopus and to this integration (6 weeks), always been greyed out.

### Reproduction steps

N/a

### Expected behaviour

Able to activate entities and date to be available 

### Tariff Code

How do I find

### Integration Version

V10.0.

### Home Assistant Version

2024.1.2

### Fresh Install?

Fresh install

### Home Assistant Logs

Na

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. Saving session entity is at an account level. There is no saving session per energy, but there is wheel of fortune spins. I'm not sure which version you started using the integration but [9.0.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/CHANGELOG.md#900-2023-11-20) introduced the breaking change or renaming the saving session and wheel of fortune entities to include the account id. This was to support future features. From this transition you are now safe to delete the old entities.

Was this the issue?

**Comment by Wright55** [comment]
The documentation refers to support for saving sessions, how do I get notified that a saving session has been created.
Thanks

**Comment by BottlecapDave** [comment]
As per the [docs](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/entities/octoplus/#saving-sessions) you have a saving session at an account level which will turn on/off when you are within a saving session that you have joined.

There is a [service](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/services/#join_octoplus_saving_session_event) available that supports joining a saving session, along with an example blueprint for using this to join saving sessions automatically. You could also use this blueprint for inspiration of an automation which could send a notification via your chosen means.

If you want to be notified of new saving sessions, there is an [event](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/events/#new-saving-session) that is fired when a new event is discovered. You can subscribe to this event via an automation and notify yourself via your chosen means.

Does this solve your issue?

**Comment by Wright55** [comment]
Thank you for your help. I have set up both the event and service. Just need to see what happens when another session is announced. Graham Sent from Mail for Windows From: David KendallSent: 10 January 2024 19:55To: BottlecapDave/HomeAssistant-OctopusEnergyCc: Wright55; AuthorSubject: Re: [BottlecapDave/HomeAssistant-OctopusEnergy] Saving sessions greyed out (Issue #695) As per the docs you have a saving session at an account level which will turn on/off when you are within a saving session that you have joined.There is a service available that supports joining a saving session, along with an example blueprint for using this to join saving sessions automatically. You could also use this blueprint for inspiration of an automation which could send a notification via your chosen means.If you want to be notified of new saving sessions, there is an event that is fired when a new event is discovered. You can subscribe to this event via an automation and notify yourself via your chosen means.Does this solve your issue?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by BottlecapDave** [comment]
In that case it sounds like your original issue is solved, so closing this ticket.
