### ISSUE TITLE
No entities created after logging in

### ISSUE THREAD

**Issue by cooperaj** [BottlecapDave/HomeAssistant-OctopusEnergy#7]
After setting up the integration I get no new entities. My logs contains

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/octopus_energy/__init__.py", line 47, in async_update_data
    current_agreement = get_active_agreement(point["agreements"])
  File "/config/custom_components/octopus_energy/utils.py", line 8, in get_active_agreement
    valid_to = as_utc(parse_datetime(agreement["valid_to"]))
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 133, in parse_datetime
    return ciso8601.parse_datetime(dt_str)
TypeError: argument 1 must be str, not None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/octopus_energy/sensor.py", line 33, in async_setup_entry
    await async_setup_default_sensors(hass, entry, async_add_entities)
  File "/config/custom_components/octopus_energy/sensor.py", line 42, in async_setup_default_sensors
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 161, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: argument 1 must be str, not None
```

Running a manual curl query at the url that provides the 'point' dict (in `async_get_account`) I get a blank response. I ran `curl -u "sk_live_muhkey:" "https://api.octopus.energy/v1/accounts/A-MUHACC"` and get back nothing. Looking at the API documentation I can't even seen a GET /v1/accounts endpoint. There is a POST one but that is for partner organisations only.

**Comment by BottlecapDave** [comment]
Ah I see the issue. I think you're on an tarrif with no current end date, whereas I'm assuming there's always one. I'll rectify this hopefully tonight.

**Comment by cooperaj** [comment]
Think i've cracked it. I get no response to `curl -u "sk_live_muhkey:" "https://api.octopus.energy/v1/accounts/A-MUHACC"` but `curl -u "sk_live_muhkey:" "https://api.octopus.energy/v1/accounts/A-MUHACC/"` brings back everything I expect (note the closing slash)

**Comment by cooperaj** [comment]
```
from homeassistant.util.dt import (utcnow, as_utc, parse_datetime)
import datetime as dt

def get_active_agreement(agreements):
  now = utcnow()

  for agreement in agreements:
    valid_from = as_utc(parse_datetime(agreement["valid_from"]))

    if agreement["valid_to"] is not None:
      valid_to = as_utc(parse_datetime(agreement["valid_to"]))
    else:
      valid_to = now + dt.timedelta(seconds=1)

    if valid_from <= now and valid_to >= now:
      return agreement
  
  return None
```

Python is not my thing but this appears to work.

**Comment by BottlecapDave** [comment]
Yup that's the area. I've updated to handle it slightly differently to how you did it, just because I don't want to make any assumptions. Closing issue as I've applied a fix, but feel free to reopen if my fix is somehow still broken

**Comment by cooperaj** [comment]
Ah, that's the path I took originally but I think won't work. The **valid_to** field will always exist, but the value may either be None or a string. I think (unless my knowledge of Python is way off) the altered code will have the same issue as reported.

**Comment by BottlecapDave** [comment]
I _think_ it should be fine, but to be on the safe side I've added the additional check you had as well.
