### ISSUE TITLE
Inform Intelligent Octopus that charging has commenced

### ISSUE THREAD

**Issue by NickSutton** [BottlecapDave/HomeAssistant-OctopusEnergy#707]
### Describe the feature

Skoda forums have lit up in the past 24hours as Octopus Energy customers are recognising that their cars, or rather VAG, are refusing to tell Octopus when charging has commenced which would normally trigger the charging window to be created and thus the early off-peak rate being applied.

Unsure as to the backstory of this, but was wondering if there is any way your integration can 'tell' IO that charging has commenced from a HA automation etc?

### Expected behaviour

Charging window is calculated.

### Use Case

To reinstate the normal working of IO with Skoda and to restore my blood pressure and stress levels.

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. The API unfortunately doesn't provide charging state. The API also doesn't provide any way of telling OE that charging as commenced, probably because this could be used to game the system.
