### ISSUE TITLE
Adaptation to France

### ISSUE THREAD

**Issue by flouck** [BottlecapDave/HomeAssistant-OctopusEnergy#708]
### Describe the feature

WOuld be great if this custom component would work for French customers as Octopus Energy is growing more and more in France.

### Expected behaviour

Work with https://www.octopusenergy.fr/

### Use Case

French market

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [ ] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. I don't believe the API is available in the french version of the company as it was a buyout and rebrand. In theory, if it moves over to the same technology, the integration should be able to be adapted. But until then, I'll close this issue.
