### ISSUE TITLE
Flexible Plan pricing incorrect after recent price increase.

### ISSUE THREAD

**Issue by bighippo999** [BottlecapDave/HomeAssistant-OctopusEnergy#71]
Hi,

I'm on Octopus Flexible pricing not Agile and been using the addon to keep the pricing up to date.
I've just noticed that the unit price in HomeAssistant is incorrect. I don't think it's a bug with the Addon but just to let you know.

The pricing in HA:
Electric: 0.51821175
Gas: 0.1482159

Both were update on 1st Oct.
But the email from Octopus I received last month advises:
Electricity: Current prices (until 30th September 2022) : 28.287p Without gov. support (from 1st October 2022) : ~~51.821p~~ New prices (from 1st October 2022) : 33.973p

Gas is similar with: Unit rate (per kWh) 7.434p ~~14.822p~~ 10.395p

So HA is seeing the prices that were struck through, not the new prices. I've emailed Octopus to see if this is intentional or if the API is going to be update to reflect the new prices. I'll update if/when I receive a reply.
Just thought it may be of some help to anyone like myself. I'm going to switch HA to a static unit price for the time being.

**Comment by bighippo999** [comment]
Received a response from Octopus:

We are working on getting online accounts updated with the correct energy prices but our priority was getting the PDF's sent out to customers. Please be assured your statement will include the correct pricing and you can see this on our blog here: https://octopus.energy/blog/energy-price-cap-oct-2022/#flexibleoct22rates
I hope that helps but if you have any further questions please do let us know.

Kind regards

**Comment by BottlecapDave** [comment]
Thanks for contacting Ocotpus on behalf of this question, and sorry for the late response. 

Because the rates come from their API, there is unfortuately little I can do without overriding the prices, which would then become wrong once they do fix the prices.

**Comment by bighippo999** [comment]
Thanks @BottlecapDave I didn't want to raise it as a bug as it's not and I agree a temporary fix would break later and the wrong way to go. Just thought it would be worth letting people know. Hopefully Octopus fix the rates soon.

Thanks again,
