### ISSUE TITLE
Charger Device Missing 10.0.2

### ISSUE THREAD

**Issue by warksit** [BottlecapDave/HomeAssistant-OctopusEnergy#712]
### Describe the bug

Charger device (Wallbox) not showing. (All charger entities went unavailable so re-added and now device not showing)

### Reproduction steps

If I upgrade from 10.0.0 to 10.0.2 charger device not there. If I downgrade to 10.0.0 it works fine. 

### Expected behaviour

I expect charger device to be there

### Tariff Code

E-1R-INTELLI-22-03-29-B

### Integration Version

10.0.2

### Home Assistant Version

2024.1.3

### Fresh Install?

Not specified

### Home Assistant Logs

N/A

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. The logic around the intelligent tariffs was tightened to filter out intelligent based tariffs where car charging isn't applicable (e.g. FLUX), and looks like your version of the tariff didn't meet this logic.

This has been fixed in v10.0.3.
