### ISSUE TITLE
Support weekly and monthly cost sensor breakdowns

### ISSUE THREAD

**Issue by BottlecapDave** [BottlecapDave/HomeAssistant-OctopusEnergy#714]
### Describe the feature

The cost sensor should be expanded to support weekly and monthly breakdowns in addition to the current daily breakdowns.

These weekly and monthly breakdowns should have peak/off peak variations

### Expected behaviour

The following sensors should be available

* sensor.octopus_energy_cost_tracker_{{COST_TRACKER_NAME}}_week
* sensor.octopus_energy_cost_tracker_{{COST_TRACKER_NAME}}_week_peak
* sensor.octopus_energy_cost_tracker_{{COST_TRACKER_NAME}}_week_off_peak
* sensor.octopus_energy_cost_tracker_{{COST_TRACKER_NAME}}_month
* sensor.octopus_energy_cost_tracker_{{COST_TRACKER_NAME}}_month_peak
* sensor.octopus_energy_cost_tracker_{{COST_TRACKER_NAME}}_month_off_peak

The day that represents the start of the week should be configurable.

The start day for the month (1-28) should be configurable and effect the month based sensors.

### Use Case

I want to be able to see what my sensors cost me on a daily or monthly basis.

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by Psai** [comment]
Would/should this also include export meters?

**Comment by BottlecapDave** [comment]
Export meters should already be supported (if they're coming through your account), as these are sensors for tracking costs of other entities within HA (e.g. television if you have a sensor reporting it's kwh usage).

**Comment by alfwro13** [comment]
You can already do the same thing with Energy Meter (HACS integration) https://github.com/zeronounours/HA-custom-component-energy-meter

**Comment by BottlecapDave** [comment]
Thank you for raising this as a potential solution. The cost trackers were introduced as I wanted a solution that would adapt automatically when a persons tariff changed and would cope with tariffs with varying rates (like agile). My main issue with the integration you linked is that It's not configurable via the UI - More users who are using HA and this integration are more comfortable with a UI and don't want to be diving into yaml to configure entities. It's crazy a simple accumulation sensor that resets on a schedule isn't available natively in HA.

**Comment by Meatballs1** [comment]
I just feed my cost tracker into utility meter helpers with a monthly schedule and that seems to do this unless I'm missing something.

**Comment by BottlecapDave** [comment]
This is now available as part of v10.2.0
