### ISSUE TITLE
Integration works - but entities don't show information

### ISSUE THREAD

**Issue by NunoMCMoreira** [BottlecapDave/HomeAssistant-OctopusEnergy#72]
Hi, i'm noob on HA, but one of the most exciting features is take control and understand the energy in my home.

what happens, i did the integration, but on the end even after i add the entities in the dashboard, ( after 5 days ) i still with no information recoded, someone can help me with that ? 

thanks

**Comment by NunoMCMoreira** [comment]
![image](https://user-images.githubusercontent.com/113090012/194955581-1e838393-bb60-4d79-b7e2-b240c371f194.png)

![image](https://user-images.githubusercontent.com/113090012/194955657-fe9066eb-6339-4640-a9f0-2913ee35bbe2.png)

**Comment by BottlecapDave** [comment]
Sorry to hear you're having issues with the integration. Are you receiving anything in your Home Assistant logs relating to the integration?

**Comment by NunoMCMoreira** [comment]
[cid:54ab41f5-e592-49d7-b3b0-138e63e9c5ca]

My one start showing something, but is continuous, is only once a day and some days was wrong 🙁  my smart meter is 1st gen so is a bit bad.




________________________________
De: andywilde16 ***@***.***>
Enviado: 19 de outubro de 2022 11:41
Para: BottlecapDave/HomeAssistant-OctopusEnergy ***@***.***>
Cc: NunoMCMoreira ***@***.***>; Author ***@***.***>
Assunto: Re: [BottlecapDave/HomeAssistant-OctopusEnergy] Integration works - but entities don't show information (Issue #72)


Hi, I am also a noob on HA and am getting the same issue and when I look in the logs I can see these errors, can anyone assist me

[image]<https://user-images.githubusercontent.com/58079970/196669405-05a0ccff-ef92-4185-82c5-3fc906266995.png>

I am presuming this is reason why no data is being pulled into HA

Thanks

**Comment by BottlecapDave** [comment]
@NunoMCMoreira Do you see anything when using the normal dashboard/app, as the integration uses the same data? Also do you see anything in your home assistant logs relating to the integration?

@andywilde16 those logbook entries don't look familiar to me. Have you renamed your entities?
