### ISSUE TITLE
Intelligent Charge Limit with Zappi Integration

### ISSUE THREAD

**Issue by dtpazz** [BottlecapDave/HomeAssistant-OctopusEnergy#720]
### Describe the feature

If possible, round "number.octopus_energy_XXXXXXX_intelligent_charge_limit" to the nearest 5% when used with Zappi Integration. I would hope that the api exposes the IO integration type, if it doesnt, feel free to close this feature request.

### Expected behaviour

number.octopus_energy_a_e9ed1dcf_intelligent_charge_limit to be rounded to nearest 5% when used with Zappi integration.

### Use Case

Within the native Octopus app and when using the Zappi Integration, the Intelligent Charge Limit is user definable only to the nearest 5%. Yet currently this Integration evaluates "number.octopus_energy_XXXXXXX_intelligent_charge_limit" to the nearest 1 decimal place. Would suggest matching to ensure the value is handled by Octopus as I presume intended - the nearest 5%.

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by RobinXe** [comment]
Just did some testing with this. If you set the charge limit, via the integration, to a non mod(5) = 0 value, the app does represent the value you've set to the %, rather than to the nearest 5.

I think it's the granularity of the app that it lacking, rather than the integration's being excessive. As the resolution of OE's dispatches is 30 minutes, you'd have to have a really big, or really slow-charging, battery for half an hour of charging to not add at least 5% in one period anyway, I think?

**Comment by BottlecapDave** [comment]
Thanks for contacting. I feel it would be best for the integration to match the app where possible, so I'll hvae a look at updating the controls to support going up/down in 5% increments. I assume the lowest is 5%? As I'm not on intelligent, I was unaware of this. Is there other parts of the integration that should be restricted?

**Comment by dtpazz** [comment]
Thanks Dave. Lowest is 10%. Please see attached.
![1000018359](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/54313766/e5bb0ef5-18fe-4b55-b006-2b30528e41f9)

The only other potential area I've considered, in the interests of preserving performance on Octopus side, is the speed at which you can adjust the charge required value. Every time you define the charge required, a service at Octopus' end must calculate the charge slots. I fear the current integration has the possibility of spamming the Octopus server with multiple requests as it's pretty much instantaneous.

**Comment by RobinXe** [comment]
> Is there other parts of the integration that should be restricted?

The ready time must be between 0400 and 1100. As the default HA time control has you change hrs and mins separately, and updates when you switch between them, the integration can (and will) send an API call that's out of range, returning an error. Example; you're changing 0630 to 1100, and change the hours first, it sends 1130 to the API when you switch to change the minutes, and it throws an exception.

**Comment by BottlecapDave** [comment]
The entity has now been updated in v10.2.0. The time entity in HA doesn't support time restrictions natively, so this restriction has been omitted.
