### ISSUE TITLE
Greenness Forecast Support

### ISSUE THREAD

**Issue by BottlecapDave** [BottlecapDave/HomeAssistant-OctopusEnergy#723]
### Describe the feature

Support the new greenness forecast feature so that people can target days where green sources are most prevalent

Example query
```
{
  greennessForecast {
    validFrom
    validTo
    greennessScore
    greennessIndex
    highlightFlag
  }
}
```

Example response

```
{
  "data": {
    "greennessForecast": [
      {
        "validFrom": "2024-01-24T23:00:00+00:00",
        "validTo": "2024-01-25T06:00:00+00:00",
        "greennessScore": 35,
        "greennessIndex": "MEDIUM",
        "highlightFlag": false
      },
      {
        "validFrom": "2024-01-25T23:00:00+00:00",
        "validTo": "2024-01-26T06:00:00+00:00",
        "greennessScore": 100,
        "greennessIndex": "HIGH",
        "highlightFlag": true
      },
      {
        "validFrom": "2024-01-26T23:00:00+00:00",
        "validTo": "2024-01-27T06:00:00+00:00",
        "greennessScore": 85,
        "greennessIndex": "HIGH",
        "highlightFlag": false
      },
      {
        "validFrom": "2024-01-27T23:00:00+00:00",
        "validTo": "2024-01-28T06:00:00+00:00",
        "greennessScore": 86,
        "greennessIndex": "HIGH",
        "highlightFlag": false
      },
      {
        "validFrom": "2024-01-28T23:00:00+00:00",
        "validTo": "2024-01-29T06:00:00+00:00",
        "greennessScore": 45,
        "greennessIndex": "MEDIUM",
        "highlightFlag": false
      },
      {
        "validFrom": "2024-01-29T23:00:00+00:00",
        "validTo": "2024-01-30T06:00:00+00:00",
        "greennessScore": 68,
        "greennessIndex": "HIGH",
        "highlightFlag": false
      },
      {
        "validFrom": "2024-01-30T23:00:00+00:00",
        "validTo": "2024-01-31T06:00:00+00:00",
        "greennessScore": 82,
        "greennessIndex": "HIGH",
        "highlightFlag": false
      }
    ]
  }
}
```

As per the [forums](https://forum.octopus.energy/t/greenness-forecast-api/8815/17?u=bottlecapdave)

```
    This returns up to the next 7 valid periods (i.e. the next 7 nights that are not completely in the past)
    Only the first 5 periods are used to set the threshold for the highlight flag (due to uncertainty the further ahead the forecast goes)
    You are welcome to ignore the highlight flag (and exclude it from the query) and calculate it yourselves if you want to consider all periods
    The scores are relative and the normalisation will change as more green generation is added (so you can’t necessarily compare scores from different forecast responses)
    Do not assume a fixed length, that the periods are contiguous, non-overlapping or in time order
    The number of results and highlight logic may change
    It updates daily at about 6 or 7 AM
```

### Expected behaviour

Should provide the following

* Coordinator to download the API data. This should follow the standard backoff process and refresh data every 60 minutes (is this too often?).
* Binary sensor (binary_sensor.octopus_energy_{{ACCOUNT_ID}}_greennest_day_today) which turns on when we're in the greennest day as highlighted by Octopus (highlightFlag = true)
* sensor (binary_sensor.octopus_energy_{{ACCOUNT_ID}}_greennest_forecast) to display the score for the current day (and index as attribute), along with the forecast exposed as an attribute.
* Entities should be disabled by default
* Unit and integration tests
* Update docs

### Use Case

Turn on devices during greennest days?

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by ChrisMarriott38** [comment]
Love the sound of this inclusion. I think from looking it does mostly link to Agiles night time pricing, so it would give a great indication for things like Car charging, waiting another day to turn things on at night etc.

**Comment by BottlecapDave** [comment]
You'll be glad to know I've been working on this. Should come in the next release, but no ETA.

**Comment by ChrisMarriott38** [comment]
That's amazing! If you need me to test or anything let me know :) I'm by no means that great with Home Assistant as fairly new to it, but  happy to help if I can.

**Comment by BottlecapDave** [comment]
This is now supported in v10.1.0. List of entities can be found at https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/entities/greenness_forecast/
