### ISSUE TITLE
Next day rates entity not available

### ISSUE THREAD

**Issue by coleburg** [BottlecapDave/HomeAssistant-OctopusEnergy#728]
### Describe the bug

next_day_rates are not available, current and previous both working perfectly.

### Reproduction steps

went into entities, opened event.octopus_energy_electricity_THISHERE_next_day_rates and it shows This entity is unavailable.

### Expected behaviour

should be able to view tomorrows rates

### Tariff Code

https://api.octopus.energy/v1/products/AGILE-23-12-06/electricity-tariffs/E-1R-AGILE-23-12-06-J/standard-unit-rates/

### Integration Version

v10.0.3

### Home Assistant Version

2024.1.5

### Fresh Install?

Fresh install

### Home Assistant Logs

nothing in the logs which relate to next day rates

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. Information can take a little while to come through when you first setup the integration. Have they populated yet? If not, do you have any errors in your logs?

**Comment by coleburg** [comment]
Ignore me, I went into the entity and it was disabled (didnt even know that was an option) enabled and all working like a dream.  Sorry for wasting your time.  

thanks

**Comment by coleburg** [comment]
Ignore me, I went into the entity and it was disabled (didnt even know that was an option) enabled and all working like a dream. Sorry for wasting your time.

thanks

**Comment by BottlecapDave** [comment]
No problem. I was about to suggest this :)
