### ISSUE TITLE
Unable to download update or reinstall

### ISSUE THREAD

**Issue by deano120** [BottlecapDave/HomeAssistant-OctopusEnergy#730]
### Describe the bug

Getting this error in logs when I try to update or reinstall after removing.

A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/BottlecapDave/HomeAssistant-OctopusEnergy/v10.0.3/custom_components/octopus_energy/gas/next_rate.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 4

### Reproduction steps

Unknown, I started off by trying to update to the latest version 10
0.3

### Expected behaviour

It to download and request a restart.

### Tariff Code

Unknown

### Integration Version

10.0.3

### Home Assistant Version

Latest

### Fresh Install?

Not specified

### Home Assistant Logs

A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/BottlecapDave/HomeAssistant-OctopusEnergy/v10.0.3/custom_components/octopus_energy/gas/next_rate.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 4

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. This is unfortunately outside of the integration and you'll need to raise with the HACs team. 

> This is not a problem with HACS but how your host communicates with GitHub

This implies it may be an issue with your instance. I can't really assist with this, but [this thread](https://community.home-assistant.io/t/just-installed-hacs-unable-to-download-anything-due-to-forever-loading/375834/6) implies it might be an issue with IPv6 and your instance.
