### ISSUE TITLE
Electricity Previous Accumulative cost is not taking all Intelligent Completed Dispatches into account when calculating cost 

### ISSUE THREAD

**Issue by mcc05** [BottlecapDave/HomeAssistant-OctopusEnergy#738]
### Describe the bug

Appears that Electricity Previous Accumulative cost is not taking all completed dispatches into account when calculating cost 

### Reproduction steps

Ongoing daily

### Expected behaviour

 Intelligent Completed Dispatches correctly adjust rates for time periods 

### Tariff Code

E-1R-INTELLI-VAR-22-10-14-G

### Integration Version

10.0.4

### Home Assistant Version

2024.1.6

### Fresh Install?

Not specified

### Home Assistant Logs

Example from this morning seem to have missed adjusting the rate for a period

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/38889743/b04de357-c08d-49d7-96d6-ede507c82fd7)

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by mcc05** [comment]
Refreshed the integration and evaluation ran again, now cost has increased and more Intelligent Completed Dispatches rate adjustment are ignored
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/38889743/1f42fc1e-fe92-4893-bc46-0ca64a967e71)

**Comment by BottlecapDave** [comment]
Hello. Assuming the ones that are not in black font are the ones in question, it looks like it's working as it should. You've highlighted on the left hand side for 2024-02-03, but the ones highlighted on the right hand side are for 2024-02-02 (a day earlier). Unless there is something I'm missing?

**Comment by mcc05** [comment]
Sorry missed that on the dates, trying to figure when the cost for previous day stabilises, I have dispatches 21:30/22:00 then 22:30 to 05:30 pretty much every day last week with close to zero use outside these windows due to battery. The calculated cost seems high due to the fact even the battery charging and car in those periods are charged at the 7.5 rate. For example yesterday is showing a cost for 12.285kW of £2.38, but if I just use the 7.5 rate + SC assuming zero outside dispatch windows that's about £1.42, hence why I'm trying to figure it out 
@BottlecapDave thanks for this integration it is brilliant, and hope you have your Oct.Pro working 😆

**Comment by BottlecapDave** [comment]
The cost includes standing charges, but there's an attribute that excludes this, which might be the discrepancy. There's also been reports of octopus not always returning all completed dispatches with certain providers, which is what are used to perform previous cost calculations.

Still waiting on trying to get the pro working :p

**Comment by mcc05** [comment]
My concern is yesterday the 3rd, Octopus dispatched to charge my car 21:30/22:00 and then 22:30 onwards, turns out car was full as charged night before and was left plugged in. But the dispatches still ran as my battery charge triggered from the binary sensor in the integration as not to drain battery while charging the car. So if these periods don't show up in dispatches complete then in this situation we must get charged higher rate? What constitutes a completed dispatch?

**Comment by mcc05** [comment]
I will track this against Octopus bill and re-open if indeed an actual issue

**Comment by BottlecapDave** [comment]
I'm not sure what constitutes as a completed dispatch. My assumption is something that has been reconciled with the charger/vehicle, but OE don't make this very clear and is probably dependent on provider. I'm not on intelligent so can't confirm either way. 

I have been told on the OE forums that the billing department use a different source to the completed dispatches. It's a difficult issue, as there is nothing in the API which confirms that a car is currently charging nor do prices get adjusted, so I have to rely on the completed dispatches for past costs. I could rely on just pending dispatches and store them for longer but these could also be wrong if they're never used. Hense why the dispatching sensor has a warning regarding use.
