### ISSUE TITLE
Prices don't include government cap? 

### ISSUE THREAD

**Issue by lozzd** [BottlecapDave/HomeAssistant-OctopusEnergy#74]
**Describe the bug**

I've just switched to Octopus last week, and as a result am on "Flexible Octopus" (for now) which contractually showed as 52p per kWh, but due to the government cap is actually 34.23p per kWh. The Octopus app and website both show as 34.23p per kWh, but obviously the API does not, as this HA integration is showing 0.52074225 GBP/kWh

```
rate:  
value_exc_vat: 49.5945 
value_inc_vat: 52.074225 
valid_from: '2022-10-17T16:00:00+00:00' 
valid_to: '2022-10-17T16:30:00+00:00' 
tariff_code: E-1R-VAR-22-10-01-H  
is_export: false 
is_smart_meter: true

```

**To Reproduce**

Have a government capped tariff. Sorry! 
I assume this is unlikely to be an issue with the integration and an API issue instead, but I thought I'd check and/or wasn't sure if you had a contact at Octopus rather than attempting to explain this to the standard customer support. 

**Expected behavior**

The correct price is returned. 

**Home Assistant Version**
2022.10.4

**Integration Version**
v4.5.1

**Fresh Install?**
Fresh install

Let me know if debug logs would help.

**Comment by richardproctor90** [comment]
if you are using this for the energy dashboard when you set it up you can state a static price per kwh

**Comment by BottlecapDave** [comment]
Hello, sorry that you've been effected by this. This has been raised previously (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/71). They said they were in the process of updating online when they were contacted by another user. Unfortunately I'm not on an effected plan so not sure what changes they've made. I will contact them and see if they're making any changes to the API that I use.

**Comment by lozzd** [comment]
Ah, didn't think to look for closed issues. Sorry for the dupe. I was thinking of contacting them but I have a couple of other ongoing emails about my switch and they're very busy so don't want things to get missed!

**Comment by BottlecapDave** [comment]
No problem. I'm awaiting an email to find out if the data from the API will be updated. I hope they haven't just updating the website/app to include these caps...

**Comment by lozzd** [comment]
Well put it this way.. my PDF contract had the non-cap price and they said "ignore that, it'll be right on the website..."

**Comment by BottlecapDave** [comment]
🤦

**Comment by FalconUK** [comment]
> yep, have done for now. but when I go to Go having it update live is obviously preferable. But having said that, Go might not have this issue.

Octopus Go isn't a capped tariff. I've just had a statement and my average rate (based on my usage) is 19.31 p/kWh, so well below the cap. The standing charge is 45.06 p/day. All before 5% VAT.

**Comment by lozzd** [comment]
I switched to Go at 3am this morning and the integration instantly showed the correct price and has continued to do so on the day rate. Very cool. 
So my issue is "resolved" and goodness knows what they're doing on the UI side for the capped tariffs 😬

Thanks by the way! Very handy.

**Comment by caraar12345** [comment]
👋 I'm seeing this issue when hitting the REST API endpoint.

```
❯ http https://api.octopus.energy/v1/products/VAR-22-04-02/electricity-tariffs/E-1R-VAR-22-04-02-B/standard-unit-rates/?period_from=2022-11-18T12:00:00Z&period_to=2022-11-18T13:00:00Z

{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "valid_from": "2022-09-30T23:00:00Z",
            "valid_to": null,
            "value_exc_vat": 48.4441,
            "value_inc_vat": 50.866305
        }
    ]
}
```

However, the GraphQL API endpoint which is already being used to grab the tariff code/product code **does** return the correct unit/standing rates. 

<details>
<summary>GraphQL query</summary>

```
query getRates($accountNumber: String!, $propertiesActiveFrom: DateTime) {
  account(accountNumber: $accountNumber) {
    properties(activeFrom: $propertiesActiveFrom) {
      electricityMeterPoints {
        agreements {
          tariff {
            ... on TariffType {
              standingCharge
              preVatStandingCharge
              productCode
            }
            ... on StandardTariff {
              unitRate
              preVatUnitRate
              tariffCode
              productCode
            }
            ... on DayNightTariff {
              dayRate
              preVatDayRate
              nightRate
              preVatNightRate
              tariffCode
              productCode
            }
            ... on HalfHourlyTariff {
              unitRates {
                value
                validFrom
                validTo
              }
              tariffCode
              productCode
            }
            ... on PrepayTariff {
              unitRate
              preVatUnitRate
              tariffCode
              productCode
            }
          }
        }
      }
      gasMeterPoints {
        agreements {
          tariff {
            tariffCode
            productCode
            unitRate
            preVatUnitRate
            standingCharge
            preVatStandingCharge
          }
        }
      }
    }
  }
}
```

</details><details>
<summary>GraphQL response</summary>

```
{
  "data": {
    "account": {
      "properties": [
        {
          "electricityMeterPoints": [
            {
              "agreements": [
                {
                  "tariff": {
                    "standingCharge": 44.12457,
                    "preVatStandingCharge": 42.0234,
                    "productCode": "VAR-22-04-02",
                    "unitRate": 33.01809,
                    "preVatUnitRate": 31.4458,
                    "tariffCode": "E-1R-VAR-22-04-02-B"
                  }
                }
              ]
            }
          ],
          "gasMeterPoints": [
            {
              "agreements": [
                {
                  "tariff": {
                    "tariffCode": "G-1R-VAR-22-04-02-B",
                    "productCode": "VAR-22-04-02",
                    "unitRate": 10.237395,
                    "preVatUnitRate": 9.7499,
                    "standingCharge": 26.84136,
                    "preVatStandingCharge": 25.5632
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```

</details>

Would it be much work to put in a config switch to say whether or not you're on a Government-capped/"more static" tariff and therefore switch to using the response from GraphQL?

**Comment by caraar12345** [comment]
I've had a bit of a play to get it into the original account data that's pulled -- but as someone on a flexible tariff, I forgot to account for fixed tariffs etc: https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/compare/develop...caraar12345:HomeAssistant-OctopusEnergy:develop

It also doesn't change the config flow etc; it's very much just the original query!

**Comment by BottlecapDave** [comment]
> https://api.octopus.energy/v1/products/VAR-22-04-02/electricity-tariffs/E-1R-VAR-22-04-02-B/standard-unit-rates/?period_from=2022-11-18T12:00:00Z&period_to=2022-11-18T13:00:00Z

I've just checked this endpoint and it seems to be returning the value returned by the GraphQL response. Is this still an issue?

**Comment by caraar12345** [comment]
Oh fantastic! Agreed -- it's definitely updated - and apparently did a while ago 😄 

I wish I'd actually checked though. I had it in my head that it was just broken so I spent all of last night writing a Python proxy API that does the GraphQL... dances... and returns a `/get_rates` for the RESTful Sensor.

Guess that's no longer needed! 😂 

Thanks!

**Comment by BottlecapDave** [comment]
I was just about to look at moving to the GraphQL APIs :)

I'm still looking at moving, but I am hestitant only because I can't test other tariffs easily with the GraphQL APIs - it's limited to the tariff associated with the account :(

Sorry for the late response.

**Comment by caraar12345** [comment]
Totally understandable. I'm more than happy to Guinea pig with a "basic" tariff if you need 😃 

But by the looks of things - aside from the tariffs with 3 rates (day, night, standing etc) - it should _largely_ match.
