### ISSUE TITLE
Setting hours to 0

### ISSUE THREAD

**Issue by djdarlo** [BottlecapDave/HomeAssistant-OctopusEnergy#740]
### Describe the feature

Would it be possible to set the number of hours to 0 and therefore return an empty target set.  I am currently using target sets to switch by solar battery charge on and off.  Some days I don't need any charge so would like to set able to set the number of hours to 0.  Currently I set it to a high value and put additional coding in the automation.

### Expected behaviour

When hours is set to 0 no target set is returned.

### Use Case

When it's sunny :) I don't need any battery charge so want to set hours to 0.

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. The integration should allow you to do this already. Are you getting any particular error when attempting to do so?

**Comment by djdarlo** [comment]
It does - my apologies.  I thought I had tried this in the past and it
hadn't worked.  Please close.

**Comment by BottlecapDave** [comment]
No problem. Just hoping I hadn't missed something :)
