### ISSUE TITLE
Tariff change shows previous day accumulation charges with wrong tariff

### ISSUE THREAD

**Issue by pacemaker82** [BottlecapDave/HomeAssistant-OctopusEnergy#748]
### Describe the bug

Change tariffs from agile to IOG

Check the previous day accumulation cost, look at the attributes

Its calculated on the most recent tariff rather than the tariff of the day. In this case its calculated on IOG prices rather than Agile which was active yesterday

<img width="544" alt="Screenshot 2024-02-12 at 13 59 03" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/157808562/32e9b3ec-11ff-42b7-a347-4149f1194906">

### Reproduction steps

as above

### Expected behaviour

Expect previous and today accumulation to be measured against the tariff that was in use at the time. The tariff history is available on the GET account apis.

### Tariff Code

E-1R-INTELLI-BB-VAR-23-03-01-J

### Integration Version

10.0.3

### Home Assistant Version

2024.1.5

### Fresh Install?

Fresh install

### Home Assistant Logs

none

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. Thanks for raising this. I'm not currently sure when I'll get around to fixing it.

**Comment by BottlecapDave** [comment]
Hello. This should be fixed in v10.1.1.
