### ISSUE TITLE
no option to breakout accumulative data from timestamps 

### ISSUE THREAD

**Issue by richardproctor90** [BottlecapDave/HomeAssistant-OctopusEnergy#75]
**Describe the bug**

When we look at the attributes from the accumulative data we can see it gives 30 min breakdowns.

There doesnt appear to be any option to utilise this data.

![image](https://user-images.githubusercontent.com/40702168/197081767-700b3fd9-235b-44e0-8ed3-ff2d856cdeb6.png)

**Comment by BottlecapDave** [comment]
This is meant as additional metadata in case you were wondering where the totals came from. You can utilise [state_attr](https://www.home-assistant.io/docs/configuration/templating/#states) in automations if you wish to do something with this data. What in particular were you after?

**Comment by richardproctor90** [comment]
The ability to plot each half hours usage on a chart.

**Comment by BottlecapDave** [comment]
As mentioned, you can probably extract the data from the attribute and potentially use it as a template sensor. With the way that the API provides the data, all of the data is extracted 24 hours behind which means it can't utilise standard HA charts (as this is plot on sensor value changes). Closing as this request is out of scope for this integration.
