### ISSUE TITLE
Export Name Removed From Current Rate Sensors

### ISSUE THREAD

**Issue by strain10** [BottlecapDave/HomeAssistant-OctopusEnergy#757]
### Describe the bug

Latest release has removed "export" from rate sensors meaning that PredBat cannot find rates as it searches for this to assign export rates.

### Reproduction steps

Export rates are not displayed.

### Expected behaviour

Automations looking for "current export rate" not displaying. 

### Tariff Code

Agile Outgoing

### Integration Version

10.0.1

### Home Assistant Version

2024.2.1

### Fresh Install?

After upgrading

### Home Assistant Logs

No errors reported

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. Nothing has changed in how this is calculated, which means it is most likely the data from OE has changed. Please follow the instruction in the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq/#ive-been-asked-for-my-meter-information-in-a-bug-request-how-do-i-obtain-this) and post the diagnostics from your meter.

**Comment by strain10** [comment]
Dave the entities have returned! 43min ago. I guess OE were having issues at their end. I will keep an eye on it over the next couple of days. Stephen
