### ISSUE TITLE
Add push notification to saving session blueprint

### ISSUE THREAD

**Issue by Peter-HVD** [BottlecapDave/HomeAssistant-OctopusEnergy#758]
### Describe the feature

Please add the ability to send a push notification when a saving session is automatically joined.

### Expected behaviour

Send a push notification when a saving session is automatically joined

### Use Case

When a saving session is automatically joined, there is no information about that except for in the HA dashboard. It would be great to have a notification sent to my iPhone so that I know to turn everything off at the appropriate time!

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [ ] I am willing/able to help contribute to the solution of this feature

**Comment by vansteedens** [comment]
Hi Peter, this is already possible by adding a device action if you have a phone set up with the HA app. This is the visual editor showing mine:

![Screenshot 2024-02-16 at 09 52 24](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/147421043/1fd348bd-54d2-4ae3-9c2a-6abcdeb775b9)

I then just used the message: Joined new Octopus Energy saving session. It starts at {{ trigger.event.data["event_start"].strftime('%H:%M') }} on {{ trigger.event.data["event_start"].day }}/{{ trigger.event.data["event_start"].month }}

Hope that helps and it will send regardless if you have external monitoring of your HA as it's just an app push.

**Comment by Peter-HVD** [comment]
Hi. Thanks, yes I know I can do that myself. My point was it would be nice if it was added to the blueprint so it can be added automatically.

**Comment by Peter-HVD** [comment]
Actually, having said that, I've tried adding an automation and I can't get it to work. Any chance you could share the yaml? Cheers.

**Comment by vansteedens** [comment]
Here you go, I've edited out my ID's and not actually sure how you find out your mobile device ID as can't find it anywhere, mine was added by the visual editor:

```
alias: Octopus Saving Session Joiner
description: Automatically Join Octopus Saving Session Events
trigger:
  - platform: event
    event_type: octopus_energy_new_octoplus_saving_session
condition: []
action:
  - service: octopus_energy.join_octoplus_saving_session_event
    data:
      event_code: "{{ trigger.event.data[\"event_code\"] }}"
    target:
      entity_id: event.octopus_energy_a_xxxxx_octoplus_saving_session_events
  - service: persistent_notification.create
    data:
      title: Octopus Saving Sessions Updated
      message: >
        Joined new Octopus Energy saving session. It starts at {{
        trigger.event.data["event_start"].strftime('%H:%M') }} on {{
        trigger.event.data["event_start"].day }}/{{
        trigger.event.data["event_start"].month }} 
  - device_id: xxxxxx
    domain: mobile_app
    type: notify
    message: >
      Joined new Octopus Energy saving session. It starts at {{
      trigger.event.data["event_start"].strftime('%H:%M') }} on {{
      trigger.event.data["event_start"].day }}/{{
      trigger.event.data["event_start"].month }}
    title: New saving session has been joined
mode: single
```

**Comment by BottlecapDave** [comment]
There is now a [separate version](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/blueprints/#automatically-join-saving-sessions) of the blueprint which supports added custom actions when a saving session is joined
