### ISSUE TITLE
Planned Dispatch source null rather than smart-charge

### ISSUE THREAD

**Issue by andynash** [BottlecapDave/HomeAssistant-OctopusEnergy#767]
### Describe the bug

I'm not sure whether this is an integration issue, or an Octopus issue.

I'm also not sure when this started as I had a separate unrelated issue interfering with my charging automations that was recently fixed (and I'm not sure when, but at least a week or two ago).

Until recently (not sure which version), planned dispatches listed under the dispatch sensor would have the source listed for each dispatch as either smart-charge or rarely, bump-charge.

To avoid charging the home battery amd other consumption during a bump charge, I set up logic that checks the source is smart-charge and only then marks the rate as being off-peak.

I'm now seeing dispatches where the first dispatch in the session is smart-charge and subsequent dispatches have a source of "null".

This means that when this part of the session overnight kicks in, our cars, battery etc stop charging, however the Octopus app shows that this is a valid off-peak session.

It's not clear whether the API is not defining a source and the integration is simply passing this on, or whether the integration is not setting the source correctly?

It's also not clear when the source becomes null - I need to remember to check the planned dispatches when they arrive, to see if later dispatch sources are initially null or change later during the planned session.

This is an example showing that last night the Dispatch sensor was correctly turned on, but my template sensor (that reads the source for the current session) reported unknown as the source was null. This was from 22:59:27 to 07:05:38, when I triggered a new planned dispatch manually. The original session had been from 19:12:24 to 11:00:00 (charger is a 3-pin plug, battery was very low).

![Screenshot_20240218_080005_Home Assistant](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/1126073/7cd2208a-3630-4f82-81a3-42222c414986)

### Reproduction steps

Connect car or adjust target charge etc to trigger a planned dispatch (may need to be before 11.30pm, not certain) so that a multiple dispatch session is created.

One or more later dispatches may have a source of null, but I've not yet observed whether this happens immediately or when the dispatches are refreshed (e.g. when the first ends and is removed from the Planned Dispatches attribute of the Dispatch sensor) and the source changes at that point.

If the source for the current dispatch is null, then changing settings manually (e.g. target charge %) to trigger a new planned dispatch results in a new dispatch with source of smart-charge as expected.

### Expected behaviour

Planned Dispatches to have the source "smart-charge" or "bump-charge".

### Tariff Code

E-1R-INTELLI-VAR-22-10-14-M

### Integration Version

10.1 1 and some earlier versons

### Home Assistant Version

2024.2.1 and some earlier verions

### Fresh Install?

After upgrading

### Home Assistant Logs

I've just enabled debug logging to capture relevant logging tonight.

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. This is a duplication of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/766. As per that issue, the data coming back from OE seems to have changed, for which I'm just passing on the raw value. They recently updated their API to try and combine adjacent dispatches into single dispatches (e.g. 10-11 and 11-12 should come back as 10-12), and so I'm not sure if this bug has been introduced as part of that addition.

I'll close this issue due to the duplication, so please follow [adjacent ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/766) for updates

**Comment by andynash** [comment]
Thanks Dave, will follow #766 👍
