### ISSUE TITLE
Blue charge time slots not visible when viewed with Safari

### ISSUE THREAD

**Issue by CPFC** [BottlecapDave/HomeAssistant-OctopusEnergy#769]
### Describe the bug

Blue charge time slots not visible when viewed with Safari web browser. Work’s perfectly when viewed with the app.

### Reproduction steps

View in a web browser 

### Expected behaviour

Charge times visible 

### Tariff Code

Na

### Integration Version

Latest  version

### Home Assistant Version

Lastest

### Fresh Install?

Fresh install

### Home Assistant Logs

The integration works perfectly otherwise thanks for your time

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. I'm not too sure what this issue is in relation to. Can you take a screenshot of what you're seeing? It feels like it's either an issue with HA UI or with the octopus energy website. Either of these two I'm. It associated with and therefore cannot help with.

**Comment by CPFC** [comment]
Hi DavidThanks for the reply and for setting the intergration up it’s brilliant.I’ve attached a screenshot from my iPad showing the blue timers and from the browser with them missing. I have seen others having the same issue with Windows computers but fine on android as well. Everything works perfectly, the entity is turning my charger on no problem.ThanksSteveOn 19 Feb 2024, at 06:24, David Kendall ***@***.***> wrote:﻿
Hello. I'm not too sure what this issue is in relation to. Can you take a screenshot of what you're seeing? It feels like it's either an issue with HA UI or with the octopus energy website. Either of these two I'm. It associated with and therefore cannot help with.

**Comment by BottlecapDave** [comment]
Unfortunately the screenshot is not attached. If it's a visualisation issue with HA, then this would be out of my control as I don't provide any customised visualisations as part of the integration.

**Comment by CPFC** [comment]
Ok no problem thanksOn 19 Feb 2024, at 09:36, David Kendall ***@***.***> wrote:﻿
Unfortunately the screenshot is not attached. If it's a visualisation issue with HA, then this would be out of my control as I don't provide any customised visualisations as part of the integration.

**Comment by BottlecapDave** [comment]
Closing as I do not believe this is an issue with the integration itself.
