### ISSUE TITLE
Entity icons no longer specific to the value

### ISSUE THREAD

**Issue by markbw999** [BottlecapDave/HomeAssistant-OctopusEnergy#771]
### Describe the bug

Hi, love the integration - thanks. The entity icons used to indicate the type of the value - e.g. £ for a cost entity, lightning bolt for energy, etc. In the last couple of releases these are gone and the icons are generic. Can the previous scheme be reinstated? It makes it much easier to find the specific entity I am searching for.

### Reproduction steps

View the list of integration related entities.

### Expected behaviour

Icons related to the value type.

### Tariff Code

Intelligent Octopus Go

### Integration Version

All since 10.1

### Home Assistant Version

2024.2.2

### Fresh Install?

After upgrading

### Home Assistant Logs

N/A

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. Nothing has actively changed in this area in any of the recent releases. This could be caused by an update that HACS has only partially applied (can happen sometimes) or something with a HA update. 

I'm not currently seeing this on either of my instances (2022.2.2). Can you provide a screenshot of what you're seeing?

**Comment by markbw999** [comment]
Thans for replying so quickly. Here's a screenshot. Should I delete and reinstall the integration?
![Screenshot 2024-02-20 165525](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/61029077/28cdf04e-b004-42c7-af1d-a44a45845f70)

**Comment by pcb1962** [comment]
I see the same when I look at the entities list:
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/5259660/670333c1-45ed-4873-95f9-fad20ccca5b0)
but when I create a card, I have icons:
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/5259660/a1910896-dc87-466f-b2f9-4e07dca1c32f)

**Comment by BottlecapDave** [comment]
Looks like HA introduced in the last updated another way of defining icons. There might be an inconsistency between these two views. I'll have a look into it when I get a chance.

**Comment by markbw999** [comment]
Thanks both. I can confirm I see the same as Peter when I go via the devices.

**Comment by pcb1962** [comment]
FWIW I'm seeing exactly the same with the Tasmota integration - no icons in the entity list but icons are ok on a card.

**Comment by pacemaker82** [comment]
Hmm, its odd. I am on the latest HA 2024.2.3 and latest integration, and its working as expected (maybe it was fixed in yesterday's 2024.2.3 update?):

<img width="482" alt="Screenshot 2024-02-24 at 10 26 43" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/157808562/7dc47412-7667-43fc-b90c-ec1ca68e79bf">

**Comment by BottlecapDave** [comment]
The icons only seem to be wrong if you look at the entities view in settings. If you look at a device or drill into an entity, the icon is correct. So it looks like an inconsistency on the HA side. Either it will be fixed in a future release or break everywhere if how icons are defined changes.

**Comment by BottlecapDave** [comment]
This looks like it was a HA issue (as suspected) and it's been fixed in the latest HA release (2024.4.1)
