### ISSUE TITLE
HA restart causes current cost to be calculated without completedDispatches (IOG)

### ISSUE THREAD

**Issue by pacemaker82** [BottlecapDave/HomeAssistant-OctopusEnergy#777]
### Describe the bug

Similar to: https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/751

If you restart HA, the current import cost resets to a state where your import costs are based on the base tariff without dispatches for some time, until some point where completedDispatches are available again and it recalculates back to where it should be.

Entity: sensor.octopus_energy_electricity_xxx_yyy_current_accumulative_cost

<img width="549" alt="Screenshot 2024-02-24 at 09 10 55" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/157808562/2af21255-7478-4261-8179-ca97a44e7a0b">

Above image shows the spike after restart. Incorrect data is present for around 15mins.

### Reproduction steps

Be on an IOG tariff that had extra cheap slots that day (completedDispatches) in the past.

Restart HA

Check the current day cost entity, it will had changed (got more expensive) since the restart.

### Expected behaviour

Either correctly calculated with the completedDispatches in mind OR does not update the entity until completedDispatches are available. Having the cost frozen in time after restart is better than it calculating with the base tariff I think. (assuming you can tell if they were there and have disappeared/are slow). I assume this might be possible as the dispatches were there pre-re-start and are now unavailable - perhaps calculate on stored dispatches until updated?

### Tariff Code

E-1R-INTELLI-BB-VAR-23-03-01-J

### Integration Version

10.1.4

### Home Assistant Version

2024.2.3

### Fresh Install?

Fresh install

### Home Assistant Logs

n/a

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Sorry you're seeing this. I can apply similar logic to what I did with the other issue. Unfortunately, this probably won't be fixed for little while.

**Comment by BottlecapDave** [comment]
This should now be fixed as part of v10.3.0
