### ISSUE TITLE
string not fully interpolated

### ISSUE THREAD

**Issue by bwduncan** [BottlecapDave/HomeAssistant-OctopusEnergy#783]
### Describe the bug

account_id doesn't get interpolated in translated string

This is a minor bug and with respect to Dave's request to take a step back, it's absolutely not urgent, just putting it here so it doesn't get lost.

### Reproduction steps

have at least one meter which isn't on a home mini, tick the home mini box, integration issue gets raised...

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/469548/8cf88a6a-8ee9-4ad2-9e04-234d04164573)

### Expected behaviour

`{account_id}` should be interpolated

### Tariff Code

NA

### Integration Version

v10.1.4

### Home Assistant Version

2023.2.4

### Fresh Install?

After upgrading

### Home Assistant Logs

NA

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Sorry for the late response. This issue should be fixed in the latest release (v10.2.0)
