### ISSUE TITLE
Add end time/duration to octopus_energy_octoplus_join_saving_session.yml

### ISSUE THREAD

**Issue by reedy** [BottlecapDave/HomeAssistant-OctopusEnergy#786]
### Describe the feature

The blueprint for auto signup and notifications for joining a saving session are great, but the last few have been 30 minutes (rather than the more usual 60 minutes etc), so it would be useful if the end time (and/or duration) of the saving session was included in the notification.

### Expected behaviour

Rather than the current `Joined a new Octopus Energy saving session. It starts at 18:00 on 2/3`, it displays something like `Joined a new Octopus Energy saving session. It starts at 18:00 on 2/3, and ends at 18:30 on 2/3.` or `Joined a new Octopus Energy saving session. It starts at 18:00 on 2/3 and lasts 30 minutes.` or even `Joined a new Octopus Energy saving session. It starts at 18:00 on 2/3, lasts 30 minutes, and ends at 18:30 on 2/3.`

### Use Case

I'm lazy and I don't want to have to open the Octopus App to see its duration. Or in some cases, even HA, as notifications could be pushed to other devices etc.

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
The blueprint has now been updated to include the duration in minutes. There is also a new variation of the blueprint which allows the user to change how the message is sent.
