### ISSUE TITLE
Add saving session duration to event

### ISSUE THREAD

**Issue by reedy** [BottlecapDave/HomeAssistant-OctopusEnergy#788]
### Describe the feature

Include the event duration in the saving session event

https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/b06499c86548847b5c75c17a487a87178f59b64a/custom_components/octopus_energy/coordinators/saving_sessions.py#L73-L81

xref #787 and #786

### Expected behaviour

`event_duration` (or similar, `event_length` etc) will be included in fired event for a saving session upon it being joined.

It may make sense to include similar duration in other saving session related events...

### Use Case

Saves the end user having to do time maths potentially in yaml/templates

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
The saving sessions and event have been updated to include the duration in minutes as part of v10.3.0.
