### ISSUE TITLE
Unmentioned breaking change for Intelligent charging

### ISSUE THREAD

**Issue by furstyferret-dev** [BottlecapDave/HomeAssistant-OctopusEnergy#789]
### Describe the bug

The binary sensor for intelligent discharging has silently changed name to include the account number (as part of the multiple accounts update?). 

This causes automations that rely on this sensor (and others) to silently fail. Don’t remember seeing this mentioned in release notes. 

It can be frustrating because a simple change like this will lead to home batteries discharging into the car during an IO charge cycle. 

### Reproduction steps

Not applicable 

### Expected behaviour

Keep the existing sensor for a little while or notification of a breaking change 

### Tariff Code

N/A

### Integration Version

10.2

### Home Assistant Version

Latest automatic update 

### Fresh Install?

After upgrading

### Home Assistant Logs

N/A

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello, sorry for the late response.

This was highlighted in the breaking change notes for [v9.0.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/CHANGELOG.md#900-2023-11-20)

> Any references to intelligent sensors will need to be updated based on name changes including account id

I try to be careful with breaking changes and release notes.
