### ISSUE TITLE
Gas Sensor History not past 30 days

### ISSUE THREAD

**Issue by MatterSec** [BottlecapDave/HomeAssistant-OctopusEnergy#790]
### Describe the bug

A couple of weeks ago, the gas sensor for "Gas Current Accumulative Consumption" is not showing previous history passed a month in the Energy Dashboard, however the Electricity Current Accumulative Consumption is showing history as normal. Data was there previously and haven't changed the data sources.  Data is showing in Octopus app still.

Is there a new setting for this to extend history past 30 days as showing in the HA Energy Dashboard?

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/58089028/fdcc04af-1636-4429-a952-96c5cd31d982)

### Reproduction steps

HomeMini enabled  running version  10.1.4 on latest Home Assistant.

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/58089028/3c10f9d0-08b0-4a12-8a42-11ed92b4d51e)

### Expected behaviour

History is more than a month, previously was.

### Tariff Code

n/a

### Integration Version

10.1.4

### Home Assistant Version

2024.4.5

### Fresh Install?

After upgrading

### Home Assistant Logs

n/a

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello, sorry for the late response. Nothing has changed in the integration regarding how long data is kept for. The data is posted to the statistics and then HA is in charge of the aggregrations. I can personally see data past 30 days for both of my sensors (not helpful I know).

Unfortunately if you're using the current consumption sensor, there is no service to add data retroactively as HA isn't built for that. This is why the previous consumption sensor has a separate sensor for use with the energy dashboard.

With no further information there isn't a lot I can do I'm afraid. Can you see data for the previous month?
