### ISSUE TITLE
Target rates not always firing

### ISSUE THREAD

**Issue by plord12** [BottlecapDave/HomeAssistant-OctopusEnergy#791]
### Describe the bug

Since the last update I've noticed that target rates are not always firing.

For example I have a simple target rate for "pond" which should switch on my pond pump when cheap rates starts and switches it off when cheap rate finishes.  Looking at the device logbook I see -

- 1st March, 03:30 - Pond turned off ... triggered by state of Octopus Energy Target pond
- 1st March, 23:30 - Pond turned on ... triggered by state of Octopus Energy Target pond
- 2nd March, 03:30 - Pond turned off
- 2nd March, 23:30 - Pond turned on
- 3rd March, 03:30 - Pond turned off - missed on
- 4th March, 03:30 - Pond turned off
- 4th March, 23:30 - Pond turned on
- 5th March, 03:30 - Pond turned off - missed on
- 6th March, 23:30 - Pond turned on - missed off
- 7th March, 03:30 - Pond turned off - missed on

I've not spotted anything useful in the logs (sometimes I see failed to connect to octopus but not at times related to the automation).

When I've manually looked, the entity seems to have the correct times set in attributes.  Eg right now I see -

- rolling target - false
- kind - target_rate
- is target export - false
- last rates - false
- Target times - start: '2024-03-07T23:30:00+00:00',     end: '2024-03-08T00:00:00+00:00', ...   start: '2024-03-08T03:00:00+00:00',   end: '2024-03-08T03:30:00+00:00'

With no specific logs, its obviously hard to pin down the cause, so any debug hints appreciated.

### Reproduction steps

Setup a target rate to trigger when cheap rates start & stop.  Verify these actually trigger.

### Expected behaviour

Automations should be called as scheduled.

### Tariff Code

E-1R-INTELLI-VAR-22-10-14-H

### Integration Version

10.1.4

### Home Assistant Version

2024.3.0

### Fresh Install?

After upgrading

### Home Assistant Logs

Nothing really ... for example, in the missed trigger of 7th March 23:30 I see logs from other components at 23:02 and the next at 00:00 ... just nothing happens at the expected time.

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by plord12** [comment]
Ah.  Probabally a duplicate of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/764

**Comment by BottlecapDave** [comment]
Sorry for the late response.

I suspect as @plord12 mentions, it's probably related to the same issue. I believe I've rectified this issue in the latest release (v10.2.0) by reloading the target rate and cost tracker sensors upon account updates.
