### ISSUE TITLE
Dispatching ending before 30min timeslot

### ISSUE THREAD

**Issue by Reddax** [BottlecapDave/HomeAssistant-OctopusEnergy#793]
### Describe the bug

With the 'Octopus Energy Intelligent Dispatching' sensor, when I unplug my car, i'd expect the dispatching to end at the end of the 30 minute block, but instead, it ends immediately. I believe this should have been fixed in the current version 10.1.4 as in the release notes there's 'Fixed issue when dispatching sensor would not stay on during full half hour when planned dispatch is active'

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/1349626/677a1789-6d1c-4e3a-8a73-a95dfe6494cd)

### Reproduction steps

1. Plug car in to get it charging, Dispatching turns on.
2. Unplug car, dispatching ends within the next 5mins, rather than end of the 30min block.

### Expected behaviour

I'd expect dispatching to run until the end of the 30min block, 00 or 30 min past the hour.

### Tariff Code

 E-1R-INTELLI-VAR-22-10-14-M

### Integration Version

10.1.4

### Home Assistant Version

2024.1.6

### Fresh Install?

Not specified

### Home Assistant Logs

Don't think is required, but can do if needed.

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry for the late response.

The dispatching sensor turns off when there isn't a pending or completed dispatch for the 30 minute period and matches the rate information that is available. It could have been that upon the update of dispatching data, OE removed the pending dispatch but didn't add a completed record (I've had reports of this happening from time to time). The next time this happens, could you please review your rate information and see if the block is reverted back to a peak rate?
