### ISSUE TITLE
Setup asking for developer account Id but Octopus is not providing that value in the developer dashboard

### ISSUE THREAD

**Issue by nomukaiki** [BottlecapDave/HomeAssistant-OctopusEnergy#794]
### Describe the bug

I was mislead by the way to get the account ID because the UI looks like this can be found on the developer dashboard.
But the developer dashboard URL is still wrong which also helped for the confusion.

~~The 2nd field of the setup form is asking for the `account Id` in the format `A-AAAA1111` and to get it from the URL https://octopus.energy/dashboard/developer/~~
1- This URL does not exist anymore and it redirects to https://octopus.energy/dashboard/new/accounts/personal-details/api-access
~~2- The Account ID is not available or visible in that page anymore.~~

![Screenshot 2024-03-11 at 16 21 14](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/6306289/71c8ef22-43cb-4948-ae23-e04a3e39f6c4)

### Reproduction steps

Start the setup of the Octopus Energy HA integration.
Visit the developer dashboard of Octopus.

### Tariff Code

E-1R-AGILE-FLEX-22-11-25-A

### Integration Version

v10.1.4

### Home Assistant Version

2024.3.0

### Fresh Install?

Fresh install

### Home Assistant Logs

not required

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry for the late response.

The url must have changed since. Doesn't sound like a big deal as long as OE is redirecting still to the correct place, but will update.

In terms of the UI, this is unfortunately how HA lays out the information provided to the form (needs more padding), however I'll add a description with further information to the account id field.

**Comment by BottlecapDave** [comment]
This has now been revised as part of v10.3.0 to be clearer.
