### ISSUE TITLE
Saving sessions not working, and not automatically registering

### ISSUE THREAD

**Issue by guy-BW** [BottlecapDave/HomeAssistant-OctopusEnergy#796]
### Describe the bug

previously when saving sessions are generated my automation via the blueprint will automatically register me for the saving session.

This did not happen today.

Executed: 14 March 2024 at 14:14:36
Error: Error rendering data template: UndefinedError: list object has no element 0

`
service: octopus_energy.join_octoplus_saving_session_event
data:
  event_code: '{{ state_attr(saving_session_event_entity, ''available_events'')[0][''code''] }}'
target:
  entity_id: event.octopus_energy_a_dxxxx_octoplus_saving_session_events
`

### Reproduction steps

I'm getting the same error when I manually run the automation.

I'm also seeing the entities for "Octopus Energy saving session" are no longer being updated.

### Expected behaviour

Automatically adding me to the saving session.

### Tariff Code

E-1R-INTELLI-VAR-22-10-14-H

### Integration Version

10.1.4

### Home Assistant Version

2024.3.0 OS 12.1

### Fresh Install?

After upgrading

### Home Assistant Logs

no relevant logs 

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry for the late response.

> Error rendering data template: UndefinedError: list object has no element 0

Unfortunately when automations are manually triggered, they do not adhere to the conditions set, which in the blueprint is making sure there is at least one available event, 

> I'm also seeing the entities for "Octopus Energy saving session" are no longer being updated.

This would be why you weren't registered, as the automation only triggers when the entity updates. The data isn't updated straight away so it might not have been available for you when you thought it should have been.

The entity has a `Data last retrieved` attribute which indicates when it successfully retrieved the data. I'm guessing this is a more recent value as this is an old issue (should be every [15 minutes](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq/)). 

As I haven't seen any other reports, this feels like a bit of an isolated issue and without logs there is very little for me to go on. As saving sessions are now over, I'll close this for now but please raise a new issue if it happens again.
