### ISSUE TITLE
Getting several errors in the logs in home assistant relating to Octopus Integration

### ISSUE THREAD

**Issue by UK-JustinSmall** [BottlecapDave/HomeAssistant-OctopusEnergy#798]
### Describe the bug

Seem to be generating large number of errors connecting to octopus integration 

### Reproduction steps

Checked logs loads of errors

### Expected behaviour

No errors

### Tariff Code

E-1R-OUTGOING-FIX-12M-19-05-13-E E-1R-AGILE-23-12-06-E G-1R-SILVER-23-12-06-E

### Integration Version

Frontend 20240306.0

### Home Assistant Version

Core 2024.3.0

### Fresh Install?

After upgrading

### Home Assistant Logs

Will update in a minute

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by UK-JustinSmall** [comment]
[home-assistant_2024-03-15T21-40-27.948Z.log](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/14621043/home-assi
![Snag_14f599](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/129121587/ce8fd5c4-7298-493c-bcc8-07a7dd3c2f27)
stant_2024-03-15T21-40-27.948Z.log)

**Comment by UK-JustinSmall** [comment]
Further Errors

Logger: custom_components.octopus_energy.coordinators.current_consumption
Source: helpers/update_coordinator.py:331
integration: Octopus Energy ([documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy), [issues](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues))
First occurred: 23 March 2024 at 19:49:55 (2 occurrences)
Last logged: 23 March 2024 at 19:49:55

Error requesting current_consumption_NN-AA-NA-AA-AA-NN-NA-AA data: Cannot connect to host api.octopus.energy:443 ssl:default [Try again]
Error requesting current_consumption_NN-AA-NA-AA-AA-NN-NA-AA data: Cannot connect to host api.octopus.energy:443 ssl:default [Try again]

**Comment by BottlecapDave** [comment]
Hello and sorry for the late response.

The error you have raised suggests that either your internet is down or the OE APIs are unavailable. Both I unfortunately can't help with. These are raised as warnings to bring them to your attention, but the integration will recover once both are back.
