### ISSUE TITLE
Error requesting current_consumption

### ISSUE THREAD

**Issue by UK-JustinSmall** [BottlecapDave/HomeAssistant-OctopusEnergy#804]
### Describe the bug

Logger: custom_components.octopus_energy.coordinators.current_consumption
Source: helpers/update_coordinator.py:331
integration: Octopus Energy ([documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy), [issues](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues))
First occurred: 01:41:37 (1 occurrences)
Last logged: 01:41:37

Error requesting current_consumption_NN-AA-NA-AA-AA-NN-NA-AA data: Cannot connect to host api.octopus.energy:443 ssl:default [Try again]

### Reproduction steps

Checking home assistant logs find this error

### Expected behaviour

No errors

### Tariff Code

E-1R-AGILE-23-12-06-E

### Integration Version

v10.1.4

### Home Assistant Version

2024.3.3

### Fresh Install?

Not specified

### Home Assistant Logs

Logger: custom_components.octopus_energy.coordinators.current_consumption
Source: helpers/update_coordinator.py:331
integration: Octopus Energy ([documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy), [issues](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues))
First occurred: 01:41:37 (1 occurrences)
Last logged: 01:41:37

Error requesting current_consumption_NN-AA-NA-AA-AA-NN-NA-AA data: Cannot connect to host api.octopus.energy:443 ssl:default [Try again]

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry for the late response.

If you are receiving an error of cannot connect to host, then this means your internet has dropped or the API is unavailable, which is unfortunately not something I can assist with.
