### ISSUE TITLE
Heat pump support

### ISSUE THREAD

**Issue by lwis** [BottlecapDave/HomeAssistant-OctopusEnergy#811]
### Describe the feature

The Octopus API exposes basic heat pump controls, it would be great to expose these as a climate entity!

### Expected behaviour

Heat pump controls from Home Assistant

### Use Case

To control the heating from Home Assistant

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by Meatballs1** [comment]
This is just pivoting requests via octopus to the onecta cloud? Just install the Daikin onecta integration and do it direct?

**Comment by BottlecapDave** [comment]
Hello and sorry for the late response.

As @Meatballs1 mentioned it would probably be best to use a more native integration as it might even be local. Does an integration already exist for your heat pump @lwis or is this a bespoke OE heatpump? There seems to be quite a lot of heat pump related APIs, so there is a question of what features are most requested other than all of them :)

As there hasn't been any demand other than yourself and I don't have one myself, it would be quite low down on my list to implement this.

**Comment by neildsb** [comment]
try this one https://github.com/jwillemsen/daikin_onecta

**Comment by lwis** [comment]
@BottlecapDave this is for a Daikin heat pump installed by Octopus, for which they provide a really basic API abstraction. Looking closer at what's currently exposed it's probably not worth the effort!

Daikin are making it harder and harder to access their devices, so this could be something worth revisiting in the (hopefully distant) future!
