### ISSUE TITLE
Previous day peak and off-peak consumption and costs showing as zero

### ISSUE THREAD

**Issue by apbarratt** [BottlecapDave/HomeAssistant-OctopusEnergy#816]
### Describe the bug

The electric consumption and cost for the previous day is only showing totals, not the peak and off-peak values.

For a long time, my current consumption and rates seemed to have stopped updating but this seems to have fixed itself in some update recently so that's nice.
As it was working again, I decided to reintroduce my gauges for yesterday's usage too.  I'm particularly keen to show where we have used too much energy during peak times to try and encourage better usage today but it seems this data is being set to zero.

I'm guessing this is a limitation Octopus has introduced but figured I'd log an issue just in case.

![Screenshot 2024-04-02 at 12 15 08](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/642320/72702308-e230-4bf2-9855-d66500568a2d)

### Reproduction steps

With a tariff such as Intelligent Octopus Go, featuring a binary peak and off-peak rate, observe the sensors for yesterday's usage appear as zero.  The total consumption and cost is working as expected.

### Expected behaviour

Peak and off-peak usage sensors for yesterday should show the breakdown of the previous period's usage and cost.

### Tariff Code

 E-1R-INTELLI-VAR-22-10-14-N

### Integration Version

10.1.4

### Home Assistant Version

2024.3.1

### Fresh Install?

Not specified

### Home Assistant Logs

Happy to provide if pointed in direction of anything particular that may help :) 

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by FalconUK** [comment]
Noticed the same, as of 02/04/24.

**Comment by paulmthomas2** [comment]
Same issues as reported above - all consumption showing peak since 1st April. Thanks

**Comment by BottlecapDave** [comment]
Hello and sorry you're seeing this.

Just to confirm this is with the previous consumption/cost based sensors?

**Comment by FalconUK** [comment]
Hi Dave,

Yes, the following sensors are reporting 0.0.

previous_accumulative_cost_peak
previous_accumulative_cost_off_peak
previous_accumulative_consumption_peak
previous_accumulative_consumption_off_peak

The 'total' consumption and cost sensors are still working okay.

Regards,

Luke

**Comment by TiberiusDarkforge** [comment]
I am also experiencing this issue, with the Peak and Off-peak sensors showing 0, while the Daily Total is still working.


![Screenshot_2024-04-07-02-39-09-33_c3a231c25ed346e59462e84656a70e50](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/46626106/ecd52b51-16da-4246-92fd-02720a610d4e)
![IMG_20240407_023611](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/46626106/dd739740-375a-4711-8b6b-0634d11f63fd)

**Comment by HarryFlatter** [comment]
Hi Dave, 

Sorry, but just to compound this problem, the same issue also applies to the previous export entities:

export_previous_accumulative_consumption_peak
export_previous_accumulative_cost_peak
export_previous_accumulative_consumption_off_peak
export_previous_accumulative_cost_off_peak

As with the 'import' entities, I can confirm that the Totals are still working fine.

**Comment by BottlecapDave** [comment]
No problem, they're all the same sensor. I believe I've tracked down the issue, so the fix should be available in the next release.

**Comment by FalconUK** [comment]
Thanks for the update @BottlecapDave :)

**Comment by TiberiusDarkforge** [comment]
Really appreciate your efforts and support.  You do an amazing job. Thank you.

**Comment by HarryFlatter** [comment]
Thanks for the update @BottlecapDave. Great job!
We'll look forward to the next update.

**Comment by BottlecapDave** [comment]
This should now be fixed as part of v10.3.0

**Comment by HarryFlatter** [comment]
Brilliant job Dave - thanks very much :-)
