### ISSUE TITLE
Huge correction in import consumption during early hours

### ISSUE THREAD

**Issue by pacemaker82** [BottlecapDave/HomeAssistant-OctopusEnergy#817]
### Describe the bug

Edit: Wondering if this is something to do with the BST change and how OE adjusts consumption? I noticed the day of BST change (31st March) my consumption was unusually high, so maybe what happened below was a correction they do?

Original Issue:

Unsure if this is a bug with the integration or OE or what has happened... during the early hours where I was consistently charging my car, I had a massive energy consumption correction:
<img width="597" alt="Screenshot 2024-04-02 at 12 38 22" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/157808562/a4aa573e-eaa4-4309-8a3a-dfc8f51c04fc">

Was a roughly ~6kWh correction, when usually this sensor just increases over time from zero every day. 

Today I have received the previous day consumption for 1st April, its showing no usage for many early hours:
<img width="504" alt="Screenshot 2024-04-02 at 12 41 38" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/157808562/f51f8013-5de4-4c49-8bdc-3a4435ef9489">

From 2.30am to 4.30am there is no import consumption, which is strange since the `Current Accumulative Consumption` clearly showed there was (despite being a weird correction)

### Reproduction steps

as above

### Expected behaviour

I did not expect the ~6kWh correction

I expected the previous day accumulation to reflec energy consumption between 2.30-4.30am

### Tariff Code

E-1R-INTELLI-BB-VAR-23-03-01-J

### Integration Version

Latest

### Home Assistant Version

Latest

### Fresh Install?

Fresh install

### Home Assistant Logs

none

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry for the late response.

The sensor requests the data from the API at the specified intervals (default 1 minute) and sets the state to this value. If there was a correction, it was a change in the data returned by the API. As it's the current consumption sensor, this comes from the mini which might have done it's own corrections on the data it had calculated.

I'm afraid there's very little else to go on, so closing this issue.
