### ISSUE TITLE
Display gas usage in kWh

### ISSUE THREAD

**Issue by tomod3606** [BottlecapDave/HomeAssistant-OctopusEnergy#82]
Hi,
Would it be possible to give the option to display gas usage in kWh rather than m3? While I realise this is the volume of gas used it doesn’t correlate with what my smart meter or bills say is used. 
thanks,

Tom

**Comment by BottlecapDave** [comment]
Hello. This has been done to match the data that the API reports back (and what is displayed on the Octopus energy dashboard). However, you can obtain a calculated kwh from an attribute on the sensor. This can be obtained via a template like so

```
{{ state_attr("sensor.octopus_energy_gas_{{METER_SERIAL_NUMBER}}_{{MPRN_NUMBER}}_previous_accumulative_consumption", "total_kwh") }}
```
