### ISSUE TITLE
First hour of cost tracker missing

### ISSUE THREAD

**Issue by TransientWolf** [BottlecapDave/HomeAssistant-OctopusEnergy#844]
### Describe the bug

My Import Cost Tracker has been wrong by a few pence compared to the energy dashboard since the change to BST in March.  The attributes all track to GMT rather than BST.  Because the cost tracker resets at midnight BST, not midnight GMT, it misses the first hour of the day (00:00-00:59 BST) and includes it in the previous day.  

This seems to be different from the other time bugs as my target sensors all work fine.  Just the cost tracker reset issue.

### Reproduction steps

Set up a cost tracker and check the attributes to confirm that the rates are all mapped to GMT.  Note that at midnight BST the cost tracker resets to zero for the day, rather than at midnight GMT.

### Expected behaviour

Either the rates should be mapped to BST (which would be preferable as it would make reading the attributes much easier during March to October) or the cost tracker daily reset should be at GMT midnight not BST midnight (I assume this is HA driven?).

### Tariff Code

Agile

### Integration Version

10.3.0

### Home Assistant Version

2024.04

### Fresh Install?

Not specified

### Home Assistant Logs

N/A

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by TransientWolf** [comment]
The more I have looked at this the less sure I am that it is the time of the reset.  What I do know is that the tracker seems to be missing about an hours worth of cost at any one time, and that seems to be the cost between 00:00 GMT and 00:00 BST.   So it always under-reports.

**Comment by BottlecapDave** [comment]
Hello and sorry that you're having issues with the cost tracker. The sensor should update whenever the sensor updates that is being tracked. Therefore if it doesn't update during a given 30 minute period, there will be a "missing entry" in the cost tracker. The cost tracker will reset every day at midnight local time (so at the moment BST). 

All rates within the integration are provided in UTC/GMT as this is what OE provide the data as. However I am looking at converting this data into local times for a future release.

Could you please elaborate on what sensor you're tracking the cost of and provide a screenshot of the updates within a certain day along with a screenshot or copy of the tracked changes in the cost tracker. Could you also elaborate on how the cost is being calculated in the energy dashboard?

**Comment by TransientWolf** [comment]
Hi.  The Energy Dashboard tracks a Utility Meter which tracks my GivTCP Import Energy Today Sensor and for cost tracks the Octopus Current Rate from your integration (on an Agile tariff).  The Cost Tracker tracks the same Utility Meter.  The attributes for the Cost Tracker start with the 00:00 to 00:30 (and then 00:30 to 01:00) time slots which are GMT and therefore technically yesterday.  The Energy Dashboard shows a higher number than the cost tracker for import every day.  The export tracker though is correct - I assume because there is nothing happening export wise at midnight GMT or BST.  Interestingly if you look at the movement in the utility meter between 00:00 and 01:00 you can see that in increases in line with consumption, however the Cost Tracker flat lines for the first hour after resetting at midnight.  It is as though it misses the first hour of the day which is also more or less the amount that it is out based on last nights agile rat at mignight.  Screen shots attached.  
<img width="557" alt="Grid Import Today at Midnight" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/78551956/18225495-0761-45e1-ad22-6aca2a32b813">
<img width="559" alt="Grid Import Today at 1am" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/78551956/9b617f81-20d4-4e8d-a42f-1068fd0b627f">
<img width="554" alt="Octopus Import Cost Tracker @ Midnight " src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/78551956/3525f435-24f5-4de5-a1eb-553ea09809cf">
<img width="557" alt="Octopus Import Cost Tracker at 1am" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/78551956/b89bac13-4856-4ba9-9563-6c9488c1d488">
<img width="562" alt="Cost Tracker Import Attribuites" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/78551956/e91174ea-06fc-43d0-8c5f-d8ab8a6b1ed2">
<img width="1085" alt="Energy Dashboard" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/78551956/9a8f5817-cc01-4ebc-9c18-be8ab1e5cb85">
<img width="376" alt="Octopus Import Cost Tracker Configuration " src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/78551956/1acd722e-20d6-4cd7-9576-caeb64d6af77">

**Comment by BottlecapDave** [comment]
Thanks for providing the overview. I'll see if I can recreate it locally.

**Comment by BottlecapDave** [comment]
I unfortunately don't have a utilty meter which updates as frequently as yours. Instead i've setup a cost tracker looking at the current accumulative conumption sensor which is correctly updating frequently after midnight. 

<img width="434" alt="Screenshot 2024-04-23 203237" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/14993950/34a5066b-b974-4cba-940e-b96de194c8db">

Is it possible for you to tell me the value of the tracked sensor at 00:00 and 00:15, 00:30 and 00:45? I'm just wondering if the utility meter isn't updating at the correct intervals.

**Comment by TransientWolf** [comment]
It updates every time there is a 0.1 increase in consumption which for the period above was as per screenshot 1 and for last night when it started charging my battery during the period as per screenshot 2.  As might be expected because it was charging last night during that period this morning the two sensors are massively out.

I will set up a cost tracker linked to the source underlying the utility meter directly and see what happens tonight.


<img width="1396" alt="Cost Tracker Update Screenshot" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/78551956/bc1761d2-7cbc-4a09-bcfd-c384810418cf">

<img width="1391" alt="Cost Tracker Update Screenshot 2" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/78551956/f6aab9f8-d771-4a2e-a77e-48258007e532">

**Comment by TransientWolf** [comment]
If I track the underlying sensor directly I get the same issue - pic below shows test cost tracker on top and the underlying sensor on the bottom.  Am I doing something wrong with the accumulative check box - i have it ticked because it accumulates right?

<img width="1398" alt="Screenshot 2024-04-25 at 10 27 42" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/78551956/7e79fda7-9b5a-4d85-bd82-a221f093b274">

**Comment by BottlecapDave** [comment]
It doesn't look like you're doing anything wrong. The cost tracker looks like it goes up slightly between 00:00 and 01:00. Could it be the costs are so low that the consumption cost is minuscule? If you could 
* Turn on debugging before the problem period - https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging
* Turn off debugging after the problem period, which should provide you with a log file.
* Edit the log file to just lines that include `octopus_energy.cost_tracker` and upload the file here.

If you are comfortable, it would be best to be on the v11.0.0-beta1 when doing this, as this has richer logging around the cost tracker, but the latest stable release should also give some good hints at what's going on.

**Comment by TransientWolf** [comment]
OK.  So I updated to v11.0.0-beta1 last night and enabled debugging but noticed this morning the cost tracker was working correctly!  I see in the target rates attributes they now show BST time with a "+ 1 hour" which is perfect and so much easier to read without adding an hour on in my head.  And for some reason seems to have fixed whatever the issue was with the cost tracker.  Won't bother posting the debug file.

**Comment by TransientWolf** [comment]
Thanks for investigating.  Will close and reopen if it comes back but so far all been fine.
