### ISSUE TITLE
Error "expected str" after fixing any issue in the data while creating a new Target Rate

### ISSUE THREAD

**Issue by heisenberg2980** [BottlecapDave/HomeAssistant-OctopusEnergy#863]
### Describe the bug

After making any mistake while introducing data on the screen and clicking submit, like in this example:

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/58039006/f8922af7-76b7-47f8-9435-a9ae4bc02aa1)

Even after fixing the issue the screen keeps returning the error "expected str", which is confusing as the data is already correct:

![Screenshot 2024-05-05 232209](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/58039006/a203d443-8a7c-46e7-ba33-97764ca70f4f)

After closing the screen and adding the same data again the Target Rate is created, which means the data is correct.

### Reproduction steps

- Click ADD ENTRY in the Octopus Energy integration
- Click Target Rate
- Click Submit
- Fill the data with some error (e.g. including uppercase letters in the name of the target)
- Click SUBMIT
- Fix the error in the data
- Click SUBMIT again, and the error "expected str" appears, event the data is correct

### Expected behaviour

If the data is correct the target rate should be created. It seems when the first error is returned the screen changes the behaviour and expects a string in the hours field instead of a number

### Tariff Code

E-1R-AGILE-24-04-03-B

### Integration Version

10.3.1

### Home Assistant Version

2024.5.1

### Fresh Install?

Not specified

### Home Assistant Logs

N/A

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Thanks for raising this. I'll try and fix this for the next update.

**Comment by BottlecapDave** [comment]
This should now be fixed in [v11.0.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v11.0.0).
