### ISSUE TITLE
Minor UI Annoyance

### ISSUE THREAD

**Issue by theopensourcerer** [BottlecapDave/HomeAssistant-OctopusEnergy#871]
### Describe the bug

When setting up the Energy Dashboard and choosing one of the entities for cost or usage, the dropdown isn't wide enough to show the useful information to decide which option to chose. 

Would it be possible to add a "title" tag to the markup so that if you hover over an option the browser shows you the full name? Screenshot attached showing the issue.

Many thanks

![Screenshot from 2024-05-15 08-09-30](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/3414988/83e0b4be-f6a8-4d6a-aaef-4f8247a51bcf)

### Reproduction steps

Edit the Energy Dashboard, Add a Consumption, Select one of the options for tracking cost, then open the dropdown below and note you can't read the full description.

### Expected behaviour

Somehow display the relevant information

### Tariff Code

E-1R-VAR-22-11-01-H

### Integration Version

10.3.1

### Home Assistant Version

2024.5.3

### Fresh Install?

Fresh install

### Home Assistant Logs

N/A

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. A title tag would be a HA request as I'm not in control of that. However if you update to the latest version (v11.0.0), the names have been adjusted to _hopefully_ have the more useful information at the start of the name. The alternative is to rename the sensors that you're interested in.
