### ISSUE TITLE
Current Accumulative rate on Export Meter

### ISSUE THREAD

**Issue by Codiwr** [BottlecapDave/HomeAssistant-OctopusEnergy#874]
### Describe the feature

Apologies if this is a limitation of Octopus itself.

I have a Octopus Smart Mini and through the integration now have access to current accumulative peak and off peak consumption in Kwh (and cost).

Is there any way of adding these entities to the export tariff meter?

### Expected behaviour

Absent

### Use Case

To calculate real-time energy cost incorporating export 

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [ ] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. Unfortunately OE doesn't expose this information via the Home Mini.

**Comment by Codiwr** [comment]
Not to worry,

Thankyou
