### ISSUE TITLE
Refreshing Gas statistics fails with error

### ISSUE THREAD

**Issue by jwt99412** [BottlecapDave/HomeAssistant-OctopusEnergy#875]
### Describe the bug

Running automation to refresh gas statistics for a previous day failed with an error. See attached screenshot.
![Screenshot 2024-05-17 at 09 35 11](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/135855523/b97a0810-f7be-4afd-bf56-1d25eb46c9e3)

Was after I upgraded to 11.0.0 and I have subsequently enabled some non default entities from the integration looking at override rates. Not sure this is relevant though.

### Reproduction steps

This is the text of my automation:

alias: Refresh Gas Consumption
description: Refresh Consumption if data was missing
trigger:
  - platform: time
    at: "05:30:00"
condition: []
action:
  - service: octopus_energy.refresh_previous_consumption_data
    data:
      start_date: "2024-05-15"
    target:
      entity_id: >-
        sensor.octopus_energy_gas_g4k00385901502_2975461904_previous_accumulative_consumption_m3
mode: single

Ignore the trigger time I have it disabled and trigger it manually if needed.

### Expected behaviour

Expected it to return statistics or at least complete without an error

### Tariff Code

G-1R-VAR-22-11-01-A

### Integration Version

11.0.0

### Home Assistant Version

Core 2024.4.0 Supervisor 2024.05.1 Operating System 12.3 Frontend 20240403.1

### Fresh Install?

After upgrading

### Home Assistant Logs

See screenshot above for step error log

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry you encountered this. This should be fixed in v11.0.1.
