### ISSUE TITLE
Dispatching not turning on (This is a problem at Octopus, read comments in this issue)

### ISSUE THREAD

**Issue by rbrooklyn** [BottlecapDave/HomeAssistant-OctopusEnergy#884]
### Describe the bug

The intelligent_dispatching sensor is currently showing as "off" even though the car is charging via intelligent

current_rate is showing as "unknown". Within that sensor:
is_export: false
is_smart_meter: true
tariff: null
start: null
end: null
is_capped: null
is_intelligent_adjusted: null
current_day_min_rate: null
current_day_max_rate: null
current_day_average_rate: null
data_last_retrieved: 2024-05-25T06:33:31.788661+01:00
last_evaluated: 2024-05-25T06:33:31.898644+01:00
unit_of_measurement: GBP/kWh
device_class: monetary
icon: mdi:currency-gbp

intelligent_dispatching detail is currently (and the car is charging as I create this issue):
planned_dispatches: 
- start: '2024-05-25T05:54:00+01:00'
  end: '2024-05-25T07:30:00+01:00'
  charge_in_kwh: -11.97
  source: null
  location: null
- start: '2024-05-25T07:30:00+01:00'
  end: '2024-05-25T08:00:00+01:00'
  charge_in_kwh: -3.37
  source: null
  location: null

completed_dispatches: 
- start: '2024-05-24T23:00:00+01:00'
  end: '2024-05-24T23:30:00+01:00'
  charge_in_kwh: -2.88
  source: null
  location: AT_HOME
- start: '2024-05-25T00:30:00+01:00'
  end: '2024-05-25T01:00:00+01:00'
  charge_in_kwh: -4.03
  source: null
  location: AT_HOME
- start: '2024-05-25T00:00:00+01:00'
  end: '2024-05-25T00:30:00+01:00'
  charge_in_kwh: -2.88
  source: null
  location: AT_HOME
- start: '2024-05-25T01:00:00+01:00'
  end: '2024-05-25T01:30:00+01:00'
  charge_in_kwh: -2.88
  source: null
  location: AT_HOME
- start: '2024-05-25T02:30:00+01:00'
  end: '2024-05-25T03:00:00+01:00'
  charge_in_kwh: -1.15
  source: null
  location: AT_HOME
- start: '2024-05-25T02:00:00+01:00'
  end: '2024-05-25T02:30:00+01:00'
  charge_in_kwh: -0.57
  source: null
  location: AT_HOME
- start: '2024-05-25T03:30:00+01:00'
  end: '2024-05-25T04:00:00+01:00'
  charge_in_kwh: -3.45
  source: null
  location: AT_HOME
- start: '2024-05-25T03:00:00+01:00'
  end: '2024-05-25T03:30:00+01:00'
  charge_in_kwh: -3.45
  source: null
  location: AT_HOME
- start: '2024-05-25T04:30:00+01:00'
  end: '2024-05-25T05:00:00+01:00'
  charge_in_kwh: -3.45
  source: null
  location: AT_HOME
- start: '2024-05-25T04:00:00+01:00'
  end: '2024-05-25T04:30:00+01:00'
  charge_in_kwh: -3.45
  source: null
  location: AT_HOME
- start: '2024-05-25T05:30:00+01:00'
  end: '2024-05-25T06:00:00+01:00'
  charge_in_kwh: -2.97
  source: null
  location: AT_HOME
- start: '2024-05-25T05:00:00+01:00'
  end: '2024-05-25T05:30:00+01:00'
  charge_in_kwh: -3.35
  source: null
  location: AT_HOME

data_last_retrieved: 2024-05-25T06:29:31.829208+01:00
last_evaluated: 2024-05-25T06:33:31.897670+01:00
provider: TESLA
vehicle_battery_size_in_kwh: 57.5
charge_point_power_in_kw: 7.4
current_start: null
current_end: null
next_start: null
next_end: null
icon: mdi:power-plug-battery
friendly_name: Intelligent Dispatching (A-CBC549CF)

This has been working fine with no changes for several months, although I have not yet smart charged the car since upgrading to 11.0.0 so maybe this is a new bug. I don't often intelligent charge the car, and instead prefer to use a schedule, but my needs required more than the normal overnight offpeak rate.

As you can see from the screenshot, it worked initially, but then something went wrong after midnight:
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/11929484/3ba07b43-da7c-4164-9553-16de06e31cba)

### Reproduction steps

Charge the car using intelligent smart charging

### Expected behaviour

intelligent_dispatching should be "on" when the car is charging

### Tariff Code

current_rate is showing as "unknown"

### Integration Version

11.0.2

### Home Assistant Version

2024.5.5

### Fresh Install?

Not specified

### Home Assistant Logs

[octopus intelligent log.txt](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/15441866/octopus.intelligent.log.txt)

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by rbrooklyn** [comment]
I have reverted to 10.3.1 and the problem is persisting, so I'm unsure if this is a problem at Octopus's end.

**Comment by R-j-walker** [comment]
I'm seeing the same behaviour this morning. So I guess it's likely a problem/change on Octopus's end

**Comment by fm7883** [comment]
Same here, Octopus App shows the extra slot, the car is charging but Dispatching is off hence the home battery is being discharged into the car.

**Comment by danbloor** [comment]
I think Octopus are having issues in general this morning. My dispatching sensor didn't update overnight and I'm now getting no current import rate, only export.

**Comment by bmadgett** [comment]
Same here, predbat has gone haywire wanting to charge all day as it's got a flat default rate rather than usual Cosy figures.

**Comment by rbrooklyn** [comment]
Thank you for your comments, that is reassuring.

I've noticed that if I tap the "Your tariff" link on my electric tariff on the "Usage" tab on the Octopus app, then the app closes. My export and gas tariffs work correctly when "Your tariff" link is pressed. Is anyone else observing the same behavior?

I suspect the two are related.

**Comment by rbrooklyn** [comment]
@BottlecapDave This is probably an issue at Octopus's end.

I'll leave the bug open for now, so anyone experiencing this issue can easily find it and read the comments. Hopefully this will reduce the number of duplicate bugs for something you cannot fix.

We should probably close the bug once we confirm that octopus is fixed.

**Comment by gwilford** [comment]
I monitor two accounts. The one on Agile is working ok but the one using intelligent go is broken this morning. Tariff data is unknown and current demand via the mini is unchanging with its latest update attribute stuck at the time of integration restart.

**Comment by dvptommy** [comment]
Hi all - the “Octopus Intelligent Tariff” integration is actually working still and has picked up the Octopus Intelligent Slot correctly, so I have started amending all my automations to using that one.

**Comment by gwilford** [comment]
A rate gap in the data is tripping up the integration on my IO account...

> Logger: homeassistant
> 
> Source: custom_components/octopus_energy/electricity/__init__.py:67
> integration: Octopus Energy ([documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy), [issues](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues))
> First occurred: 07:49:57 (459 occurrences)
> Last logged: 10:00:17
> 
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/config/custom_components/octopus_energy/electricity/__init__.py", line 65, in calculate_electricity_consumption_and_cost
>     rate = next(r for r in rate_data if r["start"] == consumption_from and r["end"] == consumption_to)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> StopIteration
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
>     await self._async_refresh(log_failures=True, scheduled=True)
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
>     self.async_update_listeners()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
>     update_callback()
>   File "/config/custom_components/octopus_energy/electricity/current_accumulative_consumption.py", line 121, in _handle_coordinator_update
>     consumption_and_cost = calculate_electricity_consumption_and_cost(
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/octopus_energy/electricity/__init__.py", line 67, in calculate_electricity_consumption_and_cost
>     raise Exception(f"Failed to find rate for consumption between {consumption_from} and {consumption_to}")
> Exception: Failed to find rate for consumption between 2024-05-25 04:30:00+00:00 and 2024-05-25 05:00:00+00:00

**Comment by BottlecapDave** [comment]
This integration uses a mixture of tariff rate information and dispatch information. This is because the dispatch information is used to power many parts of the system (e.g. show dispatching sensor, adjust rate information to off peak rates during bespoke dispatches) and so is more coupled to reduce bugs. The downside to this is when information isn't available, more parts are effected.

Based on other reports it looks like OE is having some issues providing the rate information, which is effecting this integration. However there's very little I can do, other than try and recouple the rate and dispatch sensors to try and minimise the number of effected sensors. But this won't be done anytime soon.

**Comment by rbrooklyn** [comment]
This is probably fixed as the octopus app is working properly now.

We'll know for sure if/when the dispatching entity turns on.

**Comment by Tpbradley** [comment]
Dispatching has just worked for me so looks like this is now fixed!

**Comment by rbrooklyn** [comment]
Glad to here it. I'll close the issue.

**Comment by fourmonks** [comment]
Did this happen again last night?

**Comment by R-j-walker** [comment]
> Did this happen again last night?

Yes, sadly it looks like it. It's really not good enough on Octopus's part.

**Comment by BottlecapDave** [comment]
I've raised this in the forums, and it looks like [it's been escalated](https://forum.octopus.energy/t/unitrates-not-populated-for-the-next-24hrs-at-certain-times-of-day/9460/3?u=bottlecapdave), but there's currently no time frame on a fix.

**Comment by rbrooklyn** [comment]
I think its fixed again now, judging by the octopus app no longer crashing on the usage tab.

I think I'll put some automation in to always assume 11:30 to 5:30 is off peak, regardless of what Octopus' API is doing.

**Comment by neildsb** [comment]
> I think I'll put some automation in to always assume 11:30 to 5:30 is off peak, regardless of what Octopus' API is doing.

just done the same, outside this time is a bonus depending on the API
