### ISSUE TITLE
Just adde your latest update will not initialise error and warning logs  

### ISSUE THREAD

**Issue by thorrrr** [BottlecapDave/HomeAssistant-OctopusEnergy#885]
### Describe the bug

After HA update and adding your latest update as of this morning i see error on dashboard  and warning logs 

### Reproduction steps

Nothing to doi its just a error 

### Expected behaviour

It shows not errors or warning logs 

### Tariff Code

Current Rate Electricity (17P5604074 1300004118991)

### Integration Version

11.0.2

### Home Assistant Version

Core 2024.5.5 Supervisor 2024.05.1 Operating System 12.3 Frontend

### Fresh Install?

After upgrading

### Home Assistant Logs

ogger: custom_components.octopus_energy.api_client
Source: custom_components/octopus_energy/api_client/__init__.py:1369
integration: Octopus Energy ([documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy), [issues](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues))
First occurred: 08:12:52 (10 occurrences)
Last logged: 08:17:20

Errors in request (https://api.octopus.energy/v1/graphql/): [{'message': 'Unauthorized.', 'locations': [{'line': 2, 'column': 3}], 'path': ['octoplusAccountInfo'], 'extensions': {'errorType': 'AUTHORIZATION', 'errorCode': 'KT-CT-1111', 'errorDescription': 'The viewer is not authorized to execute the query/mutation. Check authentication or roles/permissions.'}}, {'message': 'Unauthorized.', 'locations': [{'line': 5, 'column': 3}], 'path': ['account'], 'extensions': {'errorType': 'AUTHORIZATION', 'errorCode': 'KT-CT-1111', 'errorDescription': 'The viewer is not authorized to execute the query/mutation. Check authentication or roles/permissions.'}}]

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/8170673/2fe877e8-d9df-4ba4-a677-8a36202b904d)
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/8170673/6d0233bf-645b-4b1f-8fc9-f432e81349df)
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/8170673/3f9864e6-2cec-4e4f-a7ad-7790cbcb9b7b)

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by jwt99412** [comment]
All next, current and previous electricity tariff information showing as unknown from 02:00 BST this morning. Probably Octopus as has been working and I have had 11.0.2 for days.

**Comment by thorrrr** [comment]
Fixed it I renewed my API now working

**Comment by thorrrr** [comment]
Please mark as solved

**Comment by BottlecapDave** [comment]
I'm glad to hear that this was related to your API key. I'll try and add a repair notice for when this error is encountered to make it clearer.

**Comment by jwt99412** [comment]
I think the unknown rates thing is unrelated. Octopus app not showing rates either as is the octopuswatch app. Still think there is an issue at Octopus.

**Comment by BottlecapDave** [comment]
The unknown rates were not related to the original issue. I'll close this ticket in favour of a new one to generate a repair notice in the event of an invalid API key.
