### ISSUE TITLE
Update Target Rate Service template or entity support

### ISSUE THREAD

**Issue by mikihacia** [BottlecapDave/HomeAssistant-OctopusEnergy#888]
### Describe the feature

Would be great to have availability to update the target hours or other input fields when calling the service with the use of either templates or other entities.

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/52580946/3d977059-952e-4db6-9e33-6825545b6084)

### Expected behaviour

Have an option to inject a template or entity to the target hours of the service.

### Use Case

Handful when trying to charge a car and find the best rates based on the requried time to charge.
If I need to charge the car today only for 3 hours, I want to find the best rates only for that time, cause next day I may need to charge it for 6 hours.

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [ ] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. This should already be possible and is something provided by HA and not configurable by the integration. You might have better luck by changing your template to the following
```
"{{ states('sensor.charging_time_required') }}"
```

The error that is being displayed suggests that the state value you've specified either doesn't exist or is not a valid hours number, so you might want to double check this.

**Comment by mikihacia** [comment]
Hi,

The required format is a follows:

`data:
  target_hours: "\"{{ states('sensor.charging_time_required') }}\""`

It cannot be pasted in the UI, must be done in YAML and `"\ ...CODE... \"` is needed.

Thanks for pointing to the right way!
