### ISSUE TITLE
Intelligent Dispatching not triggering for second part of a scheduled charge

### ISSUE THREAD

**Issue by simeon-simsoft** [BottlecapDave/HomeAssistant-OctopusEnergy#889]
### Describe the bug

I have a two segment charging window between 23:30-00:00 and 00:00-06:00.. However the Intelligent Dispatching is off during the second window.

### Reproduction steps

this data taken at 01:23 31/5/24 BST.. the sensor is OFF when it should be ON: (is location=null expected?)

My OCPP charging is charging at this point.

planned_dispatches: 
- start: '2024-05-31T00:00:00+01:00'
  end: '2024-05-31T06:00:00+01:00'
  charge_in_kwh: -42.94
  source: smart-charge
  location: null

completed_dispatches: 
- start: '2024-05-30T23:30:00+01:00'
  end: '2024-05-31T00:00:00+01:00'
  charge_in_kwh: -3.5
  source: null
  location: AT_HOME

data_last_retrieved: 2024-05-31T01:12:39.841940+01:00
last_evaluated: 2024-05-31T01:12:40.007945+01:00
provider: OCPP_WALLBOX
vehicle_battery_size_in_kwh: 39
charge_point_power_in_kw: 6.8
current_start: null
current_end: null
next_start: null
next_end: null
icon: mdi:power-plug-battery
friendly_name: Octopus Energy Intelligent Dispatching

### Expected behaviour

The sensor value should be ON during all scheduled windows

### Tariff Code

E-1R-INTELLI-VAR-22-10-14-L

### Integration Version

11.02

### Home Assistant Version

2024.5.2

### Fresh Install?

Not specified

### Home Assistant Logs

no logs as yet

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by fourmonks** [comment]
Is this related to https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/884 ? Saw this issue today and also with issue #884

**Comment by BottlecapDave** [comment]
Hello. It looks like the OE APIs are failing to return any rate information after 2024-05-31 05:30:00 (similar to [884](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/884) as pointed out). This is not something I'm in control of, so unfortunately there's nothing I can do. I've posted in the OE forums which will hopefully get someone's attention.

**Comment by fourmonks** [comment]
For me, I see Intelligent dispatching goes "on" at 23:30 (start of off peak) and then "off" at 00:00 instead of 05:30. Same thing on 24/25th May - i.e. exactly a week ago so perhap timing is factor. Based upon last week, we might see it return correct status later in the morning.
