### ISSUE TITLE
No best period being found

### ISSUE THREAD

**Issue by usbrit** [BottlecapDave/HomeAssistant-OctopusEnergy#89]
Can anyone help with this please?

No best period being found. Created a 3 hour intermittent timer, but after 24 hours it never turned on.

![image](https://user-images.githubusercontent.com/53425475/200879750-a4f69280-d01e-48c9-b61a-def19183783e.png)

**Home Assistant Version**

2022.10.3

**Integration Version**

4.6.4

**Fresh Install?**

Fresh Install

**Comment by corvus2606** [comment]
I'm seeing the same. i've had a few targets working for months, but as of yesterday they are not finding a best time

**Comment by corvus2606** [comment]
I'm seeing this in the debug logs for the integration:
`2022-11-12 21:11:25.002 DEBUG (MainThread) [custom_components.octopus_energy.binary_sensor] None rate periods found for meter ****************`

I've tested the API using CURL, and it's taking about 2 seconds to come back with a full list of rates. so there's something happening with the processing of the data from a quick look

**Comment by BottlecapDave** [comment]
I believe I've found the culprit to this issue and think its related to https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/76. I've released a beta of the fix https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v4.6.5-beta1, but a new release should be available soon. I'll post here once it's available.

**Comment by corvus2606** [comment]
I've just installed the new beta version and on restart I have target times again 😊

**Comment by BottlecapDave** [comment]
This should now be included in the latest release https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/79
