### ISSUE TITLE
Current rate for electricity not working

### ISSUE THREAD

**Issue by blair287** [BottlecapDave/HomeAssistant-OctopusEnergy#897]
### Describe the bug

Current rate for electricity is just unknown won't populate with tariff info stopped working a few days ago.

### Reproduction steps

Nothing to reproduce just not working.

### Expected behaviour

Used to work and switch between day and night costs

### Tariff Code

Says unkown

### Integration Version

11.0.2

### Home Assistant Version

2024.5.5

### Fresh Install?

Fresh install

### Home Assistant Logs

Can't see any errors in logs.

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry that you're having this issue. What tariff are you on? Do you have any errors or warnings related to the integration in your HA logs? What is the value of the data_last_retreived attribute on the sensor and what is the value of the last_evaluated attribute?

**Comment by blair287** [comment]
All show unknown since I uninstalled and tried reinstalling it.

I'm on intelligent octopus go

**Comment by BottlecapDave** [comment]
Could you please follow the [faq](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq/#how-do-i-increase-the-logs-for-the-integration) to get an hour's worth of debug logs and post them here (after you've removed any pii) and also please post the diagnostics as per the [faq](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq/#ive-been-asked-for-my-meter-information-in-a-bug-request-how-do-i-obtain-this)

**Comment by wawyed** [comment]
Hi, I'm having the same issue. It also started happening from the 3rd of June

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/4390806/484ff98d-a5d4-4608-8a5e-b3faedb0c8bd)

I can try get the debug logs and post them.

**Comment by wawyed** [comment]
Okay it suddenly started working again. I have attached the log in case it helps anyway.

[home-assistant_octopus_energy_2024-06-12T10-02-23.692Z.log](https://github.com/user-attachments/files/15802918/home-assistant_octopus_energy_2024-06-12T10-02-23.692Z.log)

**Comment by Smk3416** [comment]
Same issue for me. Just stopped working as of 3rd July. Also on IOG. Initially devices were present just not showing anything, then moved to entities are disabled as unavailable. Attempted a reload and reinstall, now unable to connect to electricity meter (does not appear in integration when put in api etc). Interestingly I also have a home mini which no longer shows data as well for either daily or live. So unsure which end the fault had occurred.

**Comment by BottlecapDave** [comment]
If the API is not returning active electricity meters then no entities will appear. If the meters suddenly disappear on reload without an upgrade, this suggests something wrong from the data returned by OE. If home mini data is also not available in the app, then this further suggests a problem on OE side. If you retrieve the diagnostics in HA as per the faq and supply it here, then that will confirm if meter information is available.

**Comment by Smk3416** [comment]
I had upgraded relatively recently the HA core I think?

I did upgrade your integration after they werent responding in case it was that. That didn’t do any good.

When I reinstalled the integration it didn’t pick up the import meter (it was before but no data was showing for the relevant entities)
Sent from my iPhone

On 8 Jul 2024, at 17:15, David Kendall ***@***.***> wrote:

﻿

If the API is not returning active electricity meters then no entities will appear. If the meters suddenly disappear on reload without an upgrade, this suggests something wrong from the data returned by OE. If home mini data is also not available in the app, then this further suggests a problem on OE side. If you retrieve the diagnostics in HA as per the faq and supply it here, then that will confirm if meter information is available.

**Comment by Smk3416** [comment]
I’ve checked that octopus data is available via the guylipman.com url checker. Data matches what I have on the octopus app.


Sent from my iPhone

On 8 Jul 2024, at 17:15, David Kendall ***@***.***> wrote:

﻿

If the API is not returning active electricity meters then no entities will appear. If the meters suddenly disappear on reload without an upgrade, this suggests something wrong from the data returned by OE. If home mini data is also not available in the app, then this further suggests a problem on OE side. If you retrieve the diagnostics in HA as per the faq and supply it here, then that will confirm if meter information is available.
