### ISSUE TITLE
Sensors Missing - tariff code: E1R-AEVAR-1201-J

### ISSUE THREAD

**Issue by mbittorf** [BottlecapDave/HomeAssistant-OctopusEnergy#90]
**Describe the bug**

I cannot see any of the expected octopus sensors after setting up

I have noted the following relevant entry in the log:

_2022-11-08 23:19:32.624 ERROR (MainThread) [custom_components.octopus_energy] Unexpected error fetching rates data: Unable to extract product code from tariff code: E1R-AEVAR-1201-J_

The version of Home Assistant:

- Home Assistant 2022.11.2
- Supervisor 2022.10.2
- Operating System 9.3
- Frontend 20221108.0 - latest

**Comment by mbittorf** [comment]
I think this issue may have been due to me being on a tariff that was brought over when Octopus merged with Affect energy a few years ago. My tariff was previously shown in the Octopus portal as "Affect Tariff". I spoke to octopus support today who moved me onto a Octopus tariff and the plugin started working as if by magic.

**Comment by BottlecapDave** [comment]
The tariff looks like it's the wrong format. But as they've fixed it for you, I'll now close this issue.
