### ISSUE TITLE
Home Assistant core backup

### ISSUE THREAD

**Issue by andyblac** [BottlecapDave/HomeAssistant-OctopusEnergy#905]
### Describe the feature

Could you add an option to backup Home Assistant data, before doing an upgrade. I always do I backup manually to be safe that if something goes wrong I have a backup that I can restore.

### Expected behaviour

When you click on that Update available button, in the window that opens, add a check box that allows that plugin to backup the Home Assistant database etc.

### Use Case

Helpful that if something goes wrong with the upgrade to the latest version, the user has a core backup they can revert too.

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [ ] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. The is not something I'm in control of as this is the native HA entity provided by HACS. You'll need to probably raise this request in HACS repo.
