### ISSUE TITLE
Entities disappeared since updating to 11.1

### ISSUE THREAD

**Issue by tam481** [BottlecapDave/HomeAssistant-OctopusEnergy#909]
### Describe the bug

The entity created some 44 entities. Most of which stopped working since I updated to 11.1. I removed all entities and the integration itself and reinstalled. Now it's showing only 16 entities most of which are "event.octopus_energy..." type entities. 

I have already restarted HASS after re-installing the integration.

### Reproduction steps

Updated to 11.1

### Expected behaviour

All supported entities.

### Tariff Code

Missing

### Integration Version

11.1

### Home Assistant Version

2024.6.2

### Fresh Install?

After upgrading

### Home Assistant Logs

`{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2024.6.2",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "6.6.31+rpt-rpi-2712",
    "run_as_root": true
  },
  "custom_components": {
    "hildebrandglow_dcc": {
      "documentation": "https://github.com/HandyHat/ha-hildebrandglow-dcc",
      "version": "1.0.3",
      "requirements": [
        "pyglowmarkt==0.5.5"
      ]
    },
    "alexa_media": {
      "documentation": "https://github.com/alandtse/alexa_media_player/wiki",
      "version": "4.10.2",
      "requirements": [
        "alexapy==1.27.10",
        "packaging>=20.3",
        "wrapt>=1.14.0"
      ]
    },
    "pirateweather": {
      "documentation": "https://github.com/alexander0042/pirate-weather-ha",
      "version": "1.5.2",
      "requirements": [
        "python-forecastio==1.4.0"
      ]
    },
    "octopus_energy": {
      "documentation": "https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy",
      "version": "11.1.0",
      "requirements": []
    },
    "watchman": {
      "documentation": "https://github.com/dummylabs/thewatchman",
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "octopus_energy",
    "name": "Octopus Energy",
    "codeowners": [
      "bottlecapdave"
    ],
    "config_flow": true,
    "dependencies": [
      "repairs",
      "recorder"
    ],
    "documentation": "https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy",
    "homekit": {},
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues",
    "ssdp": [],
    "version": "11.1.0",
    "zeroconf": [],
    "is_built_in": false
  },
  "setup_times": {},
  "data": {
    "id": "A-B090F653",
    "octoplus_enrolled": true,
    "electricity_meter_points": [
      {
        "mpan": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "is_export": false,
            "is_smart_meter": true,
            "device_id": "**REDACTED**",
            "manufacturer": "1125 - Shenzhen Kaifa Metering",
            "model": "31324131",
            "firmware": "17101617"
          }
        ],
        "agreements": [
          {
            "start": "2023-10-24T23:00:00+00:00",
            "end": "2024-03-19T00:00:00+00:00",
            "tariff_code": "E-2R-VAR-22-11-01-A",
            "product_code": "VAR-22-11-01"
          },
          {
            "start": "2024-03-19T00:00:00+00:00",
            "end": "2025-03-21T00:00:00+00:00",
            "tariff_code": "E-FLAT2R-SILVER-23-12-06-A",
            "product_code": "SILVER-23-12-06"
          }
        ]
      }
    ],
    "gas_meter_points": [
      {
        "mprn": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "consumption_units": "m\u00b3",
            "is_smart_meter": true,
            "device_id": "**REDACTED**",
            "manufacturer": "1063 - Landis and Gyr",
            "model": "47720101",
            "firmware": "03035524"
          }
        ],
        "agreements": [
          {
            "start": "2023-10-24T23:00:00+00:00",
            "end": "2024-03-19T00:00:00+00:00",
            "tariff_code": "G-1R-VAR-22-11-01-A",
            "product_code": "VAR-22-11-01"
          },
          {
            "start": "2024-03-19T00:00:00+00:00",
            "end": "2025-03-21T00:00:00+00:00",
            "tariff_code": "G-1R-SILVER-23-12-06-A",
            "product_code": "SILVER-23-12-06"
          }
        ]
      }
    ]
  }
}`

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by tam481** [comment]
Just wanted to add that I've downgraded to 11.0.2 and the entities have come back. I can now see Current accumulate consumption, Current demand, etc

**Comment by atmezferix** [comment]
Just like to add its the same for me, all the entities are showing as unavailable in version 11.1.0

other than Off Peak Electricity

**Comment by BottlecapDave** [comment]
Hello and sorry that you're seeing this. Looks like another tariff that doesn't conform to the normal structure. I'll try and get a fix out within the next couple of days and add the tariff to my regression tests.

**Comment by BottlecapDave** [comment]
This should now be resolved as part of v11.1.1.
