### ISSUE TITLE
Wrong tariff reported

### ISSUE THREAD

**Issue by renellis** [BottlecapDave/HomeAssistant-OctopusEnergy#91]
The tariff reported seems to be wrong:

rate:
  value_exc_vat: 64.2159
  value_inc_vat: 67.426695

The correct value should be 44.35 p or 44.76p considering EPG  or not.

I have already contacted Octopus, just posting also here to understand if unybody else is seeying the same issue.

**Comment by p6sfrx725z28knfy** [comment]
@renellis Could this be the same issue described in #74 ?

**Comment by BottlecapDave** [comment]
It looks like Octopus Energy have finally updated their API and this should now be fixed.
