### ISSUE TITLE
Target rates only look at current day not all available rates

### ISSUE THREAD

**Issue by eugeneniemand** [BottlecapDave/HomeAssistant-OctopusEnergy#93]
**Describe the bug**

When setting up a new target rate using continuous and check multiple times a day it seems to only check rates for the current day and not for all available future rates. For example I had many cheap rates overnight but it told me the cheapest three hour period was from 19:30-22:30.

**To Reproduce**

Have cheaper period in the next day and look at sensor for current day

**Expected behaviour**

Best target rate for any of the future periods, not only current day

**Home Assistant Version**

Latest

**Integration Version**

v 4.6.4

**Fresh Install?**

Fresh

**Home Assistant Logs**

this happened a few days ago so I dont have any logs

**Comment by eugeneniemand** [comment]
I just took as screenshot now at 23:37 and you can see it shows no future rates
![image](https://user-images.githubusercontent.com/6813309/205466838-0cb7f254-e7c7-4585-8f20-30b6bb3b1a75.png)
But as per below screenshot you can see there are rates in the future with the cheapest 3 hours probably being around 3:30am
![image](https://user-images.githubusercontent.com/6813309/205466889-37c71222-380f-4c53-9a0e-d5c2f4d48be8.png)

**Comment by BottlecapDave** [comment]
Hello, sorry for the late reply. 

This is the desired behaviour to ensure that the sensor comes on _at least_ once a day. When the next day ticks over it would have found those cheap rates during the night. If you only want the sensor to run once a day, then you need to turn off the rolling target. As mentioned in the [readme](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/README.md), this will find the cheapest blocks per day, and if that block is in the past then it will wait until the following day.
