### ISSUE TITLE
The value of the HTTP Authorization header is not recognized as a valid access credential for this API

### ISSUE THREAD

**Issue by holdestmade** [BottlecapDave/HomeAssistant-OctopusEnergy#936]
### Describe the bug

Getting this warning in my log a couple of times a day

### Reproduction steps

na

### Expected behaviour

na

### Tariff Code

 E-1R-FLUX-IMPORT-23-02-14-M

### Integration Version

11.2.0

### Home Assistant Version

2024.6.3

### Fresh Install?

Not specified

### Home Assistant Logs

`2024-06-25 14:41:15.369 WARNING (MainThread) [custom_components.octopus_energy.api_client] Errors in request (https://api.octopus.energy/v1/graphql/): [{'message': "Value of 'Authorization' header is not a valid credential.", 'locations': [{'line': 2, 'column': 2}], 'path': ['smartMeterTelemetry'], 'extensions': {'errorType': 'AUTHORIZATION', 'errorCode': 'KT-CT-1143', 'errorDescription': 'The value of the HTTP Authorization header is not recognized as a valid access credential for this API.  Valid credentials can be generated by calling the obtainKrakenToken mutation.'}}]`

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry that you're receiving these warnings. I'm not sure why you'd be getting this as the token is refreshed 5 minutes before they expire. The only thing I can think of is the auth APIs were down briefly.
Have you changed your API token? Have you had this warning reported recently? Did you have any other errors/warnings like "Failed to retrieve auth token"?

**Comment by holdestmade** [comment]
Hi,
No, no more errors apart from the 500 error I posted and is now closed. 
These seem to have stopped now, not seen it in a few days
Not changed my API key and not seen any errors about it.

**Comment by BottlecapDave** [comment]
Ok. I don't have a lot to go on unfortunately. My guess would be the API was acting up, as there were other reports of other issues around this time. I'll close this issue for now, but please comment or re-raise if you see it again.
