### ISSUE TITLE
Current Accumulative Cost Electricity not updating since June 16th

### ISSUE THREAD

**Issue by sbonera** [BottlecapDave/HomeAssistant-OctopusEnergy#947]
### Describe the bug

Checking my energy dashboard I saw the grid total kwh but the cost is 0.00 . Have gone through history log and Current Accumulative Cost Electricity has kept the same value of £1.16 and this was last updated on the 16th June.  

### Reproduction steps

Log into Energy dashboard and view Grid Cost which is £.0.00 checked the configured is set as per energy dashboard setup [here]([url]https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/#energy-dashboard(url)) checked integration and reloaded.

### Expected behaviour

The current accumlative cost electricity should be updating daily.

### Tariff Code

22J0109863

### Integration Version

11.2.1 and previous versions

### Home Assistant Version

2024.6.3

### Fresh Install?

Not specified

### Home Assistant Logs

Will Provide if needed

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry that you're seeing this issue.

For the cost sensor, what does the `data_last_retrieved` and `last_evaluated` attributes state? Are they stuck at 16/6/2024? Do you have any errors in your logs relating to the integration? If you reload the integration, does it start coming through again?

**Comment by sbonera** [comment]
Yes checked those attributes and both still on the 16th June.  I have just reloaded the integration and will check the sensor.  Nothing that I can see in the logs.

**Comment by tonyrsutton** [comment]
I am seeing the same issue for both Gas & Electricity for **current_accumulative_consumption** - it's coming back as "The state of these configured entities are currently not available: sensor.octopus_energy_electricity_xxxxxxxxxx_xxxxxxxxxxxxx_current_accumulative_consumption (unknown)"

**Comment by eximo84** [comment]
I'm too seeing this issue. 

sensor.octopus_energy_electricity_xxx_current_consumption showing 0. Last time I had data was 16th August. 

Octopus dashboard shows fine. I have a home mini device.

**Comment by BottlecapDave** [comment]
> I am seeing the same issue for both Gas & Electricity for **current_accumulative_consumption** - it's coming back as "The state of these configured entities are currently not available: sensor.octopus_energy_electricity_xxxxxxxxxx_xxxxxxxxxxxxx_current_accumulative_consumption (unknown)"

@tonyrsutton If the entities are no longer available, this indicates your account is no longer reporting that you have an Octopus Mini. If this is the case, you might need to contact OE to get this resolved. Could you please [follow these instructions](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq/#ive-been-asked-for-my-meter-information-in-a-bug-request-how-do-i-obtain-this) to download your diagnostics and report them here?

> I'm too seeing this issue.
sensor.octopus_energy_electricity_xxx_current_consumption showing 0. Last time I had data was 16th August.
Octopus dashboard shows fine. I have a home mini device.

@eximo84 do you have any errors or warnings in your logs? I assume regarding the last time you saw data, you're getting this information from the `data_last_retrieved` attribute as well? I assume you don't see any data in the history of this sensor either? As the non accumulative version of the sensor is the delta value between updates so can report as zero. Is the accumulative version working fine?

**Comment by sbonera** [comment]
I get feeling its related to mini tooI spoke with octopus and they sent me a new octopus mini after troubleshooting  I assume once the new one is in and my account is updated , the integration will pull the new mini?

**Comment by jbarrett-fmad** [comment]
@BottlecapDave 
Hi Dave,
Unfortunately I am also seeing the same thing, no updates to usage in kwh or £ since 22nd. I have the following in the logs, which would indicate a problem retrieving the data, rather than an issue with the integration:

```
logger: homeassistant.helpers.entity
Source: helpers/entity.py:1270
First occurred: 9:01:38 AM (2 occurrences)
Last logged: 9:01:38 AM

Update of sensor.octopus_energy_electricity_xxxxxxxxxx_xxxxxxxxxx_export_previous_accumulative_consumption is taking over 10 seconds
Update of sensor.octopus_energy_gas_xxxxxxxxxx_xxxxxxxxxx_previous_accumulative_consumption_m3 is taking over 10 seconds
```

I am getting other metrics on time though, like price changes, so I don't think it's a configuration issue. Any advice on next steps would be greatly appreciated.

Thanks,
James

**Comment by BottlecapDave** [comment]
@jbarrett-fmad are you having issues with the current accumulative sensor (which is what this ticket is about) or the previous consumption sensors (which is what your logs are referring to?) The warnings are a bi-produxt of the OE APIs sometimes taking a while to respond, but don't indicate a failure.

**Comment by jbarrett-fmad** [comment]
You're right, I hadn't spotted that. Would you prefer I open a new Issue?
Agreed re the log entries, but I'm not getting anything more granular, yet metrics are not updating since 22/08.
I think it's more likely to be an Octopus issue, but I'd rather have more info before I call them.

**Comment by BottlecapDave** [comment]
So which sensors are you having issues with?

**Comment by jbarrett-fmad** [comment]
Hi Dave,
The metrics seem to have started updating again, so I have to presume it was an API issue.
Thanks anyway.
James

**Comment by jbarrett-fmad** [comment]
Hi Dave.
It was all of the previous accumulated metrics, but data has started to flow again, so must have been at Octopus' end.
Thanks for the reply though, and the awesome integration.

**Comment by BottlecapDave** [comment]
Thanks for getting back to me. You might have been hit by https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/discussions/984
