### ISSUE TITLE
Gas sensors not working

### ISSUE THREAD

**Issue by oneofthemany** [BottlecapDave/HomeAssistant-OctopusEnergy#949]
### Describe the bug

Dashboard no longer shows any of the gas sensors

### Reproduction steps

Go to energy dashboard and view gas sensors data

### Expected behaviour

Visualisation with sensors data

### Tariff Code

E6S11347702161/7725943110

### Integration Version

11.2.1

### Home Assistant Version

Core 2024.7.1 Frontend 20240705.0

### Fresh Install?

After upgrading

### Home Assistant Logs

[octopus_energy-f13d789aa4f5720613bea17ca7fe4b35-Gas Meter-2fb49cd52cca249555ec8d8f3f5e7828.json](https://github.com/user-attachments/files/16156698/octopus_energy-f13d789aa4f5720613bea17ca7fe4b35-Gas.Meter-2fb49cd52cca249555ec8d8f3f5e7828.json)

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry that you're having issues.

If you find the entities in the entities view, do you see the gas sensors and are they available? What version of the integration did you upgrade from? Do you have any errors in your logs?

**Comment by BottlecapDave** [comment]
If you updated from before v10, then [this breaking change](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/CHANGELOG.md#breaking-changes-1) might be effecting you
