### ISSUE TITLE
Wrong naming in the entities 

### ISSUE THREAD

**Issue by girussoMS** [BottlecapDave/HomeAssistant-OctopusEnergy#950]
### Describe the bug

Some entities have been wrongly named to Octoplus instead of Octopus

### Reproduction steps

Check in States and search for octopus and then repeat for OctopLus

### Expected behaviour

You will see results appearing with the both searches

### Tariff Code

event.octoplus_saving_session_events

### Integration Version

11.2.2

### Home Assistant Version

2024.7.2

### Fresh Install?

Not specified

### Home Assistant Logs

n/a

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by AndyBowden** [comment]
I don't think this is wrong. At least in UK, there is an Octoplus service, associated with saving sessions and points.
I see 3 Octoplus HA entities - saving_session, saving_session_events, and points

**Comment by BottlecapDave** [comment]
Hi @girussoMS. As mentioned by @AndyBowden these entities have the naming octoplus after the reward program by Octopus Energy, as that's what these entities related to. This is by design.

**Comment by girussoMS** [comment]
> I don't think this is wrong. At least in UK, there is an Octoplus service, associated with saving sessions and points. I see 3 Octoplus HA entities - saving_session, saving_session_events, and points.
> 
> The value of the points entity corresponds to the value shown on my Octopus app Octoplus page

Apologies. My bad! Thanks for your reply
