### ISSUE TITLE
On Intermittent mode can the total size in minutes of the upcoming block be reported

### ISSUE THREAD

**Issue by Far2Sleepy** [BottlecapDave/HomeAssistant-OctopusEnergy#96]
Feature request.

I'm trying to use my inverter's  force_charge(minutes) feature along side the intermittent mode to make best use of the cheapest overnight 30 minutes blocks. However my problem is as the 30 minutes blocks can follow each other and would therefore only fire one off->on trigger I can't use a default  of 30 in the force_charge command.  If there was a simple mechanism which reported the current block size then I could use that for the force_charge command and greatly simplify my automation trigger setup, plus reduce the number of commands sent to the inverter.

**Comment by BottlecapDave** [comment]
Thanks for the suggestion. I'll take a look and see what I can do

**Comment by BottlecapDave** [comment]
Just wanted to say sorry for the delay in the addition of this, and it's still on my radar to complete.

**Comment by BottlecapDave** [comment]
Hello! Sorry for the late addition, but this should now be available within the latest release (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v5.3.0).

**Comment by Far2Sleepy** [comment]
That's fantastic, Thanks Dave
