### ISSUE TITLE
Using device time rather than system time. 

### ISSUE THREAD

**Issue by markuk98** [BottlecapDave/HomeAssistant-OctopusEnergy#961]
### Describe the bug

Firstly thank you for a great integration. I did use your code when signing up to octopus. I have had great success with the dashboard, the only thing I have an issue with is when looking at the dashboard when I’m not in the same time zone as the server the times are from my phones time rather than the server time. I’m sure there arnt many people that suffer with this issue but would be great if the dashboard could use the server time instead.

### Reproduction steps

Change time zone of viewing device 

### Expected behaviour

Display using system time. 

### Tariff Code

Octopus Agile

### Integration Version

Latest

### Home Assistant Version

Latest 

### Fresh Install?

After upgrading

### Home Assistant Logs

None

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. Unfortunately anything to do with presentation is a HA issue that I'm not in control of. However, looking at my user profile in the HA app suggests you can make it use the server time for presentation which might solve your issue.

![Screenshot_20240802-060154](https://github.com/user-attachments/assets/00194fb7-9d15-45ce-b1e7-773bdb5b922a)
