### ISSUE TITLE
Integration fails to initialise after working fine

### ISSUE THREAD

**Issue by iamrufus** [BottlecapDave/HomeAssistant-OctopusEnergy#963]
### Describe the bug

Integration fails to initialise, the error is saying Invalid API key or account id specified. It was working fine yesterday, regenerated another API key but keep seeing the same error

### Reproduction steps

removed account and try to re-add

### Expected behaviour

initialise as normal

### Tariff Code

cant see this as integration wont load

### Integration Version

12.0

### Home Assistant Version

Core 2024.7.4 Supervisor 2024.06.2 Operating System 12.4 Frontend 20240710.0

### Fresh Install?

Not specified

### Home Assistant Logs

Logger: custom_components.octopus_energy.api_client
Source: custom_components/octopus_energy/api_client/__init__.py:1392
integration: Octopus Energy ([documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy), [issues](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues))
First occurred: 13:27:16 (16 occurrences)
Last logged: 13:43:31

Errors in request (https://api.octopus.energy/v1/graphql/): [{'message': 'Too many requests.', 'locations': [{'line': 2, 'column': 2}], 'path': ['obtainKrakenToken'], 'extensions': {'errorType': 'AUTHORIZATION', 'errorCode': 'KT-CT-1199', 'errorDescription': 'There were too many requests. Please try again later.'}}]

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by iamrufus** [comment]
Just to update the integration seems to initialise fine now. Not sure if it was something on the Octopus end perhaps, not changed anything my end

**Comment by BottlecapDave** [comment]
Hello. Sorry you encountered this issue. It looks the the Auth servers at OE were unavailable. Glad it's working now.
