### ISSUE TITLE
Octoplus points not updating / not provided 

### ISSUE THREAD

**Issue by davidb187** [BottlecapDave/HomeAssistant-OctopusEnergy#966]
### Describe the bug

My octoplus points sensor is no longer collecting the number of octoplus points i have 

### Reproduction steps

status / value of sensor.octopus_energy_a_2422fc45_octoplus_points

### Expected behaviour

current number of octoplus point associated with my account should be displayed

### Tariff Code

 E-1R-AGILE-23-12-06-J

### Integration Version

12.0.1

### Home Assistant Version

2024.7.4

### Fresh Install?

Fresh install

### Home Assistant Logs

[home-assistant_octopus_energy_2024-08-10T14-22-54.022Z.log](https://github.com/user-attachments/files/16569912/home-assistant_octopus_energy_2024-08-10T14-22-54.022Z.log)

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry you've seen this issue. I couldn't recreate this locally, but based on your logs I think I've fixed the issue in v12.0.2. Let me know if this has worked.

**Comment by UK-JustinSmall** [comment]
Can confirm I had same issue on previous version and upgrading to v12.0.2 brought back my octopoints and value. Thank you :-)

**Comment by BottlecapDave** [comment]
@davidb187 are you also happy that this issue has been fixed?

**Comment by davidb187** [comment]
Hi,

Yes,  looks great from here too now

Thanks



On 12 August 2024 04:20:01 BST, David Kendall ***@***.***> wrote:
>@davidb187 are you also happy that this issue has been fixed?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/966#issuecomment-2283048083
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
