### ISSUE TITLE
Use of Target Rate Rule - correct?

### ISSUE THREAD

**Issue by samhankin** [BottlecapDave/HomeAssistant-OctopusEnergy#970]
### Describe the bug

I'm trying to create a target rate rule for Agile that comes on anytime the rate is below 25p - so today it should be on for most of the day, but it's not working as it should and only coming on when my rate is below 15p? I think I'm doing something wrong but not sure what!

### Reproduction steps

<img width="387" alt="Screenshot 2024-08-11 at 12 10 32" src="https://github.com/user-attachments/assets/bfaf8285-185b-4a71-aa13-7486eea64c5b">

### Expected behaviour

The target rate should be on anytime the price drops below 25p.

### Tariff Code

 E-1R-AGILE-BB-23-12-06-A

### Integration Version

12.0.2

### Home Assistant Version

2024.08.0

### Fresh Install?

Fresh install

### Home Assistant Logs

<img width="543" alt="Screenshot 2024-08-11 at 12 12 41" src="https://github.com/user-attachments/assets/930cf18d-34b0-4248-8a2b-1b08cb164466">
<img width="556" alt="Screenshot 2024-08-11 at 12 12 46" src="https://github.com/user-attachments/assets/e06467ed-f907-408c-a6a4-e24c4ac91ee5">

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by samhankin** [comment]
Leaving this here for anyone who makes the same stupid mistake as me in the future...

Rates are in pence - so 25 is £25 not 25p!

Changed to 0.25 and fixed my own issue - sorry!

**Comment by BottlecapDave** [comment]
Thanks for coming back with your solution. You might also want to turn off the re-evaluate multiple times a day as this shouldn't be needed and will only come into effect once all discovered rates are in the past.

Depending on what you're using the target rate sensor for, you might also be better off just looking at the current rate sensor for more simplicity. Target rate sensors only really become valuable if you have a minimum/maximum/set number of hours you require or that you require the hours consecutively. As by the looks of things you just want "turn on below 25p as much as possible whenever", looking at the current rate sensor with a numeric_state check would have the same results.

**Comment by samhankin** [comment]
Of course - thank you, that makes so much sense! Not 100% sure why I was over complicating it so much!
