### ISSUE TITLE
Intelligent Go - Hypervolt Charger Integration

### ISSUE THREAD

**Issue by Quickstep3** [BottlecapDave/HomeAssistant-OctopusEnergy#977]
### Describe the bug

Hypervolt Charger integration is now live for Intelligent Go. HA Octopus integration now reporting a unknown Intelligent provider ‘HYPERVOLT’.

### Reproduction steps

Requires a Hypervolt EV Charger and signing up to Intelligent Go integration

### Expected behaviour

No specific error it seems although the Intelligent Dispatcher sensor is present but no of the other bump charge switch or Intelligent Go sensors available. Presumably as it looks or functions the same as the OHME charger from a code perspective reading the documentation. Not sure if the other switches or sensors should be available for the Hypervolt EV charger integration. NB Zappi charger integration has also recently been added 

### Tariff Code

E-1R-INTELLI-VAR-22-10-14-H

### Integration Version

12.1.0

### Home Assistant Version

2024.8.2

### Fresh Install?

After upgrading

### Home Assistant Logs

This error originated from a custom integration.

Logger: custom_components.octopus_energy.intelligent
Source: custom_components/octopus_energy/intelligent/__init__.py:255
integration: Octopus Energy (documentation, issues)
First occurred: 08:00:21 (6 occurrences)
Last logged: 08:00:23

Unexpected intelligent provider 'HYPERVOLT'

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Thanks for raising this. Due to not all intelligent integrations being the same, new ones need to be enabled manually. For instance, not much is enabled for OHME because it's all handled their side. Could you please confirm what features are enabled by the app with a screenshot? Bump charge, smart charge, planned dispatches, charge target/limit, ready time?

**Comment by Quickstep3** [comment]
![IMG_7584](https://github.com/user-attachments/assets/d68afe55-b98c-4bb6-8258-a0854b09a662)

Bump Charge, target charge%, ready time, and dispatches are available. Had a list of scheduled slots yesterday which were used. Looks like they might not fully have sorted the charge history bit.

**Comment by Quickstep3** [comment]
Here's the completed and planned dispatches from the sensor attribute:

Planned dispatches
Completed dispatches
- start: '2024-08-16T10:30:00+01:00' end: '2024-08-16T11:00:00+01:00' charge_in_kwh: -0.67 source: null location: UNABLE_TO_IDENTIFY
- start: '2024-08-16T10:00:00+01:00' end: '2024-08-16T10:30:00+01:00' charge_in_kwh: -2.67 source: null location: UNABLE_TO_IDENTIFY 
- start: '2024-08-16T09:30:00+01:00' end: '2024-08-16T10:00:00+01:00' charge_in_kwh: -2.85 source: null location: UNABLE_TO_IDENTIFY 
- start: '2024-08-16T09:00:00+01:00' end: '2024-08-16T09:30:00+01:00' charge_in_kwh: -3.12 source: null location: UNABLE_TO_IDENTIFY 
- start: '2024-08-16T08:30:00+01:00' end: '2024-08-16T09:00:00+01:00' charge_in_kwh: -0.04 source: null location: UNABLE_TO_IDENTIFY 
- start: '2024-08-16T08:00:00+01:00' end: '2024-08-16T08:30:00+01:00' charge_in_kwh: -0.93 source: null location: UNABLE_TO_IDENTIFY 
Data last retrieved
17 August 2024 at 14:33:58
Provider
HYPERVOLT
Vehicle battery size in kwh
64
Charge point power in kw
7
Current start
Unknown
Current end
Unknown
Next start
17 August 2024 at 23:30:00
Next end
18 August 2024 at 05:30:00


Have also unplugged and replugged car and it created a schedule for today in the Octopus App even though car is already at 100%:
![IMG_7585](https://github.com/user-attachments/assets/e7077129-6897-4fff-a115-af3256001121)
These showed up somewhere in the Octopus API as the OctoAid App picked them up, but couldn't seem to find them as planned dispatches in the attributes of the dispatching sensor (yet).

**Comment by BottlecapDave** [comment]
The support should now be added as part of v12.2.0

**Comment by Quickstep3** [comment]
Many thanks - updated and seems to picking up the Charge Limit and ready time values from Octopus. Will try another charge in a few days (as car currently at 100%!)

**Comment by BottlecapDave** [comment]
Glad to hear. Ill close this issue. If you have any other issues in the future, please raise a separate ticket.
