### ISSUE TITLE
"Intelligent Charge Limit" vs "Charge to add"

### ISSUE THREAD

**Issue by reedy** [BottlecapDave/HomeAssistant-OctopusEnergy#980]
### Describe the bug

In this add-on, the field is labelled "Intelligent Charge Limit" which feels to have a different meaning to "Charge to add" that is used in the Octopus app.

To me "Charge Limit" seems to suggest the limiting value of the vehicle battery, whereas in reality, the naming from the octopus app is more correct; it will try to add that amount of charge.

It feels like this text should be more consistent.

### Reproduction steps

n/a

### Expected behaviour

Text/meaning to match between Octopus App and HA Add on

### Tariff Code

n/a

### Integration Version

v12.2.0

### Home Assistant Version

2024.8.2

### Fresh Install?

Not specified

### Home Assistant Logs

n/a

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by Quickstep3** [comment]
I think this depends on whether your Octopus Intelligent integration is with a car or with a charger, and possibly even with certain brands of car or charger. My Octopus App definitely shows charge limit on the Hypervolt EV Charger integration.

**Comment by reedy** [comment]
That would make some sense...

I have a Myenergi Zappi 

![image](https://github.com/user-attachments/assets/02e120a6-a7ca-4ac5-b478-1fffd4263229)

From what I can tell...it uses that %, along with the car battery figure to calculate the amount to request the charger to "boost"

**Comment by BottlecapDave** [comment]
Hello. I have had mixed responses on this in the past and I believe @Quickstep3 is correct that it's based on the integration. I'm not really wanting to change the naming based on the underlying provider as I'll constantly be chasing new integrations and undoubtedly get it wrong which would result in breaking changes to "fix" the integration. You're obviously free to rename the sensors as you see fit.

I've been thinking about renaming these to "target" to better reflect the naming of the underlying API and is more inline with HA intelligent, which is what this was originally based on. It also better reflects the intention. Ive been developing this part of the integration a bit blind as I'm not on intelligent. I'm sure this change will make everyone unhappy :)

**Comment by reedy** [comment]
For cross referencing, I guess 4da40f590bf961246ab9c5964d6973e359f01d37 helps here too
