### ISSUE TITLE
Old data still showing for daily cost data import/export

### ISSUE THREAD

**Issue by justin-dev-uk** [BottlecapDave/HomeAssistant-OctopusEnergy#985]
### Describe the bug

Seems problem with data at Octopus. They requested data and appears fixed on octo-aid

but my home assistant is not showing updated vales

### Reproduction steps

Home assistant updates data daily

### Expected behaviour

Correct values showing for import and export
![IMG_7534](https://github.com/user-attachments/assets/426e2207-b93a-4904-b9b4-f68269f34fed)

### Tariff Code

Agile

### Integration Version

Latest

### Home Assistant Version

2024.8.3

### Fresh Install?

Not specified

### Home Assistant Logs

Na

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. Sorry that you're having issues. What sensors are you having issues with directly? If this is around previous consumption sensors, the sensors only look at a set timeframe for new data. If data is refreshed outside of that timeframe, it won't get picked up.

**Comment by justin-dev-uk** [comment]
That’s not good given Octopus data has been wrong all weekend so it’s now
lost

**Comment by BottlecapDave** [comment]
The sensors are built to show the latest available information, similar to other sensors with HA. Depending on the data you require, there is a [service/action](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/services/#octopus_energyrefresh_previous_consumption_data) which can be used to backfill data for the previous sensors. However, this only fills the information for the linked statistics sensors (built/recommended for energy dashboard). This won't backfill the data for the sensors themselves (e.g when you look at the history). This is a limitation in the HA sensors as they're not built for correcting historic data.

**Comment by yellowduck** [comment]
I'm having a similar problem. I switched from flux to agile with fixed export a couple of weeks ago, and my export meter is still showing the flux prices. Octopus and octoprice show the correct (fixed export) values. Logbook events suggest the values are being updated, but that is not what I am seeing.

**Comment by yellowduck** [comment]
I relented and restarted HA. That appears to have fixed things...
