### ISSUE TITLE
Feature: Add 30 min consumption reporting for SmartMeters.

### ISSUE THREAD

**Issue by andylockran** [BottlecapDave/HomeAssistant-OctopusEnergy#99]
(I'd like to work on the code to introduce this; creating it as a feature in case I've missed something you've already done that stops this being feasible).

**Describe the feature**

A new entity for a meter (either gas/electric) that reports consumption from your smart meter every 30 mins.

**API To be used**

https://developer.octopus.energy/docs/api/#list-consumption-for-a-meter

Half-hourly consumption data is only available for smart meters. Requests for consumption data for non-smart meters will return an empty response payload.

**Expected behavior**

Every 30 mins a new consumption report so that it'll work with the energy graph so I can see my daily consumption.

**Comment by BottlecapDave** [comment]
The integration already uses this endpoint to populate the previous days worth of data. Unfortunately, with the way smart meters work, Octopus Energy only gains access to data up to the previous day (this is omitting from the docs).

Having said that, they're currently trialling the [Octopus Home Mini](https://octopus.energy/blog/octopus-home-mini/) to get access to the data more quickly. However, they haven't made the API they use in their app public and I haven't had time to go digging for it. However once they do, I'll be integrating that :)

**Comment by andylockran** [comment]
Thanks for the swift reply. I'm more than happy to help :)
