### ISSUE TITLE
Detected that custom integration 'octopus_energy' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9

### ISSUE THREAD

**Issue by ProximusAl** [BottlecapDave/HomeAssistant-OctopusEnergy#991]
### Describe the bug

Detected that custom integration 'octopus_energy' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/octopus_energy/event.py, line 36: platform.async_register_entity_service(, please create a bug report at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues
Detected that custom integration 'octopus_energy' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/octopus_energy/sensor.py, line 128: platform.async_register_entity_service(, please create a bug report at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues
Detected that custom integration 'octopus_energy' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/octopus_energy/sensor.py, line 141: platform.async_register_entity_service(, please create a bug report at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues
Detected that custom integration 'octopus_energy' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/octopus_energy/sensor.py, line 157: platform.async_register_entity_service(, please create a bug report at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues

### Reproduction steps

Upgrade to latest HomeAssistant docker

### Expected behaviour

None of these logs :)

### Tariff Code

?

### Integration Version

Latest

### Home Assistant Version

2024.9.0

### Fresh Install?

After upgrading

### Home Assistant Logs

See above

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by andyblac** [comment]
same here

**Comment by trebortrebor** [comment]
Same here :-(

**Comment by BottlecapDave** [comment]
Sorry for the late response, I've been away for a couple of weeks. I'll aim to fix this warning for the next release.

**Comment by ctaggmk** [comment]
nice! thank you

**Comment by BottlecapDave** [comment]
The fix for this issue is now available in [v13.0.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v13.0.0).
