### ISSUE TITLE
Unknown intelligent provider "FORD"

### ISSUE THREAD

**Issue by grantbevis** [BottlecapDave/HomeAssistant-OctopusEnergy#993]
### Provider name

Hey Guys,

Loving the Octopus integration, I've added my car to Octopus through their app and I've had one `binary_sensor` add of Intelligent Dispatch added for my car charger. The charger itself isn't smart and Octopus is integrating with FordPass directly to monitor and control the car's charging.

What details do you need from me or even point me in the right direction on where to contribute some Python code

Kind regards,
Grant

### Features

- [X] Ability to bump charge
- [X] Ability to set the charge limit/target
- [x] Ability to set the time the charge will be at its target for
- [ ] Ability to turn smart charge on/off
- [X] Ability to see planned dispatches

**Comment by BottlecapDave** [comment]
Hello and sorry for theate response. Thanks for taking the time to add the PR. Im currently away, but will hope to take a look within the next week when I get back.
