### ISSUE TITLE
Turn on Intelligent Bump Charge fails

### ISSUE THREAD

**Issue by SteveDooley-Kingsbridge** [BottlecapDave/HomeAssistant-OctopusEnergy#995]
### Describe the bug

I have a script to "Turn on Intelligent Bump Charge (A-xxxxx )".  Using this with my EV plugged into the ZAPPI,  the whole system being on Octopus Intelligent Go tariff. Result is always as shown in the attached image. 
![20240912_201435](https://github.com/user-attachments/assets/682c91e6-941d-4720-a257-835b981c7579)

Sorry about the screen grab, but the error message only shows for a few seconds.  I am wondering if Octopus,  having created a charging schedule,  disallows this, but I can manually start a boost OK. 

### Reproduction steps

Happens every time 

### Expected behaviour

I expect the ZAPPI to start charging and show "Boosting"

### Tariff Code

22M0239951 2200020136810

### Integration Version

12.2.1

### Home Assistant Version

2024.7.1

### Fresh Install?

Fresh install

### Home Assistant Logs

[error_log1.txt](https://github.com/user-attachments/files/16984892/error_log1.txt)

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry that you've seen this issue. This error is coming back straight from OE and the error code suggests it's being activated while your vehicle is not at the home location or disconnected. Can you toggle via the app successfully at the same time the HA sensors fails? If you can, have you ever had multiple intelligent devices configured? I only ask the latter in case the integration is somehow picking up the wrong device.

**Comment by SteveDooley-Kingsbridge** [comment]
Hi Dave, sorry I have been off-line and many thanks for your reply. I have temporarily removed the Myenergi integration because of problems with the EDDI. It now seems to work OK. I can start a boost from a script. I think the way the boost works you can't actually stop it, calling the stop boost service just changes the indicator in HA. However you can stop it by calling the service to start the Intelligent Smart Charge which has the required effect. I still have a few other experiments to do, but I think all is basically OK. I'll see what happens when I reinstall the Myenergi integration.

**Comment by SteveDooley-Kingsbridge** [comment]
Done a few more experiments and the stop boost service does work, it's just that you have to be patient as it doesn't take effect at the charger for 5-10 minutes.
