### ISSUE TITLE
Is it possible to get other meter data like Volts, Current etc ?

### ISSUE THREAD

**Issue by mark-carline** [BottlecapDave/HomeAssistant-OctopusEnergy#999]
### Describe the feature

I have noticed via my own Eastron SDM120M modbus meter connected to Home Assistant that my voltage sometimes peaks at 254 volts which is over the limit of what is acceptable.  I have reported it to my DNO (SP) who are looking into it.

I wonder (for the people who do not have their own meter and just use a smart meter) if there is any other data you can pull back from the meter like volts, current etc ?

This is the kind of data which my Eastron SDM120M pulls back which maybe exposed already in household smart meters:

See PDF page 3:
https://www.etteam.com/productDIN/SDM120-MODBUS/SDM120-PROTOCOL.pdf

Happy to help test if needed (sorry i can't code)

Thanks

### Expected behaviour

Additional available values added.

### Use Case

Able to view more in depth data on meter data

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. There is no information like this available through the API that I can see. OE doesn't have a direct connection with your meter, which is why this information isn't probably available.
